C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,3)*ProjM(4,1)
C     
      SUBROUTINE FFFF1_1(F2, F3, F4, COUP, M1, W1,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP34
      REAL*8 P1(0:3)
      REAL*8 M1
      REAL*8 W1
      COMPLEX*16 F1(6)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 DENOM
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      F1(1) = +F2(1)+F3(1)+F4(1)
      F1(2) = +F2(2)+F3(2)+F4(2)
      P1(0) = -DBLE(F1(1))
      P1(1) = -DBLE(F1(2))
      P1(2) = -DIMAG(F1(2))
      P1(3) = -DIMAG(F1(1))
      TMP34 = (F2(3)*F3(3)+F2(4)*F3(4))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      F1(3)= DENOM*CI * F4(3)*TMP34*M1
      F1(4)= DENOM*CI * F4(4)*TMP34*M1
      F1(5)= DENOM*CI * TMP34*(F4(3)*(P1(3)-P1(0))+F4(4)*(P1(1)+CI
     $ *(P1(2))))
      F1(6)= DENOM*(-CI )* TMP34*(F4(3)*(+CI*(P1(2))-P1(1))+F4(4)
     $ *(P1(0)+P1(3)))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,3)*ProjM(4,1)
C     
      SUBROUTINE FFFF1_15_16_17_5_9_1(F2, F3, F4, COUP1, COUP2, COUP3,
     $  COUP4, COUP5, COUP6, M1, W1,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP6
      REAL*8 P1(0:3)
      REAL*8 M1
      COMPLEX*16 COUP5
      REAL*8 W1
      COMPLEX*16 F1(6)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP2
      COMPLEX*16 F3(*)
      COMPLEX*16 DENOM
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      INTEGER*4 I
      COMPLEX*16 F4(*)
      COMPLEX*16 FTMP(6)
      CALL FFFF1_1(F2,F3,F4,COUP1,M1,W1,F1)
      CALL FFFF15_1(F2,F3,F4,COUP2,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF16_1(F2,F3,F4,COUP3,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF17_1(F2,F3,F4,COUP4,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF5_1(F2,F3,F4,COUP5,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF9_1(F2,F3,F4,COUP6,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,3)*ProjM(4,1)
C     
      SUBROUTINE FFFF1_15_16_17_9_1(F2, F3, F4, COUP1, COUP2, COUP3,
     $  COUP4, COUP5, M1, W1,F1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP6
      REAL*8 P1(0:3)
      REAL*8 M1
      COMPLEX*16 COUP5
      REAL*8 W1
      COMPLEX*16 F1(6)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP2
      COMPLEX*16 F3(*)
      COMPLEX*16 DENOM
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      INTEGER*4 I
      COMPLEX*16 F4(*)
      COMPLEX*16 FTMP(6)
      CALL FFFF1_1(F2,F3,F4,COUP1,M1,W1,F1)
      CALL FFFF15_1(F2,F3,F4,COUP2,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF16_1(F2,F3,F4,COUP3,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF17_1(F2,F3,F4,COUP4,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      CALL FFFF9_1(F2,F3,F4,COUP5,M1,W1,FTMP)
      DO I = 3, 6
        F1(I) = F1(I) + FTMP(I)
      ENDDO
      END


