      SUBROUTINE M82_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M82_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M82_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M82_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: b b~ > t t~ vm vm~ DIM6<=1 FCNC=0 / h @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M82_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M82_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M82_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  17),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  18),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  19),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  20),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  21),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  22),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  23),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  24),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  33),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  34),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  35),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  36),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  37),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  38),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  39),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  40),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  41),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  42),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  43),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  44),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  45),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  46),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  47),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  48),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  49),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  50),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  51),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  52),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  53),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  54),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  55),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  56),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  57),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  58),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  59),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  60),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  61),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  62),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  63),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  64),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA IDEN/36/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M82_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M82_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M82_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M82_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M82_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M82_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: b b~ > t t~ vm vm~ DIM6<=1 FCNC=0 / h @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=192)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=22, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  2) /    9,    3/
C     1 T(2,1) T(3,4)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  2) /    3,    9/
C     1 T(2,4) T(3,1)
C     ----------
C     BEGIN CODE
C     ----------
      CALL IXXXXX(P(0,1),MDL_MB,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),MDL_MB,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL FFV2_5_3(W(1,1),W(1,2),GC_650,GC_660,MDL_MZ,MDL_WZ,W(1,7))
      CALL FFV2_8_3(W(1,4),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,8))
      CALL FFV2_1(W(1,5),W(1,7),GC_664,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV2_0(W(1,6),W(1,9),W(1,8),GC_664,AMP(1))
      CALL FFV2_2(W(1,6),W(1,7),GC_664,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV2_0(W(1,10),W(1,5),W(1,8),GC_664,AMP(2))
      CALL FFV11_9_3(W(1,4),W(1,3),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL FFV2_0(W(1,6),W(1,9),W(1,11),GC_664,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV2_0(W(1,10),W(1,5),W(1,11),GC_664,AMP(4))
      CALL FFV4_3(W(1,4),W(1,3),GC_948,MDL_MZ,MDL_WZ,W(1,12))
C     Amplitude(s) for diagram number 5
      CALL FFV2_0(W(1,6),W(1,9),W(1,12),GC_664,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV2_0(W(1,10),W(1,5),W(1,12),GC_664,AMP(6))
      CALL FFV2_3(W(1,4),W(1,3),GC_938,MDL_MZ,MDL_WZ,W(1,13))
C     Amplitude(s) for diagram number 7
      CALL FFV2_0(W(1,6),W(1,9),W(1,13),GC_664,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV2_0(W(1,10),W(1,5),W(1,13),GC_664,AMP(8))
      CALL FFV11_9_3(W(1,1),W(1,2),GC_723,GC_724,MDL_MZ,MDL_WZ,W(1,10))
      CALL FFV2_1(W(1,5),W(1,10),GC_664,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 9
      CALL FFV2_0(W(1,6),W(1,9),W(1,8),GC_664,AMP(9))
      CALL FFV2_2(W(1,6),W(1,10),GC_664,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 10
      CALL FFV2_0(W(1,9),W(1,5),W(1,8),GC_664,AMP(10))
      CALL FFV4_3(W(1,1),W(1,2),GC_933,MDL_MZ,MDL_WZ,W(1,9))
      CALL FFV2_1(W(1,5),W(1,9),GC_664,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 11
      CALL FFV2_0(W(1,6),W(1,14),W(1,8),GC_664,AMP(11))
      CALL FFV2_2(W(1,6),W(1,9),GC_664,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 12
      CALL FFV2_0(W(1,14),W(1,5),W(1,8),GC_664,AMP(12))
      CALL FFV2_3(W(1,1),W(1,2),GC_939,MDL_MZ,MDL_WZ,W(1,14))
      CALL FFV2_1(W(1,5),W(1,14),GC_664,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 13
      CALL FFV2_0(W(1,6),W(1,15),W(1,8),GC_664,AMP(13))
      CALL FFV2_2(W(1,6),W(1,14),GC_664,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 14
      CALL FFV2_0(W(1,15),W(1,5),W(1,8),GC_664,AMP(14))
      CALL FFV6P0_3(W(1,1),W(1,2),GC_1,ZERO,ZERO,W(1,15))
      CALL FFV2_3(W(1,6),W(1,5),GC_664,MDL_MZ,MDL_WZ,W(1,16))
      CALL FFV6_1(W(1,3),W(1,15),GC_2,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 15
      CALL FFV2_8_0(W(1,4),W(1,17),W(1,16),GC_651,GC_660,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFV11_9_0(W(1,4),W(1,17),W(1,16),GC_721,GC_722,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV4_0(W(1,4),W(1,17),W(1,16),GC_948,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV2_0(W(1,4),W(1,17),W(1,16),GC_938,AMP(18))
      CALL FFV11_9_1(W(1,3),W(1,15),GC_813,GC_814,MDL_MT,MDL_WT,W(1,17)
     $ )
C     Amplitude(s) for diagram number 19
      CALL FFV2_8_0(W(1,4),W(1,17),W(1,16),GC_651,GC_660,AMP(19))
      CALL FFV6_2(W(1,4),W(1,15),GC_2,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 20
      CALL FFV2_8_0(W(1,17),W(1,3),W(1,16),GC_651,GC_660,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV11_9_0(W(1,17),W(1,3),W(1,16),GC_721,GC_722,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV4_0(W(1,17),W(1,3),W(1,16),GC_948,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV2_0(W(1,17),W(1,3),W(1,16),GC_938,AMP(23))
      CALL FFV11_9_2(W(1,4),W(1,15),GC_813,GC_814,MDL_MT,MDL_WT,W(1,17)
     $ )
C     Amplitude(s) for diagram number 24
      CALL FFV2_8_0(W(1,17),W(1,3),W(1,16),GC_651,GC_660,AMP(24))
      CALL FFV11_9P0_3(W(1,1),W(1,2),GC_736,GC_737,ZERO,ZERO,W(1,17))
      CALL FFV6_1(W(1,3),W(1,17),GC_2,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 25
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(25))
      CALL FFV6_2(W(1,4),W(1,17),GC_2,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 26
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(26))
      CALL FFV2_8_1(W(1,3),W(1,7),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 27
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFV11_9_0(W(1,4),W(1,18),W(1,16),GC_721,GC_722,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV4_0(W(1,4),W(1,18),W(1,16),GC_948,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL FFV2_0(W(1,4),W(1,18),W(1,16),GC_938,AMP(30))
      CALL FFV11_9_1(W(1,3),W(1,7),GC_721,GC_722,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 31
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(31))
      CALL FFV4_1(W(1,3),W(1,7),GC_948,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 32
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(32))
      CALL FFV2_1(W(1,3),W(1,7),GC_938,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 33
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(33))
      CALL FFV2_8_2(W(1,4),W(1,7),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 34
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV11_9_0(W(1,18),W(1,3),W(1,16),GC_721,GC_722,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV4_0(W(1,18),W(1,3),W(1,16),GC_948,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL FFV2_0(W(1,18),W(1,3),W(1,16),GC_938,AMP(37))
      CALL FFV11_9_2(W(1,4),W(1,7),GC_721,GC_722,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 38
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(38))
      CALL FFV4_2(W(1,4),W(1,7),GC_948,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 39
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(39))
      CALL FFV2_2(W(1,4),W(1,7),GC_938,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 40
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(40))
      CALL FFV2_8_1(W(1,3),W(1,10),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 41
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(41))
      CALL FFV2_8_2(W(1,4),W(1,10),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 42
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(42))
      CALL FFV2_8_1(W(1,3),W(1,9),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 43
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(43))
      CALL FFV2_8_2(W(1,4),W(1,9),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 44
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(44))
      CALL FFV2_8_1(W(1,3),W(1,14),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 45
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(45))
      CALL FFV2_8_2(W(1,4),W(1,14),GC_651,GC_660,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 46
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(46))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_7,ZERO,ZERO,W(1,18))
      CALL FFV6_1(W(1,3),W(1,18),GC_7,MDL_MT,MDL_WT,W(1,14))
C     Amplitude(s) for diagram number 47
      CALL FFV2_8_0(W(1,4),W(1,14),W(1,16),GC_651,GC_660,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV11_9_0(W(1,4),W(1,14),W(1,16),GC_721,GC_722,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV4_0(W(1,4),W(1,14),W(1,16),GC_948,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV2_0(W(1,4),W(1,14),W(1,16),GC_938,AMP(50))
      CALL FFV11_9_1(W(1,3),W(1,18),GC_725,GC_726,MDL_MT,MDL_WT,W(1,14)
     $ )
C     Amplitude(s) for diagram number 51
      CALL FFV2_8_0(W(1,4),W(1,14),W(1,16),GC_651,GC_660,AMP(51))
      CALL FFV6_2(W(1,4),W(1,18),GC_7,MDL_MT,MDL_WT,W(1,14))
C     Amplitude(s) for diagram number 52
      CALL FFV2_8_0(W(1,14),W(1,3),W(1,16),GC_651,GC_660,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFV11_9_0(W(1,14),W(1,3),W(1,16),GC_721,GC_722,AMP(53))
C     Amplitude(s) for diagram number 54
      CALL FFV4_0(W(1,14),W(1,3),W(1,16),GC_948,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV2_0(W(1,14),W(1,3),W(1,16),GC_938,AMP(55))
      CALL FFV11_9_2(W(1,4),W(1,18),GC_725,GC_726,MDL_MT,MDL_WT,W(1,14)
     $ )
C     Amplitude(s) for diagram number 56
      CALL FFV2_8_0(W(1,14),W(1,3),W(1,16),GC_651,GC_660,AMP(56))
      CALL FFFF14_6_3(W(1,4),W(1,3),W(1,5),GC_585,GC_123,ZERO,ZERO,W(1
     $ ,14))
C     Amplitude(s) for diagram number 57
      CALL FFV2_0(W(1,6),W(1,14),W(1,7),GC_664,AMP(57))
      CALL FFFF14_6_4(W(1,4),W(1,3),W(1,6),GC_585,GC_123,ZERO,ZERO,W(1
     $ ,14))
C     Amplitude(s) for diagram number 58
      CALL FFV2_0(W(1,14),W(1,5),W(1,7),GC_664,AMP(58))
      CALL FFFF14_6_1(W(1,3),W(1,6),W(1,5),GC_585,GC_123,MDL_MT,MDL_WT
     $ ,W(1,14))
C     Amplitude(s) for diagram number 59
      CALL FFV6_0(W(1,4),W(1,14),W(1,15),GC_2,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFV2_8_0(W(1,4),W(1,14),W(1,7),GC_651,GC_660,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFV6_0(W(1,4),W(1,14),W(1,18),GC_7,AMP(61))
      CALL FFFF14_6_2(W(1,4),W(1,6),W(1,5),GC_585,GC_123,MDL_MT,MDL_WT
     $ ,W(1,9))
C     Amplitude(s) for diagram number 62
      CALL FFV6_0(W(1,9),W(1,3),W(1,15),GC_2,AMP(62))
C     Amplitude(s) for diagram number 63
      CALL FFV2_8_0(W(1,9),W(1,3),W(1,7),GC_651,GC_660,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL FFV6_0(W(1,9),W(1,3),W(1,18),GC_7,AMP(64))
      CALL FFV2_3(W(1,1),W(1,3),GC_649,MDL_MW,MDL_WW,W(1,18))
      CALL FFV2_3(W(1,4),W(1,2),GC_649,MDL_MW,MDL_WW,W(1,7))
      CALL FFV2_2(W(1,6),W(1,18),GC_649,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 65
      CALL FFV2_0(W(1,15),W(1,5),W(1,7),GC_649,AMP(65))
      CALL FFV4_3(W(1,4),W(1,2),GC_923,MDL_MW,MDL_WW,W(1,10))
C     Amplitude(s) for diagram number 66
      CALL FFV2_0(W(1,15),W(1,5),W(1,10),GC_649,AMP(66))
      CALL FFV10_3_3(W(1,4),W(1,2),GC_767,GC_742,MDL_MW,MDL_WW,W(1,17))
C     Amplitude(s) for diagram number 67
      CALL FFV2_0(W(1,15),W(1,5),W(1,17),GC_649,AMP(67))
      CALL FFV2_3(W(1,4),W(1,2),GC_740,MDL_MW,MDL_WW,W(1,19))
C     Amplitude(s) for diagram number 68
      CALL FFV2_0(W(1,15),W(1,5),W(1,19),GC_649,AMP(68))
      CALL FFV4_3(W(1,1),W(1,3),GC_924,MDL_MW,MDL_WW,W(1,15))
      CALL FFV2_2(W(1,6),W(1,15),GC_649,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 69
      CALL FFV2_0(W(1,20),W(1,5),W(1,7),GC_649,AMP(69))
      CALL FFV10_3_3(W(1,1),W(1,3),GC_741,GC_768,MDL_MW,MDL_WW,W(1,20))
      CALL FFV2_2(W(1,6),W(1,20),GC_649,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 70
      CALL FFV2_0(W(1,21),W(1,5),W(1,7),GC_649,AMP(70))
      CALL FFV2_3(W(1,1),W(1,3),GC_740,MDL_MW,MDL_WW,W(1,21))
      CALL FFV2_2(W(1,6),W(1,21),GC_649,ZERO,ZERO,W(1,22))
C     Amplitude(s) for diagram number 71
      CALL FFV2_0(W(1,22),W(1,5),W(1,7),GC_649,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL VVV1_0(W(1,7),W(1,18),W(1,16),GC_653,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL VVV1_0(W(1,10),W(1,18),W(1,16),GC_653,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL VVV1_0(W(1,17),W(1,18),W(1,16),GC_653,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL VVV1_0(W(1,19),W(1,18),W(1,16),GC_653,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL VVV1_0(W(1,7),W(1,15),W(1,16),GC_653,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL VVV1_0(W(1,7),W(1,20),W(1,16),GC_653,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL VVV1_0(W(1,7),W(1,21),W(1,16),GC_653,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFVV1_3_0(W(1,4),W(1,2),W(1,18),W(1,16),GC_838,GC_848
     $ ,AMP(79))
      CALL FFV2_1(W(1,2),W(1,18),GC_649,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 80
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFV11_9_0(W(1,4),W(1,22),W(1,16),GC_721,GC_722,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV4_0(W(1,4),W(1,22),W(1,16),GC_948,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFV2_0(W(1,4),W(1,22),W(1,16),GC_938,AMP(83))
      CALL FFV4_1(W(1,2),W(1,18),GC_923,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 84
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(84))
      CALL FFV10_3_1(W(1,2),W(1,18),GC_767,GC_742,MDL_MT,MDL_WT,W(1,22)
     $ )
C     Amplitude(s) for diagram number 85
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(85))
      CALL FFV2_1(W(1,2),W(1,18),GC_740,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 86
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(86))
      CALL FFV2_2(W(1,4),W(1,18),GC_649,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 87
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV11_9_0(W(1,22),W(1,2),W(1,16),GC_723,GC_724,AMP(88))
C     Amplitude(s) for diagram number 89
      CALL FFV4_0(W(1,22),W(1,2),W(1,16),GC_933,AMP(89))
C     Amplitude(s) for diagram number 90
      CALL FFV2_0(W(1,22),W(1,2),W(1,16),GC_939,AMP(90))
      CALL FFV4_2(W(1,4),W(1,18),GC_923,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 91
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(91))
      CALL FFV10_3_2(W(1,4),W(1,18),GC_767,GC_742,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 92
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(92))
      CALL FFV2_2(W(1,4),W(1,18),GC_740,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 93
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(93))
      CALL FFV2_1(W(1,2),W(1,15),GC_649,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 94
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(94))
      CALL FFV2_2(W(1,4),W(1,15),GC_649,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 95
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(95))
      CALL FFV2_1(W(1,2),W(1,20),GC_649,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 96
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(96))
      CALL FFV2_2(W(1,4),W(1,20),GC_649,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 97
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(97))
      CALL FFV2_1(W(1,2),W(1,21),GC_649,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 98
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,16),GC_651,GC_660,AMP(98))
      CALL FFV2_2(W(1,4),W(1,21),GC_649,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 99
      CALL FFV2_5_0(W(1,22),W(1,2),W(1,16),GC_650,GC_660,AMP(99))
      CALL FFFF10_11_20_6_110_3(W(1,4),W(1,2),W(1,5),GC_12,GC_345
     $ ,GC_343,GC_565,GC_342,ZERO,ZERO,W(1,22))
C     Amplitude(s) for diagram number 100
      CALL FFV2_0(W(1,6),W(1,22),W(1,18),GC_649,AMP(100))
      CALL FFFF6_1(W(1,2),W(1,6),W(1,5),GC_568,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 101
      CALL FFV2_0(W(1,4),W(1,22),W(1,18),GC_649,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL FFV2_0(W(1,9),W(1,2),W(1,18),GC_649,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL FFVV1_3_0(W(1,1),W(1,3),W(1,7),W(1,16),GC_847,GC_837
     $ ,AMP(103))
      CALL FFV2_2(W(1,1),W(1,7),GC_649,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 104
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV11_9_0(W(1,18),W(1,3),W(1,16),GC_721,GC_722,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV4_0(W(1,18),W(1,3),W(1,16),GC_948,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFV2_0(W(1,18),W(1,3),W(1,16),GC_938,AMP(107))
      CALL FFV4_2(W(1,1),W(1,7),GC_924,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 108
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(108))
      CALL FFV10_3_2(W(1,1),W(1,7),GC_741,GC_768,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 109
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(109))
      CALL FFV2_2(W(1,1),W(1,7),GC_740,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 110
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(110))
      CALL FFV2_5_2(W(1,1),W(1,16),GC_650,GC_660,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 111
      CALL FFV2_0(W(1,18),W(1,3),W(1,7),GC_649,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV4_0(W(1,18),W(1,3),W(1,7),GC_924,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV10_3_0(W(1,18),W(1,3),W(1,7),GC_741,GC_768,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV2_0(W(1,18),W(1,3),W(1,7),GC_740,AMP(114))
      CALL FFV11_9_2(W(1,1),W(1,16),GC_723,GC_724,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 115
      CALL FFV2_0(W(1,9),W(1,3),W(1,7),GC_649,AMP(115))
      CALL FFV4_2(W(1,1),W(1,16),GC_933,MDL_MB,ZERO,W(1,21))
C     Amplitude(s) for diagram number 116
      CALL FFV2_0(W(1,21),W(1,3),W(1,7),GC_649,AMP(116))
      CALL FFV2_2(W(1,1),W(1,16),GC_939,MDL_MB,ZERO,W(1,20))
C     Amplitude(s) for diagram number 117
      CALL FFV2_0(W(1,20),W(1,3),W(1,7),GC_649,AMP(117))
      CALL FFV2_2(W(1,1),W(1,10),GC_649,MDL_MT,MDL_WT,W(1,15))
C     Amplitude(s) for diagram number 118
      CALL FFV2_8_0(W(1,15),W(1,3),W(1,16),GC_651,GC_660,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFV2_0(W(1,18),W(1,3),W(1,10),GC_649,AMP(119))
      CALL FFV2_2(W(1,1),W(1,17),GC_649,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 120
      CALL FFV2_8_0(W(1,10),W(1,3),W(1,16),GC_651,GC_660,AMP(120))
C     Amplitude(s) for diagram number 121
      CALL FFV2_0(W(1,18),W(1,3),W(1,17),GC_649,AMP(121))
      CALL FFV2_2(W(1,1),W(1,19),GC_649,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 122
      CALL FFV2_8_0(W(1,17),W(1,3),W(1,16),GC_651,GC_660,AMP(122))
C     Amplitude(s) for diagram number 123
      CALL FFV2_0(W(1,18),W(1,3),W(1,19),GC_649,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL FFV2_0(W(1,1),W(1,14),W(1,7),GC_649,AMP(124))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_2,ZERO,ZERO,W(1,14))
      CALL FFV6_2(W(1,1),W(1,14),GC_1,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 125
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(125))
C     Amplitude(s) for diagram number 126
      CALL FFV11_9_0(W(1,19),W(1,2),W(1,16),GC_723,GC_724,AMP(126))
C     Amplitude(s) for diagram number 127
      CALL FFV4_0(W(1,19),W(1,2),W(1,16),GC_933,AMP(127))
C     Amplitude(s) for diagram number 128
      CALL FFV2_0(W(1,19),W(1,2),W(1,16),GC_939,AMP(128))
      CALL FFV11_9_2(W(1,1),W(1,14),GC_736,GC_737,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 129
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFV6_0(W(1,18),W(1,2),W(1,14),GC_1,AMP(130))
C     Amplitude(s) for diagram number 131
      CALL FFV11_9_0(W(1,18),W(1,2),W(1,14),GC_736,GC_737,AMP(131))
C     Amplitude(s) for diagram number 132
      CALL FFV6_0(W(1,9),W(1,2),W(1,14),GC_1,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL FFV6_0(W(1,21),W(1,2),W(1,14),GC_1,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL FFV6_0(W(1,20),W(1,2),W(1,14),GC_1,AMP(134))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_813,GC_814,ZERO,ZERO,W(1,19))
      CALL FFV6_2(W(1,1),W(1,19),GC_1,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 135
      CALL FFV2_5_0(W(1,17),W(1,2),W(1,16),GC_650,GC_660,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL FFV6_0(W(1,18),W(1,2),W(1,19),GC_1,AMP(136))
      CALL FFV2_5_2(W(1,1),W(1,8),GC_650,GC_660,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 137
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(137))
C     Amplitude(s) for diagram number 138
      CALL FFV11_9_0(W(1,19),W(1,2),W(1,16),GC_723,GC_724,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL FFV4_0(W(1,19),W(1,2),W(1,16),GC_933,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL FFV2_0(W(1,19),W(1,2),W(1,16),GC_939,AMP(140))
      CALL FFV11_9_2(W(1,1),W(1,8),GC_723,GC_724,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 141
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(141))
      CALL FFV4_2(W(1,1),W(1,8),GC_933,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 142
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(142))
      CALL FFV2_2(W(1,1),W(1,8),GC_939,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 143
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,8),GC_650,GC_660,AMP(144))
C     Amplitude(s) for diagram number 145
      CALL FFV11_9_0(W(1,18),W(1,2),W(1,8),GC_723,GC_724,AMP(145))
C     Amplitude(s) for diagram number 146
      CALL FFV4_0(W(1,18),W(1,2),W(1,8),GC_933,AMP(146))
C     Amplitude(s) for diagram number 147
      CALL FFV2_0(W(1,18),W(1,2),W(1,8),GC_939,AMP(147))
C     Amplitude(s) for diagram number 148
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,8),GC_650,GC_660,AMP(148))
C     Amplitude(s) for diagram number 149
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,8),GC_650,GC_660,AMP(149))
C     Amplitude(s) for diagram number 150
      CALL FFV2_5_0(W(1,20),W(1,2),W(1,8),GC_650,GC_660,AMP(150))
      CALL FFV2_5_2(W(1,1),W(1,11),GC_650,GC_660,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 151
      CALL FFV2_5_0(W(1,19),W(1,2),W(1,16),GC_650,GC_660,AMP(151))
C     Amplitude(s) for diagram number 152
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,11),GC_650,GC_660,AMP(152))
      CALL FFV2_5_2(W(1,1),W(1,12),GC_650,GC_660,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 153
      CALL FFV2_5_0(W(1,11),W(1,2),W(1,16),GC_650,GC_660,AMP(153))
C     Amplitude(s) for diagram number 154
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,12),GC_650,GC_660,AMP(154))
      CALL FFV2_5_2(W(1,1),W(1,13),GC_650,GC_660,MDL_MB,ZERO,W(1,12))
C     Amplitude(s) for diagram number 155
      CALL FFV2_5_0(W(1,12),W(1,2),W(1,16),GC_650,GC_660,AMP(155))
C     Amplitude(s) for diagram number 156
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,13),GC_650,GC_660,AMP(156))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_7,ZERO,ZERO,W(1,13))
      CALL FFV1_2(W(1,1),W(1,13),GC_7,MDL_MB,ZERO,W(1,12))
C     Amplitude(s) for diagram number 157
      CALL FFV2_5_0(W(1,12),W(1,2),W(1,16),GC_650,GC_660,AMP(157))
C     Amplitude(s) for diagram number 158
      CALL FFV11_9_0(W(1,12),W(1,2),W(1,16),GC_723,GC_724,AMP(158))
C     Amplitude(s) for diagram number 159
      CALL FFV4_0(W(1,12),W(1,2),W(1,16),GC_933,AMP(159))
C     Amplitude(s) for diagram number 160
      CALL FFV2_0(W(1,12),W(1,2),W(1,16),GC_939,AMP(160))
C     Amplitude(s) for diagram number 161
      CALL FFV1_0(W(1,18),W(1,2),W(1,13),GC_7,AMP(161))
C     Amplitude(s) for diagram number 162
      CALL FFV1_0(W(1,9),W(1,2),W(1,13),GC_7,AMP(162))
C     Amplitude(s) for diagram number 163
      CALL FFV1_0(W(1,21),W(1,2),W(1,13),GC_7,AMP(163))
C     Amplitude(s) for diagram number 164
      CALL FFV1_0(W(1,20),W(1,2),W(1,13),GC_7,AMP(164))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_725,GC_726,ZERO,ZERO,W(1,20))
      CALL FFV1_2(W(1,1),W(1,20),GC_7,MDL_MB,ZERO,W(1,21))
C     Amplitude(s) for diagram number 165
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,16),GC_650,GC_660,AMP(165))
C     Amplitude(s) for diagram number 166
      CALL FFV1_0(W(1,18),W(1,2),W(1,20),GC_7,AMP(166))
      CALL FFFF11_2_6_1(W(1,2),W(1,1),W(1,3),GC_193,GC_191,GC_571
     $ ,MDL_MT,MDL_WT,W(1,20))
      CALL FFFF1_15_16_17_5_9_1(W(1,2),W(1,1),W(1,3),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MT,MDL_WT,W(1,18))
      CALL FFFF11_2_1(W(1,2),W(1,1),W(1,3),GC_197,GC_195,MDL_MT,MDL_WT
     $ ,W(1,21))
      CALL FFFF1_15_16_17_9_1(W(1,2),W(1,1),W(1,3),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 167
      CALL FFV2_8_0(W(1,4),W(1,20),W(1,16),GC_651,GC_660,AMP(167))
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,16),GC_651,GC_660,AMP(168))
      CALL FFV2_8_0(W(1,4),W(1,21),W(1,16),GC_651,GC_660,AMP(169))
      CALL FFV2_8_0(W(1,4),W(1,9),W(1,16),GC_651,GC_660,AMP(170))
      CALL FFFF11_2_6_4(W(1,4),W(1,2),W(1,1),GC_193,GC_191,GC_571
     $ ,MDL_MT,MDL_WT,W(1,9))
      CALL FFFF1_15_16_17_5_9_4(W(1,4),W(1,2),W(1,1),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MT,MDL_WT,W(1,21))
      CALL FFFF11_2_4(W(1,4),W(1,2),W(1,1),GC_197,GC_195,MDL_MT,MDL_WT
     $ ,W(1,18))
      CALL FFFF1_15_16_17_9_4(W(1,4),W(1,2),W(1,1),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 168
      CALL FFV2_8_0(W(1,9),W(1,3),W(1,16),GC_651,GC_660,AMP(171))
      CALL FFV2_8_0(W(1,21),W(1,3),W(1,16),GC_651,GC_660,AMP(172))
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(173))
      CALL FFV2_8_0(W(1,20),W(1,3),W(1,16),GC_651,GC_660,AMP(174))
      CALL FFFF6_3(W(1,1),W(1,2),W(1,5),GC_568,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 169
      CALL FFV2_0(W(1,6),W(1,20),W(1,8),GC_664,AMP(175))
      CALL FFFF6_4(W(1,1),W(1,2),W(1,6),GC_568,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 170
      CALL FFV2_0(W(1,20),W(1,5),W(1,8),GC_664,AMP(176))
      CALL FFFF11_2_6_2(W(1,4),W(1,1),W(1,3),GC_193,GC_191,GC_571
     $ ,MDL_MB,ZERO,W(1,20))
      CALL FFFF1_15_16_17_5_9_2(W(1,4),W(1,1),W(1,3),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MB,ZERO,W(1,18))
      CALL FFFF11_2_2(W(1,4),W(1,1),W(1,3),GC_197,GC_195,MDL_MB,ZERO
     $ ,W(1,21))
      CALL FFFF1_15_16_17_9_2(W(1,4),W(1,1),W(1,3),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 171
      CALL FFV2_5_0(W(1,20),W(1,2),W(1,16),GC_650,GC_660,AMP(177))
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,16),GC_650,GC_660,AMP(178))
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,16),GC_650,GC_660,AMP(179))
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,16),GC_650,GC_660,AMP(180))
      CALL FFFF10_2_6_7_21_2(W(1,6),W(1,1),W(1,3),GC_13,GC_339,GC_565
     $ ,GC_341,GC_344,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 172
      CALL FFV2_0(W(1,9),W(1,5),W(1,7),GC_649,AMP(181))
      CALL FFFF6_2(W(1,1),W(1,6),W(1,5),GC_568,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 173
      CALL FFV2_0(W(1,9),W(1,3),W(1,7),GC_649,AMP(182))
C     Amplitude(s) for diagram number 174
      CALL FFV6_0(W(1,9),W(1,2),W(1,14),GC_1,AMP(183))
C     Amplitude(s) for diagram number 175
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,8),GC_650,GC_660,AMP(184))
C     Amplitude(s) for diagram number 176
      CALL FFV1_0(W(1,9),W(1,2),W(1,13),GC_7,AMP(185))
      CALL FFFF11_2_6_3(W(1,4),W(1,2),W(1,3),GC_193,GC_191,GC_571
     $ ,MDL_MB,ZERO,W(1,9))
      CALL FFFF1_15_16_17_5_9_3(W(1,4),W(1,2),W(1,3),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MB,ZERO,W(1,7))
      CALL FFFF11_2_3(W(1,4),W(1,2),W(1,3),GC_197,GC_195,MDL_MB,ZERO
     $ ,W(1,6))
      CALL FFFF1_15_16_17_9_3(W(1,4),W(1,2),W(1,3),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MB,ZERO,W(1,5))
C     Amplitude(s) for diagram number 177
      CALL FFV2_5_0(W(1,1),W(1,9),W(1,16),GC_650,GC_660,AMP(186))
      CALL FFV2_5_0(W(1,1),W(1,7),W(1,16),GC_650,GC_660,AMP(187))
      CALL FFV2_5_0(W(1,1),W(1,6),W(1,16),GC_650,GC_660,AMP(188))
      CALL FFV2_5_0(W(1,1),W(1,5),W(1,16),GC_650,GC_660,AMP(189))
C     Amplitude(s) for diagram number 178
      CALL FFV6_0(W(1,1),W(1,22),W(1,14),GC_1,AMP(190))
C     Amplitude(s) for diagram number 179
      CALL FFV2_5_0(W(1,1),W(1,22),W(1,8),GC_650,GC_660,AMP(191))
C     Amplitude(s) for diagram number 180
      CALL FFV1_0(W(1,1),W(1,22),W(1,13),GC_7,AMP(192))
      JAMP(1)=+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)+AMP(8)
     $ +AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)+AMP(16)
     $ +AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)+AMP(24)
     $ +AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)+AMP(32)
     $ +AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(37)+AMP(38)+AMP(39)+AMP(40)
     $ +AMP(41)+AMP(42)+AMP(43)+AMP(44)+AMP(45)+AMP(46)-1D0/6D0*AMP(47)
     $ -1D0/6D0*AMP(48)-1D0/6D0*AMP(49)-1D0/6D0*AMP(50)-1D0/6D0*AMP(51)
     $ -1D0/6D0*AMP(52)-1D0/6D0*AMP(53)-1D0/6D0*AMP(54)-1D0/6D0*AMP(55)
     $ -1D0/6D0*AMP(56)+AMP(57)+AMP(58)+AMP(59)+AMP(60)-1D0/6D0*AMP(61)
     $ +AMP(62)+AMP(63)-1D0/6D0*AMP(64)+AMP(125)+AMP(126)+AMP(127)
     $ +AMP(128)+AMP(129)+AMP(130)+AMP(131)+AMP(132)+AMP(133)+AMP(134)
     $ +AMP(135)+AMP(136)+AMP(137)+AMP(138)+AMP(139)+AMP(140)+AMP(141)
     $ +AMP(142)+AMP(143)+AMP(144)+AMP(145)+AMP(146)+AMP(147)+AMP(148)
     $ +AMP(149)+AMP(150)+AMP(151)+AMP(152)+AMP(153)+AMP(154)+AMP(155)
     $ +AMP(156)-1D0/6D0*AMP(157)-1D0/6D0*AMP(158)-1D0/6D0*AMP(159)
     $ -1D0/6D0*AMP(160)-1D0/6D0*AMP(161)-1D0/6D0*AMP(162)-1D0/6D0
     $ *AMP(163)-1D0/6D0*AMP(164)-1D0/6D0*AMP(165)-1D0/6D0*AMP(166)
     $ -AMP(168)+1D0/6D0*AMP(170)-1D0/2D0*AMP(169)-AMP(172)+1D0/6D0
     $ *AMP(174)-1D0/2D0*AMP(173)+AMP(175)+AMP(176)-AMP(178)+1D0/6D0
     $ *AMP(180)-1D0/2D0*AMP(179)+AMP(183)+AMP(184)-1D0/6D0*AMP(185)
     $ -AMP(187)+1D0/6D0*AMP(189)-1D0/2D0*AMP(188)+AMP(190)+AMP(191)
     $ -1D0/6D0*AMP(192)
      JAMP(2)=+1D0/2D0*AMP(47)+1D0/2D0*AMP(48)+1D0/2D0*AMP(49)+1D0/2D0
     $ *AMP(50)+1D0/2D0*AMP(51)+1D0/2D0*AMP(52)+1D0/2D0*AMP(53)+1D0
     $ /2D0*AMP(54)+1D0/2D0*AMP(55)+1D0/2D0*AMP(56)+1D0/2D0*AMP(61)
     $ +1D0/2D0*AMP(64)-AMP(65)-AMP(66)-AMP(67)-AMP(68)-AMP(69)-AMP(70)
     $ -AMP(71)-AMP(72)-AMP(73)-AMP(74)-AMP(75)-AMP(76)-AMP(77)-AMP(78)
     $ -AMP(79)-AMP(80)-AMP(81)-AMP(82)-AMP(83)-AMP(84)-AMP(85)-AMP(86)
     $ -AMP(87)-AMP(88)-AMP(89)-AMP(90)-AMP(91)-AMP(92)-AMP(93)-AMP(94)
     $ -AMP(95)-AMP(96)-AMP(97)-AMP(98)-AMP(99)-AMP(100)-AMP(101)
     $ -AMP(102)-AMP(103)-AMP(104)-AMP(105)-AMP(106)-AMP(107)-AMP(108)
     $ -AMP(109)-AMP(110)-AMP(111)-AMP(112)-AMP(113)-AMP(114)-AMP(115)
     $ -AMP(116)-AMP(117)-AMP(118)-AMP(119)-AMP(120)-AMP(121)-AMP(122)
     $ -AMP(123)-AMP(124)+1D0/2D0*AMP(157)+1D0/2D0*AMP(158)+1D0/2D0
     $ *AMP(159)+1D0/2D0*AMP(160)+1D0/2D0*AMP(161)+1D0/2D0*AMP(162)
     $ +1D0/2D0*AMP(163)+1D0/2D0*AMP(164)+1D0/2D0*AMP(165)+1D0/2D0
     $ *AMP(166)-1D0/2D0*AMP(170)-AMP(167)+1D0/6D0*AMP(169)-1D0/2D0
     $ *AMP(174)-AMP(171)+1D0/6D0*AMP(173)-1D0/2D0*AMP(180)-AMP(177)
     $ +1D0/6D0*AMP(179)-AMP(181)-AMP(182)+1D0/2D0*AMP(185)-1D0/2D0
     $ *AMP(189)-AMP(186)+1D0/6D0*AMP(188)+1D0/2D0*AMP(192)

      M82_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M82_MATRIX = M82_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M82_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M82_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M82_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M82_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M82_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=64)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M82_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M82_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M82_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M82_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

