      SUBROUTINE M15_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M15_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M15_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M15_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: d u~ > t~ b g ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     Process: s c~ > t~ b g ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M15_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M15_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M15_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,7) / 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,   2),I=1,7) / 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,   3),I=1,7) / 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,   4),I=1,7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,   5),I=1,7) / 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,   6),I=1,7) / 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,   7),I=1,7) / 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,   8),I=1,7) / 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,   9),I=1,7) / 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,7) / 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,7) / 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,7) / 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,7) / 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,7) / 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  18),I=1,7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  19),I=1,7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  20),I=1,7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  21),I=1,7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  22),I=1,7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  23),I=1,7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  24),I=1,7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  25),I=1,7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  26),I=1,7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  27),I=1,7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  28),I=1,7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  29),I=1,7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  30),I=1,7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  31),I=1,7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  32),I=1,7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  33),I=1,7) / 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,7) / 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,7) / 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,7) / 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,7) / 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,7) / 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,7) / 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,7) / 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,7) / 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  42),I=1,7) / 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  43),I=1,7) / 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  44),I=1,7) / 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  45),I=1,7) / 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  46),I=1,7) / 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  47),I=1,7) / 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  48),I=1,7) / 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  49),I=1,7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  50),I=1,7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  51),I=1,7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  52),I=1,7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  53),I=1,7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  54),I=1,7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  55),I=1,7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  56),I=1,7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  57),I=1,7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  58),I=1,7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  59),I=1,7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  60),I=1,7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  61),I=1,7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  62),I=1,7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  63),I=1,7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  64),I=1,7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  65),I=1,7) /-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  66),I=1,7) /-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  67),I=1,7) /-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  68),I=1,7) /-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  69),I=1,7) /-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  70),I=1,7) /-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  71),I=1,7) /-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  72),I=1,7) /-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  73),I=1,7) /-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  74),I=1,7) /-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  75),I=1,7) /-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  76),I=1,7) /-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  77),I=1,7) /-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  78),I=1,7) /-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  79),I=1,7) /-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  80),I=1,7) /-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  81),I=1,7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  82),I=1,7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  83),I=1,7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  84),I=1,7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  85),I=1,7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  86),I=1,7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  87),I=1,7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  88),I=1,7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  89),I=1,7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  90),I=1,7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  91),I=1,7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  92),I=1,7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  93),I=1,7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  94),I=1,7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  95),I=1,7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  96),I=1,7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  97),I=1,7) /-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  98),I=1,7) /-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  99),I=1,7) /-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 100),I=1,7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 101),I=1,7) /-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 102),I=1,7) /-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 103),I=1,7) /-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 104),I=1,7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 105),I=1,7) /-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 106),I=1,7) /-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 107),I=1,7) /-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 108),I=1,7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 109),I=1,7) /-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 110),I=1,7) /-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 111),I=1,7) /-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 112),I=1,7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 113),I=1,7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 114),I=1,7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 115),I=1,7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 116),I=1,7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 117),I=1,7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 118),I=1,7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 119),I=1,7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 120),I=1,7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 121),I=1,7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 122),I=1,7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 123),I=1,7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 124),I=1,7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 125),I=1,7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 126),I=1,7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 127),I=1,7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 128),I=1,7) /-1, 1,-1, 1, 1,-1, 1/
      DATA IDEN/36/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M15_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M15_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M15_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M15_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M15_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M15_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: d u~ > t~ b g ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     Process: s c~ > t~ b g ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=80)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=18, NCOLOR=4)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  4) /   12,    4,    4,    0/
C     1 T(2,1) T(5,4,3)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  4) /    4,   12,    0,    4/
C     1 T(2,3) T(5,4,1)
      DATA DENOM(3)/1/
      DATA (CF(I,  3),I=  1,  4) /    4,    0,   12,    4/
C     1 T(4,1) T(5,2,3)
      DATA DENOM(4)/1/
      DATA (CF(I,  4),I=  1,  4) /    0,    4,    4,   12/
C     1 T(4,3) T(5,2,1)
C     ----------
C     BEGIN CODE
C     ----------
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL IXXXXX(P(0,3),MDL_MT,NHEL(3),-1*IC(3),W(1,3))
      CALL OXXXXX(P(0,4),MDL_MB,NHEL(4),+1*IC(4),W(1,4))
      CALL VXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),MDL_MTA,NHEL(6),-1*IC(6),W(1,6))
      CALL OXXXXX(P(0,7),MDL_MTA,NHEL(7),+1*IC(7),W(1,7))
      CALL FFV1_2(W(1,1),W(1,5),GC_7,ZERO,ZERO,W(1,8))
      CALL FFV1P0_3(W(1,6),W(1,7),GC_3,ZERO,ZERO,W(1,9))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,8),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,10))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,8),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 1
      CALL FFV6_0(W(1,10),W(1,4),W(1,9),GC_1,AMP(1))
      CALL FFV6_0(W(1,11),W(1,4),W(1,9),GC_1,AMP(2))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,8),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,8),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,13))
C     Amplitude(s) for diagram number 2
      CALL FFV6_0(W(1,3),W(1,12),W(1,9),GC_2,AMP(3))
      CALL FFV6_0(W(1,3),W(1,13),W(1,9),GC_2,AMP(4))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,14))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 3
      CALL FFV1_0(W(1,14),W(1,2),W(1,9),GC_2,AMP(5))
      CALL FFV1_0(W(1,15),W(1,2),W(1,9),GC_2,AMP(6))
      CALL FFV2_7_3(W(1,6),W(1,7),GC_650,GC_661,MDL_MZ,MDL_WZ,W(1,16))
C     Amplitude(s) for diagram number 4
      CALL FFV2_5_0(W(1,10),W(1,4),W(1,16),GC_650,GC_660,AMP(7))
      CALL FFV2_5_0(W(1,11),W(1,4),W(1,16),GC_650,GC_660,AMP(8))
C     Amplitude(s) for diagram number 5
      CALL FFV2_8_0(W(1,3),W(1,12),W(1,16),GC_651,GC_660,AMP(9))
      CALL FFV2_8_0(W(1,3),W(1,13),W(1,16),GC_651,GC_660,AMP(10))
C     Amplitude(s) for diagram number 6
      CALL FFV2_8_0(W(1,14),W(1,2),W(1,16),GC_651,GC_660,AMP(11))
      CALL FFV2_8_0(W(1,15),W(1,2),W(1,16),GC_651,GC_660,AMP(12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,4),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,15))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,4),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 7
      CALL FFV1_0(W(1,8),W(1,15),W(1,9),GC_1,AMP(13))
      CALL FFV1_0(W(1,8),W(1,14),W(1,9),GC_1,AMP(14))
C     Amplitude(s) for diagram number 8
      CALL FFV2_5_0(W(1,8),W(1,15),W(1,16),GC_650,GC_660,AMP(15))
      CALL FFV2_5_0(W(1,8),W(1,14),W(1,16),GC_650,GC_660,AMP(16))
      CALL FFV1_1(W(1,2),W(1,5),GC_7,ZERO,ZERO,W(1,8))
      CALL FFV1_2(W(1,1),W(1,9),GC_1,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 9
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,4),W(1,13),W(1
     $ ,8),GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,AMP(17))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,4),W(1,13),W(1
     $ ,8),GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,AMP(18))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,1),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,1),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 10
      CALL FFV6_0(W(1,12),W(1,4),W(1,9),GC_1,AMP(19))
      CALL FFV6_0(W(1,11),W(1,4),W(1,9),GC_1,AMP(20))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,1),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,10))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,1),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,7))
C     Amplitude(s) for diagram number 11
      CALL FFV6_0(W(1,3),W(1,10),W(1,9),GC_2,AMP(21))
      CALL FFV6_0(W(1,3),W(1,7),W(1,9),GC_2,AMP(22))
      CALL FFV2_5_2(W(1,1),W(1,16),GC_650,GC_660,ZERO,ZERO,W(1,6))
C     Amplitude(s) for diagram number 12
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,4),W(1,6),W(1,8)
     $ ,GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,AMP(23))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,4),W(1,6),W(1,8)
     $ ,GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,AMP(24))
C     Amplitude(s) for diagram number 13
      CALL FFV2_5_0(W(1,12),W(1,4),W(1,16),GC_650,GC_660,AMP(25))
      CALL FFV2_5_0(W(1,11),W(1,4),W(1,16),GC_650,GC_660,AMP(26))
C     Amplitude(s) for diagram number 14
      CALL FFV2_8_0(W(1,3),W(1,10),W(1,16),GC_651,GC_660,AMP(27))
      CALL FFV2_8_0(W(1,3),W(1,7),W(1,16),GC_651,GC_660,AMP(28))
      CALL FFV6_2(W(1,3),W(1,5),GC_7,MDL_MT,MDL_WT,W(1,7))
C     Amplitude(s) for diagram number 15
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,7),W(1,4),W(1,13),W(1
     $ ,2),GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,AMP(29))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,7),W(1,4),W(1,13),W(1
     $ ,2),GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,AMP(30))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,7),W(1,1),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,10))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,7),W(1,1),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 16
      CALL FFV6_0(W(1,10),W(1,4),W(1,9),GC_1,AMP(31))
      CALL FFV6_0(W(1,11),W(1,4),W(1,9),GC_1,AMP(32))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,7),W(1,4),W(1,1),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,7),W(1,4),W(1,1),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,12),W(1,2),W(1,9),GC_2,AMP(33))
      CALL FFV1_0(W(1,17),W(1,2),W(1,9),GC_2,AMP(34))
C     Amplitude(s) for diagram number 18
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,7),W(1,4),W(1,6),W(1,2)
     $ ,GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,AMP(35))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,7),W(1,4),W(1,6),W(1,2)
     $ ,GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,AMP(36))
C     Amplitude(s) for diagram number 19
      CALL FFV2_5_0(W(1,10),W(1,4),W(1,16),GC_650,GC_660,AMP(37))
      CALL FFV2_5_0(W(1,11),W(1,4),W(1,16),GC_650,GC_660,AMP(38))
C     Amplitude(s) for diagram number 20
      CALL FFV2_8_0(W(1,12),W(1,2),W(1,16),GC_651,GC_660,AMP(39))
      CALL FFV2_8_0(W(1,17),W(1,2),W(1,16),GC_651,GC_660,AMP(40))
      CALL FFV1_1(W(1,4),W(1,5),GC_7,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 21
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,17),W(1,13),W(1
     $ ,2),GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,AMP(41))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,17),W(1,13),W(1
     $ ,2),GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,AMP(42))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,17),W(1,1),W(1,2)
     $ ,GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,MDL_MT,MDL_WT,W(1,12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,17),W(1,1),W(1,2)
     $ ,GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,MDL_MT,MDL_WT,W(1,11))
C     Amplitude(s) for diagram number 22
      CALL FFV6_0(W(1,3),W(1,12),W(1,9),GC_2,AMP(43))
      CALL FFV6_0(W(1,3),W(1,11),W(1,9),GC_2,AMP(44))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,17),W(1,1)
     $ ,GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,ZERO,ZERO,W(1,10))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,17),W(1,1)
     $ ,GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 23
      CALL FFV1_0(W(1,10),W(1,2),W(1,9),GC_2,AMP(45))
      CALL FFV1_0(W(1,18),W(1,2),W(1,9),GC_2,AMP(46))
C     Amplitude(s) for diagram number 24
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,17),W(1,6),W(1
     $ ,2),GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,AMP(47))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_0(W(1,3),W(1,17),W(1,6),W(1
     $ ,2),GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,AMP(48))
C     Amplitude(s) for diagram number 25
      CALL FFV2_8_0(W(1,3),W(1,12),W(1,16),GC_651,GC_660,AMP(49))
      CALL FFV2_8_0(W(1,3),W(1,11),W(1,16),GC_651,GC_660,AMP(50))
C     Amplitude(s) for diagram number 26
      CALL FFV2_8_0(W(1,10),W(1,2),W(1,16),GC_651,GC_660,AMP(51))
      CALL FFV2_8_0(W(1,18),W(1,2),W(1,16),GC_651,GC_660,AMP(52))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,1),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,18))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,1),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,10))
C     Amplitude(s) for diagram number 27
      CALL FFV6_0(W(1,18),W(1,17),W(1,9),GC_1,AMP(53))
      CALL FFV6_0(W(1,10),W(1,17),W(1,9),GC_1,AMP(54))
C     Amplitude(s) for diagram number 28
      CALL FFV2_5_0(W(1,18),W(1,17),W(1,16),GC_650,GC_660,AMP(55))
      CALL FFV2_5_0(W(1,10),W(1,17),W(1,16),GC_650,GC_660,AMP(56))
      CALL FFV1_2(W(1,18),W(1,5),GC_7,MDL_MB,ZERO,W(1,17))
      CALL FFV1_2(W(1,10),W(1,5),GC_7,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 29
      CALL FFV6_0(W(1,17),W(1,4),W(1,9),GC_1,AMP(57))
      CALL FFV6_0(W(1,18),W(1,4),W(1,9),GC_1,AMP(58))
C     Amplitude(s) for diagram number 30
      CALL FFV2_5_0(W(1,17),W(1,4),W(1,16),GC_650,GC_660,AMP(59))
      CALL FFV2_5_0(W(1,18),W(1,4),W(1,16),GC_650,GC_660,AMP(60))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,1),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,18))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,1),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 31
      CALL FFV6_0(W(1,7),W(1,18),W(1,9),GC_2,AMP(61))
      CALL FFV6_0(W(1,7),W(1,17),W(1,9),GC_2,AMP(62))
C     Amplitude(s) for diagram number 32
      CALL FFV2_8_0(W(1,7),W(1,18),W(1,16),GC_651,GC_660,AMP(63))
      CALL FFV2_8_0(W(1,7),W(1,17),W(1,16),GC_651,GC_660,AMP(64))
      CALL FFV6_1(W(1,18),W(1,5),GC_7,MDL_MT,MDL_WT,W(1,7))
      CALL FFV6_1(W(1,17),W(1,5),GC_7,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 33
      CALL FFV6_0(W(1,3),W(1,7),W(1,9),GC_2,AMP(65))
      CALL FFV6_0(W(1,3),W(1,18),W(1,9),GC_2,AMP(66))
C     Amplitude(s) for diagram number 34
      CALL FFV2_8_0(W(1,3),W(1,7),W(1,16),GC_651,GC_660,AMP(67))
      CALL FFV2_8_0(W(1,3),W(1,18),W(1,16),GC_651,GC_660,AMP(68))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,1),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,18))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,1),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 35
      CALL FFV1_0(W(1,18),W(1,8),W(1,9),GC_2,AMP(69))
      CALL FFV1_0(W(1,7),W(1,8),W(1,9),GC_2,AMP(70))
C     Amplitude(s) for diagram number 36
      CALL FFV2_8_0(W(1,18),W(1,8),W(1,16),GC_651,GC_660,AMP(71))
      CALL FFV2_8_0(W(1,7),W(1,8),W(1,16),GC_651,GC_660,AMP(72))
      CALL FFV1_2(W(1,18),W(1,5),GC_7,ZERO,ZERO,W(1,8))
      CALL FFV1_2(W(1,7),W(1,5),GC_7,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,8),W(1,2),W(1,9),GC_2,AMP(73))
      CALL FFV1_0(W(1,18),W(1,2),W(1,9),GC_2,AMP(74))
C     Amplitude(s) for diagram number 38
      CALL FFV2_8_0(W(1,8),W(1,2),W(1,16),GC_651,GC_660,AMP(75))
      CALL FFV2_8_0(W(1,18),W(1,2),W(1,16),GC_651,GC_660,AMP(76))
C     Amplitude(s) for diagram number 39
      CALL FFV1_0(W(1,13),W(1,15),W(1,5),GC_7,AMP(77))
      CALL FFV1_0(W(1,13),W(1,14),W(1,5),GC_7,AMP(78))
C     Amplitude(s) for diagram number 40
      CALL FFV1_0(W(1,6),W(1,15),W(1,5),GC_7,AMP(79))
      CALL FFV1_0(W(1,6),W(1,14),W(1,5),GC_7,AMP(80))
      JAMP(1)=-1D0/6D0*AMP(30)+AMP(29)+AMP(31)-1D0/6D0*AMP(32)+AMP(33)
     $ -1D0/6D0*AMP(34)-1D0/6D0*AMP(36)+AMP(35)+AMP(37)-1D0/6D0*AMP(38)
     $ +AMP(39)-1D0/6D0*AMP(40)-1D0/6D0*AMP(42)+AMP(41)+AMP(43)-1D0
     $ /6D0*AMP(44)+AMP(45)-1D0/6D0*AMP(46)-1D0/6D0*AMP(48)+AMP(47)
     $ +AMP(49)-1D0/6D0*AMP(50)+AMP(51)-1D0/6D0*AMP(52)+AMP(53)-1D0
     $ /6D0*AMP(54)+AMP(55)-1D0/6D0*AMP(56)+AMP(57)-1D0/6D0*AMP(58)
     $ +AMP(59)-1D0/6D0*AMP(60)+AMP(61)-1D0/6D0*AMP(62)+AMP(63)-1D0
     $ /6D0*AMP(64)+AMP(65)-1D0/6D0*AMP(66)+AMP(67)-1D0/6D0*AMP(68)
      JAMP(2)=+1D0/2D0*(+AMP(2)+AMP(4)+AMP(6)+AMP(8)+AMP(10)+AMP(12)
     $ +AMP(14)+AMP(16)+AMP(42)+AMP(44)+AMP(46)+AMP(48)+AMP(50)+AMP(52)
     $ +AMP(54)+AMP(56)+AMP(58)+AMP(60)+AMP(78)+AMP(80))
      JAMP(3)=+1D0/2D0*(+AMP(18)+AMP(20)+AMP(22)+AMP(24)+AMP(26)
     $ +AMP(28)+AMP(30)+AMP(32)+AMP(34)+AMP(36)+AMP(38)+AMP(40)+AMP(62)
     $ +AMP(64)+AMP(66)+AMP(68)+AMP(70)+AMP(72)+AMP(74)+AMP(76))
      JAMP(4)=+AMP(1)-1D0/6D0*AMP(2)+AMP(3)-1D0/6D0*AMP(4)+AMP(5)-1D0
     $ /6D0*AMP(6)+AMP(7)-1D0/6D0*AMP(8)+AMP(9)-1D0/6D0*AMP(10)+AMP(11)
     $ -1D0/6D0*AMP(12)+AMP(13)-1D0/6D0*AMP(14)+AMP(15)-1D0/6D0*AMP(16)
     $ -1D0/6D0*AMP(18)+AMP(17)+AMP(19)-1D0/6D0*AMP(20)+AMP(21)-1D0
     $ /6D0*AMP(22)-1D0/6D0*AMP(24)+AMP(23)+AMP(25)-1D0/6D0*AMP(26)
     $ +AMP(27)-1D0/6D0*AMP(28)+AMP(69)-1D0/6D0*AMP(70)+AMP(71)-1D0
     $ /6D0*AMP(72)+AMP(73)-1D0/6D0*AMP(74)+AMP(75)-1D0/6D0*AMP(76)
     $ +AMP(77)-1D0/6D0*AMP(78)+AMP(79)-1D0/6D0*AMP(80)

      M15_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M15_MATRIX = M15_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M15_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M15_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M15_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M15_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M15_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NCOMB
      PARAMETER (NCOMB=128)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M15_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M15_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M15_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M15_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

