C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjP(-3,1)*ProjP(-2,3)
C     
      SUBROUTINE FFFF16_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP43
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      TMP43 = (F1(5)*F3(6)*(F2(4)*F4(3)-F2(3)*F4(4))+F1(6)*F3(5)*(F2(3)
     $ *F4(4)-F2(4)*F4(3)))
      VERTEX = COUP*(-2D0 * CI * TMP43)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(-1,2,-2)*Gamma(-1,4,-3)*ProjP(-3,1)*ProjP(-2,3)
C     
      SUBROUTINE FFFF16_5_111_0(F1, F2, F3, F4, COUP1, COUP2, COUP3
     $ ,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP
      COMPLEX*16 F3(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP3
      COMPLEX*16 F4(*)
      CALL FFFF16_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF5_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF111_0(F1,F2,F3,F4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      END


