C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)*ProjP(4,3)
C     
      SUBROUTINE FFFF10_3(F1, F2, F4, COUP, M3, W3,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(6)
      COMPLEX*16 COUP
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP18
      F3(1) = +F1(1)+F2(1)+F4(1)
      F3(2) = +F1(2)+F2(2)+F4(2)
      P3(0) = -DBLE(F3(1))
      P3(1) = -DBLE(F3(2))
      P3(2) = -DIMAG(F3(2))
      P3(3) = -DIMAG(F3(1))
      TMP18 = (F1(3)*F2(3)+F1(4)*F2(4))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      F3(3)= DENOM*(-CI )* TMP18*(F4(5)*(P3(0)+P3(3))+F4(6)*(P3(1)+CI
     $ *(P3(2))))
      F3(4)= DENOM*CI * TMP18*(F4(5)*(+CI*(P3(2))-P3(1))+F4(6)*(P3(3)
     $ -P3(0)))
      F3(5)= DENOM*CI * F4(5)*TMP18*M3
      F3(6)= DENOM*CI * F4(6)*TMP18*M3
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)*ProjP(4,3)
C     
      SUBROUTINE FFFF10_14_18_19_6_8_3(F1, F2, F4, COUP1, COUP2, COUP3
     $ , COUP4, COUP5, COUP6, M3, W3,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 COUP6
      COMPLEX*16 FTMP(6)
      REAL*8 W3
      COMPLEX*16 COUP5
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP2
      COMPLEX*16 F3(6)
      COMPLEX*16 COUP4
      COMPLEX*16 COUP3
      INTEGER*4 I
      COMPLEX*16 F4(*)
      CALL FFFF10_3(F1,F2,F4,COUP1,M3,W3,F3)
      CALL FFFF14_3(F1,F2,F4,COUP2,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF18_3(F1,F2,F4,COUP3,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF19_3(F1,F2,F4,COUP4,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF6_3(F1,F2,F4,COUP5,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      CALL FFFF8_3(F1,F2,F4,COUP6,M3,W3,FTMP)
      DO I = 3, 6
        F3(I) = F3(I) + FTMP(I)
      ENDDO
      END


