      SUBROUTINE M80_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M80_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M80_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M80_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: b b~ > t t~ ta+ ta- DIM6<=1 FCNC=0 / h
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M80_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M80_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M80_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   2),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   3),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   4),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   5),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   6),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   7),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   8),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  13),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  14),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  15),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  16),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  17),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  18),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  19),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  20),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  21),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  22),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  23),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  24),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  33),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  34),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  35),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  36),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  37),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  38),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  39),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  40),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  41),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  42),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  43),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  44),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  45),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  46),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  47),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  48),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  49),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  50),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  51),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  52),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  53),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  54),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  55),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  56),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  57),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  58),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  59),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  60),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  61),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  62),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  63),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  64),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA IDEN/36/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M80_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M80_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M80_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M80_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M80_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M80_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: b b~ > t t~ ta+ ta- DIM6<=1 FCNC=0 / h
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=339)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=32, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  2) /    9,    3/
C     1 T(2,1) T(3,4)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  2) /    3,    9/
C     1 T(2,4) T(3,1)
C     ----------
C     BEGIN CODE
C     ----------
      CALL IXXXXX(P(0,1),MDL_MB,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),MDL_MB,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL IXXXXX(P(0,5),MDL_MTA,NHEL(5),-1*IC(5),W(1,5))
      CALL OXXXXX(P(0,6),MDL_MTA,NHEL(6),+1*IC(6),W(1,6))
      CALL FFV6P0_3(W(1,1),W(1,2),GC_1,ZERO,ZERO,W(1,7))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_2,ZERO,ZERO,W(1,8))
      CALL FFV1_2(W(1,5),W(1,7),GC_3,MDL_MTA,ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(1))
      CALL FFV1_1(W(1,6),W(1,7),GC_3,MDL_MTA,ZERO,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,5),W(1,10),W(1,8),GC_3,AMP(2))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_813,GC_814,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL FFV1_0(W(1,9),W(1,6),W(1,11),GC_3,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0(W(1,5),W(1,10),W(1,11),GC_3,AMP(4))
      CALL FFV2_8_3(W(1,4),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,12))
C     Amplitude(s) for diagram number 5
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,12),GC_650,GC_661,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV2_7_0(W(1,5),W(1,10),W(1,12),GC_650,GC_661,AMP(6))
      CALL FFV11_9_3(W(1,4),W(1,3),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,13))
C     Amplitude(s) for diagram number 7
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,13),GC_650,GC_661,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV2_7_0(W(1,5),W(1,10),W(1,13),GC_650,GC_661,AMP(8))
      CALL FFV4_3(W(1,4),W(1,3),GC_948,MDL_MZ,MDL_WZ,W(1,14))
C     Amplitude(s) for diagram number 9
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,14),GC_650,GC_661,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV2_7_0(W(1,5),W(1,10),W(1,14),GC_650,GC_661,AMP(10))
      CALL FFV2_3(W(1,4),W(1,3),GC_938,MDL_MZ,MDL_WZ,W(1,15))
C     Amplitude(s) for diagram number 11
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,15),GC_650,GC_661,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFV2_7_0(W(1,5),W(1,10),W(1,15),GC_650,GC_661,AMP(12))
      CALL FFV11_9P0_3(W(1,1),W(1,2),GC_736,GC_737,ZERO,ZERO,W(1,10))
      CALL FFV1_2(W(1,5),W(1,10),GC_3,MDL_MTA,ZERO,W(1,9))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(13))
      CALL FFV1_1(W(1,6),W(1,10),GC_3,MDL_MTA,ZERO,W(1,16))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,5),W(1,16),W(1,8),GC_3,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,12),GC_650,GC_661,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFV2_7_0(W(1,5),W(1,16),W(1,12),GC_650,GC_661,AMP(16))
      CALL FFV2_5_3(W(1,1),W(1,2),GC_650,GC_660,MDL_MZ,MDL_WZ,W(1,16))
      CALL FFV2_7_2(W(1,5),W(1,16),GC_650,GC_661,MDL_MTA,ZERO,W(1,9))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(17))
      CALL FFV2_7_1(W(1,6),W(1,16),GC_650,GC_661,MDL_MTA,ZERO,W(1,17))
C     Amplitude(s) for diagram number 18
      CALL FFV1_0(W(1,5),W(1,17),W(1,8),GC_3,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL FFV1_0(W(1,9),W(1,6),W(1,11),GC_3,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV1_0(W(1,5),W(1,17),W(1,11),GC_3,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,12),GC_650,GC_661,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV2_7_0(W(1,5),W(1,17),W(1,12),GC_650,GC_661,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,13),GC_650,GC_661,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV2_7_0(W(1,5),W(1,17),W(1,13),GC_650,GC_661,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,14),GC_650,GC_661,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV2_7_0(W(1,5),W(1,17),W(1,14),GC_650,GC_661,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,15),GC_650,GC_661,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFV2_7_0(W(1,5),W(1,17),W(1,15),GC_650,GC_661,AMP(28))
      CALL FFV11_9_3(W(1,1),W(1,2),GC_723,GC_724,MDL_MZ,MDL_WZ,W(1,17))
      CALL FFV2_7_2(W(1,5),W(1,17),GC_650,GC_661,MDL_MTA,ZERO,W(1,9))
C     Amplitude(s) for diagram number 29
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(29))
      CALL FFV2_7_1(W(1,6),W(1,17),GC_650,GC_661,MDL_MTA,ZERO,W(1,18))
C     Amplitude(s) for diagram number 30
      CALL FFV1_0(W(1,5),W(1,18),W(1,8),GC_3,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,12),GC_650,GC_661,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFV2_7_0(W(1,5),W(1,18),W(1,12),GC_650,GC_661,AMP(32))
      CALL FFV4_3(W(1,1),W(1,2),GC_933,MDL_MZ,MDL_WZ,W(1,18))
      CALL FFV2_7_2(W(1,5),W(1,18),GC_650,GC_661,MDL_MTA,ZERO,W(1,9))
C     Amplitude(s) for diagram number 33
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(33))
      CALL FFV2_7_1(W(1,6),W(1,18),GC_650,GC_661,MDL_MTA,ZERO,W(1,19))
C     Amplitude(s) for diagram number 34
      CALL FFV1_0(W(1,5),W(1,19),W(1,8),GC_3,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,12),GC_650,GC_661,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV2_7_0(W(1,5),W(1,19),W(1,12),GC_650,GC_661,AMP(36))
      CALL FFV2_3(W(1,1),W(1,2),GC_939,MDL_MZ,MDL_WZ,W(1,19))
      CALL FFV2_7_2(W(1,5),W(1,19),GC_650,GC_661,MDL_MTA,ZERO,W(1,9))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(37))
      CALL FFV2_7_1(W(1,6),W(1,19),GC_650,GC_661,MDL_MTA,ZERO,W(1,20))
C     Amplitude(s) for diagram number 38
      CALL FFV1_0(W(1,5),W(1,20),W(1,8),GC_3,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV2_7_0(W(1,9),W(1,6),W(1,12),GC_650,GC_661,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV2_7_0(W(1,5),W(1,20),W(1,12),GC_650,GC_661,AMP(40))
      CALL FFV1P0_3(W(1,5),W(1,6),GC_3,ZERO,ZERO,W(1,20))
      CALL FFV6_1(W(1,3),W(1,7),GC_2,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 41
      CALL FFV6_0(W(1,4),W(1,9),W(1,20),GC_2,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV11_9_0(W(1,4),W(1,9),W(1,20),GC_813,GC_814,AMP(42))
      CALL FFV11_9_1(W(1,3),W(1,7),GC_813,GC_814,MDL_MT,MDL_WT,W(1,21))
C     Amplitude(s) for diagram number 43
      CALL FFV6_0(W(1,4),W(1,21),W(1,20),GC_2,AMP(43))
      CALL FFV6_2(W(1,4),W(1,7),GC_2,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 44
      CALL FFV6_0(W(1,22),W(1,3),W(1,20),GC_2,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV11_9_0(W(1,22),W(1,3),W(1,20),GC_813,GC_814,AMP(45))
      CALL FFV11_9_2(W(1,4),W(1,7),GC_813,GC_814,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 46
      CALL FFV6_0(W(1,23),W(1,3),W(1,20),GC_2,AMP(46))
      CALL FFV2_7_3(W(1,5),W(1,6),GC_650,GC_661,MDL_MZ,MDL_WZ,W(1,24))
C     Amplitude(s) for diagram number 47
      CALL FFV2_8_0(W(1,4),W(1,9),W(1,24),GC_651,GC_660,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV11_9_0(W(1,4),W(1,9),W(1,24),GC_721,GC_722,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV4_0(W(1,4),W(1,9),W(1,24),GC_948,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV2_0(W(1,4),W(1,9),W(1,24),GC_938,AMP(50))
C     Amplitude(s) for diagram number 51
      CALL FFV2_8_0(W(1,4),W(1,21),W(1,24),GC_651,GC_660,AMP(51))
C     Amplitude(s) for diagram number 52
      CALL FFV2_8_0(W(1,22),W(1,3),W(1,24),GC_651,GC_660,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFV11_9_0(W(1,22),W(1,3),W(1,24),GC_721,GC_722,AMP(53))
C     Amplitude(s) for diagram number 54
      CALL FFV4_0(W(1,22),W(1,3),W(1,24),GC_948,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV2_0(W(1,22),W(1,3),W(1,24),GC_938,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV2_8_0(W(1,23),W(1,3),W(1,24),GC_651,GC_660,AMP(56))
      CALL FFV6_1(W(1,3),W(1,10),GC_2,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 57
      CALL FFV6_0(W(1,4),W(1,23),W(1,20),GC_2,AMP(57))
      CALL FFV6_2(W(1,4),W(1,10),GC_2,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 58
      CALL FFV6_0(W(1,22),W(1,3),W(1,20),GC_2,AMP(58))
C     Amplitude(s) for diagram number 59
      CALL FFV2_8_0(W(1,4),W(1,23),W(1,24),GC_651,GC_660,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFV2_8_0(W(1,22),W(1,3),W(1,24),GC_651,GC_660,AMP(60))
      CALL FFV2_8_1(W(1,3),W(1,16),GC_651,GC_660,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 61
      CALL FFV6_0(W(1,4),W(1,22),W(1,20),GC_2,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL FFV11_9_0(W(1,4),W(1,22),W(1,20),GC_813,GC_814,AMP(62))
      CALL FFV11_9_1(W(1,3),W(1,16),GC_721,GC_722,MDL_MT,MDL_WT,W(1,23)
     $ )
C     Amplitude(s) for diagram number 63
      CALL FFV6_0(W(1,4),W(1,23),W(1,20),GC_2,AMP(63))
      CALL FFV4_1(W(1,3),W(1,16),GC_948,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 64
      CALL FFV6_0(W(1,4),W(1,10),W(1,20),GC_2,AMP(64))
      CALL FFV2_1(W(1,3),W(1,16),GC_938,MDL_MT,MDL_WT,W(1,21))
C     Amplitude(s) for diagram number 65
      CALL FFV6_0(W(1,4),W(1,21),W(1,20),GC_2,AMP(65))
      CALL FFV2_8_2(W(1,4),W(1,16),GC_651,GC_660,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 66
      CALL FFV6_0(W(1,9),W(1,3),W(1,20),GC_2,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL FFV11_9_0(W(1,9),W(1,3),W(1,20),GC_813,GC_814,AMP(67))
      CALL FFV11_9_2(W(1,4),W(1,16),GC_721,GC_722,MDL_MT,MDL_WT,W(1,25)
     $ )
C     Amplitude(s) for diagram number 68
      CALL FFV6_0(W(1,25),W(1,3),W(1,20),GC_2,AMP(68))
      CALL FFV4_2(W(1,4),W(1,16),GC_948,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 69
      CALL FFV6_0(W(1,26),W(1,3),W(1,20),GC_2,AMP(69))
      CALL FFV2_2(W(1,4),W(1,16),GC_938,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 70
      CALL FFV6_0(W(1,27),W(1,3),W(1,20),GC_2,AMP(70))
C     Amplitude(s) for diagram number 71
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,24),GC_651,GC_660,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL FFV11_9_0(W(1,4),W(1,22),W(1,24),GC_721,GC_722,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL FFV4_0(W(1,4),W(1,22),W(1,24),GC_948,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL FFV2_0(W(1,4),W(1,22),W(1,24),GC_938,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV2_8_0(W(1,4),W(1,23),W(1,24),GC_651,GC_660,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL FFV2_8_0(W(1,4),W(1,10),W(1,24),GC_651,GC_660,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL FFV2_8_0(W(1,4),W(1,21),W(1,24),GC_651,GC_660,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL FFV2_8_0(W(1,9),W(1,3),W(1,24),GC_651,GC_660,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV11_9_0(W(1,9),W(1,3),W(1,24),GC_721,GC_722,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV4_0(W(1,9),W(1,3),W(1,24),GC_948,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFV2_0(W(1,9),W(1,3),W(1,24),GC_938,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV2_8_0(W(1,25),W(1,3),W(1,24),GC_651,GC_660,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFV2_8_0(W(1,26),W(1,3),W(1,24),GC_651,GC_660,AMP(83))
C     Amplitude(s) for diagram number 84
      CALL FFV2_8_0(W(1,27),W(1,3),W(1,24),GC_651,GC_660,AMP(84))
      CALL FFV2_8_1(W(1,3),W(1,17),GC_651,GC_660,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 85
      CALL FFV6_0(W(1,4),W(1,27),W(1,20),GC_2,AMP(85))
      CALL FFV2_8_2(W(1,4),W(1,17),GC_651,GC_660,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 86
      CALL FFV6_0(W(1,26),W(1,3),W(1,20),GC_2,AMP(86))
C     Amplitude(s) for diagram number 87
      CALL FFV2_8_0(W(1,4),W(1,27),W(1,24),GC_651,GC_660,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV2_8_0(W(1,26),W(1,3),W(1,24),GC_651,GC_660,AMP(88))
      CALL FFV2_8_1(W(1,3),W(1,18),GC_651,GC_660,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 89
      CALL FFV6_0(W(1,4),W(1,26),W(1,20),GC_2,AMP(89))
      CALL FFV2_8_2(W(1,4),W(1,18),GC_651,GC_660,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 90
      CALL FFV6_0(W(1,27),W(1,3),W(1,20),GC_2,AMP(90))
C     Amplitude(s) for diagram number 91
      CALL FFV2_8_0(W(1,4),W(1,26),W(1,24),GC_651,GC_660,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL FFV2_8_0(W(1,27),W(1,3),W(1,24),GC_651,GC_660,AMP(92))
      CALL FFV2_8_1(W(1,3),W(1,19),GC_651,GC_660,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 93
      CALL FFV6_0(W(1,4),W(1,27),W(1,20),GC_2,AMP(93))
      CALL FFV2_8_2(W(1,4),W(1,19),GC_651,GC_660,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 94
      CALL FFV6_0(W(1,26),W(1,3),W(1,20),GC_2,AMP(94))
C     Amplitude(s) for diagram number 95
      CALL FFV2_8_0(W(1,4),W(1,27),W(1,24),GC_651,GC_660,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL FFV2_8_0(W(1,26),W(1,3),W(1,24),GC_651,GC_660,AMP(96))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_7,ZERO,ZERO,W(1,26))
      CALL FFV6_1(W(1,3),W(1,26),GC_7,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 97
      CALL FFV6_0(W(1,4),W(1,27),W(1,20),GC_2,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV11_9_0(W(1,4),W(1,27),W(1,20),GC_813,GC_814,AMP(98))
      CALL FFV11_9_1(W(1,3),W(1,26),GC_725,GC_726,MDL_MT,MDL_WT,W(1,19)
     $ )
C     Amplitude(s) for diagram number 99
      CALL FFV6_0(W(1,4),W(1,19),W(1,20),GC_2,AMP(99))
      CALL FFV6_2(W(1,4),W(1,26),GC_7,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 100
      CALL FFV6_0(W(1,18),W(1,3),W(1,20),GC_2,AMP(100))
C     Amplitude(s) for diagram number 101
      CALL FFV11_9_0(W(1,18),W(1,3),W(1,20),GC_813,GC_814,AMP(101))
      CALL FFV11_9_2(W(1,4),W(1,26),GC_725,GC_726,MDL_MT,MDL_WT,W(1,17)
     $ )
C     Amplitude(s) for diagram number 102
      CALL FFV6_0(W(1,17),W(1,3),W(1,20),GC_2,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL FFV2_8_0(W(1,4),W(1,27),W(1,24),GC_651,GC_660,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFV11_9_0(W(1,4),W(1,27),W(1,24),GC_721,GC_722,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV4_0(W(1,4),W(1,27),W(1,24),GC_948,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV2_0(W(1,4),W(1,27),W(1,24),GC_938,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFV2_8_0(W(1,4),W(1,19),W(1,24),GC_651,GC_660,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,24),GC_651,GC_660,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV11_9_0(W(1,18),W(1,3),W(1,24),GC_721,GC_722,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFV4_0(W(1,18),W(1,3),W(1,24),GC_948,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV2_0(W(1,18),W(1,3),W(1,24),GC_938,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV2_8_0(W(1,17),W(1,3),W(1,24),GC_651,GC_660,AMP(112))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,5),W(1,4),W(1,3)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MTA,ZERO,W(1,17))
C     Amplitude(s) for diagram number 113
      CALL FFV1_0(W(1,17),W(1,6),W(1,7),GC_3,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV2_7_0(W(1,17),W(1,6),W(1,16),GC_650,GC_661,AMP(114))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,6),W(1,4),W(1,3)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MTA,ZERO,W(1,17))
C     Amplitude(s) for diagram number 115
      CALL FFV1_0(W(1,5),W(1,17),W(1,7),GC_3,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFV2_7_0(W(1,5),W(1,17),W(1,16),GC_650,GC_661,AMP(116))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,5),W(1,6),W(1,3)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 117
      CALL FFV6_0(W(1,4),W(1,17),W(1,7),GC_2,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL FFV2_8_0(W(1,4),W(1,17),W(1,16),GC_651,GC_660,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFV6_0(W(1,4),W(1,17),W(1,26),GC_7,AMP(119))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,5),W(1,6),W(1,4)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 120
      CALL FFV6_0(W(1,18),W(1,3),W(1,7),GC_2,AMP(120))
C     Amplitude(s) for diagram number 121
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,16),GC_651,GC_660,AMP(121))
C     Amplitude(s) for diagram number 122
      CALL FFV6_0(W(1,18),W(1,3),W(1,26),GC_7,AMP(122))
      CALL FFV2_3(W(1,1),W(1,3),GC_649,MDL_MW,MDL_WW,W(1,26))
      CALL FFV2_3(W(1,4),W(1,2),GC_649,MDL_MW,MDL_WW,W(1,16))
      CALL FFV2_1(W(1,6),W(1,26),GC_649,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 123
      CALL FFV2_0(W(1,5),W(1,7),W(1,16),GC_649,AMP(123))
      CALL FFV4_3(W(1,4),W(1,2),GC_923,MDL_MW,MDL_WW,W(1,19))
C     Amplitude(s) for diagram number 124
      CALL FFV2_0(W(1,5),W(1,7),W(1,19),GC_649,AMP(124))
      CALL FFV10_3_3(W(1,4),W(1,2),GC_767,GC_742,MDL_MW,MDL_WW,W(1,27))
C     Amplitude(s) for diagram number 125
      CALL FFV2_0(W(1,5),W(1,7),W(1,27),GC_649,AMP(125))
      CALL FFV2_3(W(1,4),W(1,2),GC_740,MDL_MW,MDL_WW,W(1,25))
C     Amplitude(s) for diagram number 126
      CALL FFV2_0(W(1,5),W(1,7),W(1,25),GC_649,AMP(126))
      CALL FFV4_3(W(1,1),W(1,3),GC_924,MDL_MW,MDL_WW,W(1,7))
      CALL FFV2_1(W(1,6),W(1,7),GC_649,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 127
      CALL FFV2_0(W(1,5),W(1,9),W(1,16),GC_649,AMP(127))
      CALL FFV10_3_3(W(1,1),W(1,3),GC_741,GC_768,MDL_MW,MDL_WW,W(1,9))
      CALL FFV2_1(W(1,6),W(1,9),GC_649,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 128
      CALL FFV2_0(W(1,5),W(1,21),W(1,16),GC_649,AMP(128))
      CALL FFV2_3(W(1,1),W(1,3),GC_740,MDL_MW,MDL_WW,W(1,21))
      CALL FFV2_1(W(1,6),W(1,21),GC_649,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 129
      CALL FFV2_0(W(1,5),W(1,10),W(1,16),GC_649,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL VVV1_0(W(1,20),W(1,16),W(1,26),GC_4,AMP(130))
C     Amplitude(s) for diagram number 131
      CALL VVV1_0(W(1,16),W(1,26),W(1,24),GC_653,AMP(131))
C     Amplitude(s) for diagram number 132
      CALL VVV1_0(W(1,20),W(1,19),W(1,26),GC_4,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL VVV1_0(W(1,19),W(1,26),W(1,24),GC_653,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL VVV1_0(W(1,20),W(1,27),W(1,26),GC_4,AMP(134))
C     Amplitude(s) for diagram number 135
      CALL VVV1_0(W(1,27),W(1,26),W(1,24),GC_653,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL VVV1_0(W(1,20),W(1,25),W(1,26),GC_4,AMP(136))
C     Amplitude(s) for diagram number 137
      CALL VVV1_0(W(1,25),W(1,26),W(1,24),GC_653,AMP(137))
C     Amplitude(s) for diagram number 138
      CALL VVV1_0(W(1,20),W(1,16),W(1,7),GC_4,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL VVV1_0(W(1,16),W(1,7),W(1,24),GC_653,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL VVV1_0(W(1,20),W(1,16),W(1,9),GC_4,AMP(140))
C     Amplitude(s) for diagram number 141
      CALL VVV1_0(W(1,16),W(1,9),W(1,24),GC_653,AMP(141))
C     Amplitude(s) for diagram number 142
      CALL VVV1_0(W(1,20),W(1,16),W(1,21),GC_4,AMP(142))
C     Amplitude(s) for diagram number 143
      CALL VVV1_0(W(1,16),W(1,21),W(1,24),GC_653,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL FFVV1_3_0(W(1,4),W(1,2),W(1,20),W(1,26),GC_785,GC_795
     $ ,AMP(144))
      CALL FFV2_1(W(1,2),W(1,26),GC_649,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 145
      CALL FFV6_0(W(1,4),W(1,10),W(1,20),GC_2,AMP(145))
C     Amplitude(s) for diagram number 146
      CALL FFV11_9_0(W(1,4),W(1,10),W(1,20),GC_813,GC_814,AMP(146))
      CALL FFV4_1(W(1,2),W(1,26),GC_923,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 147
      CALL FFV6_0(W(1,4),W(1,23),W(1,20),GC_2,AMP(147))
      CALL FFV10_3_1(W(1,2),W(1,26),GC_767,GC_742,MDL_MT,MDL_WT,W(1,22)
     $ )
C     Amplitude(s) for diagram number 148
      CALL FFV6_0(W(1,4),W(1,22),W(1,20),GC_2,AMP(148))
      CALL FFV2_1(W(1,2),W(1,26),GC_740,MDL_MT,MDL_WT,W(1,28))
C     Amplitude(s) for diagram number 149
      CALL FFV6_0(W(1,4),W(1,28),W(1,20),GC_2,AMP(149))
      CALL FFV2_2(W(1,4),W(1,26),GC_649,MDL_MB,ZERO,W(1,29))
C     Amplitude(s) for diagram number 150
      CALL FFV6_0(W(1,29),W(1,2),W(1,20),GC_1,AMP(150))
C     Amplitude(s) for diagram number 151
      CALL FFV11_9_0(W(1,29),W(1,2),W(1,20),GC_736,GC_737,AMP(151))
      CALL FFV4_2(W(1,4),W(1,26),GC_923,MDL_MB,ZERO,W(1,30))
C     Amplitude(s) for diagram number 152
      CALL FFV6_0(W(1,30),W(1,2),W(1,20),GC_1,AMP(152))
      CALL FFV10_3_2(W(1,4),W(1,26),GC_767,GC_742,MDL_MB,ZERO,W(1,31))
C     Amplitude(s) for diagram number 153
      CALL FFV6_0(W(1,31),W(1,2),W(1,20),GC_1,AMP(153))
      CALL FFV2_2(W(1,4),W(1,26),GC_740,MDL_MB,ZERO,W(1,32))
C     Amplitude(s) for diagram number 154
      CALL FFV6_0(W(1,32),W(1,2),W(1,20),GC_1,AMP(154))
C     Amplitude(s) for diagram number 155
      CALL FFVV1_3_0(W(1,4),W(1,2),W(1,26),W(1,24),GC_838,GC_848
     $ ,AMP(155))
C     Amplitude(s) for diagram number 156
      CALL FFV2_8_0(W(1,4),W(1,10),W(1,24),GC_651,GC_660,AMP(156))
C     Amplitude(s) for diagram number 157
      CALL FFV11_9_0(W(1,4),W(1,10),W(1,24),GC_721,GC_722,AMP(157))
C     Amplitude(s) for diagram number 158
      CALL FFV4_0(W(1,4),W(1,10),W(1,24),GC_948,AMP(158))
C     Amplitude(s) for diagram number 159
      CALL FFV2_0(W(1,4),W(1,10),W(1,24),GC_938,AMP(159))
C     Amplitude(s) for diagram number 160
      CALL FFV2_8_0(W(1,4),W(1,23),W(1,24),GC_651,GC_660,AMP(160))
C     Amplitude(s) for diagram number 161
      CALL FFV2_8_0(W(1,4),W(1,22),W(1,24),GC_651,GC_660,AMP(161))
C     Amplitude(s) for diagram number 162
      CALL FFV2_8_0(W(1,4),W(1,28),W(1,24),GC_651,GC_660,AMP(162))
C     Amplitude(s) for diagram number 163
      CALL FFV2_5_0(W(1,29),W(1,2),W(1,24),GC_650,GC_660,AMP(163))
C     Amplitude(s) for diagram number 164
      CALL FFV11_9_0(W(1,29),W(1,2),W(1,24),GC_723,GC_724,AMP(164))
C     Amplitude(s) for diagram number 165
      CALL FFV4_0(W(1,29),W(1,2),W(1,24),GC_933,AMP(165))
C     Amplitude(s) for diagram number 166
      CALL FFV2_0(W(1,29),W(1,2),W(1,24),GC_939,AMP(166))
C     Amplitude(s) for diagram number 167
      CALL FFV2_5_0(W(1,30),W(1,2),W(1,24),GC_650,GC_660,AMP(167))
C     Amplitude(s) for diagram number 168
      CALL FFV2_5_0(W(1,31),W(1,2),W(1,24),GC_650,GC_660,AMP(168))
C     Amplitude(s) for diagram number 169
      CALL FFV2_5_0(W(1,32),W(1,2),W(1,24),GC_650,GC_660,AMP(169))
      CALL FFV2_1(W(1,2),W(1,7),GC_649,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 170
      CALL FFV6_0(W(1,4),W(1,32),W(1,20),GC_2,AMP(170))
      CALL FFV2_2(W(1,4),W(1,7),GC_649,MDL_MB,ZERO,W(1,31))
C     Amplitude(s) for diagram number 171
      CALL FFV6_0(W(1,31),W(1,2),W(1,20),GC_1,AMP(171))
C     Amplitude(s) for diagram number 172
      CALL FFV2_8_0(W(1,4),W(1,32),W(1,24),GC_651,GC_660,AMP(172))
C     Amplitude(s) for diagram number 173
      CALL FFV2_5_0(W(1,31),W(1,2),W(1,24),GC_650,GC_660,AMP(173))
      CALL FFV2_1(W(1,2),W(1,9),GC_649,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 174
      CALL FFV6_0(W(1,4),W(1,31),W(1,20),GC_2,AMP(174))
      CALL FFV2_2(W(1,4),W(1,9),GC_649,MDL_MB,ZERO,W(1,32))
C     Amplitude(s) for diagram number 175
      CALL FFV6_0(W(1,32),W(1,2),W(1,20),GC_1,AMP(175))
C     Amplitude(s) for diagram number 176
      CALL FFV2_8_0(W(1,4),W(1,31),W(1,24),GC_651,GC_660,AMP(176))
C     Amplitude(s) for diagram number 177
      CALL FFV2_5_0(W(1,32),W(1,2),W(1,24),GC_650,GC_660,AMP(177))
      CALL FFV2_1(W(1,2),W(1,21),GC_649,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 178
      CALL FFV6_0(W(1,4),W(1,32),W(1,20),GC_2,AMP(178))
      CALL FFV2_2(W(1,4),W(1,21),GC_649,MDL_MB,ZERO,W(1,31))
C     Amplitude(s) for diagram number 179
      CALL FFV6_0(W(1,31),W(1,2),W(1,20),GC_1,AMP(179))
C     Amplitude(s) for diagram number 180
      CALL FFV2_8_0(W(1,4),W(1,32),W(1,24),GC_651,GC_660,AMP(180))
C     Amplitude(s) for diagram number 181
      CALL FFV2_5_0(W(1,31),W(1,2),W(1,24),GC_650,GC_660,AMP(181))
      CALL FFFF10_11_20_6_110_4(W(1,4),W(1,2),W(1,5),GC_14,GC_353
     $ ,GC_351,GC_566,GC_350,ZERO,ZERO,W(1,31))
C     Amplitude(s) for diagram number 182
      CALL FFV2_0(W(1,31),W(1,6),W(1,26),GC_649,AMP(182))
      CALL FFFF10_14_6_8_3(W(1,5),W(1,6),W(1,2),GC_15,GC_563,GC_124
     $ ,GC_14,MDL_MB,ZERO,W(1,31))
C     Amplitude(s) for diagram number 183
      CALL FFV2_0(W(1,4),W(1,31),W(1,26),GC_649,AMP(183))
C     Amplitude(s) for diagram number 184
      CALL FFV2_0(W(1,18),W(1,2),W(1,26),GC_649,AMP(184))
C     Amplitude(s) for diagram number 185
      CALL FFVV1_3_0(W(1,1),W(1,3),W(1,20),W(1,16),GC_796,GC_786
     $ ,AMP(185))
      CALL FFV2_2(W(1,1),W(1,16),GC_649,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 186
      CALL FFV6_0(W(1,26),W(1,3),W(1,20),GC_2,AMP(186))
C     Amplitude(s) for diagram number 187
      CALL FFV11_9_0(W(1,26),W(1,3),W(1,20),GC_813,GC_814,AMP(187))
      CALL FFV4_2(W(1,1),W(1,16),GC_924,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 188
      CALL FFV6_0(W(1,18),W(1,3),W(1,20),GC_2,AMP(188))
      CALL FFV10_3_2(W(1,1),W(1,16),GC_741,GC_768,MDL_MT,MDL_WT,W(1,32)
     $ )
C     Amplitude(s) for diagram number 189
      CALL FFV6_0(W(1,32),W(1,3),W(1,20),GC_2,AMP(189))
      CALL FFV2_2(W(1,1),W(1,16),GC_740,MDL_MT,MDL_WT,W(1,21))
C     Amplitude(s) for diagram number 190
      CALL FFV6_0(W(1,21),W(1,3),W(1,20),GC_2,AMP(190))
      CALL FFV6_2(W(1,1),W(1,20),GC_1,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 191
      CALL FFV2_0(W(1,9),W(1,3),W(1,16),GC_649,AMP(191))
C     Amplitude(s) for diagram number 192
      CALL FFV4_0(W(1,9),W(1,3),W(1,16),GC_924,AMP(192))
C     Amplitude(s) for diagram number 193
      CALL FFV10_3_0(W(1,9),W(1,3),W(1,16),GC_741,GC_768,AMP(193))
C     Amplitude(s) for diagram number 194
      CALL FFV2_0(W(1,9),W(1,3),W(1,16),GC_740,AMP(194))
      CALL FFV11_9_2(W(1,1),W(1,20),GC_736,GC_737,MDL_MB,ZERO,W(1,7))
C     Amplitude(s) for diagram number 195
      CALL FFV2_0(W(1,7),W(1,3),W(1,16),GC_649,AMP(195))
C     Amplitude(s) for diagram number 196
      CALL FFVV1_3_0(W(1,1),W(1,3),W(1,16),W(1,24),GC_847,GC_837
     $ ,AMP(196))
C     Amplitude(s) for diagram number 197
      CALL FFV2_8_0(W(1,26),W(1,3),W(1,24),GC_651,GC_660,AMP(197))
C     Amplitude(s) for diagram number 198
      CALL FFV11_9_0(W(1,26),W(1,3),W(1,24),GC_721,GC_722,AMP(198))
C     Amplitude(s) for diagram number 199
      CALL FFV4_0(W(1,26),W(1,3),W(1,24),GC_948,AMP(199))
C     Amplitude(s) for diagram number 200
      CALL FFV2_0(W(1,26),W(1,3),W(1,24),GC_938,AMP(200))
C     Amplitude(s) for diagram number 201
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,24),GC_651,GC_660,AMP(201))
C     Amplitude(s) for diagram number 202
      CALL FFV2_8_0(W(1,32),W(1,3),W(1,24),GC_651,GC_660,AMP(202))
C     Amplitude(s) for diagram number 203
      CALL FFV2_8_0(W(1,21),W(1,3),W(1,24),GC_651,GC_660,AMP(203))
      CALL FFV2_5_2(W(1,1),W(1,24),GC_650,GC_660,MDL_MB,ZERO,W(1,21))
C     Amplitude(s) for diagram number 204
      CALL FFV2_0(W(1,21),W(1,3),W(1,16),GC_649,AMP(204))
C     Amplitude(s) for diagram number 205
      CALL FFV4_0(W(1,21),W(1,3),W(1,16),GC_924,AMP(205))
C     Amplitude(s) for diagram number 206
      CALL FFV10_3_0(W(1,21),W(1,3),W(1,16),GC_741,GC_768,AMP(206))
C     Amplitude(s) for diagram number 207
      CALL FFV2_0(W(1,21),W(1,3),W(1,16),GC_740,AMP(207))
      CALL FFV11_9_2(W(1,1),W(1,24),GC_723,GC_724,MDL_MB,ZERO,W(1,32))
C     Amplitude(s) for diagram number 208
      CALL FFV2_0(W(1,32),W(1,3),W(1,16),GC_649,AMP(208))
      CALL FFV4_2(W(1,1),W(1,24),GC_933,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 209
      CALL FFV2_0(W(1,18),W(1,3),W(1,16),GC_649,AMP(209))
      CALL FFV2_2(W(1,1),W(1,24),GC_939,MDL_MB,ZERO,W(1,26))
C     Amplitude(s) for diagram number 210
      CALL FFV2_0(W(1,26),W(1,3),W(1,16),GC_649,AMP(210))
      CALL FFV2_2(W(1,1),W(1,19),GC_649,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 211
      CALL FFV6_0(W(1,30),W(1,3),W(1,20),GC_2,AMP(211))
C     Amplitude(s) for diagram number 212
      CALL FFV2_0(W(1,9),W(1,3),W(1,19),GC_649,AMP(212))
C     Amplitude(s) for diagram number 213
      CALL FFV2_8_0(W(1,30),W(1,3),W(1,24),GC_651,GC_660,AMP(213))
C     Amplitude(s) for diagram number 214
      CALL FFV2_0(W(1,21),W(1,3),W(1,19),GC_649,AMP(214))
      CALL FFV2_2(W(1,1),W(1,27),GC_649,MDL_MT,MDL_WT,W(1,19))
C     Amplitude(s) for diagram number 215
      CALL FFV6_0(W(1,19),W(1,3),W(1,20),GC_2,AMP(215))
C     Amplitude(s) for diagram number 216
      CALL FFV2_0(W(1,9),W(1,3),W(1,27),GC_649,AMP(216))
C     Amplitude(s) for diagram number 217
      CALL FFV2_8_0(W(1,19),W(1,3),W(1,24),GC_651,GC_660,AMP(217))
C     Amplitude(s) for diagram number 218
      CALL FFV2_0(W(1,21),W(1,3),W(1,27),GC_649,AMP(218))
      CALL FFV2_2(W(1,1),W(1,25),GC_649,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 219
      CALL FFV6_0(W(1,27),W(1,3),W(1,20),GC_2,AMP(219))
C     Amplitude(s) for diagram number 220
      CALL FFV2_0(W(1,9),W(1,3),W(1,25),GC_649,AMP(220))
C     Amplitude(s) for diagram number 221
      CALL FFV2_8_0(W(1,27),W(1,3),W(1,24),GC_651,GC_660,AMP(221))
C     Amplitude(s) for diagram number 222
      CALL FFV2_0(W(1,21),W(1,3),W(1,25),GC_649,AMP(222))
C     Amplitude(s) for diagram number 223
      CALL FFV2_0(W(1,1),W(1,17),W(1,16),GC_649,AMP(223))
      CALL FFV6_2(W(1,1),W(1,8),GC_1,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 224
      CALL FFV6_0(W(1,17),W(1,2),W(1,20),GC_1,AMP(224))
C     Amplitude(s) for diagram number 225
      CALL FFV11_9_0(W(1,17),W(1,2),W(1,20),GC_736,GC_737,AMP(225))
      CALL FFV11_9_2(W(1,1),W(1,8),GC_736,GC_737,MDL_MB,ZERO,W(1,25))
C     Amplitude(s) for diagram number 226
      CALL FFV6_0(W(1,25),W(1,2),W(1,20),GC_1,AMP(226))
C     Amplitude(s) for diagram number 227
      CALL FFV6_0(W(1,9),W(1,2),W(1,8),GC_1,AMP(227))
C     Amplitude(s) for diagram number 228
      CALL FFV11_9_0(W(1,9),W(1,2),W(1,8),GC_736,GC_737,AMP(228))
C     Amplitude(s) for diagram number 229
      CALL FFV6_0(W(1,7),W(1,2),W(1,8),GC_1,AMP(229))
C     Amplitude(s) for diagram number 230
      CALL FFV2_5_0(W(1,17),W(1,2),W(1,24),GC_650,GC_660,AMP(230))
C     Amplitude(s) for diagram number 231
      CALL FFV11_9_0(W(1,17),W(1,2),W(1,24),GC_723,GC_724,AMP(231))
C     Amplitude(s) for diagram number 232
      CALL FFV4_0(W(1,17),W(1,2),W(1,24),GC_933,AMP(232))
C     Amplitude(s) for diagram number 233
      CALL FFV2_0(W(1,17),W(1,2),W(1,24),GC_939,AMP(233))
C     Amplitude(s) for diagram number 234
      CALL FFV2_5_0(W(1,25),W(1,2),W(1,24),GC_650,GC_660,AMP(234))
C     Amplitude(s) for diagram number 235
      CALL FFV6_0(W(1,21),W(1,2),W(1,8),GC_1,AMP(235))
C     Amplitude(s) for diagram number 236
      CALL FFV11_9_0(W(1,21),W(1,2),W(1,8),GC_736,GC_737,AMP(236))
C     Amplitude(s) for diagram number 237
      CALL FFV6_0(W(1,32),W(1,2),W(1,8),GC_1,AMP(237))
C     Amplitude(s) for diagram number 238
      CALL FFV6_0(W(1,18),W(1,2),W(1,8),GC_1,AMP(238))
C     Amplitude(s) for diagram number 239
      CALL FFV6_0(W(1,26),W(1,2),W(1,8),GC_1,AMP(239))
      CALL FFV6_2(W(1,1),W(1,11),GC_1,MDL_MB,ZERO,W(1,25))
C     Amplitude(s) for diagram number 240
      CALL FFV6_0(W(1,25),W(1,2),W(1,20),GC_1,AMP(240))
C     Amplitude(s) for diagram number 241
      CALL FFV6_0(W(1,9),W(1,2),W(1,11),GC_1,AMP(241))
C     Amplitude(s) for diagram number 242
      CALL FFV2_5_0(W(1,25),W(1,2),W(1,24),GC_650,GC_660,AMP(242))
C     Amplitude(s) for diagram number 243
      CALL FFV6_0(W(1,21),W(1,2),W(1,11),GC_1,AMP(243))
      CALL FFV2_5_2(W(1,1),W(1,12),GC_650,GC_660,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 244
      CALL FFV6_0(W(1,11),W(1,2),W(1,20),GC_1,AMP(244))
C     Amplitude(s) for diagram number 245
      CALL FFV11_9_0(W(1,11),W(1,2),W(1,20),GC_736,GC_737,AMP(245))
      CALL FFV11_9_2(W(1,1),W(1,12),GC_723,GC_724,MDL_MB,ZERO,W(1,25))
C     Amplitude(s) for diagram number 246
      CALL FFV6_0(W(1,25),W(1,2),W(1,20),GC_1,AMP(246))
      CALL FFV4_2(W(1,1),W(1,12),GC_933,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 247
      CALL FFV6_0(W(1,17),W(1,2),W(1,20),GC_1,AMP(247))
      CALL FFV2_2(W(1,1),W(1,12),GC_939,MDL_MB,ZERO,W(1,27))
C     Amplitude(s) for diagram number 248
      CALL FFV6_0(W(1,27),W(1,2),W(1,20),GC_1,AMP(248))
C     Amplitude(s) for diagram number 249
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,12),GC_650,GC_660,AMP(249))
C     Amplitude(s) for diagram number 250
      CALL FFV11_9_0(W(1,9),W(1,2),W(1,12),GC_723,GC_724,AMP(250))
C     Amplitude(s) for diagram number 251
      CALL FFV4_0(W(1,9),W(1,2),W(1,12),GC_933,AMP(251))
C     Amplitude(s) for diagram number 252
      CALL FFV2_0(W(1,9),W(1,2),W(1,12),GC_939,AMP(252))
C     Amplitude(s) for diagram number 253
      CALL FFV2_5_0(W(1,7),W(1,2),W(1,12),GC_650,GC_660,AMP(253))
C     Amplitude(s) for diagram number 254
      CALL FFV2_5_0(W(1,11),W(1,2),W(1,24),GC_650,GC_660,AMP(254))
C     Amplitude(s) for diagram number 255
      CALL FFV11_9_0(W(1,11),W(1,2),W(1,24),GC_723,GC_724,AMP(255))
C     Amplitude(s) for diagram number 256
      CALL FFV4_0(W(1,11),W(1,2),W(1,24),GC_933,AMP(256))
C     Amplitude(s) for diagram number 257
      CALL FFV2_0(W(1,11),W(1,2),W(1,24),GC_939,AMP(257))
C     Amplitude(s) for diagram number 258
      CALL FFV2_5_0(W(1,25),W(1,2),W(1,24),GC_650,GC_660,AMP(258))
C     Amplitude(s) for diagram number 259
      CALL FFV2_5_0(W(1,17),W(1,2),W(1,24),GC_650,GC_660,AMP(259))
C     Amplitude(s) for diagram number 260
      CALL FFV2_5_0(W(1,27),W(1,2),W(1,24),GC_650,GC_660,AMP(260))
C     Amplitude(s) for diagram number 261
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,12),GC_650,GC_660,AMP(261))
C     Amplitude(s) for diagram number 262
      CALL FFV11_9_0(W(1,21),W(1,2),W(1,12),GC_723,GC_724,AMP(262))
C     Amplitude(s) for diagram number 263
      CALL FFV4_0(W(1,21),W(1,2),W(1,12),GC_933,AMP(263))
C     Amplitude(s) for diagram number 264
      CALL FFV2_0(W(1,21),W(1,2),W(1,12),GC_939,AMP(264))
C     Amplitude(s) for diagram number 265
      CALL FFV2_5_0(W(1,32),W(1,2),W(1,12),GC_650,GC_660,AMP(265))
C     Amplitude(s) for diagram number 266
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,12),GC_650,GC_660,AMP(266))
C     Amplitude(s) for diagram number 267
      CALL FFV2_5_0(W(1,26),W(1,2),W(1,12),GC_650,GC_660,AMP(267))
      CALL FFV2_5_2(W(1,1),W(1,13),GC_650,GC_660,MDL_MB,ZERO,W(1,27))
C     Amplitude(s) for diagram number 268
      CALL FFV6_0(W(1,27),W(1,2),W(1,20),GC_1,AMP(268))
C     Amplitude(s) for diagram number 269
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,13),GC_650,GC_660,AMP(269))
C     Amplitude(s) for diagram number 270
      CALL FFV2_5_0(W(1,27),W(1,2),W(1,24),GC_650,GC_660,AMP(270))
C     Amplitude(s) for diagram number 271
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,13),GC_650,GC_660,AMP(271))
      CALL FFV2_5_2(W(1,1),W(1,14),GC_650,GC_660,MDL_MB,ZERO,W(1,13))
C     Amplitude(s) for diagram number 272
      CALL FFV6_0(W(1,13),W(1,2),W(1,20),GC_1,AMP(272))
C     Amplitude(s) for diagram number 273
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,14),GC_650,GC_660,AMP(273))
C     Amplitude(s) for diagram number 274
      CALL FFV2_5_0(W(1,13),W(1,2),W(1,24),GC_650,GC_660,AMP(274))
C     Amplitude(s) for diagram number 275
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,14),GC_650,GC_660,AMP(275))
      CALL FFV2_5_2(W(1,1),W(1,15),GC_650,GC_660,MDL_MB,ZERO,W(1,14))
C     Amplitude(s) for diagram number 276
      CALL FFV6_0(W(1,14),W(1,2),W(1,20),GC_1,AMP(276))
C     Amplitude(s) for diagram number 277
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,15),GC_650,GC_660,AMP(277))
C     Amplitude(s) for diagram number 278
      CALL FFV2_5_0(W(1,14),W(1,2),W(1,24),GC_650,GC_660,AMP(278))
C     Amplitude(s) for diagram number 279
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,15),GC_650,GC_660,AMP(279))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_7,ZERO,ZERO,W(1,15))
      CALL FFV1_2(W(1,1),W(1,15),GC_7,MDL_MB,ZERO,W(1,14))
C     Amplitude(s) for diagram number 280
      CALL FFV6_0(W(1,14),W(1,2),W(1,20),GC_1,AMP(280))
C     Amplitude(s) for diagram number 281
      CALL FFV11_9_0(W(1,14),W(1,2),W(1,20),GC_736,GC_737,AMP(281))
C     Amplitude(s) for diagram number 282
      CALL FFV1_0(W(1,9),W(1,2),W(1,15),GC_7,AMP(282))
C     Amplitude(s) for diagram number 283
      CALL FFV1_0(W(1,7),W(1,2),W(1,15),GC_7,AMP(283))
C     Amplitude(s) for diagram number 284
      CALL FFV2_5_0(W(1,14),W(1,2),W(1,24),GC_650,GC_660,AMP(284))
C     Amplitude(s) for diagram number 285
      CALL FFV11_9_0(W(1,14),W(1,2),W(1,24),GC_723,GC_724,AMP(285))
C     Amplitude(s) for diagram number 286
      CALL FFV4_0(W(1,14),W(1,2),W(1,24),GC_933,AMP(286))
C     Amplitude(s) for diagram number 287
      CALL FFV2_0(W(1,14),W(1,2),W(1,24),GC_939,AMP(287))
C     Amplitude(s) for diagram number 288
      CALL FFV1_0(W(1,21),W(1,2),W(1,15),GC_7,AMP(288))
C     Amplitude(s) for diagram number 289
      CALL FFV1_0(W(1,32),W(1,2),W(1,15),GC_7,AMP(289))
C     Amplitude(s) for diagram number 290
      CALL FFV1_0(W(1,18),W(1,2),W(1,15),GC_7,AMP(290))
C     Amplitude(s) for diagram number 291
      CALL FFV1_0(W(1,26),W(1,2),W(1,15),GC_7,AMP(291))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_725,GC_726,ZERO,ZERO,W(1,26))
      CALL FFV1_2(W(1,1),W(1,26),GC_7,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 292
      CALL FFV6_0(W(1,18),W(1,2),W(1,20),GC_1,AMP(292))
C     Amplitude(s) for diagram number 293
      CALL FFV1_0(W(1,9),W(1,2),W(1,26),GC_7,AMP(293))
C     Amplitude(s) for diagram number 294
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,24),GC_650,GC_660,AMP(294))
C     Amplitude(s) for diagram number 295
      CALL FFV1_0(W(1,21),W(1,2),W(1,26),GC_7,AMP(295))
      CALL FFFF11_2_6_1(W(1,2),W(1,1),W(1,3),GC_193,GC_191,GC_571
     $ ,MDL_MT,MDL_WT,W(1,26))
      CALL FFFF1_15_16_17_5_9_1(W(1,2),W(1,1),W(1,3),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MT,MDL_WT,W(1,21))
      CALL FFFF11_2_1(W(1,2),W(1,1),W(1,3),GC_197,GC_195,MDL_MT,MDL_WT
     $ ,W(1,18))
      CALL FFFF1_15_16_17_9_1(W(1,2),W(1,1),W(1,3),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 296
      CALL FFV6_0(W(1,4),W(1,26),W(1,20),GC_2,AMP(296))
      CALL FFV6_0(W(1,4),W(1,21),W(1,20),GC_2,AMP(297))
      CALL FFV6_0(W(1,4),W(1,18),W(1,20),GC_2,AMP(298))
      CALL FFV6_0(W(1,4),W(1,9),W(1,20),GC_2,AMP(299))
C     Amplitude(s) for diagram number 297
      CALL FFV2_8_0(W(1,4),W(1,26),W(1,24),GC_651,GC_660,AMP(300))
      CALL FFV2_8_0(W(1,4),W(1,21),W(1,24),GC_651,GC_660,AMP(301))
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,24),GC_651,GC_660,AMP(302))
      CALL FFV2_8_0(W(1,4),W(1,9),W(1,24),GC_651,GC_660,AMP(303))
      CALL FFFF11_2_6_4(W(1,4),W(1,2),W(1,1),GC_193,GC_191,GC_571
     $ ,MDL_MT,MDL_WT,W(1,9))
      CALL FFFF1_15_16_17_5_9_4(W(1,4),W(1,2),W(1,1),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MT,MDL_WT,W(1,18))
      CALL FFFF11_2_4(W(1,4),W(1,2),W(1,1),GC_197,GC_195,MDL_MT,MDL_WT
     $ ,W(1,21))
      CALL FFFF1_15_16_17_9_4(W(1,4),W(1,2),W(1,1),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 298
      CALL FFV6_0(W(1,9),W(1,3),W(1,20),GC_2,AMP(304))
      CALL FFV6_0(W(1,18),W(1,3),W(1,20),GC_2,AMP(305))
      CALL FFV6_0(W(1,21),W(1,3),W(1,20),GC_2,AMP(306))
      CALL FFV6_0(W(1,26),W(1,3),W(1,20),GC_2,AMP(307))
C     Amplitude(s) for diagram number 299
      CALL FFV2_8_0(W(1,9),W(1,3),W(1,24),GC_651,GC_660,AMP(308))
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,24),GC_651,GC_660,AMP(309))
      CALL FFV2_8_0(W(1,21),W(1,3),W(1,24),GC_651,GC_660,AMP(310))
      CALL FFV2_8_0(W(1,26),W(1,3),W(1,24),GC_651,GC_660,AMP(311))
      CALL FFFF10_14_6_8_2(W(1,5),W(1,1),W(1,2),GC_15,GC_563,GC_124
     $ ,GC_14,MDL_MTA,ZERO,W(1,26))
C     Amplitude(s) for diagram number 300
      CALL FFV1_0(W(1,26),W(1,6),W(1,8),GC_3,AMP(312))
C     Amplitude(s) for diagram number 301
      CALL FFV2_7_0(W(1,26),W(1,6),W(1,12),GC_650,GC_661,AMP(313))
      CALL FFFF10_14_6_8_1(W(1,6),W(1,1),W(1,2),GC_15,GC_563,GC_124
     $ ,GC_14,MDL_MTA,ZERO,W(1,26))
C     Amplitude(s) for diagram number 302
      CALL FFV1_0(W(1,5),W(1,26),W(1,8),GC_3,AMP(314))
C     Amplitude(s) for diagram number 303
      CALL FFV2_7_0(W(1,5),W(1,26),W(1,12),GC_650,GC_661,AMP(315))
      CALL FFFF11_2_6_2(W(1,4),W(1,1),W(1,3),GC_193,GC_191,GC_571
     $ ,MDL_MB,ZERO,W(1,26))
      CALL FFFF1_15_16_17_5_9_2(W(1,4),W(1,1),W(1,3),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MB,ZERO,W(1,21))
      CALL FFFF11_2_2(W(1,4),W(1,1),W(1,3),GC_197,GC_195,MDL_MB,ZERO
     $ ,W(1,18))
      CALL FFFF1_15_16_17_9_2(W(1,4),W(1,1),W(1,3),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 304
      CALL FFV6_0(W(1,26),W(1,2),W(1,20),GC_1,AMP(316))
      CALL FFV6_0(W(1,21),W(1,2),W(1,20),GC_1,AMP(317))
      CALL FFV6_0(W(1,18),W(1,2),W(1,20),GC_1,AMP(318))
      CALL FFV6_0(W(1,9),W(1,2),W(1,20),GC_1,AMP(319))
C     Amplitude(s) for diagram number 305
      CALL FFV2_5_0(W(1,26),W(1,2),W(1,24),GC_650,GC_660,AMP(320))
      CALL FFV2_5_0(W(1,21),W(1,2),W(1,24),GC_650,GC_660,AMP(321))
      CALL FFV2_5_0(W(1,18),W(1,2),W(1,24),GC_650,GC_660,AMP(322))
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,24),GC_650,GC_660,AMP(323))
      CALL FFFF10_2_6_7_21_1(W(1,6),W(1,1),W(1,3),GC_15,GC_347,GC_566
     $ ,GC_349,GC_352,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 306
      CALL FFV2_0(W(1,5),W(1,9),W(1,16),GC_649,AMP(324))
      CALL FFFF10_14_6_8_4(W(1,5),W(1,6),W(1,1),GC_15,GC_563,GC_124
     $ ,GC_14,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 307
      CALL FFV2_0(W(1,9),W(1,3),W(1,16),GC_649,AMP(325))
C     Amplitude(s) for diagram number 308
      CALL FFV6_0(W(1,9),W(1,2),W(1,8),GC_1,AMP(326))
C     Amplitude(s) for diagram number 309
      CALL FFV2_5_0(W(1,9),W(1,2),W(1,12),GC_650,GC_660,AMP(327))
C     Amplitude(s) for diagram number 310
      CALL FFV1_0(W(1,9),W(1,2),W(1,15),GC_7,AMP(328))
      CALL FFFF11_2_6_3(W(1,4),W(1,2),W(1,3),GC_193,GC_191,GC_571
     $ ,MDL_MB,ZERO,W(1,9))
      CALL FFFF1_15_16_17_5_9_3(W(1,4),W(1,2),W(1,3),-GC_194,-GC_573,
     $ -GC_577,-GC_557,-GC_175,-GC_192,MDL_MB,ZERO,W(1,16))
      CALL FFFF11_2_3(W(1,4),W(1,2),W(1,3),GC_197,GC_195,MDL_MB,ZERO
     $ ,W(1,6))
      CALL FFFF1_15_16_17_9_3(W(1,4),W(1,2),W(1,3),-GC_198,-GC_574,
     $ -GC_578,-GC_558,-GC_196,MDL_MB,ZERO,W(1,5))
C     Amplitude(s) for diagram number 311
      CALL FFV6_0(W(1,1),W(1,9),W(1,20),GC_1,AMP(329))
      CALL FFV6_0(W(1,1),W(1,16),W(1,20),GC_1,AMP(330))
      CALL FFV6_0(W(1,1),W(1,6),W(1,20),GC_1,AMP(331))
      CALL FFV6_0(W(1,1),W(1,5),W(1,20),GC_1,AMP(332))
C     Amplitude(s) for diagram number 312
      CALL FFV2_5_0(W(1,1),W(1,9),W(1,24),GC_650,GC_660,AMP(333))
      CALL FFV2_5_0(W(1,1),W(1,16),W(1,24),GC_650,GC_660,AMP(334))
      CALL FFV2_5_0(W(1,1),W(1,6),W(1,24),GC_650,GC_660,AMP(335))
      CALL FFV2_5_0(W(1,1),W(1,5),W(1,24),GC_650,GC_660,AMP(336))
C     Amplitude(s) for diagram number 313
      CALL FFV6_0(W(1,1),W(1,31),W(1,8),GC_1,AMP(337))
C     Amplitude(s) for diagram number 314
      CALL FFV2_5_0(W(1,1),W(1,31),W(1,12),GC_650,GC_660,AMP(338))
C     Amplitude(s) for diagram number 315
      CALL FFV1_0(W(1,1),W(1,31),W(1,15),GC_7,AMP(339))
      JAMP(1)=-AMP(1)-AMP(2)-AMP(3)-AMP(4)-AMP(5)-AMP(6)-AMP(7)-AMP(8)
     $ -AMP(9)-AMP(10)-AMP(11)-AMP(12)-AMP(13)-AMP(14)-AMP(15)-AMP(16)
     $ -AMP(17)-AMP(18)-AMP(19)-AMP(20)-AMP(21)-AMP(22)-AMP(23)-AMP(24)
     $ -AMP(25)-AMP(26)-AMP(27)-AMP(28)-AMP(29)-AMP(30)-AMP(31)-AMP(32)
     $ -AMP(33)-AMP(34)-AMP(35)-AMP(36)-AMP(37)-AMP(38)-AMP(39)-AMP(40)
     $ -AMP(41)-AMP(42)-AMP(43)-AMP(44)-AMP(45)-AMP(46)-AMP(47)-AMP(48)
     $ -AMP(49)-AMP(50)-AMP(51)-AMP(52)-AMP(53)-AMP(54)-AMP(55)-AMP(56)
     $ -AMP(57)-AMP(58)-AMP(59)-AMP(60)-AMP(61)-AMP(62)-AMP(63)-AMP(64)
     $ -AMP(65)-AMP(66)-AMP(67)-AMP(68)-AMP(69)-AMP(70)-AMP(71)-AMP(72)
     $ -AMP(73)-AMP(74)-AMP(75)-AMP(76)-AMP(77)-AMP(78)-AMP(79)-AMP(80)
     $ -AMP(81)-AMP(82)-AMP(83)-AMP(84)-AMP(85)-AMP(86)-AMP(87)-AMP(88)
     $ -AMP(89)-AMP(90)-AMP(91)-AMP(92)-AMP(93)-AMP(94)-AMP(95)-AMP(96)
     $ +1D0/6D0*AMP(97)+1D0/6D0*AMP(98)+1D0/6D0*AMP(99)+1D0/6D0
     $ *AMP(100)+1D0/6D0*AMP(101)+1D0/6D0*AMP(102)+1D0/6D0*AMP(103)
     $ +1D0/6D0*AMP(104)+1D0/6D0*AMP(105)+1D0/6D0*AMP(106)+1D0/6D0
     $ *AMP(107)+1D0/6D0*AMP(108)+1D0/6D0*AMP(109)+1D0/6D0*AMP(110)
     $ +1D0/6D0*AMP(111)+1D0/6D0*AMP(112)-AMP(113)-AMP(114)-AMP(115)
     $ -AMP(116)-AMP(117)-AMP(118)+1D0/6D0*AMP(119)-AMP(120)-AMP(121)
     $ +1D0/6D0*AMP(122)-AMP(224)-AMP(225)-AMP(226)-AMP(227)-AMP(228)
     $ -AMP(229)-AMP(230)-AMP(231)-AMP(232)-AMP(233)-AMP(234)-AMP(235)
     $ -AMP(236)-AMP(237)-AMP(238)-AMP(239)-AMP(240)-AMP(241)-AMP(242)
     $ -AMP(243)-AMP(244)-AMP(245)-AMP(246)-AMP(247)-AMP(248)-AMP(249)
     $ -AMP(250)-AMP(251)-AMP(252)-AMP(253)-AMP(254)-AMP(255)-AMP(256)
     $ -AMP(257)-AMP(258)-AMP(259)-AMP(260)-AMP(261)-AMP(262)-AMP(263)
     $ -AMP(264)-AMP(265)-AMP(266)-AMP(267)-AMP(268)-AMP(269)-AMP(270)
     $ -AMP(271)-AMP(272)-AMP(273)-AMP(274)-AMP(275)-AMP(276)-AMP(277)
     $ -AMP(278)-AMP(279)+1D0/6D0*AMP(280)+1D0/6D0*AMP(281)+1D0/6D0
     $ *AMP(282)+1D0/6D0*AMP(283)+1D0/6D0*AMP(284)+1D0/6D0*AMP(285)
     $ +1D0/6D0*AMP(286)+1D0/6D0*AMP(287)+1D0/6D0*AMP(288)+1D0/6D0
     $ *AMP(289)+1D0/6D0*AMP(290)+1D0/6D0*AMP(291)+1D0/6D0*AMP(292)
     $ +1D0/6D0*AMP(293)+1D0/6D0*AMP(294)+1D0/6D0*AMP(295)+AMP(297)
     $ -1D0/6D0*AMP(299)+1D0/2D0*AMP(298)+AMP(301)-1D0/6D0*AMP(303)
     $ +1D0/2D0*AMP(302)+AMP(305)-1D0/6D0*AMP(307)+1D0/2D0*AMP(306)
     $ +AMP(309)-1D0/6D0*AMP(311)+1D0/2D0*AMP(310)-AMP(312)-AMP(313)
     $ -AMP(314)-AMP(315)+AMP(317)-1D0/6D0*AMP(319)+1D0/2D0*AMP(318)
     $ +AMP(321)-1D0/6D0*AMP(323)+1D0/2D0*AMP(322)-AMP(326)-AMP(327)
     $ +1D0/6D0*AMP(328)+AMP(330)-1D0/6D0*AMP(332)+1D0/2D0*AMP(331)
     $ +AMP(334)-1D0/6D0*AMP(336)+1D0/2D0*AMP(335)-AMP(337)-AMP(338)
     $ +1D0/6D0*AMP(339)
      JAMP(2)=-1D0/2D0*AMP(97)-1D0/2D0*AMP(98)-1D0/2D0*AMP(99)-1D0/2D0
     $ *AMP(100)-1D0/2D0*AMP(101)-1D0/2D0*AMP(102)-1D0/2D0*AMP(103)
     $ -1D0/2D0*AMP(104)-1D0/2D0*AMP(105)-1D0/2D0*AMP(106)-1D0/2D0
     $ *AMP(107)-1D0/2D0*AMP(108)-1D0/2D0*AMP(109)-1D0/2D0*AMP(110)
     $ -1D0/2D0*AMP(111)-1D0/2D0*AMP(112)-1D0/2D0*AMP(119)-1D0/2D0
     $ *AMP(122)+AMP(123)+AMP(124)+AMP(125)+AMP(126)+AMP(127)+AMP(128)
     $ +AMP(129)+AMP(130)+AMP(131)+AMP(132)+AMP(133)+AMP(134)+AMP(135)
     $ +AMP(136)+AMP(137)+AMP(138)+AMP(139)+AMP(140)+AMP(141)+AMP(142)
     $ +AMP(143)+AMP(144)+AMP(145)+AMP(146)+AMP(147)+AMP(148)+AMP(149)
     $ +AMP(150)+AMP(151)+AMP(152)+AMP(153)+AMP(154)+AMP(155)+AMP(156)
     $ +AMP(157)+AMP(158)+AMP(159)+AMP(160)+AMP(161)+AMP(162)+AMP(163)
     $ +AMP(164)+AMP(165)+AMP(166)+AMP(167)+AMP(168)+AMP(169)+AMP(170)
     $ +AMP(171)+AMP(172)+AMP(173)+AMP(174)+AMP(175)+AMP(176)+AMP(177)
     $ +AMP(178)+AMP(179)+AMP(180)+AMP(181)+AMP(182)+AMP(183)+AMP(184)
     $ +AMP(185)+AMP(186)+AMP(187)+AMP(188)+AMP(189)+AMP(190)+AMP(191)
     $ +AMP(192)+AMP(193)+AMP(194)+AMP(195)+AMP(196)+AMP(197)+AMP(198)
     $ +AMP(199)+AMP(200)+AMP(201)+AMP(202)+AMP(203)+AMP(204)+AMP(205)
     $ +AMP(206)+AMP(207)+AMP(208)+AMP(209)+AMP(210)+AMP(211)+AMP(212)
     $ +AMP(213)+AMP(214)+AMP(215)+AMP(216)+AMP(217)+AMP(218)+AMP(219)
     $ +AMP(220)+AMP(221)+AMP(222)+AMP(223)-1D0/2D0*AMP(280)-1D0/2D0
     $ *AMP(281)-1D0/2D0*AMP(282)-1D0/2D0*AMP(283)-1D0/2D0*AMP(284)
     $ -1D0/2D0*AMP(285)-1D0/2D0*AMP(286)-1D0/2D0*AMP(287)-1D0/2D0
     $ *AMP(288)-1D0/2D0*AMP(289)-1D0/2D0*AMP(290)-1D0/2D0*AMP(291)
     $ -1D0/2D0*AMP(292)-1D0/2D0*AMP(293)-1D0/2D0*AMP(294)-1D0/2D0
     $ *AMP(295)+1D0/2D0*AMP(299)+AMP(296)-1D0/6D0*AMP(298)+1D0/2D0
     $ *AMP(303)+AMP(300)-1D0/6D0*AMP(302)+1D0/2D0*AMP(307)+AMP(304)
     $ -1D0/6D0*AMP(306)+1D0/2D0*AMP(311)+AMP(308)-1D0/6D0*AMP(310)
     $ +1D0/2D0*AMP(319)+AMP(316)-1D0/6D0*AMP(318)+1D0/2D0*AMP(323)
     $ +AMP(320)-1D0/6D0*AMP(322)+AMP(324)+AMP(325)-1D0/2D0*AMP(328)
     $ +1D0/2D0*AMP(332)+AMP(329)-1D0/6D0*AMP(331)+1D0/2D0*AMP(336)
     $ +AMP(333)-1D0/6D0*AMP(335)-1D0/2D0*AMP(339)

      M80_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M80_MATRIX = M80_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M80_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M80_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M80_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M80_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M80_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=64)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M80_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M80_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M80_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M80_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

