      SUBROUTINE M7_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M7_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M7_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M7_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g s > t t~ ta- vt~ c DIM6<=1 FCNC=0 @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M7_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M7_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M7_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,   2),I=1,7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,   3),I=1,7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,   4),I=1,7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,   5),I=1,7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,   6),I=1,7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,   7),I=1,7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,   8),I=1,7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,   9),I=1,7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,7) /-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  18),I=1,7) /-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  19),I=1,7) /-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  20),I=1,7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  21),I=1,7) /-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  22),I=1,7) /-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  23),I=1,7) /-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  24),I=1,7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  25),I=1,7) /-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  26),I=1,7) /-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  27),I=1,7) /-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  28),I=1,7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  29),I=1,7) /-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  30),I=1,7) /-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  31),I=1,7) /-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  32),I=1,7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  33),I=1,7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  42),I=1,7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  43),I=1,7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  44),I=1,7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  45),I=1,7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  46),I=1,7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  47),I=1,7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  48),I=1,7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  49),I=1,7) /-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  50),I=1,7) /-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  51),I=1,7) /-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  52),I=1,7) /-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  53),I=1,7) /-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  54),I=1,7) /-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  55),I=1,7) /-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  56),I=1,7) /-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  57),I=1,7) /-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  58),I=1,7) /-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  59),I=1,7) /-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  60),I=1,7) /-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  61),I=1,7) /-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  62),I=1,7) /-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  63),I=1,7) /-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  64),I=1,7) /-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  65),I=1,7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  66),I=1,7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  67),I=1,7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  68),I=1,7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  69),I=1,7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  70),I=1,7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  71),I=1,7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  72),I=1,7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  73),I=1,7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  74),I=1,7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  75),I=1,7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  76),I=1,7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  77),I=1,7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  78),I=1,7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  79),I=1,7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  80),I=1,7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  81),I=1,7) / 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  82),I=1,7) / 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  83),I=1,7) / 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  84),I=1,7) / 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  85),I=1,7) / 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  86),I=1,7) / 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  87),I=1,7) / 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  88),I=1,7) / 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  89),I=1,7) / 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  90),I=1,7) / 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  91),I=1,7) / 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  92),I=1,7) / 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  93),I=1,7) / 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  94),I=1,7) / 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  95),I=1,7) / 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  96),I=1,7) / 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  97),I=1,7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  98),I=1,7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  99),I=1,7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 100),I=1,7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 101),I=1,7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 102),I=1,7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 103),I=1,7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 104),I=1,7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 105),I=1,7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 106),I=1,7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 107),I=1,7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 108),I=1,7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 109),I=1,7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 110),I=1,7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 111),I=1,7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 112),I=1,7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 113),I=1,7) / 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 114),I=1,7) / 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 115),I=1,7) / 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 116),I=1,7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 117),I=1,7) / 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 118),I=1,7) / 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 119),I=1,7) / 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 120),I=1,7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 121),I=1,7) / 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 122),I=1,7) / 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 123),I=1,7) / 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 124),I=1,7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 125),I=1,7) / 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 126),I=1,7) / 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 127),I=1,7) / 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 128),I=1,7) / 1,-1, 1,-1, 1,-1, 1/
      DATA IDEN/96/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M7_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M7_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M7_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M7_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M7_IS_BORN_HEL_SELECTED(IHEL)
     $       ) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M7_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g s > t t~ ta- vt~ c DIM6<=1 FCNC=0 @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=278)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=58, NCOLOR=4)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  4) /   12,    4,    4,    0/
C     1 T(1,3,2) T(7,4)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  4) /    4,   12,    0,    4/
C     1 T(1,3,4) T(7,2)
      DATA DENOM(3)/1/
      DATA (CF(I,  3),I=  1,  4) /    4,    0,   12,    4/
C     1 T(1,7,2) T(3,4)
      DATA DENOM(4)/1/
      DATA (CF(I,  4),I=  1,  4) /    0,    4,    4,   12/
C     1 T(1,7,4) T(3,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),MDL_MTA,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL OXXXXX(P(0,7),ZERO,NHEL(7),+1*IC(7),W(1,7))
      CALL FFV1_2(W(1,2),W(1,1),GC_7,ZERO,ZERO,W(1,8))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_2,ZERO,ZERO,W(1,9))
      CALL FFV2_3(W(1,8),W(1,7),GC_649,MDL_MW,MDL_WW,W(1,10))
      CALL FFV1_1(W(1,5),W(1,9),GC_3,MDL_MTA,ZERO,W(1,11))
C     Amplitude(s) for diagram number 1
      CALL FFV2_0(W(1,6),W(1,11),W(1,10),GC_649,AMP(1))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_813,GC_814,ZERO,ZERO,W(1,12))
      CALL FFV1_1(W(1,5),W(1,12),GC_3,MDL_MTA,ZERO,W(1,13))
C     Amplitude(s) for diagram number 2
      CALL FFV2_0(W(1,6),W(1,13),W(1,10),GC_649,AMP(2))
      CALL FFV2_8_3(W(1,4),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,14))
      CALL FFV2_7_1(W(1,5),W(1,14),GC_650,GC_661,MDL_MTA,ZERO,W(1,15))
C     Amplitude(s) for diagram number 3
      CALL FFV2_0(W(1,6),W(1,15),W(1,10),GC_649,AMP(3))
      CALL FFV2_2(W(1,6),W(1,14),GC_664,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 4
      CALL FFV2_0(W(1,16),W(1,5),W(1,10),GC_649,AMP(4))
      CALL FFV11_9_3(W(1,4),W(1,3),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,17))
      CALL FFV2_7_1(W(1,5),W(1,17),GC_650,GC_661,MDL_MTA,ZERO,W(1,18))
C     Amplitude(s) for diagram number 5
      CALL FFV2_0(W(1,6),W(1,18),W(1,10),GC_649,AMP(5))
      CALL FFV2_2(W(1,6),W(1,17),GC_664,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 6
      CALL FFV2_0(W(1,19),W(1,5),W(1,10),GC_649,AMP(6))
      CALL FFV4_3(W(1,4),W(1,3),GC_948,MDL_MZ,MDL_WZ,W(1,20))
      CALL FFV2_7_1(W(1,5),W(1,20),GC_650,GC_661,MDL_MTA,ZERO,W(1,21))
C     Amplitude(s) for diagram number 7
      CALL FFV2_0(W(1,6),W(1,21),W(1,10),GC_649,AMP(7))
      CALL FFV2_2(W(1,6),W(1,20),GC_664,ZERO,ZERO,W(1,22))
C     Amplitude(s) for diagram number 8
      CALL FFV2_0(W(1,22),W(1,5),W(1,10),GC_649,AMP(8))
      CALL FFV2_3(W(1,4),W(1,3),GC_938,MDL_MZ,MDL_WZ,W(1,23))
      CALL FFV2_7_1(W(1,5),W(1,23),GC_650,GC_661,MDL_MTA,ZERO,W(1,24))
C     Amplitude(s) for diagram number 9
      CALL FFV2_0(W(1,6),W(1,24),W(1,10),GC_649,AMP(9))
      CALL FFV2_2(W(1,6),W(1,23),GC_664,ZERO,ZERO,W(1,25))
C     Amplitude(s) for diagram number 10
      CALL FFV2_0(W(1,25),W(1,5),W(1,10),GC_649,AMP(10))
      CALL FFS2_4_3(W(1,4),W(1,3),GC_739,GC_738,MDL_MH,MDL_WH,W(1,26))
      CALL FFS4_1(W(1,5),W(1,26),GC_955,MDL_MTA,ZERO,W(1,27))
C     Amplitude(s) for diagram number 11
      CALL FFV2_0(W(1,6),W(1,27),W(1,10),GC_649,AMP(11))
      CALL FFS4_3(W(1,4),W(1,3),GC_954,MDL_MH,MDL_WH,W(1,28))
      CALL FFS4_1(W(1,5),W(1,28),GC_955,MDL_MTA,ZERO,W(1,29))
C     Amplitude(s) for diagram number 12
      CALL FFV2_0(W(1,6),W(1,29),W(1,10),GC_649,AMP(12))
      CALL FFV2_3(W(1,6),W(1,5),GC_649,MDL_MW,MDL_WW,W(1,30))
      CALL FFV1_2(W(1,8),W(1,9),GC_1,ZERO,ZERO,W(1,31))
C     Amplitude(s) for diagram number 13
      CALL FFV2_0(W(1,31),W(1,7),W(1,30),GC_649,AMP(13))
      CALL FFV2_2(W(1,8),W(1,30),GC_649,ZERO,ZERO,W(1,31))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,31),W(1,7),W(1,9),GC_2,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL VVV1_0(W(1,9),W(1,30),W(1,10),GC_4,AMP(15))
      CALL FFV1_2(W(1,8),W(1,12),GC_1,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 16
      CALL FFV2_0(W(1,32),W(1,7),W(1,30),GC_649,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,31),W(1,7),W(1,12),GC_2,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL VVV1_0(W(1,12),W(1,30),W(1,10),GC_4,AMP(18))
      CALL FFV2_5_2(W(1,8),W(1,14),GC_650,GC_660,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 19
      CALL FFV2_0(W(1,32),W(1,7),W(1,30),GC_649,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV2_8_0(W(1,31),W(1,7),W(1,14),GC_651,GC_660,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL VVV1_0(W(1,30),W(1,10),W(1,14),GC_653,AMP(21))
      CALL FFV2_5_2(W(1,8),W(1,17),GC_650,GC_660,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 22
      CALL FFV2_0(W(1,32),W(1,7),W(1,30),GC_649,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV2_8_0(W(1,31),W(1,7),W(1,17),GC_651,GC_660,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL VVV1_0(W(1,30),W(1,10),W(1,17),GC_653,AMP(24))
      CALL FFV2_5_2(W(1,8),W(1,20),GC_650,GC_660,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 25
      CALL FFV2_0(W(1,32),W(1,7),W(1,30),GC_649,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV2_8_0(W(1,31),W(1,7),W(1,20),GC_651,GC_660,AMP(26))
C     Amplitude(s) for diagram number 27
      CALL VVV1_0(W(1,30),W(1,10),W(1,20),GC_653,AMP(27))
      CALL FFV2_5_2(W(1,8),W(1,23),GC_650,GC_660,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 28
      CALL FFV2_0(W(1,32),W(1,7),W(1,30),GC_649,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV2_8_0(W(1,31),W(1,7),W(1,23),GC_651,GC_660,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL VVV1_0(W(1,30),W(1,10),W(1,23),GC_653,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL VVS1_0(W(1,30),W(1,10),W(1,26),GC_730,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL VVS1_0(W(1,30),W(1,10),W(1,28),GC_730,AMP(32))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_7,ZERO,ZERO,W(1,32))
      CALL FFV1_2(W(1,8),W(1,32),GC_7,ZERO,ZERO,W(1,33))
C     Amplitude(s) for diagram number 33
      CALL FFV2_0(W(1,33),W(1,7),W(1,30),GC_649,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFV1_0(W(1,31),W(1,7),W(1,32),GC_7,AMP(34))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_725,GC_726,ZERO,ZERO,W(1,33))
      CALL FFV1_2(W(1,8),W(1,33),GC_7,ZERO,ZERO,W(1,34))
C     Amplitude(s) for diagram number 35
      CALL FFV2_0(W(1,34),W(1,7),W(1,30),GC_649,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV1_0(W(1,31),W(1,7),W(1,33),GC_7,AMP(36))
      CALL FFV2_1(W(1,3),W(1,30),GC_649,MDL_MB,ZERO,W(1,31))
C     Amplitude(s) for diagram number 37
      CALL FFV2_0(W(1,4),W(1,31),W(1,10),GC_649,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFV4_0(W(1,4),W(1,31),W(1,10),GC_923,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV10_3_0(W(1,4),W(1,31),W(1,10),GC_767,GC_742,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV2_0(W(1,4),W(1,31),W(1,10),GC_740,AMP(40))
      CALL FFV4_1(W(1,3),W(1,30),GC_924,MDL_MB,ZERO,W(1,34))
C     Amplitude(s) for diagram number 41
      CALL FFV2_0(W(1,4),W(1,34),W(1,10),GC_649,AMP(41))
      CALL FFV10_3_1(W(1,3),W(1,30),GC_741,GC_768,MDL_MB,ZERO,W(1,35))
C     Amplitude(s) for diagram number 42
      CALL FFV2_0(W(1,4),W(1,35),W(1,10),GC_649,AMP(42))
      CALL FFV2_1(W(1,3),W(1,30),GC_740,MDL_MB,ZERO,W(1,36))
C     Amplitude(s) for diagram number 43
      CALL FFV2_0(W(1,4),W(1,36),W(1,10),GC_649,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFVV2_4_0(W(1,4),W(1,3),W(1,30),W(1,10),GC_735,GC_734
     $ ,AMP(44))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,8),W(1,4),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,37))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,8),W(1,4),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,38))
C     Amplitude(s) for diagram number 45
      CALL FFV2_0(W(1,37),W(1,7),W(1,30),GC_649,AMP(45))
      CALL FFV2_0(W(1,38),W(1,7),W(1,30),GC_649,AMP(46))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,4),W(1,8),W(1,7),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,38))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,4),W(1,8),W(1,7),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,37))
C     Amplitude(s) for diagram number 46
      CALL FFV2_0(W(1,38),W(1,3),W(1,30),GC_649,AMP(47))
      CALL FFV2_0(W(1,37),W(1,3),W(1,30),GC_649,AMP(48))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,5),W(1,4),W(1,3)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MTA,ZERO,W(1,37))
C     Amplitude(s) for diagram number 47
      CALL FFV2_0(W(1,6),W(1,37),W(1,10),GC_649,AMP(49))
      CALL FFFF14_6_4(W(1,4),W(1,3),W(1,6),GC_586,GC_124,ZERO,ZERO,W(1
     $ ,38))
C     Amplitude(s) for diagram number 48
      CALL FFV2_0(W(1,38),W(1,5),W(1,10),GC_649,AMP(50))
      CALL FFFF10_14_18_19_6_8_3(W(1,4),W(1,3),W(1,7),GC_471,GC_589
     $ ,GC_575,GC_592,GC_150,GC_472,ZERO,ZERO,W(1,39))
      CALL FFFF10_14_18_19_6_8_3(W(1,4),W(1,3),W(1,7),GC_473,GC_590
     $ ,GC_576,GC_593,GC_178,GC_474,ZERO,ZERO,W(1,40))
C     Amplitude(s) for diagram number 49
      CALL FFV2_0(W(1,8),W(1,39),W(1,30),GC_649,AMP(51))
      CALL FFV2_0(W(1,8),W(1,40),W(1,30),GC_649,AMP(52))
      CALL FFFF10_2_6_7_21_3(W(1,6),W(1,5),W(1,3),GC_15,GC_347,GC_566
     $ ,GC_349,GC_352,MDL_MB,ZERO,W(1,8))
C     Amplitude(s) for diagram number 50
      CALL FFV2_0(W(1,4),W(1,8),W(1,10),GC_649,AMP(53))
      CALL FFV6_1(W(1,3),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,10))
      CALL FFV2_3(W(1,2),W(1,7),GC_649,MDL_MW,MDL_WW,W(1,41))
      CALL FFV2_8_3(W(1,4),W(1,10),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,42))
      CALL FFV2_1(W(1,5),W(1,41),GC_649,ZERO,ZERO,W(1,43))
C     Amplitude(s) for diagram number 51
      CALL FFV2_0(W(1,6),W(1,43),W(1,42),GC_664,AMP(54))
      CALL FFV11_9_3(W(1,4),W(1,10),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,44)
     $ )
C     Amplitude(s) for diagram number 52
      CALL FFV2_0(W(1,6),W(1,43),W(1,44),GC_664,AMP(55))
      CALL FFV4_3(W(1,4),W(1,10),GC_948,MDL_MZ,MDL_WZ,W(1,45))
C     Amplitude(s) for diagram number 53
      CALL FFV2_0(W(1,6),W(1,43),W(1,45),GC_664,AMP(56))
      CALL FFV2_3(W(1,4),W(1,10),GC_938,MDL_MZ,MDL_WZ,W(1,46))
C     Amplitude(s) for diagram number 54
      CALL FFV2_0(W(1,6),W(1,43),W(1,46),GC_664,AMP(57))
      CALL FFV6P0_3(W(1,4),W(1,10),GC_2,ZERO,ZERO,W(1,47))
      CALL FFV2_2(W(1,6),W(1,41),GC_649,MDL_MTA,ZERO,W(1,48))
C     Amplitude(s) for diagram number 55
      CALL FFV1_0(W(1,48),W(1,5),W(1,47),GC_3,AMP(58))
      CALL FFV11_9P0_3(W(1,4),W(1,10),GC_813,GC_814,ZERO,ZERO,W(1,49))
C     Amplitude(s) for diagram number 56
      CALL FFV1_0(W(1,48),W(1,5),W(1,49),GC_3,AMP(59))
C     Amplitude(s) for diagram number 57
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,42),GC_650,GC_661,AMP(60))
C     Amplitude(s) for diagram number 58
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,44),GC_650,GC_661,AMP(61))
C     Amplitude(s) for diagram number 59
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,45),GC_650,GC_661,AMP(62))
C     Amplitude(s) for diagram number 60
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,46),GC_650,GC_661,AMP(63))
      CALL FFS2_4_3(W(1,4),W(1,10),GC_739,GC_738,MDL_MH,MDL_WH,W(1,50))
C     Amplitude(s) for diagram number 61
      CALL FFS4_0(W(1,48),W(1,5),W(1,50),GC_955,AMP(64))
      CALL FFS4_3(W(1,4),W(1,10),GC_954,MDL_MH,MDL_WH,W(1,51))
C     Amplitude(s) for diagram number 62
      CALL FFS4_0(W(1,48),W(1,5),W(1,51),GC_955,AMP(65))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,5),W(1,4),W(1,10)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MTA,ZERO,W(1,52))
C     Amplitude(s) for diagram number 63
      CALL FFV2_0(W(1,6),W(1,52),W(1,41),GC_649,AMP(66))
      CALL FFFF14_6_4(W(1,4),W(1,10),W(1,6),GC_586,GC_124,ZERO,ZERO
     $ ,W(1,52))
C     Amplitude(s) for diagram number 64
      CALL FFV2_0(W(1,52),W(1,5),W(1,41),GC_649,AMP(67))
      CALL FFFF10_2_6_7_21_3(W(1,6),W(1,5),W(1,10),GC_15,GC_347,GC_566
     $ ,GC_349,GC_352,MDL_MB,ZERO,W(1,52))
C     Amplitude(s) for diagram number 65
      CALL FFV2_0(W(1,4),W(1,52),W(1,41),GC_649,AMP(68))
      CALL FFV11_9_1(W(1,3),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,52))
      CALL FFV2_8_3(W(1,4),W(1,52),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,53))
C     Amplitude(s) for diagram number 66
      CALL FFV2_0(W(1,6),W(1,43),W(1,53),GC_664,AMP(69))
      CALL FFV6P0_3(W(1,4),W(1,52),GC_2,ZERO,ZERO,W(1,54))
C     Amplitude(s) for diagram number 67
      CALL FFV1_0(W(1,48),W(1,5),W(1,54),GC_3,AMP(70))
C     Amplitude(s) for diagram number 68
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,53),GC_650,GC_661,AMP(71))
      CALL FFS4_3(W(1,4),W(1,52),GC_954,MDL_MH,MDL_WH,W(1,55))
C     Amplitude(s) for diagram number 69
      CALL FFS4_0(W(1,48),W(1,5),W(1,55),GC_955,AMP(72))
C     Amplitude(s) for diagram number 70
      CALL FFVV2_4_0(W(1,4),W(1,10),W(1,30),W(1,41),GC_735,GC_734
     $ ,AMP(73))
C     Amplitude(s) for diagram number 71
      CALL VVV1_0(W(1,47),W(1,30),W(1,41),GC_4,AMP(74))
C     Amplitude(s) for diagram number 72
      CALL VVV1_0(W(1,49),W(1,30),W(1,41),GC_4,AMP(75))
C     Amplitude(s) for diagram number 73
      CALL VVV1_0(W(1,30),W(1,41),W(1,42),GC_653,AMP(76))
C     Amplitude(s) for diagram number 74
      CALL VVV1_0(W(1,30),W(1,41),W(1,44),GC_653,AMP(77))
C     Amplitude(s) for diagram number 75
      CALL VVV1_0(W(1,30),W(1,41),W(1,45),GC_653,AMP(78))
C     Amplitude(s) for diagram number 76
      CALL VVV1_0(W(1,30),W(1,41),W(1,46),GC_653,AMP(79))
C     Amplitude(s) for diagram number 77
      CALL VVS1_0(W(1,30),W(1,41),W(1,50),GC_730,AMP(80))
C     Amplitude(s) for diagram number 78
      CALL VVS1_0(W(1,30),W(1,41),W(1,51),GC_730,AMP(81))
      CALL FFV2_1(W(1,10),W(1,30),GC_649,MDL_MB,ZERO,W(1,51))
C     Amplitude(s) for diagram number 79
      CALL FFV2_0(W(1,4),W(1,51),W(1,41),GC_649,AMP(82))
C     Amplitude(s) for diagram number 80
      CALL FFV4_0(W(1,4),W(1,51),W(1,41),GC_923,AMP(83))
C     Amplitude(s) for diagram number 81
      CALL FFV10_3_0(W(1,4),W(1,51),W(1,41),GC_767,GC_742,AMP(84))
C     Amplitude(s) for diagram number 82
      CALL FFV2_0(W(1,4),W(1,51),W(1,41),GC_740,AMP(85))
      CALL FFV4_1(W(1,10),W(1,30),GC_924,MDL_MB,ZERO,W(1,51))
C     Amplitude(s) for diagram number 83
      CALL FFV2_0(W(1,4),W(1,51),W(1,41),GC_649,AMP(86))
      CALL FFV10_3_1(W(1,10),W(1,30),GC_741,GC_768,MDL_MB,ZERO,W(1,51))
C     Amplitude(s) for diagram number 84
      CALL FFV2_0(W(1,4),W(1,51),W(1,41),GC_649,AMP(87))
      CALL FFV2_1(W(1,10),W(1,30),GC_740,MDL_MB,ZERO,W(1,51))
C     Amplitude(s) for diagram number 85
      CALL FFV2_0(W(1,4),W(1,51),W(1,41),GC_649,AMP(88))
C     Amplitude(s) for diagram number 86
      CALL VVV1_0(W(1,54),W(1,30),W(1,41),GC_4,AMP(89))
C     Amplitude(s) for diagram number 87
      CALL VVV1_0(W(1,30),W(1,41),W(1,53),GC_653,AMP(90))
C     Amplitude(s) for diagram number 88
      CALL VVS1_0(W(1,30),W(1,41),W(1,55),GC_730,AMP(91))
      CALL FFV2_1(W(1,52),W(1,30),GC_649,MDL_MB,ZERO,W(1,55))
C     Amplitude(s) for diagram number 89
      CALL FFV2_0(W(1,4),W(1,55),W(1,41),GC_649,AMP(92))
      CALL FFV2_2(W(1,2),W(1,30),GC_649,ZERO,ZERO,W(1,55))
C     Amplitude(s) for diagram number 90
      CALL FFV1_0(W(1,55),W(1,7),W(1,47),GC_2,AMP(93))
C     Amplitude(s) for diagram number 91
      CALL FFV1_0(W(1,55),W(1,7),W(1,49),GC_2,AMP(94))
C     Amplitude(s) for diagram number 92
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,42),GC_651,GC_660,AMP(95))
C     Amplitude(s) for diagram number 93
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,44),GC_651,GC_660,AMP(96))
C     Amplitude(s) for diagram number 94
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,45),GC_651,GC_660,AMP(97))
C     Amplitude(s) for diagram number 95
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,46),GC_651,GC_660,AMP(98))
      CALL FFV6P0_3(W(1,4),W(1,10),GC_7,ZERO,ZERO,W(1,51))
C     Amplitude(s) for diagram number 96
      CALL FFV1_0(W(1,55),W(1,7),W(1,51),GC_7,AMP(99))
      CALL FFV11_9P0_3(W(1,4),W(1,10),GC_725,GC_726,ZERO,ZERO,W(1,50))
C     Amplitude(s) for diagram number 97
      CALL FFV1_0(W(1,55),W(1,7),W(1,50),GC_7,AMP(100))
      CALL FFV2_1(W(1,7),W(1,30),GC_649,ZERO,ZERO,W(1,56))
C     Amplitude(s) for diagram number 98
      CALL FFV1_0(W(1,2),W(1,56),W(1,47),GC_1,AMP(101))
C     Amplitude(s) for diagram number 99
      CALL FFV1_0(W(1,2),W(1,56),W(1,49),GC_1,AMP(102))
C     Amplitude(s) for diagram number 100
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,42),GC_650,GC_660,AMP(103))
C     Amplitude(s) for diagram number 101
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,44),GC_650,GC_660,AMP(104))
C     Amplitude(s) for diagram number 102
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,45),GC_650,GC_660,AMP(105))
C     Amplitude(s) for diagram number 103
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,46),GC_650,GC_660,AMP(106))
C     Amplitude(s) for diagram number 104
      CALL FFV1_0(W(1,2),W(1,56),W(1,51),GC_7,AMP(107))
C     Amplitude(s) for diagram number 105
      CALL FFV1_0(W(1,2),W(1,56),W(1,50),GC_7,AMP(108))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,10)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,50))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,10)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,51))
C     Amplitude(s) for diagram number 106
      CALL FFV2_0(W(1,50),W(1,7),W(1,30),GC_649,AMP(109))
      CALL FFV2_0(W(1,51),W(1,7),W(1,30),GC_649,AMP(110))
      CALL FFFF10_14_18_19_6_8_3(W(1,4),W(1,10),W(1,7),GC_471,GC_589
     $ ,GC_575,GC_592,GC_150,GC_472,ZERO,ZERO,W(1,51))
      CALL FFFF10_14_18_19_6_8_3(W(1,4),W(1,10),W(1,7),GC_473,GC_590
     $ ,GC_576,GC_593,GC_178,GC_474,ZERO,ZERO,W(1,50))
C     Amplitude(s) for diagram number 107
      CALL FFV2_0(W(1,2),W(1,51),W(1,30),GC_649,AMP(111))
      CALL FFV2_0(W(1,2),W(1,50),W(1,30),GC_649,AMP(112))
C     Amplitude(s) for diagram number 108
      CALL FFV1_0(W(1,55),W(1,7),W(1,54),GC_2,AMP(113))
C     Amplitude(s) for diagram number 109
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,53),GC_651,GC_660,AMP(114))
      CALL FFV6P0_3(W(1,4),W(1,52),GC_7,ZERO,ZERO,W(1,50))
C     Amplitude(s) for diagram number 110
      CALL FFV1_0(W(1,55),W(1,7),W(1,50),GC_7,AMP(115))
C     Amplitude(s) for diagram number 111
      CALL FFV1_0(W(1,2),W(1,56),W(1,54),GC_1,AMP(116))
C     Amplitude(s) for diagram number 112
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,53),GC_650,GC_660,AMP(117))
C     Amplitude(s) for diagram number 113
      CALL FFV1_0(W(1,2),W(1,56),W(1,50),GC_7,AMP(118))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,4),W(1,2),W(1,7),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,50))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,4),W(1,2),W(1,7),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,53))
C     Amplitude(s) for diagram number 114
      CALL FFV2_0(W(1,50),W(1,10),W(1,30),GC_649,AMP(119))
      CALL FFV2_0(W(1,53),W(1,10),W(1,30),GC_649,AMP(120))
      CALL FFV6_2(W(1,4),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,10))
      CALL FFV2_8_3(W(1,10),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,54))
C     Amplitude(s) for diagram number 115
      CALL FFV2_0(W(1,6),W(1,43),W(1,54),GC_664,AMP(121))
      CALL FFV11_9_3(W(1,10),W(1,3),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,52)
     $ )
C     Amplitude(s) for diagram number 116
      CALL FFV2_0(W(1,6),W(1,43),W(1,52),GC_664,AMP(122))
      CALL FFV4_3(W(1,10),W(1,3),GC_948,MDL_MZ,MDL_WZ,W(1,51))
C     Amplitude(s) for diagram number 117
      CALL FFV2_0(W(1,6),W(1,43),W(1,51),GC_664,AMP(123))
      CALL FFV2_3(W(1,10),W(1,3),GC_938,MDL_MZ,MDL_WZ,W(1,46))
C     Amplitude(s) for diagram number 118
      CALL FFV2_0(W(1,6),W(1,43),W(1,46),GC_664,AMP(124))
      CALL FFV6P0_3(W(1,10),W(1,3),GC_2,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 119
      CALL FFV1_0(W(1,48),W(1,5),W(1,45),GC_3,AMP(125))
      CALL FFV11_9P0_3(W(1,10),W(1,3),GC_813,GC_814,ZERO,ZERO,W(1,44))
C     Amplitude(s) for diagram number 120
      CALL FFV1_0(W(1,48),W(1,5),W(1,44),GC_3,AMP(126))
C     Amplitude(s) for diagram number 121
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,54),GC_650,GC_661,AMP(127))
C     Amplitude(s) for diagram number 122
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,52),GC_650,GC_661,AMP(128))
C     Amplitude(s) for diagram number 123
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,51),GC_650,GC_661,AMP(129))
C     Amplitude(s) for diagram number 124
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,46),GC_650,GC_661,AMP(130))
      CALL FFS2_4_3(W(1,10),W(1,3),GC_739,GC_738,MDL_MH,MDL_WH,W(1,42))
C     Amplitude(s) for diagram number 125
      CALL FFS4_0(W(1,48),W(1,5),W(1,42),GC_955,AMP(131))
      CALL FFS4_3(W(1,10),W(1,3),GC_954,MDL_MH,MDL_WH,W(1,49))
C     Amplitude(s) for diagram number 126
      CALL FFS4_0(W(1,48),W(1,5),W(1,49),GC_955,AMP(132))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,5),W(1,10),W(1,3)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MTA,ZERO,W(1,47))
C     Amplitude(s) for diagram number 127
      CALL FFV2_0(W(1,6),W(1,47),W(1,41),GC_649,AMP(133))
      CALL FFFF14_6_4(W(1,10),W(1,3),W(1,6),GC_586,GC_124,ZERO,ZERO
     $ ,W(1,47))
C     Amplitude(s) for diagram number 128
      CALL FFV2_0(W(1,47),W(1,5),W(1,41),GC_649,AMP(134))
      CALL FFV11_9_2(W(1,4),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,47))
      CALL FFV2_8_3(W(1,47),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,57))
C     Amplitude(s) for diagram number 129
      CALL FFV2_0(W(1,6),W(1,43),W(1,57),GC_664,AMP(135))
      CALL FFV6P0_3(W(1,47),W(1,3),GC_2,ZERO,ZERO,W(1,43))
C     Amplitude(s) for diagram number 130
      CALL FFV1_0(W(1,48),W(1,5),W(1,43),GC_3,AMP(136))
C     Amplitude(s) for diagram number 131
      CALL FFV2_7_0(W(1,48),W(1,5),W(1,57),GC_650,GC_661,AMP(137))
      CALL FFS4_3(W(1,47),W(1,3),GC_954,MDL_MH,MDL_WH,W(1,58))
C     Amplitude(s) for diagram number 132
      CALL FFS4_0(W(1,48),W(1,5),W(1,58),GC_955,AMP(138))
C     Amplitude(s) for diagram number 133
      CALL FFVV2_4_0(W(1,10),W(1,3),W(1,30),W(1,41),GC_735,GC_734
     $ ,AMP(139))
      CALL FFV2_2(W(1,10),W(1,41),GC_649,MDL_MB,ZERO,W(1,48))
C     Amplitude(s) for diagram number 134
      CALL FFV2_0(W(1,48),W(1,3),W(1,30),GC_649,AMP(140))
C     Amplitude(s) for diagram number 135
      CALL FFV4_0(W(1,48),W(1,3),W(1,30),GC_924,AMP(141))
C     Amplitude(s) for diagram number 136
      CALL FFV10_3_0(W(1,48),W(1,3),W(1,30),GC_741,GC_768,AMP(142))
C     Amplitude(s) for diagram number 137
      CALL FFV2_0(W(1,48),W(1,3),W(1,30),GC_740,AMP(143))
      CALL FFV4_2(W(1,10),W(1,41),GC_923,MDL_MB,ZERO,W(1,48))
C     Amplitude(s) for diagram number 138
      CALL FFV2_0(W(1,48),W(1,3),W(1,30),GC_649,AMP(144))
      CALL FFV10_3_2(W(1,10),W(1,41),GC_767,GC_742,MDL_MB,ZERO,W(1,48))
C     Amplitude(s) for diagram number 139
      CALL FFV2_0(W(1,48),W(1,3),W(1,30),GC_649,AMP(145))
      CALL FFV2_2(W(1,10),W(1,41),GC_740,MDL_MB,ZERO,W(1,48))
C     Amplitude(s) for diagram number 140
      CALL FFV2_0(W(1,48),W(1,3),W(1,30),GC_649,AMP(146))
C     Amplitude(s) for diagram number 141
      CALL VVV1_0(W(1,45),W(1,30),W(1,41),GC_4,AMP(147))
C     Amplitude(s) for diagram number 142
      CALL VVV1_0(W(1,44),W(1,30),W(1,41),GC_4,AMP(148))
C     Amplitude(s) for diagram number 143
      CALL VVV1_0(W(1,30),W(1,41),W(1,54),GC_653,AMP(149))
C     Amplitude(s) for diagram number 144
      CALL VVV1_0(W(1,30),W(1,41),W(1,52),GC_653,AMP(150))
C     Amplitude(s) for diagram number 145
      CALL VVV1_0(W(1,30),W(1,41),W(1,51),GC_653,AMP(151))
C     Amplitude(s) for diagram number 146
      CALL VVV1_0(W(1,30),W(1,41),W(1,46),GC_653,AMP(152))
C     Amplitude(s) for diagram number 147
      CALL VVS1_0(W(1,30),W(1,41),W(1,42),GC_730,AMP(153))
C     Amplitude(s) for diagram number 148
      CALL VVS1_0(W(1,30),W(1,41),W(1,49),GC_730,AMP(154))
      CALL FFV2_2(W(1,47),W(1,41),GC_649,MDL_MB,ZERO,W(1,49))
C     Amplitude(s) for diagram number 149
      CALL FFV2_0(W(1,49),W(1,3),W(1,30),GC_649,AMP(155))
C     Amplitude(s) for diagram number 150
      CALL VVV1_0(W(1,43),W(1,30),W(1,41),GC_4,AMP(156))
C     Amplitude(s) for diagram number 151
      CALL VVV1_0(W(1,30),W(1,41),W(1,57),GC_653,AMP(157))
C     Amplitude(s) for diagram number 152
      CALL VVS1_0(W(1,30),W(1,41),W(1,58),GC_730,AMP(158))
C     Amplitude(s) for diagram number 153
      CALL FFV2_0(W(1,10),W(1,8),W(1,41),GC_649,AMP(159))
C     Amplitude(s) for diagram number 154
      CALL FFV1_0(W(1,55),W(1,7),W(1,45),GC_2,AMP(160))
C     Amplitude(s) for diagram number 155
      CALL FFV1_0(W(1,55),W(1,7),W(1,44),GC_2,AMP(161))
C     Amplitude(s) for diagram number 156
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,54),GC_651,GC_660,AMP(162))
C     Amplitude(s) for diagram number 157
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,52),GC_651,GC_660,AMP(163))
C     Amplitude(s) for diagram number 158
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,51),GC_651,GC_660,AMP(164))
C     Amplitude(s) for diagram number 159
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,46),GC_651,GC_660,AMP(165))
      CALL FFV6P0_3(W(1,10),W(1,3),GC_7,ZERO,ZERO,W(1,58))
C     Amplitude(s) for diagram number 160
      CALL FFV1_0(W(1,55),W(1,7),W(1,58),GC_7,AMP(166))
      CALL FFV11_9P0_3(W(1,10),W(1,3),GC_725,GC_726,ZERO,ZERO,W(1,49))
C     Amplitude(s) for diagram number 161
      CALL FFV1_0(W(1,55),W(1,7),W(1,49),GC_7,AMP(167))
C     Amplitude(s) for diagram number 162
      CALL FFV1_0(W(1,2),W(1,56),W(1,45),GC_1,AMP(168))
C     Amplitude(s) for diagram number 163
      CALL FFV1_0(W(1,2),W(1,56),W(1,44),GC_1,AMP(169))
C     Amplitude(s) for diagram number 164
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,54),GC_650,GC_660,AMP(170))
C     Amplitude(s) for diagram number 165
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,52),GC_650,GC_660,AMP(171))
C     Amplitude(s) for diagram number 166
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,51),GC_650,GC_660,AMP(172))
C     Amplitude(s) for diagram number 167
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,46),GC_650,GC_660,AMP(173))
C     Amplitude(s) for diagram number 168
      CALL FFV1_0(W(1,2),W(1,56),W(1,58),GC_7,AMP(174))
C     Amplitude(s) for diagram number 169
      CALL FFV1_0(W(1,2),W(1,56),W(1,49),GC_7,AMP(175))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,10),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,49))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,10),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,58))
C     Amplitude(s) for diagram number 170
      CALL FFV2_0(W(1,49),W(1,7),W(1,30),GC_649,AMP(176))
      CALL FFV2_0(W(1,58),W(1,7),W(1,30),GC_649,AMP(177))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,10),W(1,2),W(1,7)
     $ ,GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,MDL_MB,ZERO,W(1,58))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,10),W(1,2),W(1,7)
     $ ,GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,MDL_MB,ZERO,W(1,49))
C     Amplitude(s) for diagram number 171
      CALL FFV2_0(W(1,58),W(1,3),W(1,30),GC_649,AMP(178))
      CALL FFV2_0(W(1,49),W(1,3),W(1,30),GC_649,AMP(179))
      CALL FFFF10_14_18_19_6_8_3(W(1,10),W(1,3),W(1,7),GC_471,GC_589
     $ ,GC_575,GC_592,GC_150,GC_472,ZERO,ZERO,W(1,49))
      CALL FFFF10_14_18_19_6_8_3(W(1,10),W(1,3),W(1,7),GC_473,GC_590
     $ ,GC_576,GC_593,GC_178,GC_474,ZERO,ZERO,W(1,58))
C     Amplitude(s) for diagram number 172
      CALL FFV2_0(W(1,2),W(1,49),W(1,30),GC_649,AMP(180))
      CALL FFV2_0(W(1,2),W(1,58),W(1,30),GC_649,AMP(181))
C     Amplitude(s) for diagram number 173
      CALL FFV1_0(W(1,55),W(1,7),W(1,43),GC_2,AMP(182))
C     Amplitude(s) for diagram number 174
      CALL FFV2_8_0(W(1,55),W(1,7),W(1,57),GC_651,GC_660,AMP(183))
      CALL FFV6P0_3(W(1,47),W(1,3),GC_7,ZERO,ZERO,W(1,58))
C     Amplitude(s) for diagram number 175
      CALL FFV1_0(W(1,55),W(1,7),W(1,58),GC_7,AMP(184))
C     Amplitude(s) for diagram number 176
      CALL FFV1_0(W(1,2),W(1,56),W(1,43),GC_1,AMP(185))
C     Amplitude(s) for diagram number 177
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,57),GC_650,GC_660,AMP(186))
C     Amplitude(s) for diagram number 178
      CALL FFV1_0(W(1,2),W(1,56),W(1,58),GC_7,AMP(187))
      CALL FFV1_1(W(1,7),W(1,1),GC_7,ZERO,ZERO,W(1,58))
      CALL FFV2_3(W(1,2),W(1,58),GC_649,MDL_MW,MDL_WW,W(1,57))
C     Amplitude(s) for diagram number 179
      CALL FFV2_0(W(1,6),W(1,11),W(1,57),GC_649,AMP(188))
C     Amplitude(s) for diagram number 180
      CALL FFV2_0(W(1,6),W(1,13),W(1,57),GC_649,AMP(189))
C     Amplitude(s) for diagram number 181
      CALL FFV2_0(W(1,6),W(1,15),W(1,57),GC_649,AMP(190))
C     Amplitude(s) for diagram number 182
      CALL FFV2_0(W(1,16),W(1,5),W(1,57),GC_649,AMP(191))
C     Amplitude(s) for diagram number 183
      CALL FFV2_0(W(1,6),W(1,18),W(1,57),GC_649,AMP(192))
C     Amplitude(s) for diagram number 184
      CALL FFV2_0(W(1,19),W(1,5),W(1,57),GC_649,AMP(193))
C     Amplitude(s) for diagram number 185
      CALL FFV2_0(W(1,6),W(1,21),W(1,57),GC_649,AMP(194))
C     Amplitude(s) for diagram number 186
      CALL FFV2_0(W(1,22),W(1,5),W(1,57),GC_649,AMP(195))
C     Amplitude(s) for diagram number 187
      CALL FFV2_0(W(1,6),W(1,24),W(1,57),GC_649,AMP(196))
C     Amplitude(s) for diagram number 188
      CALL FFV2_0(W(1,25),W(1,5),W(1,57),GC_649,AMP(197))
C     Amplitude(s) for diagram number 189
      CALL FFV2_0(W(1,6),W(1,27),W(1,57),GC_649,AMP(198))
C     Amplitude(s) for diagram number 190
      CALL FFV2_0(W(1,6),W(1,29),W(1,57),GC_649,AMP(199))
C     Amplitude(s) for diagram number 191
      CALL VVV1_0(W(1,9),W(1,30),W(1,57),GC_4,AMP(200))
      CALL FFV1_1(W(1,58),W(1,9),GC_2,ZERO,ZERO,W(1,29))
C     Amplitude(s) for diagram number 192
      CALL FFV2_0(W(1,2),W(1,29),W(1,30),GC_649,AMP(201))
      CALL FFV2_1(W(1,58),W(1,30),GC_649,ZERO,ZERO,W(1,29))
C     Amplitude(s) for diagram number 193
      CALL FFV1_0(W(1,2),W(1,29),W(1,9),GC_1,AMP(202))
C     Amplitude(s) for diagram number 194
      CALL VVV1_0(W(1,12),W(1,30),W(1,57),GC_4,AMP(203))
      CALL FFV1_1(W(1,58),W(1,12),GC_2,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 195
      CALL FFV2_0(W(1,2),W(1,27),W(1,30),GC_649,AMP(204))
C     Amplitude(s) for diagram number 196
      CALL FFV1_0(W(1,2),W(1,29),W(1,12),GC_1,AMP(205))
C     Amplitude(s) for diagram number 197
      CALL VVV1_0(W(1,30),W(1,57),W(1,14),GC_653,AMP(206))
      CALL FFV2_8_1(W(1,58),W(1,14),GC_651,GC_660,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 198
      CALL FFV2_0(W(1,2),W(1,27),W(1,30),GC_649,AMP(207))
C     Amplitude(s) for diagram number 199
      CALL FFV2_5_0(W(1,2),W(1,29),W(1,14),GC_650,GC_660,AMP(208))
C     Amplitude(s) for diagram number 200
      CALL VVV1_0(W(1,30),W(1,57),W(1,17),GC_653,AMP(209))
      CALL FFV2_8_1(W(1,58),W(1,17),GC_651,GC_660,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 201
      CALL FFV2_0(W(1,2),W(1,27),W(1,30),GC_649,AMP(210))
C     Amplitude(s) for diagram number 202
      CALL FFV2_5_0(W(1,2),W(1,29),W(1,17),GC_650,GC_660,AMP(211))
C     Amplitude(s) for diagram number 203
      CALL VVV1_0(W(1,30),W(1,57),W(1,20),GC_653,AMP(212))
      CALL FFV2_8_1(W(1,58),W(1,20),GC_651,GC_660,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 204
      CALL FFV2_0(W(1,2),W(1,27),W(1,30),GC_649,AMP(213))
C     Amplitude(s) for diagram number 205
      CALL FFV2_5_0(W(1,2),W(1,29),W(1,20),GC_650,GC_660,AMP(214))
C     Amplitude(s) for diagram number 206
      CALL VVV1_0(W(1,30),W(1,57),W(1,23),GC_653,AMP(215))
      CALL FFV2_8_1(W(1,58),W(1,23),GC_651,GC_660,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 207
      CALL FFV2_0(W(1,2),W(1,27),W(1,30),GC_649,AMP(216))
C     Amplitude(s) for diagram number 208
      CALL FFV2_5_0(W(1,2),W(1,29),W(1,23),GC_650,GC_660,AMP(217))
C     Amplitude(s) for diagram number 209
      CALL VVS1_0(W(1,30),W(1,57),W(1,26),GC_730,AMP(218))
C     Amplitude(s) for diagram number 210
      CALL VVS1_0(W(1,30),W(1,57),W(1,28),GC_730,AMP(219))
      CALL FFV1_1(W(1,58),W(1,32),GC_7,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 211
      CALL FFV2_0(W(1,2),W(1,28),W(1,30),GC_649,AMP(220))
C     Amplitude(s) for diagram number 212
      CALL FFV1_0(W(1,2),W(1,29),W(1,32),GC_7,AMP(221))
      CALL FFV1_1(W(1,58),W(1,33),GC_7,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 213
      CALL FFV2_0(W(1,2),W(1,28),W(1,30),GC_649,AMP(222))
C     Amplitude(s) for diagram number 214
      CALL FFV1_0(W(1,2),W(1,29),W(1,33),GC_7,AMP(223))
C     Amplitude(s) for diagram number 215
      CALL FFV2_0(W(1,4),W(1,31),W(1,57),GC_649,AMP(224))
C     Amplitude(s) for diagram number 216
      CALL FFV4_0(W(1,4),W(1,31),W(1,57),GC_923,AMP(225))
C     Amplitude(s) for diagram number 217
      CALL FFV10_3_0(W(1,4),W(1,31),W(1,57),GC_767,GC_742,AMP(226))
C     Amplitude(s) for diagram number 218
      CALL FFV2_0(W(1,4),W(1,31),W(1,57),GC_740,AMP(227))
C     Amplitude(s) for diagram number 219
      CALL FFV2_0(W(1,4),W(1,34),W(1,57),GC_649,AMP(228))
C     Amplitude(s) for diagram number 220
      CALL FFV2_0(W(1,4),W(1,35),W(1,57),GC_649,AMP(229))
C     Amplitude(s) for diagram number 221
      CALL FFV2_0(W(1,4),W(1,36),W(1,57),GC_649,AMP(230))
C     Amplitude(s) for diagram number 222
      CALL FFVV2_4_0(W(1,4),W(1,3),W(1,30),W(1,57),GC_735,GC_734
     $ ,AMP(231))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,4),W(1,2),W(1,58)
     $ ,GC_40,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60
     $ ,GC_203,MDL_MB,ZERO,W(1,29))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,4),W(1,2),W(1,58)
     $ ,GC_42,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68
     $ ,GC_211,MDL_MB,ZERO,W(1,28))
C     Amplitude(s) for diagram number 223
      CALL FFV2_0(W(1,29),W(1,3),W(1,30),GC_649,AMP(232))
      CALL FFV2_0(W(1,28),W(1,3),W(1,30),GC_649,AMP(233))
      CALL FFFF10_14_18_19_6_8_3(W(1,4),W(1,3),W(1,58),GC_471,GC_589
     $ ,GC_575,GC_592,GC_150,GC_472,ZERO,ZERO,W(1,28))
      CALL FFFF10_14_18_19_6_8_3(W(1,4),W(1,3),W(1,58),GC_473,GC_590
     $ ,GC_576,GC_593,GC_178,GC_474,ZERO,ZERO,W(1,29))
C     Amplitude(s) for diagram number 224
      CALL FFV2_0(W(1,2),W(1,28),W(1,30),GC_649,AMP(234))
      CALL FFV2_0(W(1,2),W(1,29),W(1,30),GC_649,AMP(235))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,29))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 225
      CALL FFV2_0(W(1,29),W(1,58),W(1,30),GC_649,AMP(236))
      CALL FFV2_0(W(1,28),W(1,58),W(1,30),GC_649,AMP(237))
C     Amplitude(s) for diagram number 226
      CALL FFV2_0(W(1,6),W(1,37),W(1,57),GC_649,AMP(238))
C     Amplitude(s) for diagram number 227
      CALL FFV2_0(W(1,38),W(1,5),W(1,57),GC_649,AMP(239))
C     Amplitude(s) for diagram number 228
      CALL FFV2_0(W(1,4),W(1,8),W(1,57),GC_649,AMP(240))
      CALL FFV2_2(W(1,4),W(1,41),GC_649,MDL_MB,ZERO,W(1,57))
C     Amplitude(s) for diagram number 229
      CALL FFV1_0(W(1,57),W(1,31),W(1,1),GC_7,AMP(241))
C     Amplitude(s) for diagram number 230
      CALL FFV1_0(W(1,57),W(1,34),W(1,1),GC_7,AMP(242))
C     Amplitude(s) for diagram number 231
      CALL FFV1_0(W(1,57),W(1,35),W(1,1),GC_7,AMP(243))
C     Amplitude(s) for diagram number 232
      CALL FFV1_0(W(1,57),W(1,36),W(1,1),GC_7,AMP(244))
      CALL FFV4_2(W(1,4),W(1,41),GC_923,MDL_MB,ZERO,W(1,57))
C     Amplitude(s) for diagram number 233
      CALL FFV1_0(W(1,57),W(1,31),W(1,1),GC_7,AMP(245))
      CALL FFV10_3_2(W(1,4),W(1,41),GC_767,GC_742,MDL_MB,ZERO,W(1,57))
C     Amplitude(s) for diagram number 234
      CALL FFV1_0(W(1,57),W(1,31),W(1,1),GC_7,AMP(246))
      CALL FFV2_2(W(1,4),W(1,41),GC_740,MDL_MB,ZERO,W(1,57))
C     Amplitude(s) for diagram number 235
      CALL FFV1_0(W(1,57),W(1,31),W(1,1),GC_7,AMP(247))
      CALL FFV1_1(W(1,8),W(1,1),GC_7,MDL_MB,ZERO,W(1,57))
C     Amplitude(s) for diagram number 236
      CALL FFV2_0(W(1,4),W(1,57),W(1,41),GC_649,AMP(248))
      CALL FFV1_2(W(1,2),W(1,9),GC_1,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 237
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(249))
      CALL FFV1_1(W(1,7),W(1,9),GC_2,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 238
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(250))
      CALL FFV1_2(W(1,2),W(1,12),GC_1,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 239
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(251))
      CALL FFV1_1(W(1,7),W(1,12),GC_2,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 240
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(252))
      CALL FFV2_5_2(W(1,2),W(1,14),GC_650,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 241
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(253))
      CALL FFV2_8_1(W(1,7),W(1,14),GC_651,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 242
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(254))
      CALL FFV2_5_2(W(1,2),W(1,17),GC_650,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 243
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(255))
      CALL FFV2_8_1(W(1,7),W(1,17),GC_651,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 244
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(256))
      CALL FFV2_5_2(W(1,2),W(1,20),GC_650,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 245
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(257))
      CALL FFV2_8_1(W(1,7),W(1,20),GC_651,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 246
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(258))
      CALL FFV2_5_2(W(1,2),W(1,23),GC_650,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 247
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(259))
      CALL FFV2_8_1(W(1,7),W(1,23),GC_651,GC_660,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 248
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(260))
      CALL VVV1P0_1(W(1,1),W(1,32),GC_6,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 249
      CALL FFV1_0(W(1,55),W(1,7),W(1,57),GC_7,AMP(261))
C     Amplitude(s) for diagram number 250
      CALL FFV1_0(W(1,2),W(1,56),W(1,57),GC_7,AMP(262))
      CALL FFV1_2(W(1,2),W(1,32),GC_7,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 251
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(263))
      CALL FFV1_1(W(1,7),W(1,32),GC_7,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 252
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(264))
      CALL VVV1P0_1(W(1,1),W(1,33),GC_6,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 253
      CALL FFV1_0(W(1,55),W(1,7),W(1,57),GC_7,AMP(265))
C     Amplitude(s) for diagram number 254
      CALL FFV1_0(W(1,2),W(1,56),W(1,57),GC_7,AMP(266))
      CALL FFV1_2(W(1,2),W(1,33),GC_7,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 255
      CALL FFV1_0(W(1,57),W(1,56),W(1,1),GC_7,AMP(267))
      CALL FFV1_1(W(1,7),W(1,33),GC_7,ZERO,ZERO,W(1,57))
C     Amplitude(s) for diagram number 256
      CALL FFV1_0(W(1,55),W(1,57),W(1,1),GC_7,AMP(268))
      CALL FFVS4_6_4(W(1,4),W(1,3),W(1,1),GC_599,GC_598,MDL_MH,MDL_WH
     $ ,W(1,57))
      CALL FFS4_1(W(1,5),W(1,57),GC_955,MDL_MTA,ZERO,W(1,55))
C     Amplitude(s) for diagram number 257
      CALL FFV2_0(W(1,6),W(1,55),W(1,41),GC_649,AMP(269))
C     Amplitude(s) for diagram number 258
      CALL VVS1_0(W(1,30),W(1,41),W(1,57),GC_730,AMP(270))
      CALL FFVV2_4P0_3(W(1,4),W(1,3),W(1,1),GC_728,GC_727,ZERO,ZERO
     $ ,W(1,57))
      CALL FFV1_2(W(1,2),W(1,57),GC_7,ZERO,ZERO,W(1,4))
C     Amplitude(s) for diagram number 259
      CALL FFV2_0(W(1,4),W(1,7),W(1,30),GC_649,AMP(271))
      CALL FFV1_1(W(1,7),W(1,57),GC_7,ZERO,ZERO,W(1,4))
C     Amplitude(s) for diagram number 260
      CALL FFV2_0(W(1,2),W(1,4),W(1,30),GC_649,AMP(272))
      CALL FFV1_2(W(1,29),W(1,1),GC_7,ZERO,ZERO,W(1,4))
      CALL FFV1_2(W(1,28),W(1,1),GC_7,ZERO,ZERO,W(1,29))
C     Amplitude(s) for diagram number 261
      CALL FFV2_0(W(1,4),W(1,7),W(1,30),GC_649,AMP(273))
      CALL FFV2_0(W(1,29),W(1,7),W(1,30),GC_649,AMP(274))
      CALL FFV1_2(W(1,50),W(1,1),GC_7,MDL_MB,ZERO,W(1,29))
      CALL FFV1_2(W(1,53),W(1,1),GC_7,MDL_MB,ZERO,W(1,50))
C     Amplitude(s) for diagram number 262
      CALL FFV2_0(W(1,29),W(1,3),W(1,30),GC_649,AMP(275))
      CALL FFV2_0(W(1,50),W(1,3),W(1,30),GC_649,AMP(276))
      CALL FFV1_1(W(1,39),W(1,1),GC_7,ZERO,ZERO,W(1,50))
      CALL FFV1_1(W(1,40),W(1,1),GC_7,ZERO,ZERO,W(1,39))
C     Amplitude(s) for diagram number 263
      CALL FFV2_0(W(1,2),W(1,50),W(1,30),GC_649,AMP(277))
      CALL FFV2_0(W(1,2),W(1,39),W(1,30),GC_649,AMP(278))
      JAMP(1)=+1D0/2D0*(+AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(46)
     $ +AMP(48)+AMP(52)+AMP(99)+AMP(100)+AMP(107)+AMP(108)+AMP(110)
     $ +AMP(112)+AMP(115)+AMP(118)+AMP(120)+IMAG1*AMP(261)+IMAG1
     $ *AMP(262)+AMP(264)+IMAG1*AMP(265)+IMAG1*AMP(266)+AMP(268)+IMAG1
     $ *AMP(271)+IMAG1*AMP(272)+AMP(276)+AMP(278))
      JAMP(2)=+AMP(54)+AMP(55)+AMP(56)+AMP(57)+AMP(58)+AMP(59)+AMP(60)
     $ +AMP(61)+AMP(62)+AMP(63)+AMP(64)+AMP(65)+AMP(66)+AMP(67)+AMP(68)
     $ +AMP(69)+AMP(70)+AMP(71)+AMP(72)+AMP(73)+AMP(74)+AMP(75)+AMP(76)
     $ +AMP(77)+AMP(78)+AMP(79)+AMP(80)+AMP(81)+AMP(82)+AMP(83)+AMP(84)
     $ +AMP(85)+AMP(86)+AMP(87)+AMP(88)+AMP(89)+AMP(90)+AMP(91)+AMP(92)
     $ +AMP(93)+AMP(94)+AMP(95)+AMP(96)+AMP(97)+AMP(98)-1D0/6D0*AMP(99)
     $ -1D0/6D0*AMP(100)+AMP(101)+AMP(102)+AMP(103)+AMP(104)+AMP(105)
     $ +AMP(106)-1D0/6D0*AMP(107)-1D0/6D0*AMP(108)+AMP(109)-1D0/6D0
     $ *AMP(110)+AMP(111)-1D0/6D0*AMP(112)+AMP(113)+AMP(114)-1D0/6D0
     $ *AMP(115)+AMP(116)+AMP(117)-1D0/6D0*AMP(118)+AMP(119)-1D0/6D0
     $ *AMP(120)+AMP(121)+AMP(122)+AMP(123)+AMP(124)+AMP(125)+AMP(126)
     $ +AMP(127)+AMP(128)+AMP(129)+AMP(130)+AMP(131)+AMP(132)+AMP(133)
     $ +AMP(134)+AMP(135)+AMP(136)+AMP(137)+AMP(138)+AMP(139)+AMP(140)
     $ +AMP(141)+AMP(142)+AMP(143)+AMP(144)+AMP(145)+AMP(146)+AMP(147)
     $ +AMP(148)+AMP(149)+AMP(150)+AMP(151)+AMP(152)+AMP(153)+AMP(154)
     $ +AMP(155)+AMP(156)+AMP(157)+AMP(158)+AMP(159)+AMP(160)+AMP(161)
     $ +AMP(162)+AMP(163)+AMP(164)+AMP(165)-1D0/6D0*AMP(166)-1D0/6D0
     $ *AMP(167)+AMP(168)+AMP(169)+AMP(170)+AMP(171)+AMP(172)+AMP(173)
     $ -1D0/6D0*AMP(174)-1D0/6D0*AMP(175)+AMP(176)-1D0/6D0*AMP(177)
     $ +AMP(178)-1D0/6D0*AMP(179)+AMP(180)-1D0/6D0*AMP(181)+AMP(182)
     $ +AMP(183)-1D0/6D0*AMP(184)+AMP(185)+AMP(186)-1D0/6D0*AMP(187)
     $ +AMP(241)+AMP(242)+AMP(243)+AMP(244)+AMP(245)+AMP(246)+AMP(247)
     $ +AMP(248)+AMP(269)+AMP(270)+AMP(275)-1D0/6D0*AMP(276)
      JAMP(3)=+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)+AMP(8)
     $ +AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)+AMP(16)
     $ +AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)+AMP(24)
     $ +AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)+AMP(32)
     $ -1D0/6D0*AMP(33)-1D0/6D0*AMP(34)-1D0/6D0*AMP(35)-1D0/6D0*AMP(36)
     $ +AMP(37)+AMP(38)+AMP(39)+AMP(40)+AMP(41)+AMP(42)+AMP(43)+AMP(44)
     $ +AMP(45)-1D0/6D0*AMP(46)+AMP(47)-1D0/6D0*AMP(48)+AMP(49)+AMP(50)
     $ +AMP(51)-1D0/6D0*AMP(52)+AMP(53)+AMP(188)+AMP(189)+AMP(190)
     $ +AMP(191)+AMP(192)+AMP(193)+AMP(194)+AMP(195)+AMP(196)+AMP(197)
     $ +AMP(198)+AMP(199)+AMP(200)+AMP(201)+AMP(202)+AMP(203)+AMP(204)
     $ +AMP(205)+AMP(206)+AMP(207)+AMP(208)+AMP(209)+AMP(210)+AMP(211)
     $ +AMP(212)+AMP(213)+AMP(214)+AMP(215)+AMP(216)+AMP(217)+AMP(218)
     $ +AMP(219)-1D0/6D0*AMP(220)-1D0/6D0*AMP(221)-1D0/6D0*AMP(222)
     $ -1D0/6D0*AMP(223)+AMP(224)+AMP(225)+AMP(226)+AMP(227)+AMP(228)
     $ +AMP(229)+AMP(230)+AMP(231)+AMP(232)-1D0/6D0*AMP(233)+AMP(234)
     $ -1D0/6D0*AMP(235)+AMP(236)-1D0/6D0*AMP(237)+AMP(238)+AMP(239)
     $ +AMP(240)+AMP(249)+AMP(250)+AMP(251)+AMP(252)+AMP(253)+AMP(254)
     $ +AMP(255)+AMP(256)+AMP(257)+AMP(258)+AMP(259)+AMP(260)-1D0/6D0
     $ *AMP(263)-1D0/6D0*AMP(264)-1D0/6D0*AMP(267)-1D0/6D0*AMP(268)
     $ +AMP(273)-1D0/6D0*AMP(274)+AMP(277)-1D0/6D0*AMP(278)
      JAMP(4)=+1D0/2D0*(+AMP(166)+AMP(167)+AMP(174)+AMP(175)+AMP(177)
     $ +AMP(179)+AMP(181)+AMP(184)+AMP(187)+AMP(220)+AMP(221)+AMP(222)
     $ +AMP(223)+AMP(233)+AMP(235)+AMP(237)-IMAG1*AMP(261)-IMAG1
     $ *AMP(262)+AMP(263)-IMAG1*AMP(265)-IMAG1*AMP(266)+AMP(267)-IMAG1
     $ *AMP(271)-IMAG1*AMP(272)+AMP(274))

      M7_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M7_MATRIX = M7_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M7_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M7_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M7_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M7_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M7_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NCOMB
      PARAMETER (NCOMB=128)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M7_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M7_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M7_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M7_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

