      SUBROUTINE M10_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M10_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M10_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M10_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g d > t~ b u ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     Process: g s > t~ b c ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M10_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M10_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M10_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,7) /-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,   2),I=1,7) /-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,   3),I=1,7) /-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,   4),I=1,7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,   5),I=1,7) /-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,   6),I=1,7) /-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,   7),I=1,7) /-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,   8),I=1,7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,   9),I=1,7) /-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,7) /-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,7) /-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,7) /-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,7) /-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,7) /-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  18),I=1,7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  19),I=1,7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  20),I=1,7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  21),I=1,7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  22),I=1,7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  23),I=1,7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  24),I=1,7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  25),I=1,7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  26),I=1,7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  27),I=1,7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  28),I=1,7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  29),I=1,7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  30),I=1,7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  31),I=1,7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  32),I=1,7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  33),I=1,7) /-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,7) /-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,7) /-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,7) /-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,7) /-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,7) /-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,7) /-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,7) /-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,7) /-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  42),I=1,7) /-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  43),I=1,7) /-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  44),I=1,7) /-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  45),I=1,7) /-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  46),I=1,7) /-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  47),I=1,7) /-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  48),I=1,7) /-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  49),I=1,7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  50),I=1,7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  51),I=1,7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  52),I=1,7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  53),I=1,7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  54),I=1,7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  55),I=1,7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  56),I=1,7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  57),I=1,7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  58),I=1,7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  59),I=1,7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  60),I=1,7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  61),I=1,7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  62),I=1,7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  63),I=1,7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  64),I=1,7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  65),I=1,7) / 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  66),I=1,7) / 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  67),I=1,7) / 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  68),I=1,7) / 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  69),I=1,7) / 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  70),I=1,7) / 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  71),I=1,7) / 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  72),I=1,7) / 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  73),I=1,7) / 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  74),I=1,7) / 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  75),I=1,7) / 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  76),I=1,7) / 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  77),I=1,7) / 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  78),I=1,7) / 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  79),I=1,7) / 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  80),I=1,7) / 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  81),I=1,7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  82),I=1,7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  83),I=1,7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  84),I=1,7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  85),I=1,7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  86),I=1,7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  87),I=1,7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  88),I=1,7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  89),I=1,7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  90),I=1,7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  91),I=1,7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  92),I=1,7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  93),I=1,7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  94),I=1,7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  95),I=1,7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  96),I=1,7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  97),I=1,7) / 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  98),I=1,7) / 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  99),I=1,7) / 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 100),I=1,7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 101),I=1,7) / 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 102),I=1,7) / 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 103),I=1,7) / 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 104),I=1,7) / 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 105),I=1,7) / 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 106),I=1,7) / 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 107),I=1,7) / 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 108),I=1,7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 109),I=1,7) / 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 110),I=1,7) / 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 111),I=1,7) / 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 112),I=1,7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 113),I=1,7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 114),I=1,7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 115),I=1,7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 116),I=1,7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 117),I=1,7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 118),I=1,7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 119),I=1,7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 120),I=1,7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 121),I=1,7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 122),I=1,7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 123),I=1,7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 124),I=1,7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 125),I=1,7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 126),I=1,7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 127),I=1,7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 128),I=1,7) / 1,-1,-1, 1, 1,-1, 1/
      DATA IDEN/96/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M10_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M10_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M10_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M10_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M10_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M10_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g d > t~ b u ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     Process: g s > t~ b c ta+ ta- DIM6<=1 FCNC=0 $$ w+ w- / h @2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=233)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=30, NCOLOR=4)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  4) /   12,    4,    4,    0/
C     1 T(1,4,2) T(5,3)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  4) /    4,   12,    0,    4/
C     1 T(1,4,3) T(5,2)
      DATA DENOM(3)/1/
      DATA (CF(I,  3),I=  1,  4) /    4,    0,   12,    4/
C     1 T(1,5,2) T(4,3)
      DATA DENOM(4)/1/
      DATA (CF(I,  4),I=  1,  4) /    0,    4,    4,   12/
C     1 T(1,5,3) T(4,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))
      CALL IXXXXX(P(0,3),MDL_MT,NHEL(3),-1*IC(3),W(1,3))
      CALL OXXXXX(P(0,4),MDL_MB,NHEL(4),+1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),MDL_MTA,NHEL(6),-1*IC(6),W(1,6))
      CALL OXXXXX(P(0,7),MDL_MTA,NHEL(7),+1*IC(7),W(1,7))
      CALL FFV1_2(W(1,2),W(1,1),GC_7,ZERO,ZERO,W(1,8))
      CALL FFV1P0_3(W(1,6),W(1,7),GC_3,ZERO,ZERO,W(1,9))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,10))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,10),W(1,5),W(1,9),GC_2,AMP(1))
      CALL FFV1_0(W(1,11),W(1,5),W(1,9),GC_2,AMP(2))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,8),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,8),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,13))
C     Amplitude(s) for diagram number 2
      CALL FFV6_0(W(1,12),W(1,4),W(1,9),GC_1,AMP(3))
      CALL FFV6_0(W(1,13),W(1,4),W(1,9),GC_1,AMP(4))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,8),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,14))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,8),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,15))
C     Amplitude(s) for diagram number 3
      CALL FFV6_0(W(1,3),W(1,14),W(1,9),GC_2,AMP(5))
      CALL FFV6_0(W(1,3),W(1,15),W(1,9),GC_2,AMP(6))
      CALL FFV2_7_3(W(1,6),W(1,7),GC_650,GC_661,MDL_MZ,MDL_WZ,W(1,16))
C     Amplitude(s) for diagram number 4
      CALL FFV2_8_0(W(1,10),W(1,5),W(1,16),GC_651,GC_660,AMP(7))
      CALL FFV2_8_0(W(1,11),W(1,5),W(1,16),GC_651,GC_660,AMP(8))
C     Amplitude(s) for diagram number 5
      CALL FFV2_5_0(W(1,12),W(1,4),W(1,16),GC_650,GC_660,AMP(9))
      CALL FFV2_5_0(W(1,13),W(1,4),W(1,16),GC_650,GC_660,AMP(10))
C     Amplitude(s) for diagram number 6
      CALL FFV2_8_0(W(1,3),W(1,14),W(1,16),GC_651,GC_660,AMP(11))
      CALL FFV2_8_0(W(1,3),W(1,15),W(1,16),GC_651,GC_660,AMP(12))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,4),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,15))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,4),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 7
      CALL FFV1_0(W(1,8),W(1,15),W(1,9),GC_1,AMP(13))
      CALL FFV1_0(W(1,8),W(1,14),W(1,9),GC_1,AMP(14))
C     Amplitude(s) for diagram number 8
      CALL FFV2_5_0(W(1,8),W(1,15),W(1,16),GC_650,GC_660,AMP(15))
      CALL FFV2_5_0(W(1,8),W(1,14),W(1,16),GC_650,GC_660,AMP(16))
      CALL FFV6_2(W(1,3),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,8))
      CALL FFV2_3(W(1,2),W(1,5),GC_649,MDL_MW,MDL_WW,W(1,13))
      CALL FFV2_3(W(1,8),W(1,4),GC_649,MDL_MW,MDL_WW,W(1,12))
      CALL FFV2_1(W(1,7),W(1,13),GC_649,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 9
      CALL FFV2_0(W(1,6),W(1,11),W(1,12),GC_649,AMP(17))
      CALL FFV4_3(W(1,8),W(1,4),GC_923,MDL_MW,MDL_WW,W(1,10))
C     Amplitude(s) for diagram number 10
      CALL FFV2_0(W(1,6),W(1,11),W(1,10),GC_649,AMP(18))
      CALL FFV10_3_3(W(1,8),W(1,4),GC_767,GC_742,MDL_MW,MDL_WW,W(1,17))
C     Amplitude(s) for diagram number 11
      CALL FFV2_0(W(1,6),W(1,11),W(1,17),GC_649,AMP(19))
      CALL FFV2_3(W(1,8),W(1,4),GC_740,MDL_MW,MDL_WW,W(1,18))
C     Amplitude(s) for diagram number 12
      CALL FFV2_0(W(1,6),W(1,11),W(1,18),GC_649,AMP(20))
      CALL FFFF10_11_20_6_110_4(W(1,8),W(1,4),W(1,6),GC_14,GC_353
     $ ,GC_351,GC_566,GC_350,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 13
      CALL FFV2_0(W(1,19),W(1,7),W(1,13),GC_649,AMP(21))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,6),W(1,7),W(1,8)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MT,MDL_WT,W(1,19))
C     Amplitude(s) for diagram number 14
      CALL FFV2_0(W(1,19),W(1,4),W(1,13),GC_649,AMP(22))
      CALL FFV11_9_2(W(1,3),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,19))
      CALL FFV2_3(W(1,19),W(1,4),GC_649,MDL_MW,MDL_WW,W(1,20))
C     Amplitude(s) for diagram number 15
      CALL FFV2_0(W(1,6),W(1,11),W(1,20),GC_649,AMP(23))
C     Amplitude(s) for diagram number 16
      CALL FFVV1_3_0(W(1,8),W(1,4),W(1,9),W(1,13),GC_785,GC_795,AMP(24)
     $ )
      CALL FFV2_2(W(1,8),W(1,13),GC_649,MDL_MB,ZERO,W(1,21))
C     Amplitude(s) for diagram number 17
      CALL FFV6_0(W(1,21),W(1,4),W(1,9),GC_1,AMP(25))
C     Amplitude(s) for diagram number 18
      CALL FFV11_9_0(W(1,21),W(1,4),W(1,9),GC_736,GC_737,AMP(26))
      CALL FFV4_2(W(1,8),W(1,13),GC_923,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 19
      CALL FFV6_0(W(1,22),W(1,4),W(1,9),GC_1,AMP(27))
      CALL FFV10_3_2(W(1,8),W(1,13),GC_767,GC_742,MDL_MB,ZERO,W(1,23))
C     Amplitude(s) for diagram number 20
      CALL FFV6_0(W(1,23),W(1,4),W(1,9),GC_1,AMP(28))
      CALL FFV2_2(W(1,8),W(1,13),GC_740,MDL_MB,ZERO,W(1,24))
C     Amplitude(s) for diagram number 21
      CALL FFV6_0(W(1,24),W(1,4),W(1,9),GC_1,AMP(29))
C     Amplitude(s) for diagram number 22
      CALL VVV1_0(W(1,9),W(1,12),W(1,13),GC_4,AMP(30))
C     Amplitude(s) for diagram number 23
      CALL VVV1_0(W(1,9),W(1,10),W(1,13),GC_4,AMP(31))
C     Amplitude(s) for diagram number 24
      CALL VVV1_0(W(1,9),W(1,17),W(1,13),GC_4,AMP(32))
C     Amplitude(s) for diagram number 25
      CALL VVV1_0(W(1,9),W(1,18),W(1,13),GC_4,AMP(33))
      CALL FFV6_2(W(1,8),W(1,9),GC_2,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 26
      CALL FFV2_0(W(1,25),W(1,4),W(1,13),GC_649,AMP(34))
C     Amplitude(s) for diagram number 27
      CALL FFV4_0(W(1,25),W(1,4),W(1,13),GC_923,AMP(35))
C     Amplitude(s) for diagram number 28
      CALL FFV10_3_0(W(1,25),W(1,4),W(1,13),GC_767,GC_742,AMP(36))
C     Amplitude(s) for diagram number 29
      CALL FFV2_0(W(1,25),W(1,4),W(1,13),GC_740,AMP(37))
      CALL FFV11_9_2(W(1,8),W(1,9),GC_813,GC_814,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 30
      CALL FFV2_0(W(1,25),W(1,4),W(1,13),GC_649,AMP(38))
C     Amplitude(s) for diagram number 31
      CALL FFVV1_3_0(W(1,8),W(1,4),W(1,13),W(1,16),GC_838,GC_848
     $ ,AMP(39))
C     Amplitude(s) for diagram number 32
      CALL FFV2_5_0(W(1,21),W(1,4),W(1,16),GC_650,GC_660,AMP(40))
C     Amplitude(s) for diagram number 33
      CALL FFV11_9_0(W(1,21),W(1,4),W(1,16),GC_723,GC_724,AMP(41))
C     Amplitude(s) for diagram number 34
      CALL FFV4_0(W(1,21),W(1,4),W(1,16),GC_933,AMP(42))
C     Amplitude(s) for diagram number 35
      CALL FFV2_0(W(1,21),W(1,4),W(1,16),GC_939,AMP(43))
C     Amplitude(s) for diagram number 36
      CALL FFV2_5_0(W(1,22),W(1,4),W(1,16),GC_650,GC_660,AMP(44))
C     Amplitude(s) for diagram number 37
      CALL FFV2_5_0(W(1,23),W(1,4),W(1,16),GC_650,GC_660,AMP(45))
C     Amplitude(s) for diagram number 38
      CALL FFV2_5_0(W(1,24),W(1,4),W(1,16),GC_650,GC_660,AMP(46))
C     Amplitude(s) for diagram number 39
      CALL VVV1_0(W(1,12),W(1,13),W(1,16),GC_653,AMP(47))
C     Amplitude(s) for diagram number 40
      CALL VVV1_0(W(1,10),W(1,13),W(1,16),GC_653,AMP(48))
C     Amplitude(s) for diagram number 41
      CALL VVV1_0(W(1,17),W(1,13),W(1,16),GC_653,AMP(49))
C     Amplitude(s) for diagram number 42
      CALL VVV1_0(W(1,18),W(1,13),W(1,16),GC_653,AMP(50))
      CALL FFV2_8_2(W(1,8),W(1,16),GC_651,GC_660,MDL_MT,MDL_WT,W(1,24))
C     Amplitude(s) for diagram number 43
      CALL FFV2_0(W(1,24),W(1,4),W(1,13),GC_649,AMP(51))
C     Amplitude(s) for diagram number 44
      CALL FFV4_0(W(1,24),W(1,4),W(1,13),GC_923,AMP(52))
C     Amplitude(s) for diagram number 45
      CALL FFV10_3_0(W(1,24),W(1,4),W(1,13),GC_767,GC_742,AMP(53))
C     Amplitude(s) for diagram number 46
      CALL FFV2_0(W(1,24),W(1,4),W(1,13),GC_740,AMP(54))
      CALL FFV11_9_2(W(1,8),W(1,16),GC_721,GC_722,MDL_MT,MDL_WT,W(1,24)
     $ )
C     Amplitude(s) for diagram number 47
      CALL FFV2_0(W(1,24),W(1,4),W(1,13),GC_649,AMP(55))
      CALL FFV4_2(W(1,8),W(1,16),GC_948,MDL_MT,MDL_WT,W(1,24))
C     Amplitude(s) for diagram number 48
      CALL FFV2_0(W(1,24),W(1,4),W(1,13),GC_649,AMP(56))
      CALL FFV2_2(W(1,8),W(1,16),GC_938,MDL_MT,MDL_WT,W(1,24))
C     Amplitude(s) for diagram number 49
      CALL FFV2_0(W(1,24),W(1,4),W(1,13),GC_649,AMP(57))
      CALL FFV2_2(W(1,19),W(1,13),GC_649,MDL_MB,ZERO,W(1,24))
C     Amplitude(s) for diagram number 50
      CALL FFV6_0(W(1,24),W(1,4),W(1,9),GC_1,AMP(58))
C     Amplitude(s) for diagram number 51
      CALL VVV1_0(W(1,9),W(1,20),W(1,13),GC_4,AMP(59))
      CALL FFV6_2(W(1,19),W(1,9),GC_2,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 52
      CALL FFV2_0(W(1,23),W(1,4),W(1,13),GC_649,AMP(60))
C     Amplitude(s) for diagram number 53
      CALL FFV2_5_0(W(1,24),W(1,4),W(1,16),GC_650,GC_660,AMP(61))
C     Amplitude(s) for diagram number 54
      CALL VVV1_0(W(1,20),W(1,13),W(1,16),GC_653,AMP(62))
      CALL FFV2_8_2(W(1,19),W(1,16),GC_651,GC_660,MDL_MT,MDL_WT,W(1,24)
     $ )
C     Amplitude(s) for diagram number 55
      CALL FFV2_0(W(1,24),W(1,4),W(1,13),GC_649,AMP(63))
      CALL FFFF10_14_6_8_3(W(1,6),W(1,7),W(1,4),GC_15,GC_563,GC_124
     $ ,GC_14,MDL_MB,ZERO,W(1,24))
C     Amplitude(s) for diagram number 56
      CALL FFV2_0(W(1,8),W(1,24),W(1,13),GC_649,AMP(64))
      CALL FFV1_2(W(1,2),W(1,9),GC_1,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 57
      CALL FFV2_0(W(1,19),W(1,5),W(1,12),GC_649,AMP(65))
C     Amplitude(s) for diagram number 58
      CALL FFV2_0(W(1,19),W(1,5),W(1,10),GC_649,AMP(66))
C     Amplitude(s) for diagram number 59
      CALL FFV2_0(W(1,19),W(1,5),W(1,17),GC_649,AMP(67))
C     Amplitude(s) for diagram number 60
      CALL FFV2_0(W(1,19),W(1,5),W(1,18),GC_649,AMP(68))
      CALL FFV1_1(W(1,5),W(1,9),GC_2,ZERO,ZERO,W(1,23))
C     Amplitude(s) for diagram number 61
      CALL FFV2_0(W(1,2),W(1,23),W(1,12),GC_649,AMP(69))
C     Amplitude(s) for diagram number 62
      CALL FFV2_0(W(1,2),W(1,23),W(1,10),GC_649,AMP(70))
C     Amplitude(s) for diagram number 63
      CALL FFV2_0(W(1,2),W(1,23),W(1,17),GC_649,AMP(71))
C     Amplitude(s) for diagram number 64
      CALL FFV2_0(W(1,2),W(1,23),W(1,18),GC_649,AMP(72))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,8),W(1,4),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,22))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,8),W(1,4),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 65
      CALL FFV1_0(W(1,22),W(1,5),W(1,9),GC_2,AMP(73))
      CALL FFV1_0(W(1,21),W(1,5),W(1,9),GC_2,AMP(74))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,8),W(1,2),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,25))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,8),W(1,2),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,26))
C     Amplitude(s) for diagram number 66
      CALL FFV6_0(W(1,25),W(1,4),W(1,9),GC_1,AMP(75))
      CALL FFV6_0(W(1,26),W(1,4),W(1,9),GC_1,AMP(76))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,8),W(1,4),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,27))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,8),W(1,4),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 67
      CALL FFV1_0(W(1,2),W(1,27),W(1,9),GC_1,AMP(77))
      CALL FFV1_0(W(1,2),W(1,28),W(1,9),GC_1,AMP(78))
      CALL FFV2_5_2(W(1,2),W(1,16),GC_650,GC_660,ZERO,ZERO,W(1,29))
C     Amplitude(s) for diagram number 68
      CALL FFV2_0(W(1,29),W(1,5),W(1,12),GC_649,AMP(79))
C     Amplitude(s) for diagram number 69
      CALL FFV2_0(W(1,29),W(1,5),W(1,10),GC_649,AMP(80))
C     Amplitude(s) for diagram number 70
      CALL FFV2_0(W(1,29),W(1,5),W(1,17),GC_649,AMP(81))
C     Amplitude(s) for diagram number 71
      CALL FFV2_0(W(1,29),W(1,5),W(1,18),GC_649,AMP(82))
      CALL FFV2_8_1(W(1,5),W(1,16),GC_651,GC_660,ZERO,ZERO,W(1,30))
C     Amplitude(s) for diagram number 72
      CALL FFV2_0(W(1,2),W(1,30),W(1,12),GC_649,AMP(83))
C     Amplitude(s) for diagram number 73
      CALL FFV2_0(W(1,2),W(1,30),W(1,10),GC_649,AMP(84))
C     Amplitude(s) for diagram number 74
      CALL FFV2_0(W(1,2),W(1,30),W(1,17),GC_649,AMP(85))
C     Amplitude(s) for diagram number 75
      CALL FFV2_0(W(1,2),W(1,30),W(1,18),GC_649,AMP(86))
C     Amplitude(s) for diagram number 76
      CALL FFV2_8_0(W(1,22),W(1,5),W(1,16),GC_651,GC_660,AMP(87))
      CALL FFV2_8_0(W(1,21),W(1,5),W(1,16),GC_651,GC_660,AMP(88))
C     Amplitude(s) for diagram number 77
      CALL FFV2_5_0(W(1,25),W(1,4),W(1,16),GC_650,GC_660,AMP(89))
      CALL FFV2_5_0(W(1,26),W(1,4),W(1,16),GC_650,GC_660,AMP(90))
C     Amplitude(s) for diagram number 78
      CALL FFV2_5_0(W(1,2),W(1,27),W(1,16),GC_650,GC_660,AMP(91))
      CALL FFV2_5_0(W(1,2),W(1,28),W(1,16),GC_650,GC_660,AMP(92))
C     Amplitude(s) for diagram number 79
      CALL FFV2_0(W(1,19),W(1,5),W(1,20),GC_649,AMP(93))
C     Amplitude(s) for diagram number 80
      CALL FFV2_0(W(1,2),W(1,23),W(1,20),GC_649,AMP(94))
C     Amplitude(s) for diagram number 81
      CALL FFV2_0(W(1,29),W(1,5),W(1,20),GC_649,AMP(95))
C     Amplitude(s) for diagram number 82
      CALL FFV2_0(W(1,2),W(1,30),W(1,20),GC_649,AMP(96))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,2),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,20))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,2),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,28))
C     Amplitude(s) for diagram number 83
      CALL FFV6_0(W(1,8),W(1,20),W(1,9),GC_2,AMP(97))
      CALL FFV6_0(W(1,8),W(1,28),W(1,9),GC_2,AMP(98))
C     Amplitude(s) for diagram number 84
      CALL FFV2_8_0(W(1,8),W(1,20),W(1,16),GC_651,GC_660,AMP(99))
      CALL FFV2_8_0(W(1,8),W(1,28),W(1,16),GC_651,GC_660,AMP(100))
      CALL FFV1_1(W(1,4),W(1,1),GC_7,MDL_MB,ZERO,W(1,8))
      CALL FFV2_3(W(1,3),W(1,8),GC_649,MDL_MW,MDL_WW,W(1,27))
C     Amplitude(s) for diagram number 85
      CALL FFV2_0(W(1,6),W(1,11),W(1,27),GC_649,AMP(101))
      CALL FFV4_3(W(1,3),W(1,8),GC_923,MDL_MW,MDL_WW,W(1,26))
C     Amplitude(s) for diagram number 86
      CALL FFV2_0(W(1,6),W(1,11),W(1,26),GC_649,AMP(102))
      CALL FFV10_3_3(W(1,3),W(1,8),GC_767,GC_742,MDL_MW,MDL_WW,W(1,25))
C     Amplitude(s) for diagram number 87
      CALL FFV2_0(W(1,6),W(1,11),W(1,25),GC_649,AMP(103))
      CALL FFV2_3(W(1,3),W(1,8),GC_740,MDL_MW,MDL_WW,W(1,21))
C     Amplitude(s) for diagram number 88
      CALL FFV2_0(W(1,6),W(1,11),W(1,21),GC_649,AMP(104))
      CALL FFFF10_11_20_6_110_4(W(1,3),W(1,8),W(1,6),GC_14,GC_353
     $ ,GC_351,GC_566,GC_350,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 89
      CALL FFV2_0(W(1,11),W(1,7),W(1,13),GC_649,AMP(105))
      CALL FFFF10_14_6_8_3(W(1,6),W(1,7),W(1,8),GC_15,GC_563,GC_124
     $ ,GC_14,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 90
      CALL FFV2_0(W(1,3),W(1,11),W(1,13),GC_649,AMP(106))
C     Amplitude(s) for diagram number 91
      CALL FFVV1_3_0(W(1,3),W(1,8),W(1,9),W(1,13),GC_785,GC_795
     $ ,AMP(107))
      CALL FFV2_1(W(1,8),W(1,13),GC_649,MDL_MT,MDL_WT,W(1,11))
C     Amplitude(s) for diagram number 92
      CALL FFV6_0(W(1,3),W(1,11),W(1,9),GC_2,AMP(108))
C     Amplitude(s) for diagram number 93
      CALL FFV11_9_0(W(1,3),W(1,11),W(1,9),GC_813,GC_814,AMP(109))
      CALL FFV4_1(W(1,8),W(1,13),GC_923,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 94
      CALL FFV6_0(W(1,3),W(1,22),W(1,9),GC_2,AMP(110))
      CALL FFV10_3_1(W(1,8),W(1,13),GC_767,GC_742,MDL_MT,MDL_WT,W(1,18)
     $ )
C     Amplitude(s) for diagram number 95
      CALL FFV6_0(W(1,3),W(1,18),W(1,9),GC_2,AMP(111))
      CALL FFV2_1(W(1,8),W(1,13),GC_740,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 96
      CALL FFV6_0(W(1,3),W(1,17),W(1,9),GC_2,AMP(112))
C     Amplitude(s) for diagram number 97
      CALL VVV1_0(W(1,9),W(1,27),W(1,13),GC_4,AMP(113))
C     Amplitude(s) for diagram number 98
      CALL VVV1_0(W(1,9),W(1,26),W(1,13),GC_4,AMP(114))
C     Amplitude(s) for diagram number 99
      CALL VVV1_0(W(1,9),W(1,25),W(1,13),GC_4,AMP(115))
C     Amplitude(s) for diagram number 100
      CALL VVV1_0(W(1,9),W(1,21),W(1,13),GC_4,AMP(116))
      CALL FFV6_1(W(1,8),W(1,9),GC_1,MDL_MB,ZERO,W(1,10))
C     Amplitude(s) for diagram number 101
      CALL FFV2_0(W(1,3),W(1,10),W(1,13),GC_649,AMP(117))
C     Amplitude(s) for diagram number 102
      CALL FFV4_0(W(1,3),W(1,10),W(1,13),GC_923,AMP(118))
C     Amplitude(s) for diagram number 103
      CALL FFV10_3_0(W(1,3),W(1,10),W(1,13),GC_767,GC_742,AMP(119))
C     Amplitude(s) for diagram number 104
      CALL FFV2_0(W(1,3),W(1,10),W(1,13),GC_740,AMP(120))
      CALL FFV11_9_1(W(1,8),W(1,9),GC_736,GC_737,MDL_MB,ZERO,W(1,10))
C     Amplitude(s) for diagram number 105
      CALL FFV2_0(W(1,3),W(1,10),W(1,13),GC_649,AMP(121))
C     Amplitude(s) for diagram number 106
      CALL FFVV1_3_0(W(1,3),W(1,8),W(1,13),W(1,16),GC_838,GC_848
     $ ,AMP(122))
C     Amplitude(s) for diagram number 107
      CALL FFV2_8_0(W(1,3),W(1,11),W(1,16),GC_651,GC_660,AMP(123))
C     Amplitude(s) for diagram number 108
      CALL FFV11_9_0(W(1,3),W(1,11),W(1,16),GC_721,GC_722,AMP(124))
C     Amplitude(s) for diagram number 109
      CALL FFV4_0(W(1,3),W(1,11),W(1,16),GC_948,AMP(125))
C     Amplitude(s) for diagram number 110
      CALL FFV2_0(W(1,3),W(1,11),W(1,16),GC_938,AMP(126))
C     Amplitude(s) for diagram number 111
      CALL FFV2_8_0(W(1,3),W(1,22),W(1,16),GC_651,GC_660,AMP(127))
C     Amplitude(s) for diagram number 112
      CALL FFV2_8_0(W(1,3),W(1,18),W(1,16),GC_651,GC_660,AMP(128))
C     Amplitude(s) for diagram number 113
      CALL FFV2_8_0(W(1,3),W(1,17),W(1,16),GC_651,GC_660,AMP(129))
C     Amplitude(s) for diagram number 114
      CALL VVV1_0(W(1,27),W(1,13),W(1,16),GC_653,AMP(130))
C     Amplitude(s) for diagram number 115
      CALL VVV1_0(W(1,26),W(1,13),W(1,16),GC_653,AMP(131))
C     Amplitude(s) for diagram number 116
      CALL VVV1_0(W(1,25),W(1,13),W(1,16),GC_653,AMP(132))
C     Amplitude(s) for diagram number 117
      CALL VVV1_0(W(1,21),W(1,13),W(1,16),GC_653,AMP(133))
      CALL FFV2_5_1(W(1,8),W(1,16),GC_650,GC_660,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 118
      CALL FFV2_0(W(1,3),W(1,17),W(1,13),GC_649,AMP(134))
C     Amplitude(s) for diagram number 119
      CALL FFV4_0(W(1,3),W(1,17),W(1,13),GC_923,AMP(135))
C     Amplitude(s) for diagram number 120
      CALL FFV10_3_0(W(1,3),W(1,17),W(1,13),GC_767,GC_742,AMP(136))
C     Amplitude(s) for diagram number 121
      CALL FFV2_0(W(1,3),W(1,17),W(1,13),GC_740,AMP(137))
      CALL FFV11_9_1(W(1,8),W(1,16),GC_723,GC_724,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 122
      CALL FFV2_0(W(1,3),W(1,17),W(1,13),GC_649,AMP(138))
      CALL FFV4_1(W(1,8),W(1,16),GC_933,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 123
      CALL FFV2_0(W(1,3),W(1,17),W(1,13),GC_649,AMP(139))
      CALL FFV2_1(W(1,8),W(1,16),GC_939,MDL_MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 124
      CALL FFV2_0(W(1,3),W(1,17),W(1,13),GC_649,AMP(140))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,6),W(1,7),W(1,3)
     $ ,GC_348,GC_563,GC_586,GC_583,GC_354,GC_350,GC_569,GC_352,GC_349
     $ ,GC_351,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 125
      CALL FFV2_0(W(1,17),W(1,8),W(1,13),GC_649,AMP(141))
C     Amplitude(s) for diagram number 126
      CALL FFV2_0(W(1,19),W(1,5),W(1,27),GC_649,AMP(142))
C     Amplitude(s) for diagram number 127
      CALL FFV2_0(W(1,19),W(1,5),W(1,26),GC_649,AMP(143))
C     Amplitude(s) for diagram number 128
      CALL FFV2_0(W(1,19),W(1,5),W(1,25),GC_649,AMP(144))
C     Amplitude(s) for diagram number 129
      CALL FFV2_0(W(1,19),W(1,5),W(1,21),GC_649,AMP(145))
C     Amplitude(s) for diagram number 130
      CALL FFV2_0(W(1,2),W(1,23),W(1,27),GC_649,AMP(146))
C     Amplitude(s) for diagram number 131
      CALL FFV2_0(W(1,2),W(1,23),W(1,26),GC_649,AMP(147))
C     Amplitude(s) for diagram number 132
      CALL FFV2_0(W(1,2),W(1,23),W(1,25),GC_649,AMP(148))
C     Amplitude(s) for diagram number 133
      CALL FFV2_0(W(1,2),W(1,23),W(1,21),GC_649,AMP(149))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,8),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,23))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,8),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 134
      CALL FFV1_0(W(1,23),W(1,5),W(1,9),GC_2,AMP(150))
      CALL FFV1_0(W(1,19),W(1,5),W(1,9),GC_2,AMP(151))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,8),W(1,2),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,7))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,8),W(1,2),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 135
      CALL FFV6_0(W(1,3),W(1,7),W(1,9),GC_2,AMP(152))
      CALL FFV6_0(W(1,3),W(1,6),W(1,9),GC_2,AMP(153))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,8),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,18))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,8),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,22))
C     Amplitude(s) for diagram number 136
      CALL FFV1_0(W(1,2),W(1,18),W(1,9),GC_1,AMP(154))
      CALL FFV1_0(W(1,2),W(1,22),W(1,9),GC_1,AMP(155))
C     Amplitude(s) for diagram number 137
      CALL FFV2_0(W(1,29),W(1,5),W(1,27),GC_649,AMP(156))
C     Amplitude(s) for diagram number 138
      CALL FFV2_0(W(1,29),W(1,5),W(1,26),GC_649,AMP(157))
C     Amplitude(s) for diagram number 139
      CALL FFV2_0(W(1,29),W(1,5),W(1,25),GC_649,AMP(158))
C     Amplitude(s) for diagram number 140
      CALL FFV2_0(W(1,29),W(1,5),W(1,21),GC_649,AMP(159))
C     Amplitude(s) for diagram number 141
      CALL FFV2_0(W(1,2),W(1,30),W(1,27),GC_649,AMP(160))
C     Amplitude(s) for diagram number 142
      CALL FFV2_0(W(1,2),W(1,30),W(1,26),GC_649,AMP(161))
C     Amplitude(s) for diagram number 143
      CALL FFV2_0(W(1,2),W(1,30),W(1,25),GC_649,AMP(162))
C     Amplitude(s) for diagram number 144
      CALL FFV2_0(W(1,2),W(1,30),W(1,21),GC_649,AMP(163))
C     Amplitude(s) for diagram number 145
      CALL FFV2_8_0(W(1,23),W(1,5),W(1,16),GC_651,GC_660,AMP(164))
      CALL FFV2_8_0(W(1,19),W(1,5),W(1,16),GC_651,GC_660,AMP(165))
C     Amplitude(s) for diagram number 146
      CALL FFV2_8_0(W(1,3),W(1,7),W(1,16),GC_651,GC_660,AMP(166))
      CALL FFV2_8_0(W(1,3),W(1,6),W(1,16),GC_651,GC_660,AMP(167))
C     Amplitude(s) for diagram number 147
      CALL FFV2_5_0(W(1,2),W(1,18),W(1,16),GC_650,GC_660,AMP(168))
      CALL FFV2_5_0(W(1,2),W(1,22),W(1,16),GC_650,GC_660,AMP(169))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,2),W(1,5),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,22))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,2),W(1,5),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 148
      CALL FFV6_0(W(1,22),W(1,8),W(1,9),GC_1,AMP(170))
      CALL FFV6_0(W(1,18),W(1,8),W(1,9),GC_1,AMP(171))
C     Amplitude(s) for diagram number 149
      CALL FFV2_5_0(W(1,22),W(1,8),W(1,16),GC_650,GC_660,AMP(172))
      CALL FFV2_5_0(W(1,18),W(1,8),W(1,16),GC_650,GC_660,AMP(173))
      CALL FFV1_1(W(1,5),W(1,1),GC_7,ZERO,ZERO,W(1,8))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,2),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MB,ZERO,W(1,6))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_2(W(1,3),W(1,2),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MB,ZERO,W(1,7))
C     Amplitude(s) for diagram number 150
      CALL FFV6_0(W(1,6),W(1,4),W(1,9),GC_1,AMP(174))
      CALL FFV6_0(W(1,7),W(1,4),W(1,9),GC_1,AMP(175))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,2),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,MDL_MT,MDL_WT,W(1,19))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_1(W(1,4),W(1,2),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 151
      CALL FFV6_0(W(1,3),W(1,19),W(1,9),GC_2,AMP(176))
      CALL FFV6_0(W(1,3),W(1,23),W(1,9),GC_2,AMP(177))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,4),W(1,8),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,21))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_3(W(1,3),W(1,4),W(1,8),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,30))
C     Amplitude(s) for diagram number 152
      CALL FFV1_0(W(1,2),W(1,21),W(1,9),GC_1,AMP(178))
      CALL FFV1_0(W(1,2),W(1,30),W(1,9),GC_1,AMP(179))
C     Amplitude(s) for diagram number 153
      CALL FFV2_5_0(W(1,6),W(1,4),W(1,16),GC_650,GC_660,AMP(180))
      CALL FFV2_5_0(W(1,7),W(1,4),W(1,16),GC_650,GC_660,AMP(181))
C     Amplitude(s) for diagram number 154
      CALL FFV2_8_0(W(1,3),W(1,19),W(1,16),GC_651,GC_660,AMP(182))
      CALL FFV2_8_0(W(1,3),W(1,23),W(1,16),GC_651,GC_660,AMP(183))
C     Amplitude(s) for diagram number 155
      CALL FFV2_5_0(W(1,2),W(1,21),W(1,16),GC_650,GC_660,AMP(184))
      CALL FFV2_5_0(W(1,2),W(1,30),W(1,16),GC_650,GC_660,AMP(185))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,2),GC_40
     $ ,GC_200,GC_44,GC_65,GC_202,GC_570,GC_63,GC_472,GC_60,GC_203
     $ ,ZERO,ZERO,W(1,30))
      CALL FFFF10_11_19_2_20_6_7_8_21_110_4(W(1,3),W(1,4),W(1,2),GC_42
     $ ,GC_208,GC_46,GC_73,GC_210,GC_572,GC_71,GC_474,GC_68,GC_211
     $ ,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 156
      CALL FFV1_0(W(1,30),W(1,8),W(1,9),GC_2,AMP(186))
      CALL FFV1_0(W(1,21),W(1,8),W(1,9),GC_2,AMP(187))
C     Amplitude(s) for diagram number 157
      CALL FFV2_8_0(W(1,30),W(1,8),W(1,16),GC_651,GC_660,AMP(188))
      CALL FFV2_8_0(W(1,21),W(1,8),W(1,16),GC_651,GC_660,AMP(189))
      CALL FFV2_2(W(1,3),W(1,13),GC_649,MDL_MB,ZERO,W(1,8))
      CALL FFV6_1(W(1,4),W(1,9),GC_1,MDL_MB,ZERO,W(1,23))
C     Amplitude(s) for diagram number 158
      CALL FFV1_0(W(1,8),W(1,23),W(1,1),GC_7,AMP(190))
      CALL FFV11_9_1(W(1,4),W(1,9),GC_736,GC_737,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 159
      CALL FFV1_0(W(1,8),W(1,19),W(1,1),GC_7,AMP(191))
      CALL FFV4_2(W(1,3),W(1,13),GC_923,MDL_MB,ZERO,W(1,19))
C     Amplitude(s) for diagram number 160
      CALL FFV1_0(W(1,19),W(1,23),W(1,1),GC_7,AMP(192))
      CALL FFV10_3_2(W(1,3),W(1,13),GC_767,GC_742,MDL_MB,ZERO,W(1,7))
C     Amplitude(s) for diagram number 161
      CALL FFV1_0(W(1,7),W(1,23),W(1,1),GC_7,AMP(193))
      CALL FFV2_2(W(1,3),W(1,13),GC_740,MDL_MB,ZERO,W(1,6))
C     Amplitude(s) for diagram number 162
      CALL FFV1_0(W(1,6),W(1,23),W(1,1),GC_7,AMP(194))
      CALL FFV2_1(W(1,4),W(1,13),GC_649,MDL_MT,MDL_WT,W(1,23))
      CALL FFV6_2(W(1,3),W(1,9),GC_2,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 163
      CALL FFV6_0(W(1,25),W(1,23),W(1,1),GC_7,AMP(195))
C     Amplitude(s) for diagram number 164
      CALL FFV11_9_0(W(1,25),W(1,23),W(1,1),GC_725,GC_726,AMP(196))
      CALL FFV11_9_2(W(1,3),W(1,9),GC_813,GC_814,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 165
      CALL FFV6_0(W(1,26),W(1,23),W(1,1),GC_7,AMP(197))
      CALL FFV4_1(W(1,4),W(1,13),GC_923,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 166
      CALL FFV6_0(W(1,25),W(1,26),W(1,1),GC_7,AMP(198))
      CALL FFV10_3_1(W(1,4),W(1,13),GC_767,GC_742,MDL_MT,MDL_WT,W(1,27)
     $ )
C     Amplitude(s) for diagram number 167
      CALL FFV6_0(W(1,25),W(1,27),W(1,1),GC_7,AMP(199))
      CALL FFV2_1(W(1,4),W(1,13),GC_740,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 168
      CALL FFV6_0(W(1,25),W(1,29),W(1,1),GC_7,AMP(200))
      CALL FFV2_5_1(W(1,4),W(1,16),GC_650,GC_660,MDL_MB,ZERO,W(1,25))
C     Amplitude(s) for diagram number 169
      CALL FFV1_0(W(1,8),W(1,25),W(1,1),GC_7,AMP(201))
      CALL FFV11_9_1(W(1,4),W(1,16),GC_723,GC_724,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 170
      CALL FFV1_0(W(1,8),W(1,11),W(1,1),GC_7,AMP(202))
      CALL FFV4_1(W(1,4),W(1,16),GC_933,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 171
      CALL FFV1_0(W(1,8),W(1,11),W(1,1),GC_7,AMP(203))
      CALL FFV2_1(W(1,4),W(1,16),GC_939,MDL_MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 172
      CALL FFV1_0(W(1,8),W(1,11),W(1,1),GC_7,AMP(204))
C     Amplitude(s) for diagram number 173
      CALL FFV1_0(W(1,19),W(1,25),W(1,1),GC_7,AMP(205))
C     Amplitude(s) for diagram number 174
      CALL FFV1_0(W(1,7),W(1,25),W(1,1),GC_7,AMP(206))
C     Amplitude(s) for diagram number 175
      CALL FFV1_0(W(1,6),W(1,25),W(1,1),GC_7,AMP(207))
      CALL FFV2_8_2(W(1,3),W(1,16),GC_651,GC_660,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 176
      CALL FFV6_0(W(1,25),W(1,23),W(1,1),GC_7,AMP(208))
C     Amplitude(s) for diagram number 177
      CALL FFV11_9_0(W(1,25),W(1,23),W(1,1),GC_725,GC_726,AMP(209))
      CALL FFV11_9_2(W(1,3),W(1,16),GC_721,GC_722,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 178
      CALL FFV6_0(W(1,6),W(1,23),W(1,1),GC_7,AMP(210))
      CALL FFV4_2(W(1,3),W(1,16),GC_948,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 179
      CALL FFV6_0(W(1,6),W(1,23),W(1,1),GC_7,AMP(211))
      CALL FFV2_2(W(1,3),W(1,16),GC_938,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 180
      CALL FFV6_0(W(1,6),W(1,23),W(1,1),GC_7,AMP(212))
C     Amplitude(s) for diagram number 181
      CALL FFV6_0(W(1,25),W(1,26),W(1,1),GC_7,AMP(213))
C     Amplitude(s) for diagram number 182
      CALL FFV6_0(W(1,25),W(1,27),W(1,1),GC_7,AMP(214))
C     Amplitude(s) for diagram number 183
      CALL FFV6_0(W(1,25),W(1,29),W(1,1),GC_7,AMP(215))
      CALL FFV6_2(W(1,17),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 184
      CALL FFV2_0(W(1,25),W(1,4),W(1,13),GC_649,AMP(216))
      CALL FFV1_1(W(1,24),W(1,1),GC_7,MDL_MB,ZERO,W(1,25))
C     Amplitude(s) for diagram number 185
      CALL FFV2_0(W(1,3),W(1,25),W(1,13),GC_649,AMP(217))
      CALL FFV1_2(W(1,30),W(1,1),GC_7,ZERO,ZERO,W(1,25))
      CALL FFV1_2(W(1,21),W(1,1),GC_7,ZERO,ZERO,W(1,30))
C     Amplitude(s) for diagram number 186
      CALL FFV1_0(W(1,25),W(1,5),W(1,9),GC_2,AMP(218))
      CALL FFV1_0(W(1,30),W(1,5),W(1,9),GC_2,AMP(219))
C     Amplitude(s) for diagram number 187
      CALL FFV2_8_0(W(1,25),W(1,5),W(1,16),GC_651,GC_660,AMP(220))
      CALL FFV2_8_0(W(1,30),W(1,5),W(1,16),GC_651,GC_660,AMP(221))
      CALL FFV1_2(W(1,22),W(1,1),GC_7,MDL_MB,ZERO,W(1,30))
      CALL FFV1_2(W(1,18),W(1,1),GC_7,MDL_MB,ZERO,W(1,22))
C     Amplitude(s) for diagram number 188
      CALL FFV6_0(W(1,30),W(1,4),W(1,9),GC_1,AMP(222))
      CALL FFV6_0(W(1,22),W(1,4),W(1,9),GC_1,AMP(223))
C     Amplitude(s) for diagram number 189
      CALL FFV2_5_0(W(1,30),W(1,4),W(1,16),GC_650,GC_660,AMP(224))
      CALL FFV2_5_0(W(1,22),W(1,4),W(1,16),GC_650,GC_660,AMP(225))
      CALL FFV6_1(W(1,20),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,22))
      CALL FFV6_1(W(1,28),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 190
      CALL FFV6_0(W(1,3),W(1,22),W(1,9),GC_2,AMP(226))
      CALL FFV6_0(W(1,3),W(1,20),W(1,9),GC_2,AMP(227))
C     Amplitude(s) for diagram number 191
      CALL FFV2_8_0(W(1,3),W(1,22),W(1,16),GC_651,GC_660,AMP(228))
      CALL FFV2_8_0(W(1,3),W(1,20),W(1,16),GC_651,GC_660,AMP(229))
      CALL FFV1_1(W(1,15),W(1,1),GC_7,ZERO,ZERO,W(1,20))
      CALL FFV1_1(W(1,14),W(1,1),GC_7,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 192
      CALL FFV1_0(W(1,2),W(1,20),W(1,9),GC_1,AMP(230))
      CALL FFV1_0(W(1,2),W(1,15),W(1,9),GC_1,AMP(231))
C     Amplitude(s) for diagram number 193
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,16),GC_650,GC_660,AMP(232))
      CALL FFV2_5_0(W(1,2),W(1,15),W(1,16),GC_650,GC_660,AMP(233))
      JAMP(1)=+1D0/2D0*(+AMP(2)+AMP(4)+AMP(6)+AMP(8)+AMP(10)+AMP(12)
     $ +AMP(14)+AMP(16)+AMP(151)+AMP(153)+AMP(155)+AMP(165)+AMP(167)
     $ +AMP(169)+AMP(171)+AMP(173)+AMP(223)+AMP(225)+AMP(231)+AMP(233))
      JAMP(2)=+AMP(17)+AMP(18)+AMP(19)+AMP(20)+AMP(21)+AMP(22)+AMP(23)
     $ +AMP(24)+AMP(25)+AMP(26)+AMP(27)+AMP(28)+AMP(29)+AMP(30)+AMP(31)
     $ +AMP(32)+AMP(33)+AMP(34)+AMP(35)+AMP(36)+AMP(37)+AMP(38)+AMP(39)
     $ +AMP(40)+AMP(41)+AMP(42)+AMP(43)+AMP(44)+AMP(45)+AMP(46)+AMP(47)
     $ +AMP(48)+AMP(49)+AMP(50)+AMP(51)+AMP(52)+AMP(53)+AMP(54)+AMP(55)
     $ +AMP(56)+AMP(57)+AMP(58)+AMP(59)+AMP(60)+AMP(61)+AMP(62)+AMP(63)
     $ +AMP(64)+AMP(65)+AMP(66)+AMP(67)+AMP(68)+AMP(69)+AMP(70)+AMP(71)
     $ +AMP(72)+AMP(73)-1D0/6D0*AMP(74)+AMP(75)-1D0/6D0*AMP(76)+AMP(77)
     $ -1D0/6D0*AMP(78)+AMP(79)+AMP(80)+AMP(81)+AMP(82)+AMP(83)+AMP(84)
     $ +AMP(85)+AMP(86)+AMP(87)-1D0/6D0*AMP(88)+AMP(89)-1D0/6D0*AMP(90)
     $ +AMP(91)-1D0/6D0*AMP(92)+AMP(93)+AMP(94)+AMP(95)+AMP(96)+AMP(97)
     $ -1D0/6D0*AMP(98)+AMP(99)-1D0/6D0*AMP(100)+AMP(101)+AMP(102)
     $ +AMP(103)+AMP(104)+AMP(105)+AMP(106)+AMP(107)+AMP(108)+AMP(109)
     $ +AMP(110)+AMP(111)+AMP(112)+AMP(113)+AMP(114)+AMP(115)+AMP(116)
     $ +AMP(117)+AMP(118)+AMP(119)+AMP(120)+AMP(121)+AMP(122)+AMP(123)
     $ +AMP(124)+AMP(125)+AMP(126)+AMP(127)+AMP(128)+AMP(129)+AMP(130)
     $ +AMP(131)+AMP(132)+AMP(133)+AMP(134)+AMP(135)+AMP(136)+AMP(137)
     $ +AMP(138)+AMP(139)+AMP(140)+AMP(141)+AMP(142)+AMP(143)+AMP(144)
     $ +AMP(145)+AMP(146)+AMP(147)+AMP(148)+AMP(149)+AMP(150)-1D0/6D0
     $ *AMP(151)+AMP(152)-1D0/6D0*AMP(153)+AMP(154)-1D0/6D0*AMP(155)
     $ +AMP(156)+AMP(157)+AMP(158)+AMP(159)+AMP(160)+AMP(161)+AMP(162)
     $ +AMP(163)+AMP(164)-1D0/6D0*AMP(165)+AMP(166)-1D0/6D0*AMP(167)
     $ +AMP(168)-1D0/6D0*AMP(169)+AMP(170)-1D0/6D0*AMP(171)+AMP(172)
     $ -1D0/6D0*AMP(173)+AMP(190)+AMP(191)+AMP(192)+AMP(193)+AMP(194)
     $ +AMP(195)+AMP(196)+AMP(197)+AMP(198)+AMP(199)+AMP(200)+AMP(201)
     $ +AMP(202)+AMP(203)+AMP(204)+AMP(205)+AMP(206)+AMP(207)+AMP(208)
     $ +AMP(209)+AMP(210)+AMP(211)+AMP(212)+AMP(213)+AMP(214)+AMP(215)
     $ +AMP(216)+AMP(217)+AMP(222)-1D0/6D0*AMP(223)+AMP(224)-1D0/6D0
     $ *AMP(225)+AMP(226)-1D0/6D0*AMP(227)+AMP(228)-1D0/6D0*AMP(229)
      JAMP(3)=+AMP(1)-1D0/6D0*AMP(2)+AMP(3)-1D0/6D0*AMP(4)+AMP(5)-1D0
     $ /6D0*AMP(6)+AMP(7)-1D0/6D0*AMP(8)+AMP(9)-1D0/6D0*AMP(10)+AMP(11)
     $ -1D0/6D0*AMP(12)+AMP(13)-1D0/6D0*AMP(14)+AMP(15)-1D0/6D0*AMP(16)
     $ +AMP(174)-1D0/6D0*AMP(175)+AMP(176)-1D0/6D0*AMP(177)+AMP(178)
     $ -1D0/6D0*AMP(179)+AMP(180)-1D0/6D0*AMP(181)+AMP(182)-1D0/6D0
     $ *AMP(183)+AMP(184)-1D0/6D0*AMP(185)+AMP(186)-1D0/6D0*AMP(187)
     $ +AMP(188)-1D0/6D0*AMP(189)+AMP(218)-1D0/6D0*AMP(219)+AMP(220)
     $ -1D0/6D0*AMP(221)+AMP(230)-1D0/6D0*AMP(231)+AMP(232)-1D0/6D0
     $ *AMP(233)
      JAMP(4)=+1D0/2D0*(+AMP(74)+AMP(76)+AMP(78)+AMP(88)+AMP(90)
     $ +AMP(92)+AMP(98)+AMP(100)+AMP(175)+AMP(177)+AMP(179)+AMP(181)
     $ +AMP(183)+AMP(185)+AMP(187)+AMP(189)+AMP(219)+AMP(221)+AMP(227)
     $ +AMP(229))

      M10_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M10_MATRIX = M10_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M10_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M10_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M10_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M10_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M10_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NCOMB
      PARAMETER (NCOMB=128)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M10_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M10_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M10_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M10_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

