      SUBROUTINE M55_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M55_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M55_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M55_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g d > t t~ vm vm~ d DIM6<=1 FCNC=0 / h @3
C     Process: g s > t t~ vm vm~ s DIM6<=1 FCNC=0 / h @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M55_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M55_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M55_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,   2),I=1,7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,   3),I=1,7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,   4),I=1,7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,   5),I=1,7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,   6),I=1,7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,   7),I=1,7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,   8),I=1,7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,   9),I=1,7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,7) /-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  18),I=1,7) /-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  19),I=1,7) /-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  20),I=1,7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  21),I=1,7) /-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  22),I=1,7) /-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  23),I=1,7) /-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  24),I=1,7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  25),I=1,7) /-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  26),I=1,7) /-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  27),I=1,7) /-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  28),I=1,7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  29),I=1,7) /-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  30),I=1,7) /-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  31),I=1,7) /-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  32),I=1,7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  33),I=1,7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  42),I=1,7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  43),I=1,7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  44),I=1,7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  45),I=1,7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  46),I=1,7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  47),I=1,7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  48),I=1,7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  49),I=1,7) /-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  50),I=1,7) /-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  51),I=1,7) /-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  52),I=1,7) /-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  53),I=1,7) /-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  54),I=1,7) /-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  55),I=1,7) /-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  56),I=1,7) /-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  57),I=1,7) /-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  58),I=1,7) /-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  59),I=1,7) /-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  60),I=1,7) /-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  61),I=1,7) /-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  62),I=1,7) /-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  63),I=1,7) /-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  64),I=1,7) /-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  65),I=1,7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  66),I=1,7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  67),I=1,7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  68),I=1,7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  69),I=1,7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  70),I=1,7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  71),I=1,7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  72),I=1,7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  73),I=1,7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  74),I=1,7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  75),I=1,7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  76),I=1,7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  77),I=1,7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  78),I=1,7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  79),I=1,7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  80),I=1,7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  81),I=1,7) / 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  82),I=1,7) / 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  83),I=1,7) / 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  84),I=1,7) / 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  85),I=1,7) / 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  86),I=1,7) / 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  87),I=1,7) / 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  88),I=1,7) / 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  89),I=1,7) / 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  90),I=1,7) / 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  91),I=1,7) / 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  92),I=1,7) / 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  93),I=1,7) / 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  94),I=1,7) / 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  95),I=1,7) / 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  96),I=1,7) / 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  97),I=1,7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  98),I=1,7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  99),I=1,7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 100),I=1,7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 101),I=1,7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 102),I=1,7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 103),I=1,7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 104),I=1,7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 105),I=1,7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 106),I=1,7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 107),I=1,7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 108),I=1,7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 109),I=1,7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 110),I=1,7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 111),I=1,7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 112),I=1,7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 113),I=1,7) / 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 114),I=1,7) / 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 115),I=1,7) / 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 116),I=1,7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 117),I=1,7) / 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 118),I=1,7) / 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 119),I=1,7) / 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 120),I=1,7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 121),I=1,7) / 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 122),I=1,7) / 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 123),I=1,7) / 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 124),I=1,7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 125),I=1,7) / 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 126),I=1,7) / 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 127),I=1,7) / 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 128),I=1,7) / 1,-1, 1,-1, 1,-1, 1/
      DATA IDEN/96/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M55_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M55_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M55_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M55_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M55_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M55_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g d > t t~ vm vm~ d DIM6<=1 FCNC=0 / h @3
C     Process: g s > t t~ vm vm~ s DIM6<=1 FCNC=0 / h @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=414)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=57, NCOLOR=4)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,  1),I=  1,  4) /   12,    4,    4,    0/
C     1 T(1,3,2) T(7,4)
      DATA DENOM(2)/1/
      DATA (CF(I,  2),I=  1,  4) /    4,   12,    0,    4/
C     1 T(1,3,4) T(7,2)
      DATA DENOM(3)/1/
      DATA (CF(I,  3),I=  1,  4) /    4,    0,   12,    4/
C     1 T(1,7,2) T(3,4)
      DATA DENOM(4)/1/
      DATA (CF(I,  4),I=  1,  4) /    0,    4,    4,   12/
C     1 T(1,7,4) T(3,2)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL OXXXXX(P(0,7),ZERO,NHEL(7),+1*IC(7),W(1,7))
      CALL FFV1_2(W(1,2),W(1,1),GC_7,ZERO,ZERO,W(1,8))
      CALL FFV2_8_3(W(1,4),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,9))
      CALL FFV2_5_3(W(1,8),W(1,7),GC_650,GC_660,MDL_MZ,MDL_WZ,W(1,10))
      CALL FFV2_1(W(1,5),W(1,9),GC_664,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 1
      CALL FFV2_0(W(1,6),W(1,11),W(1,10),GC_664,AMP(1))
      CALL FFV2_2(W(1,6),W(1,9),GC_664,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 2
      CALL FFV2_0(W(1,12),W(1,5),W(1,10),GC_664,AMP(2))
      CALL FFV11_9_3(W(1,4),W(1,3),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,13))
      CALL FFV2_1(W(1,5),W(1,13),GC_664,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 3
      CALL FFV2_0(W(1,6),W(1,14),W(1,10),GC_664,AMP(3))
      CALL FFV2_2(W(1,6),W(1,13),GC_664,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 4
      CALL FFV2_0(W(1,15),W(1,5),W(1,10),GC_664,AMP(4))
      CALL FFV4_3(W(1,4),W(1,3),GC_948,MDL_MZ,MDL_WZ,W(1,16))
      CALL FFV2_1(W(1,5),W(1,16),GC_664,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 5
      CALL FFV2_0(W(1,6),W(1,17),W(1,10),GC_664,AMP(5))
      CALL FFV2_2(W(1,6),W(1,16),GC_664,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 6
      CALL FFV2_0(W(1,18),W(1,5),W(1,10),GC_664,AMP(6))
      CALL FFV2_3(W(1,4),W(1,3),GC_938,MDL_MZ,MDL_WZ,W(1,19))
      CALL FFV2_1(W(1,5),W(1,19),GC_664,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 7
      CALL FFV2_0(W(1,6),W(1,20),W(1,10),GC_664,AMP(7))
      CALL FFV2_2(W(1,6),W(1,19),GC_664,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 8
      CALL FFV2_0(W(1,21),W(1,5),W(1,10),GC_664,AMP(8))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_2,ZERO,ZERO,W(1,22))
      CALL FFV2_3(W(1,6),W(1,5),GC_664,MDL_MZ,MDL_WZ,W(1,23))
      CALL FFV1_2(W(1,8),W(1,22),GC_1,ZERO,ZERO,W(1,24))
C     Amplitude(s) for diagram number 9
      CALL FFV2_5_0(W(1,24),W(1,7),W(1,23),GC_650,GC_660,AMP(9))
      CALL FFV2_5_2(W(1,8),W(1,23),GC_650,GC_660,ZERO,ZERO,W(1,24))
C     Amplitude(s) for diagram number 10
      CALL FFV1_0(W(1,24),W(1,7),W(1,22),GC_1,AMP(10))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_813,GC_814,ZERO,ZERO,W(1,25))
      CALL FFV1_2(W(1,8),W(1,25),GC_1,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 11
      CALL FFV2_5_0(W(1,26),W(1,7),W(1,23),GC_650,GC_660,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFV1_0(W(1,24),W(1,7),W(1,25),GC_1,AMP(12))
      CALL FFV2_5_2(W(1,8),W(1,9),GC_650,GC_660,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 13
      CALL FFV2_5_0(W(1,26),W(1,7),W(1,23),GC_650,GC_660,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL FFV2_5_0(W(1,24),W(1,7),W(1,9),GC_650,GC_660,AMP(14))
      CALL FFV2_5_2(W(1,8),W(1,13),GC_650,GC_660,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 15
      CALL FFV2_5_0(W(1,26),W(1,7),W(1,23),GC_650,GC_660,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFV2_5_0(W(1,24),W(1,7),W(1,13),GC_650,GC_660,AMP(16))
      CALL FFV2_5_2(W(1,8),W(1,16),GC_650,GC_660,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 17
      CALL FFV2_5_0(W(1,26),W(1,7),W(1,23),GC_650,GC_660,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV2_5_0(W(1,24),W(1,7),W(1,16),GC_650,GC_660,AMP(18))
      CALL FFV2_5_2(W(1,8),W(1,19),GC_650,GC_660,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 19
      CALL FFV2_5_0(W(1,26),W(1,7),W(1,23),GC_650,GC_660,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV2_5_0(W(1,24),W(1,7),W(1,19),GC_650,GC_660,AMP(20))
      CALL FFV6P0_3(W(1,4),W(1,3),GC_7,ZERO,ZERO,W(1,26))
      CALL FFV1_2(W(1,8),W(1,26),GC_7,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 21
      CALL FFV2_5_0(W(1,27),W(1,7),W(1,23),GC_650,GC_660,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV1_0(W(1,24),W(1,7),W(1,26),GC_7,AMP(22))
      CALL FFV11_9P0_3(W(1,4),W(1,3),GC_725,GC_726,ZERO,ZERO,W(1,27))
      CALL FFV1_2(W(1,8),W(1,27),GC_7,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 23
      CALL FFV2_5_0(W(1,28),W(1,7),W(1,23),GC_650,GC_660,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV1_0(W(1,24),W(1,7),W(1,27),GC_7,AMP(24))
      CALL FFV1P0_3(W(1,8),W(1,7),GC_1,ZERO,ZERO,W(1,24))
      CALL FFV2_8_1(W(1,3),W(1,23),GC_651,GC_660,MDL_MT,MDL_WT,W(1,28))
C     Amplitude(s) for diagram number 25
      CALL FFV6_0(W(1,4),W(1,28),W(1,24),GC_2,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,24),GC_813,GC_814,AMP(26))
      CALL FFV11_9_1(W(1,3),W(1,23),GC_721,GC_722,MDL_MT,MDL_WT,W(1,29)
     $ )
C     Amplitude(s) for diagram number 27
      CALL FFV6_0(W(1,4),W(1,29),W(1,24),GC_2,AMP(27))
      CALL FFV4_1(W(1,3),W(1,23),GC_948,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 28
      CALL FFV6_0(W(1,4),W(1,30),W(1,24),GC_2,AMP(28))
      CALL FFV2_1(W(1,3),W(1,23),GC_938,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 29
      CALL FFV6_0(W(1,4),W(1,31),W(1,24),GC_2,AMP(29))
      CALL FFV1P0_3(W(1,8),W(1,7),GC_7,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 30
      CALL FFV6_0(W(1,4),W(1,28),W(1,32),GC_7,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,32),GC_725,GC_726,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFV6_0(W(1,4),W(1,29),W(1,32),GC_7,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV6_0(W(1,4),W(1,30),W(1,32),GC_7,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFV6_0(W(1,4),W(1,31),W(1,32),GC_7,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV2_8_0(W(1,4),W(1,28),W(1,10),GC_651,GC_660,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,10),GC_721,GC_722,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL FFV4_0(W(1,4),W(1,28),W(1,10),GC_948,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFV2_0(W(1,4),W(1,28),W(1,10),GC_938,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV2_8_0(W(1,4),W(1,29),W(1,10),GC_651,GC_660,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV2_8_0(W(1,4),W(1,30),W(1,10),GC_651,GC_660,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV2_8_0(W(1,4),W(1,31),W(1,10),GC_651,GC_660,AMP(41))
      CALL FFV2_8_2(W(1,4),W(1,23),GC_651,GC_660,MDL_MT,MDL_WT,W(1,33))
C     Amplitude(s) for diagram number 42
      CALL FFV6_0(W(1,33),W(1,3),W(1,24),GC_2,AMP(42))
C     Amplitude(s) for diagram number 43
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,24),GC_813,GC_814,AMP(43))
      CALL FFV11_9_2(W(1,4),W(1,23),GC_721,GC_722,MDL_MT,MDL_WT,W(1,34)
     $ )
C     Amplitude(s) for diagram number 44
      CALL FFV6_0(W(1,34),W(1,3),W(1,24),GC_2,AMP(44))
      CALL FFV4_2(W(1,4),W(1,23),GC_948,MDL_MT,MDL_WT,W(1,35))
C     Amplitude(s) for diagram number 45
      CALL FFV6_0(W(1,35),W(1,3),W(1,24),GC_2,AMP(45))
      CALL FFV2_2(W(1,4),W(1,23),GC_938,MDL_MT,MDL_WT,W(1,36))
C     Amplitude(s) for diagram number 46
      CALL FFV6_0(W(1,36),W(1,3),W(1,24),GC_2,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV6_0(W(1,33),W(1,3),W(1,32),GC_7,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,32),GC_725,GC_726,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV6_0(W(1,34),W(1,3),W(1,32),GC_7,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV6_0(W(1,35),W(1,3),W(1,32),GC_7,AMP(50))
C     Amplitude(s) for diagram number 51
      CALL FFV6_0(W(1,36),W(1,3),W(1,32),GC_7,AMP(51))
C     Amplitude(s) for diagram number 52
      CALL FFV2_8_0(W(1,33),W(1,3),W(1,10),GC_651,GC_660,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,10),GC_721,GC_722,AMP(53))
C     Amplitude(s) for diagram number 54
      CALL FFV4_0(W(1,33),W(1,3),W(1,10),GC_948,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV2_0(W(1,33),W(1,3),W(1,10),GC_938,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV2_8_0(W(1,34),W(1,3),W(1,10),GC_651,GC_660,AMP(56))
C     Amplitude(s) for diagram number 57
      CALL FFV2_8_0(W(1,35),W(1,3),W(1,10),GC_651,GC_660,AMP(57))
C     Amplitude(s) for diagram number 58
      CALL FFV2_8_0(W(1,36),W(1,3),W(1,10),GC_651,GC_660,AMP(58))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,8),W(1,4),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,37))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,8),W(1,4),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,38))
C     Amplitude(s) for diagram number 59
      CALL FFV2_5_0(W(1,37),W(1,7),W(1,23),GC_650,GC_660,AMP(59))
      CALL FFV2_5_0(W(1,38),W(1,7),W(1,23),GC_650,GC_660,AMP(60))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,8),W(1,7),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,38))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,8),W(1,7),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 60
      CALL FFV2_8_0(W(1,4),W(1,38),W(1,23),GC_651,GC_660,AMP(61))
      CALL FFV2_8_0(W(1,4),W(1,37),W(1,23),GC_651,GC_660,AMP(62))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,8),W(1,7),W(1,4)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,37))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,8),W(1,7),W(1,4)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,38))
C     Amplitude(s) for diagram number 61
      CALL FFV2_8_0(W(1,37),W(1,3),W(1,23),GC_651,GC_660,AMP(63))
      CALL FFV2_8_0(W(1,38),W(1,3),W(1,23),GC_651,GC_660,AMP(64))
      CALL FFFF14_6_3(W(1,4),W(1,3),W(1,5),GC_585,GC_123,ZERO,ZERO,W(1
     $ ,38))
C     Amplitude(s) for diagram number 62
      CALL FFV2_0(W(1,6),W(1,38),W(1,10),GC_664,AMP(65))
      CALL FFFF14_6_4(W(1,4),W(1,3),W(1,6),GC_585,GC_123,ZERO,ZERO,W(1
     $ ,37))
C     Amplitude(s) for diagram number 63
      CALL FFV2_0(W(1,37),W(1,5),W(1,10),GC_664,AMP(66))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,7),W(1,4),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,39))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,7),W(1,4),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,40))
C     Amplitude(s) for diagram number 64
      CALL FFV2_5_0(W(1,8),W(1,39),W(1,23),GC_650,GC_660,AMP(67))
      CALL FFV2_5_0(W(1,8),W(1,40),W(1,23),GC_650,GC_660,AMP(68))
      CALL FFFF14_6_1(W(1,3),W(1,6),W(1,5),GC_585,GC_123,MDL_MT,MDL_WT
     $ ,W(1,8))
C     Amplitude(s) for diagram number 65
      CALL FFV6_0(W(1,4),W(1,8),W(1,24),GC_2,AMP(69))
C     Amplitude(s) for diagram number 66
      CALL FFV6_0(W(1,4),W(1,8),W(1,32),GC_7,AMP(70))
C     Amplitude(s) for diagram number 67
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,10),GC_651,GC_660,AMP(71))
      CALL FFFF14_6_2(W(1,4),W(1,6),W(1,5),GC_585,GC_123,MDL_MT,MDL_WT
     $ ,W(1,41))
C     Amplitude(s) for diagram number 68
      CALL FFV6_0(W(1,41),W(1,3),W(1,24),GC_2,AMP(72))
C     Amplitude(s) for diagram number 69
      CALL FFV6_0(W(1,41),W(1,3),W(1,32),GC_7,AMP(73))
C     Amplitude(s) for diagram number 70
      CALL FFV2_8_0(W(1,41),W(1,3),W(1,10),GC_651,GC_660,AMP(74))
      CALL FFV6_1(W(1,3),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,10))
      CALL FFV1P0_3(W(1,2),W(1,7),GC_1,ZERO,ZERO,W(1,32))
      CALL FFFF14_6_1(W(1,10),W(1,6),W(1,5),GC_585,GC_123,MDL_MT
     $ ,MDL_WT,W(1,24))
C     Amplitude(s) for diagram number 71
      CALL FFV6_0(W(1,4),W(1,24),W(1,32),GC_2,AMP(75))
      CALL FFV1P0_3(W(1,2),W(1,7),GC_7,ZERO,ZERO,W(1,42))
C     Amplitude(s) for diagram number 72
      CALL FFV6_0(W(1,4),W(1,24),W(1,42),GC_7,AMP(76))
      CALL FFV2_5_3(W(1,2),W(1,7),GC_650,GC_660,MDL_MZ,MDL_WZ,W(1,43))
      CALL FFV2_8_3(W(1,4),W(1,10),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,44))
      CALL FFV2_1(W(1,5),W(1,43),GC_664,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 73
      CALL FFV2_0(W(1,6),W(1,45),W(1,44),GC_664,AMP(77))
      CALL FFV11_9_3(W(1,4),W(1,10),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,46)
     $ )
C     Amplitude(s) for diagram number 74
      CALL FFV2_0(W(1,6),W(1,45),W(1,46),GC_664,AMP(78))
      CALL FFV4_3(W(1,4),W(1,10),GC_948,MDL_MZ,MDL_WZ,W(1,47))
C     Amplitude(s) for diagram number 75
      CALL FFV2_0(W(1,6),W(1,45),W(1,47),GC_664,AMP(79))
      CALL FFV2_3(W(1,4),W(1,10),GC_938,MDL_MZ,MDL_WZ,W(1,48))
C     Amplitude(s) for diagram number 76
      CALL FFV2_0(W(1,6),W(1,45),W(1,48),GC_664,AMP(80))
      CALL FFV2_2(W(1,6),W(1,43),GC_664,ZERO,ZERO,W(1,49))
C     Amplitude(s) for diagram number 77
      CALL FFV2_0(W(1,49),W(1,5),W(1,44),GC_664,AMP(81))
C     Amplitude(s) for diagram number 78
      CALL FFV2_0(W(1,49),W(1,5),W(1,46),GC_664,AMP(82))
C     Amplitude(s) for diagram number 79
      CALL FFV2_0(W(1,49),W(1,5),W(1,47),GC_664,AMP(83))
C     Amplitude(s) for diagram number 80
      CALL FFV2_0(W(1,49),W(1,5),W(1,48),GC_664,AMP(84))
      CALL FFFF14_6_3(W(1,4),W(1,10),W(1,5),GC_585,GC_123,ZERO,ZERO
     $ ,W(1,50))
C     Amplitude(s) for diagram number 81
      CALL FFV2_0(W(1,6),W(1,50),W(1,43),GC_664,AMP(85))
      CALL FFFF14_6_4(W(1,4),W(1,10),W(1,6),GC_585,GC_123,ZERO,ZERO
     $ ,W(1,50))
C     Amplitude(s) for diagram number 82
      CALL FFV2_0(W(1,50),W(1,5),W(1,43),GC_664,AMP(86))
C     Amplitude(s) for diagram number 83
      CALL FFV2_8_0(W(1,4),W(1,24),W(1,43),GC_651,GC_660,AMP(87))
      CALL FFV11_9_1(W(1,3),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,24))
      CALL FFV2_8_3(W(1,4),W(1,24),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,50))
C     Amplitude(s) for diagram number 84
      CALL FFV2_0(W(1,6),W(1,45),W(1,50),GC_664,AMP(88))
C     Amplitude(s) for diagram number 85
      CALL FFV2_0(W(1,49),W(1,5),W(1,50),GC_664,AMP(89))
      CALL FFV6_1(W(1,10),W(1,32),GC_2,MDL_MT,MDL_WT,W(1,51))
C     Amplitude(s) for diagram number 86
      CALL FFV2_8_0(W(1,4),W(1,51),W(1,23),GC_651,GC_660,AMP(90))
C     Amplitude(s) for diagram number 87
      CALL FFV11_9_0(W(1,4),W(1,51),W(1,23),GC_721,GC_722,AMP(91))
C     Amplitude(s) for diagram number 88
      CALL FFV4_0(W(1,4),W(1,51),W(1,23),GC_948,AMP(92))
C     Amplitude(s) for diagram number 89
      CALL FFV2_0(W(1,4),W(1,51),W(1,23),GC_938,AMP(93))
      CALL FFV11_9_1(W(1,10),W(1,32),GC_813,GC_814,MDL_MT,MDL_WT,W(1
     $ ,51))
C     Amplitude(s) for diagram number 90
      CALL FFV2_8_0(W(1,4),W(1,51),W(1,23),GC_651,GC_660,AMP(94))
      CALL FFV2_8_1(W(1,10),W(1,23),GC_651,GC_660,MDL_MT,MDL_WT,W(1,51)
     $ )
C     Amplitude(s) for diagram number 91
      CALL FFV6_0(W(1,4),W(1,51),W(1,32),GC_2,AMP(95))
C     Amplitude(s) for diagram number 92
      CALL FFV11_9_0(W(1,4),W(1,51),W(1,32),GC_813,GC_814,AMP(96))
      CALL FFV11_9_1(W(1,10),W(1,23),GC_721,GC_722,MDL_MT,MDL_WT,W(1
     $ ,52))
C     Amplitude(s) for diagram number 93
      CALL FFV6_0(W(1,4),W(1,52),W(1,32),GC_2,AMP(97))
      CALL FFV4_1(W(1,10),W(1,23),GC_948,MDL_MT,MDL_WT,W(1,53))
C     Amplitude(s) for diagram number 94
      CALL FFV6_0(W(1,4),W(1,53),W(1,32),GC_2,AMP(98))
      CALL FFV2_1(W(1,10),W(1,23),GC_938,MDL_MT,MDL_WT,W(1,54))
C     Amplitude(s) for diagram number 95
      CALL FFV6_0(W(1,4),W(1,54),W(1,32),GC_2,AMP(99))
      CALL FFV6_1(W(1,10),W(1,42),GC_7,MDL_MT,MDL_WT,W(1,55))
C     Amplitude(s) for diagram number 96
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(100))
C     Amplitude(s) for diagram number 97
      CALL FFV11_9_0(W(1,4),W(1,55),W(1,23),GC_721,GC_722,AMP(101))
C     Amplitude(s) for diagram number 98
      CALL FFV4_0(W(1,4),W(1,55),W(1,23),GC_948,AMP(102))
C     Amplitude(s) for diagram number 99
      CALL FFV2_0(W(1,4),W(1,55),W(1,23),GC_938,AMP(103))
      CALL FFV11_9_1(W(1,10),W(1,42),GC_725,GC_726,MDL_MT,MDL_WT,W(1
     $ ,55))
C     Amplitude(s) for diagram number 100
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(104))
C     Amplitude(s) for diagram number 101
      CALL FFV6_0(W(1,4),W(1,51),W(1,42),GC_7,AMP(105))
C     Amplitude(s) for diagram number 102
      CALL FFV11_9_0(W(1,4),W(1,51),W(1,42),GC_725,GC_726,AMP(106))
C     Amplitude(s) for diagram number 103
      CALL FFV6_0(W(1,4),W(1,52),W(1,42),GC_7,AMP(107))
C     Amplitude(s) for diagram number 104
      CALL FFV6_0(W(1,4),W(1,53),W(1,42),GC_7,AMP(108))
C     Amplitude(s) for diagram number 105
      CALL FFV6_0(W(1,4),W(1,54),W(1,42),GC_7,AMP(109))
      CALL FFV2_8_1(W(1,10),W(1,43),GC_651,GC_660,MDL_MT,MDL_WT,W(1,55)
     $ )
C     Amplitude(s) for diagram number 106
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(110))
C     Amplitude(s) for diagram number 107
      CALL FFV11_9_0(W(1,4),W(1,55),W(1,23),GC_721,GC_722,AMP(111))
C     Amplitude(s) for diagram number 108
      CALL FFV4_0(W(1,4),W(1,55),W(1,23),GC_948,AMP(112))
C     Amplitude(s) for diagram number 109
      CALL FFV2_0(W(1,4),W(1,55),W(1,23),GC_938,AMP(113))
      CALL FFV11_9_1(W(1,10),W(1,43),GC_721,GC_722,MDL_MT,MDL_WT,W(1
     $ ,55))
C     Amplitude(s) for diagram number 110
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(114))
      CALL FFV4_1(W(1,10),W(1,43),GC_948,MDL_MT,MDL_WT,W(1,55))
C     Amplitude(s) for diagram number 111
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(115))
      CALL FFV2_1(W(1,10),W(1,43),GC_938,MDL_MT,MDL_WT,W(1,55))
C     Amplitude(s) for diagram number 112
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(116))
C     Amplitude(s) for diagram number 113
      CALL FFV2_8_0(W(1,4),W(1,51),W(1,43),GC_651,GC_660,AMP(117))
C     Amplitude(s) for diagram number 114
      CALL FFV11_9_0(W(1,4),W(1,51),W(1,43),GC_721,GC_722,AMP(118))
C     Amplitude(s) for diagram number 115
      CALL FFV4_0(W(1,4),W(1,51),W(1,43),GC_948,AMP(119))
C     Amplitude(s) for diagram number 116
      CALL FFV2_0(W(1,4),W(1,51),W(1,43),GC_938,AMP(120))
C     Amplitude(s) for diagram number 117
      CALL FFV2_8_0(W(1,4),W(1,52),W(1,43),GC_651,GC_660,AMP(121))
C     Amplitude(s) for diagram number 118
      CALL FFV2_8_0(W(1,4),W(1,53),W(1,43),GC_651,GC_660,AMP(122))
C     Amplitude(s) for diagram number 119
      CALL FFV2_8_0(W(1,4),W(1,54),W(1,43),GC_651,GC_660,AMP(123))
      CALL FFV6_1(W(1,24),W(1,32),GC_2,MDL_MT,MDL_WT,W(1,54))
C     Amplitude(s) for diagram number 120
      CALL FFV2_8_0(W(1,4),W(1,54),W(1,23),GC_651,GC_660,AMP(124))
      CALL FFV2_8_1(W(1,24),W(1,23),GC_651,GC_660,MDL_MT,MDL_WT,W(1,54)
     $ )
C     Amplitude(s) for diagram number 121
      CALL FFV6_0(W(1,4),W(1,54),W(1,32),GC_2,AMP(125))
      CALL FFV6_1(W(1,24),W(1,42),GC_7,MDL_MT,MDL_WT,W(1,53))
C     Amplitude(s) for diagram number 122
      CALL FFV2_8_0(W(1,4),W(1,53),W(1,23),GC_651,GC_660,AMP(126))
C     Amplitude(s) for diagram number 123
      CALL FFV6_0(W(1,4),W(1,54),W(1,42),GC_7,AMP(127))
      CALL FFV2_8_1(W(1,24),W(1,43),GC_651,GC_660,MDL_MT,MDL_WT,W(1,53)
     $ )
C     Amplitude(s) for diagram number 124
      CALL FFV2_8_0(W(1,4),W(1,53),W(1,23),GC_651,GC_660,AMP(128))
C     Amplitude(s) for diagram number 125
      CALL FFV2_8_0(W(1,4),W(1,54),W(1,43),GC_651,GC_660,AMP(129))
C     Amplitude(s) for diagram number 126
      CALL FFV6_0(W(1,41),W(1,10),W(1,32),GC_2,AMP(130))
C     Amplitude(s) for diagram number 127
      CALL FFV6_0(W(1,41),W(1,10),W(1,42),GC_7,AMP(131))
C     Amplitude(s) for diagram number 128
      CALL FFV2_8_0(W(1,41),W(1,10),W(1,43),GC_651,GC_660,AMP(132))
      CALL FFV6P0_3(W(1,4),W(1,10),GC_2,ZERO,ZERO,W(1,54))
      CALL FFV2_5_2(W(1,2),W(1,23),GC_650,GC_660,ZERO,ZERO,W(1,53))
C     Amplitude(s) for diagram number 129
      CALL FFV1_0(W(1,53),W(1,7),W(1,54),GC_1,AMP(133))
      CALL FFV11_9P0_3(W(1,4),W(1,10),GC_813,GC_814,ZERO,ZERO,W(1,52))
C     Amplitude(s) for diagram number 130
      CALL FFV1_0(W(1,53),W(1,7),W(1,52),GC_1,AMP(134))
C     Amplitude(s) for diagram number 131
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,44),GC_650,GC_660,AMP(135))
C     Amplitude(s) for diagram number 132
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,46),GC_650,GC_660,AMP(136))
C     Amplitude(s) for diagram number 133
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,47),GC_650,GC_660,AMP(137))
C     Amplitude(s) for diagram number 134
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,48),GC_650,GC_660,AMP(138))
      CALL FFV6P0_3(W(1,4),W(1,10),GC_7,ZERO,ZERO,W(1,51))
C     Amplitude(s) for diagram number 135
      CALL FFV1_0(W(1,53),W(1,7),W(1,51),GC_7,AMP(139))
      CALL FFV11_9P0_3(W(1,4),W(1,10),GC_725,GC_726,ZERO,ZERO,W(1,55))
C     Amplitude(s) for diagram number 136
      CALL FFV1_0(W(1,53),W(1,7),W(1,55),GC_7,AMP(140))
      CALL FFV2_5_1(W(1,7),W(1,23),GC_650,GC_660,ZERO,ZERO,W(1,56))
C     Amplitude(s) for diagram number 137
      CALL FFV1_0(W(1,2),W(1,56),W(1,54),GC_1,AMP(141))
C     Amplitude(s) for diagram number 138
      CALL FFV1_0(W(1,2),W(1,56),W(1,52),GC_1,AMP(142))
C     Amplitude(s) for diagram number 139
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,44),GC_650,GC_660,AMP(143))
C     Amplitude(s) for diagram number 140
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,46),GC_650,GC_660,AMP(144))
C     Amplitude(s) for diagram number 141
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,47),GC_650,GC_660,AMP(145))
C     Amplitude(s) for diagram number 142
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,48),GC_650,GC_660,AMP(146))
C     Amplitude(s) for diagram number 143
      CALL FFV1_0(W(1,2),W(1,56),W(1,51),GC_7,AMP(147))
C     Amplitude(s) for diagram number 144
      CALL FFV1_0(W(1,2),W(1,56),W(1,55),GC_7,AMP(148))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,10)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,55))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,10)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,51))
C     Amplitude(s) for diagram number 145
      CALL FFV2_5_0(W(1,55),W(1,7),W(1,23),GC_650,GC_660,AMP(149))
      CALL FFV2_5_0(W(1,51),W(1,7),W(1,23),GC_650,GC_660,AMP(150))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,2),W(1,7),W(1,10)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,51))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,2),W(1,7),W(1,10)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,55))
C     Amplitude(s) for diagram number 146
      CALL FFV2_8_0(W(1,4),W(1,51),W(1,23),GC_651,GC_660,AMP(151))
      CALL FFV2_8_0(W(1,4),W(1,55),W(1,23),GC_651,GC_660,AMP(152))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,7),W(1,4),W(1,10)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,55))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,7),W(1,4),W(1,10)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,51))
C     Amplitude(s) for diagram number 147
      CALL FFV2_5_0(W(1,2),W(1,55),W(1,23),GC_650,GC_660,AMP(153))
      CALL FFV2_5_0(W(1,2),W(1,51),W(1,23),GC_650,GC_660,AMP(154))
      CALL FFV6P0_3(W(1,4),W(1,24),GC_2,ZERO,ZERO,W(1,51))
C     Amplitude(s) for diagram number 148
      CALL FFV1_0(W(1,53),W(1,7),W(1,51),GC_1,AMP(155))
C     Amplitude(s) for diagram number 149
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,50),GC_650,GC_660,AMP(156))
      CALL FFV6P0_3(W(1,4),W(1,24),GC_7,ZERO,ZERO,W(1,55))
C     Amplitude(s) for diagram number 150
      CALL FFV1_0(W(1,53),W(1,7),W(1,55),GC_7,AMP(157))
C     Amplitude(s) for diagram number 151
      CALL FFV1_0(W(1,2),W(1,56),W(1,51),GC_1,AMP(158))
C     Amplitude(s) for diagram number 152
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,50),GC_650,GC_660,AMP(159))
C     Amplitude(s) for diagram number 153
      CALL FFV1_0(W(1,2),W(1,56),W(1,55),GC_7,AMP(160))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,2),W(1,7),W(1,4)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,55))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,2),W(1,7),W(1,4)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,50))
C     Amplitude(s) for diagram number 154
      CALL FFV2_8_0(W(1,55),W(1,10),W(1,23),GC_651,GC_660,AMP(161))
      CALL FFV2_8_0(W(1,50),W(1,10),W(1,23),GC_651,GC_660,AMP(162))
      CALL FFV6_2(W(1,4),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,10))
      CALL FFFF14_6_2(W(1,10),W(1,6),W(1,5),GC_585,GC_123,MDL_MT
     $ ,MDL_WT,W(1,51))
C     Amplitude(s) for diagram number 155
      CALL FFV6_0(W(1,51),W(1,3),W(1,32),GC_2,AMP(163))
C     Amplitude(s) for diagram number 156
      CALL FFV6_0(W(1,51),W(1,3),W(1,42),GC_7,AMP(164))
      CALL FFV2_8_3(W(1,10),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,24))
C     Amplitude(s) for diagram number 157
      CALL FFV2_0(W(1,6),W(1,45),W(1,24),GC_664,AMP(165))
      CALL FFV11_9_3(W(1,10),W(1,3),GC_721,GC_722,MDL_MZ,MDL_WZ,W(1,48)
     $ )
C     Amplitude(s) for diagram number 158
      CALL FFV2_0(W(1,6),W(1,45),W(1,48),GC_664,AMP(166))
      CALL FFV4_3(W(1,10),W(1,3),GC_948,MDL_MZ,MDL_WZ,W(1,47))
C     Amplitude(s) for diagram number 159
      CALL FFV2_0(W(1,6),W(1,45),W(1,47),GC_664,AMP(167))
      CALL FFV2_3(W(1,10),W(1,3),GC_938,MDL_MZ,MDL_WZ,W(1,46))
C     Amplitude(s) for diagram number 160
      CALL FFV2_0(W(1,6),W(1,45),W(1,46),GC_664,AMP(168))
C     Amplitude(s) for diagram number 161
      CALL FFV2_0(W(1,49),W(1,5),W(1,24),GC_664,AMP(169))
C     Amplitude(s) for diagram number 162
      CALL FFV2_0(W(1,49),W(1,5),W(1,48),GC_664,AMP(170))
C     Amplitude(s) for diagram number 163
      CALL FFV2_0(W(1,49),W(1,5),W(1,47),GC_664,AMP(171))
C     Amplitude(s) for diagram number 164
      CALL FFV2_0(W(1,49),W(1,5),W(1,46),GC_664,AMP(172))
      CALL FFFF14_6_3(W(1,10),W(1,3),W(1,5),GC_585,GC_123,ZERO,ZERO
     $ ,W(1,44))
C     Amplitude(s) for diagram number 165
      CALL FFV2_0(W(1,6),W(1,44),W(1,43),GC_664,AMP(173))
      CALL FFFF14_6_4(W(1,10),W(1,3),W(1,6),GC_585,GC_123,ZERO,ZERO
     $ ,W(1,44))
C     Amplitude(s) for diagram number 166
      CALL FFV2_0(W(1,44),W(1,5),W(1,43),GC_664,AMP(174))
C     Amplitude(s) for diagram number 167
      CALL FFV2_8_0(W(1,51),W(1,3),W(1,43),GC_651,GC_660,AMP(175))
      CALL FFV11_9_2(W(1,4),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,51))
      CALL FFV2_8_3(W(1,51),W(1,3),GC_651,GC_660,MDL_MZ,MDL_WZ,W(1,44))
C     Amplitude(s) for diagram number 168
      CALL FFV2_0(W(1,6),W(1,45),W(1,44),GC_664,AMP(176))
C     Amplitude(s) for diagram number 169
      CALL FFV2_0(W(1,49),W(1,5),W(1,44),GC_664,AMP(177))
      CALL FFV6_2(W(1,10),W(1,32),GC_2,MDL_MT,MDL_WT,W(1,49))
C     Amplitude(s) for diagram number 170
      CALL FFV2_8_0(W(1,49),W(1,3),W(1,23),GC_651,GC_660,AMP(178))
C     Amplitude(s) for diagram number 171
      CALL FFV11_9_0(W(1,49),W(1,3),W(1,23),GC_721,GC_722,AMP(179))
C     Amplitude(s) for diagram number 172
      CALL FFV4_0(W(1,49),W(1,3),W(1,23),GC_948,AMP(180))
C     Amplitude(s) for diagram number 173
      CALL FFV2_0(W(1,49),W(1,3),W(1,23),GC_938,AMP(181))
      CALL FFV11_9_2(W(1,10),W(1,32),GC_813,GC_814,MDL_MT,MDL_WT,W(1
     $ ,49))
C     Amplitude(s) for diagram number 174
      CALL FFV2_8_0(W(1,49),W(1,3),W(1,23),GC_651,GC_660,AMP(182))
      CALL FFV2_8_2(W(1,10),W(1,23),GC_651,GC_660,MDL_MT,MDL_WT,W(1,49)
     $ )
C     Amplitude(s) for diagram number 175
      CALL FFV6_0(W(1,49),W(1,3),W(1,32),GC_2,AMP(183))
C     Amplitude(s) for diagram number 176
      CALL FFV11_9_0(W(1,49),W(1,3),W(1,32),GC_813,GC_814,AMP(184))
      CALL FFV11_9_2(W(1,10),W(1,23),GC_721,GC_722,MDL_MT,MDL_WT,W(1
     $ ,45))
C     Amplitude(s) for diagram number 177
      CALL FFV6_0(W(1,45),W(1,3),W(1,32),GC_2,AMP(185))
      CALL FFV4_2(W(1,10),W(1,23),GC_948,MDL_MT,MDL_WT,W(1,52))
C     Amplitude(s) for diagram number 178
      CALL FFV6_0(W(1,52),W(1,3),W(1,32),GC_2,AMP(186))
      CALL FFV2_2(W(1,10),W(1,23),GC_938,MDL_MT,MDL_WT,W(1,54))
C     Amplitude(s) for diagram number 179
      CALL FFV6_0(W(1,54),W(1,3),W(1,32),GC_2,AMP(187))
      CALL FFV6_2(W(1,10),W(1,42),GC_7,MDL_MT,MDL_WT,W(1,57))
C     Amplitude(s) for diagram number 180
      CALL FFV2_8_0(W(1,57),W(1,3),W(1,23),GC_651,GC_660,AMP(188))
C     Amplitude(s) for diagram number 181
      CALL FFV11_9_0(W(1,57),W(1,3),W(1,23),GC_721,GC_722,AMP(189))
C     Amplitude(s) for diagram number 182
      CALL FFV4_0(W(1,57),W(1,3),W(1,23),GC_948,AMP(190))
C     Amplitude(s) for diagram number 183
      CALL FFV2_0(W(1,57),W(1,3),W(1,23),GC_938,AMP(191))
      CALL FFV11_9_2(W(1,10),W(1,42),GC_725,GC_726,MDL_MT,MDL_WT,W(1
     $ ,57))
C     Amplitude(s) for diagram number 184
      CALL FFV2_8_0(W(1,57),W(1,3),W(1,23),GC_651,GC_660,AMP(192))
C     Amplitude(s) for diagram number 185
      CALL FFV6_0(W(1,49),W(1,3),W(1,42),GC_7,AMP(193))
C     Amplitude(s) for diagram number 186
      CALL FFV11_9_0(W(1,49),W(1,3),W(1,42),GC_725,GC_726,AMP(194))
C     Amplitude(s) for diagram number 187
      CALL FFV6_0(W(1,45),W(1,3),W(1,42),GC_7,AMP(195))
C     Amplitude(s) for diagram number 188
      CALL FFV6_0(W(1,52),W(1,3),W(1,42),GC_7,AMP(196))
C     Amplitude(s) for diagram number 189
      CALL FFV6_0(W(1,54),W(1,3),W(1,42),GC_7,AMP(197))
      CALL FFV2_8_2(W(1,10),W(1,43),GC_651,GC_660,MDL_MT,MDL_WT,W(1,57)
     $ )
C     Amplitude(s) for diagram number 190
      CALL FFV2_8_0(W(1,57),W(1,3),W(1,23),GC_651,GC_660,AMP(198))
C     Amplitude(s) for diagram number 191
      CALL FFV11_9_0(W(1,57),W(1,3),W(1,23),GC_721,GC_722,AMP(199))
C     Amplitude(s) for diagram number 192
      CALL FFV4_0(W(1,57),W(1,3),W(1,23),GC_948,AMP(200))
C     Amplitude(s) for diagram number 193
      CALL FFV2_0(W(1,57),W(1,3),W(1,23),GC_938,AMP(201))
      CALL FFV11_9_2(W(1,10),W(1,43),GC_721,GC_722,MDL_MT,MDL_WT,W(1
     $ ,57))
C     Amplitude(s) for diagram number 194
      CALL FFV2_8_0(W(1,57),W(1,3),W(1,23),GC_651,GC_660,AMP(202))
      CALL FFV4_2(W(1,10),W(1,43),GC_948,MDL_MT,MDL_WT,W(1,57))
C     Amplitude(s) for diagram number 195
      CALL FFV2_8_0(W(1,57),W(1,3),W(1,23),GC_651,GC_660,AMP(203))
      CALL FFV2_2(W(1,10),W(1,43),GC_938,MDL_MT,MDL_WT,W(1,57))
C     Amplitude(s) for diagram number 196
      CALL FFV2_8_0(W(1,57),W(1,3),W(1,23),GC_651,GC_660,AMP(204))
C     Amplitude(s) for diagram number 197
      CALL FFV2_8_0(W(1,49),W(1,3),W(1,43),GC_651,GC_660,AMP(205))
C     Amplitude(s) for diagram number 198
      CALL FFV11_9_0(W(1,49),W(1,3),W(1,43),GC_721,GC_722,AMP(206))
C     Amplitude(s) for diagram number 199
      CALL FFV4_0(W(1,49),W(1,3),W(1,43),GC_948,AMP(207))
C     Amplitude(s) for diagram number 200
      CALL FFV2_0(W(1,49),W(1,3),W(1,43),GC_938,AMP(208))
C     Amplitude(s) for diagram number 201
      CALL FFV2_8_0(W(1,45),W(1,3),W(1,43),GC_651,GC_660,AMP(209))
C     Amplitude(s) for diagram number 202
      CALL FFV2_8_0(W(1,52),W(1,3),W(1,43),GC_651,GC_660,AMP(210))
C     Amplitude(s) for diagram number 203
      CALL FFV2_8_0(W(1,54),W(1,3),W(1,43),GC_651,GC_660,AMP(211))
      CALL FFV6_2(W(1,51),W(1,32),GC_2,MDL_MT,MDL_WT,W(1,54))
C     Amplitude(s) for diagram number 204
      CALL FFV2_8_0(W(1,54),W(1,3),W(1,23),GC_651,GC_660,AMP(212))
      CALL FFV2_8_2(W(1,51),W(1,23),GC_651,GC_660,MDL_MT,MDL_WT,W(1,54)
     $ )
C     Amplitude(s) for diagram number 205
      CALL FFV6_0(W(1,54),W(1,3),W(1,32),GC_2,AMP(213))
      CALL FFV6_2(W(1,51),W(1,42),GC_7,MDL_MT,MDL_WT,W(1,52))
C     Amplitude(s) for diagram number 206
      CALL FFV2_8_0(W(1,52),W(1,3),W(1,23),GC_651,GC_660,AMP(214))
C     Amplitude(s) for diagram number 207
      CALL FFV6_0(W(1,54),W(1,3),W(1,42),GC_7,AMP(215))
      CALL FFV2_8_2(W(1,51),W(1,43),GC_651,GC_660,MDL_MT,MDL_WT,W(1,52)
     $ )
C     Amplitude(s) for diagram number 208
      CALL FFV2_8_0(W(1,52),W(1,3),W(1,23),GC_651,GC_660,AMP(216))
C     Amplitude(s) for diagram number 209
      CALL FFV2_8_0(W(1,54),W(1,3),W(1,43),GC_651,GC_660,AMP(217))
C     Amplitude(s) for diagram number 210
      CALL FFV6_0(W(1,10),W(1,8),W(1,32),GC_2,AMP(218))
C     Amplitude(s) for diagram number 211
      CALL FFV6_0(W(1,10),W(1,8),W(1,42),GC_7,AMP(219))
C     Amplitude(s) for diagram number 212
      CALL FFV2_8_0(W(1,10),W(1,8),W(1,43),GC_651,GC_660,AMP(220))
      CALL FFV6P0_3(W(1,10),W(1,3),GC_2,ZERO,ZERO,W(1,54))
C     Amplitude(s) for diagram number 213
      CALL FFV1_0(W(1,53),W(1,7),W(1,54),GC_1,AMP(221))
      CALL FFV11_9P0_3(W(1,10),W(1,3),GC_813,GC_814,ZERO,ZERO,W(1,52))
C     Amplitude(s) for diagram number 214
      CALL FFV1_0(W(1,53),W(1,7),W(1,52),GC_1,AMP(222))
C     Amplitude(s) for diagram number 215
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,24),GC_650,GC_660,AMP(223))
C     Amplitude(s) for diagram number 216
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,48),GC_650,GC_660,AMP(224))
C     Amplitude(s) for diagram number 217
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,47),GC_650,GC_660,AMP(225))
C     Amplitude(s) for diagram number 218
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,46),GC_650,GC_660,AMP(226))
      CALL FFV6P0_3(W(1,10),W(1,3),GC_7,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 219
      CALL FFV1_0(W(1,53),W(1,7),W(1,45),GC_7,AMP(227))
      CALL FFV11_9P0_3(W(1,10),W(1,3),GC_725,GC_726,ZERO,ZERO,W(1,49))
C     Amplitude(s) for diagram number 220
      CALL FFV1_0(W(1,53),W(1,7),W(1,49),GC_7,AMP(228))
C     Amplitude(s) for diagram number 221
      CALL FFV1_0(W(1,2),W(1,56),W(1,54),GC_1,AMP(229))
C     Amplitude(s) for diagram number 222
      CALL FFV1_0(W(1,2),W(1,56),W(1,52),GC_1,AMP(230))
C     Amplitude(s) for diagram number 223
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,24),GC_650,GC_660,AMP(231))
C     Amplitude(s) for diagram number 224
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,48),GC_650,GC_660,AMP(232))
C     Amplitude(s) for diagram number 225
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,47),GC_650,GC_660,AMP(233))
C     Amplitude(s) for diagram number 226
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,46),GC_650,GC_660,AMP(234))
C     Amplitude(s) for diagram number 227
      CALL FFV1_0(W(1,2),W(1,56),W(1,45),GC_7,AMP(235))
C     Amplitude(s) for diagram number 228
      CALL FFV1_0(W(1,2),W(1,56),W(1,49),GC_7,AMP(236))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,10),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,49))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,10),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 229
      CALL FFV2_5_0(W(1,49),W(1,7),W(1,23),GC_650,GC_660,AMP(237))
      CALL FFV2_5_0(W(1,45),W(1,7),W(1,23),GC_650,GC_660,AMP(238))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,2),W(1,7),W(1,10)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,45))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,2),W(1,7),W(1,10)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,49))
C     Amplitude(s) for diagram number 230
      CALL FFV2_8_0(W(1,45),W(1,3),W(1,23),GC_651,GC_660,AMP(239))
      CALL FFV2_8_0(W(1,49),W(1,3),W(1,23),GC_651,GC_660,AMP(240))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,7),W(1,10),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,49))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,7),W(1,10),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 231
      CALL FFV2_5_0(W(1,2),W(1,49),W(1,23),GC_650,GC_660,AMP(241))
      CALL FFV2_5_0(W(1,2),W(1,45),W(1,23),GC_650,GC_660,AMP(242))
      CALL FFV6P0_3(W(1,51),W(1,3),GC_2,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 232
      CALL FFV1_0(W(1,53),W(1,7),W(1,45),GC_1,AMP(243))
C     Amplitude(s) for diagram number 233
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,44),GC_650,GC_660,AMP(244))
      CALL FFV6P0_3(W(1,51),W(1,3),GC_7,ZERO,ZERO,W(1,49))
C     Amplitude(s) for diagram number 234
      CALL FFV1_0(W(1,53),W(1,7),W(1,49),GC_7,AMP(245))
C     Amplitude(s) for diagram number 235
      CALL FFV1_0(W(1,2),W(1,56),W(1,45),GC_1,AMP(246))
C     Amplitude(s) for diagram number 236
      CALL FFV2_5_0(W(1,2),W(1,56),W(1,44),GC_650,GC_660,AMP(247))
C     Amplitude(s) for diagram number 237
      CALL FFV1_0(W(1,2),W(1,56),W(1,49),GC_7,AMP(248))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,2),W(1,7),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,49))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,2),W(1,7),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,44))
C     Amplitude(s) for diagram number 238
      CALL FFV2_8_0(W(1,10),W(1,49),W(1,23),GC_651,GC_660,AMP(249))
      CALL FFV2_8_0(W(1,10),W(1,44),W(1,23),GC_651,GC_660,AMP(250))
      CALL FFV1_1(W(1,7),W(1,1),GC_7,ZERO,ZERO,W(1,10))
      CALL FFV2_5_3(W(1,2),W(1,10),GC_650,GC_660,MDL_MZ,MDL_WZ,W(1,45))
C     Amplitude(s) for diagram number 239
      CALL FFV2_0(W(1,6),W(1,11),W(1,45),GC_664,AMP(251))
C     Amplitude(s) for diagram number 240
      CALL FFV2_0(W(1,12),W(1,5),W(1,45),GC_664,AMP(252))
C     Amplitude(s) for diagram number 241
      CALL FFV2_0(W(1,6),W(1,14),W(1,45),GC_664,AMP(253))
C     Amplitude(s) for diagram number 242
      CALL FFV2_0(W(1,15),W(1,5),W(1,45),GC_664,AMP(254))
C     Amplitude(s) for diagram number 243
      CALL FFV2_0(W(1,6),W(1,17),W(1,45),GC_664,AMP(255))
C     Amplitude(s) for diagram number 244
      CALL FFV2_0(W(1,18),W(1,5),W(1,45),GC_664,AMP(256))
C     Amplitude(s) for diagram number 245
      CALL FFV2_0(W(1,6),W(1,20),W(1,45),GC_664,AMP(257))
C     Amplitude(s) for diagram number 246
      CALL FFV2_0(W(1,21),W(1,5),W(1,45),GC_664,AMP(258))
      CALL FFV1_1(W(1,10),W(1,22),GC_1,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 247
      CALL FFV2_5_0(W(1,2),W(1,21),W(1,23),GC_650,GC_660,AMP(259))
      CALL FFV2_5_1(W(1,10),W(1,23),GC_650,GC_660,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 248
      CALL FFV1_0(W(1,2),W(1,21),W(1,22),GC_1,AMP(260))
      CALL FFV1_1(W(1,10),W(1,25),GC_1,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 249
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(261))
C     Amplitude(s) for diagram number 250
      CALL FFV1_0(W(1,2),W(1,21),W(1,25),GC_1,AMP(262))
      CALL FFV2_5_1(W(1,10),W(1,9),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 251
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(263))
C     Amplitude(s) for diagram number 252
      CALL FFV2_5_0(W(1,2),W(1,21),W(1,9),GC_650,GC_660,AMP(264))
      CALL FFV2_5_1(W(1,10),W(1,13),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 253
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(265))
C     Amplitude(s) for diagram number 254
      CALL FFV2_5_0(W(1,2),W(1,21),W(1,13),GC_650,GC_660,AMP(266))
      CALL FFV2_5_1(W(1,10),W(1,16),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 255
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(267))
C     Amplitude(s) for diagram number 256
      CALL FFV2_5_0(W(1,2),W(1,21),W(1,16),GC_650,GC_660,AMP(268))
      CALL FFV2_5_1(W(1,10),W(1,19),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 257
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(269))
C     Amplitude(s) for diagram number 258
      CALL FFV2_5_0(W(1,2),W(1,21),W(1,19),GC_650,GC_660,AMP(270))
      CALL FFV1_1(W(1,10),W(1,26),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 259
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(271))
C     Amplitude(s) for diagram number 260
      CALL FFV1_0(W(1,2),W(1,21),W(1,26),GC_7,AMP(272))
      CALL FFV1_1(W(1,10),W(1,27),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 261
      CALL FFV2_5_0(W(1,2),W(1,20),W(1,23),GC_650,GC_660,AMP(273))
C     Amplitude(s) for diagram number 262
      CALL FFV1_0(W(1,2),W(1,21),W(1,27),GC_7,AMP(274))
      CALL FFV1P0_3(W(1,2),W(1,10),GC_1,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 263
      CALL FFV6_0(W(1,4),W(1,28),W(1,21),GC_2,AMP(275))
C     Amplitude(s) for diagram number 264
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,21),GC_813,GC_814,AMP(276))
C     Amplitude(s) for diagram number 265
      CALL FFV6_0(W(1,4),W(1,29),W(1,21),GC_2,AMP(277))
C     Amplitude(s) for diagram number 266
      CALL FFV6_0(W(1,4),W(1,30),W(1,21),GC_2,AMP(278))
C     Amplitude(s) for diagram number 267
      CALL FFV6_0(W(1,4),W(1,31),W(1,21),GC_2,AMP(279))
      CALL FFV1P0_3(W(1,2),W(1,10),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 268
      CALL FFV6_0(W(1,4),W(1,28),W(1,20),GC_7,AMP(280))
C     Amplitude(s) for diagram number 269
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,20),GC_725,GC_726,AMP(281))
C     Amplitude(s) for diagram number 270
      CALL FFV6_0(W(1,4),W(1,29),W(1,20),GC_7,AMP(282))
C     Amplitude(s) for diagram number 271
      CALL FFV6_0(W(1,4),W(1,30),W(1,20),GC_7,AMP(283))
C     Amplitude(s) for diagram number 272
      CALL FFV6_0(W(1,4),W(1,31),W(1,20),GC_7,AMP(284))
C     Amplitude(s) for diagram number 273
      CALL FFV2_8_0(W(1,4),W(1,28),W(1,45),GC_651,GC_660,AMP(285))
C     Amplitude(s) for diagram number 274
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,45),GC_721,GC_722,AMP(286))
C     Amplitude(s) for diagram number 275
      CALL FFV4_0(W(1,4),W(1,28),W(1,45),GC_948,AMP(287))
C     Amplitude(s) for diagram number 276
      CALL FFV2_0(W(1,4),W(1,28),W(1,45),GC_938,AMP(288))
C     Amplitude(s) for diagram number 277
      CALL FFV2_8_0(W(1,4),W(1,29),W(1,45),GC_651,GC_660,AMP(289))
C     Amplitude(s) for diagram number 278
      CALL FFV2_8_0(W(1,4),W(1,30),W(1,45),GC_651,GC_660,AMP(290))
C     Amplitude(s) for diagram number 279
      CALL FFV2_8_0(W(1,4),W(1,31),W(1,45),GC_651,GC_660,AMP(291))
C     Amplitude(s) for diagram number 280
      CALL FFV6_0(W(1,33),W(1,3),W(1,21),GC_2,AMP(292))
C     Amplitude(s) for diagram number 281
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,21),GC_813,GC_814,AMP(293))
C     Amplitude(s) for diagram number 282
      CALL FFV6_0(W(1,34),W(1,3),W(1,21),GC_2,AMP(294))
C     Amplitude(s) for diagram number 283
      CALL FFV6_0(W(1,35),W(1,3),W(1,21),GC_2,AMP(295))
C     Amplitude(s) for diagram number 284
      CALL FFV6_0(W(1,36),W(1,3),W(1,21),GC_2,AMP(296))
C     Amplitude(s) for diagram number 285
      CALL FFV6_0(W(1,33),W(1,3),W(1,20),GC_7,AMP(297))
C     Amplitude(s) for diagram number 286
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,20),GC_725,GC_726,AMP(298))
C     Amplitude(s) for diagram number 287
      CALL FFV6_0(W(1,34),W(1,3),W(1,20),GC_7,AMP(299))
C     Amplitude(s) for diagram number 288
      CALL FFV6_0(W(1,35),W(1,3),W(1,20),GC_7,AMP(300))
C     Amplitude(s) for diagram number 289
      CALL FFV6_0(W(1,36),W(1,3),W(1,20),GC_7,AMP(301))
C     Amplitude(s) for diagram number 290
      CALL FFV2_8_0(W(1,33),W(1,3),W(1,45),GC_651,GC_660,AMP(302))
C     Amplitude(s) for diagram number 291
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,45),GC_721,GC_722,AMP(303))
C     Amplitude(s) for diagram number 292
      CALL FFV4_0(W(1,33),W(1,3),W(1,45),GC_948,AMP(304))
C     Amplitude(s) for diagram number 293
      CALL FFV2_0(W(1,33),W(1,3),W(1,45),GC_938,AMP(305))
C     Amplitude(s) for diagram number 294
      CALL FFV2_8_0(W(1,34),W(1,3),W(1,45),GC_651,GC_660,AMP(306))
C     Amplitude(s) for diagram number 295
      CALL FFV2_8_0(W(1,35),W(1,3),W(1,45),GC_651,GC_660,AMP(307))
C     Amplitude(s) for diagram number 296
      CALL FFV2_8_0(W(1,36),W(1,3),W(1,45),GC_651,GC_660,AMP(308))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,2),W(1,10),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,18))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_3(W(1,2),W(1,10),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 297
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,23),GC_651,GC_660,AMP(309))
      CALL FFV2_8_0(W(1,4),W(1,17),W(1,23),GC_651,GC_660,AMP(310))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,2),W(1,10),W(1,4)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,MDL_MT,MDL_WT,W(1,17))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_4(W(1,2),W(1,10),W(1,4)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 298
      CALL FFV2_8_0(W(1,17),W(1,3),W(1,23),GC_651,GC_660,AMP(311))
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,23),GC_651,GC_660,AMP(312))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,10),W(1,4),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,18))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_1(W(1,10),W(1,4),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 299
      CALL FFV2_5_0(W(1,2),W(1,18),W(1,23),GC_650,GC_660,AMP(313))
      CALL FFV2_5_0(W(1,2),W(1,17),W(1,23),GC_650,GC_660,AMP(314))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,3)
     $ ,GC_205,GC_559,GC_589,GC_579,GC_199,GC_203,GC_149,GC_201,GC_204
     $ ,GC_202,ZERO,ZERO,W(1,17))
      CALL FFFF11_14_18_19_2_20_6_7_21_110_2(W(1,2),W(1,4),W(1,3)
     $ ,GC_213,GC_560,GC_590,GC_580,GC_207,GC_211,GC_177,GC_209,GC_212
     $ ,GC_210,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 300
      CALL FFV2_5_0(W(1,17),W(1,10),W(1,23),GC_650,GC_660,AMP(315))
      CALL FFV2_5_0(W(1,18),W(1,10),W(1,23),GC_650,GC_660,AMP(316))
C     Amplitude(s) for diagram number 301
      CALL FFV2_0(W(1,6),W(1,38),W(1,45),GC_664,AMP(317))
C     Amplitude(s) for diagram number 302
      CALL FFV2_0(W(1,37),W(1,5),W(1,45),GC_664,AMP(318))
C     Amplitude(s) for diagram number 303
      CALL FFV6_0(W(1,4),W(1,8),W(1,21),GC_2,AMP(319))
C     Amplitude(s) for diagram number 304
      CALL FFV6_0(W(1,4),W(1,8),W(1,20),GC_7,AMP(320))
C     Amplitude(s) for diagram number 305
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,45),GC_651,GC_660,AMP(321))
C     Amplitude(s) for diagram number 306
      CALL FFV6_0(W(1,41),W(1,3),W(1,21),GC_2,AMP(322))
C     Amplitude(s) for diagram number 307
      CALL FFV6_0(W(1,41),W(1,3),W(1,20),GC_7,AMP(323))
C     Amplitude(s) for diagram number 308
      CALL FFV2_8_0(W(1,41),W(1,3),W(1,45),GC_651,GC_660,AMP(324))
      CALL FFV6_1(W(1,3),W(1,32),GC_2,MDL_MT,MDL_WT,W(1,45))
C     Amplitude(s) for diagram number 309
      CALL FFV6_0(W(1,33),W(1,45),W(1,1),GC_7,AMP(325))
C     Amplitude(s) for diagram number 310
      CALL FFV11_9_0(W(1,33),W(1,45),W(1,1),GC_725,GC_726,AMP(326))
C     Amplitude(s) for diagram number 311
      CALL FFV6_0(W(1,34),W(1,45),W(1,1),GC_7,AMP(327))
C     Amplitude(s) for diagram number 312
      CALL FFV6_0(W(1,35),W(1,45),W(1,1),GC_7,AMP(328))
C     Amplitude(s) for diagram number 313
      CALL FFV6_0(W(1,36),W(1,45),W(1,1),GC_7,AMP(329))
      CALL FFV11_9_1(W(1,3),W(1,32),GC_813,GC_814,MDL_MT,MDL_WT,W(1,45)
     $ )
C     Amplitude(s) for diagram number 314
      CALL FFV6_0(W(1,33),W(1,45),W(1,1),GC_7,AMP(330))
      CALL FFV6_2(W(1,4),W(1,32),GC_2,MDL_MT,MDL_WT,W(1,45))
C     Amplitude(s) for diagram number 315
      CALL FFV6_0(W(1,45),W(1,28),W(1,1),GC_7,AMP(331))
C     Amplitude(s) for diagram number 316
      CALL FFV11_9_0(W(1,45),W(1,28),W(1,1),GC_725,GC_726,AMP(332))
C     Amplitude(s) for diagram number 317
      CALL FFV6_0(W(1,45),W(1,29),W(1,1),GC_7,AMP(333))
C     Amplitude(s) for diagram number 318
      CALL FFV6_0(W(1,45),W(1,30),W(1,1),GC_7,AMP(334))
C     Amplitude(s) for diagram number 319
      CALL FFV6_0(W(1,45),W(1,31),W(1,1),GC_7,AMP(335))
      CALL FFV11_9_2(W(1,4),W(1,32),GC_813,GC_814,MDL_MT,MDL_WT,W(1,45)
     $ )
C     Amplitude(s) for diagram number 320
      CALL FFV6_0(W(1,45),W(1,28),W(1,1),GC_7,AMP(336))
      CALL VVV1P0_1(W(1,1),W(1,42),GC_6,ZERO,ZERO,W(1,45))
C     Amplitude(s) for diagram number 321
      CALL FFV6_0(W(1,4),W(1,28),W(1,45),GC_7,AMP(337))
C     Amplitude(s) for diagram number 322
      CALL FFV11_9_0(W(1,4),W(1,28),W(1,45),GC_725,GC_726,AMP(338))
C     Amplitude(s) for diagram number 323
      CALL FFV6_0(W(1,4),W(1,29),W(1,45),GC_7,AMP(339))
C     Amplitude(s) for diagram number 324
      CALL FFV6_0(W(1,4),W(1,30),W(1,45),GC_7,AMP(340))
C     Amplitude(s) for diagram number 325
      CALL FFV6_0(W(1,4),W(1,31),W(1,45),GC_7,AMP(341))
C     Amplitude(s) for diagram number 326
      CALL FFV6_0(W(1,33),W(1,3),W(1,45),GC_7,AMP(342))
C     Amplitude(s) for diagram number 327
      CALL FFV11_9_0(W(1,33),W(1,3),W(1,45),GC_725,GC_726,AMP(343))
C     Amplitude(s) for diagram number 328
      CALL FFV6_0(W(1,34),W(1,3),W(1,45),GC_7,AMP(344))
C     Amplitude(s) for diagram number 329
      CALL FFV6_0(W(1,35),W(1,3),W(1,45),GC_7,AMP(345))
C     Amplitude(s) for diagram number 330
      CALL FFV6_0(W(1,36),W(1,3),W(1,45),GC_7,AMP(346))
      CALL FFV6_1(W(1,3),W(1,42),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 331
      CALL FFV6_0(W(1,33),W(1,20),W(1,1),GC_7,AMP(347))
C     Amplitude(s) for diagram number 332
      CALL FFV11_9_0(W(1,33),W(1,20),W(1,1),GC_725,GC_726,AMP(348))
C     Amplitude(s) for diagram number 333
      CALL FFV6_0(W(1,34),W(1,20),W(1,1),GC_7,AMP(349))
C     Amplitude(s) for diagram number 334
      CALL FFV6_0(W(1,35),W(1,20),W(1,1),GC_7,AMP(350))
C     Amplitude(s) for diagram number 335
      CALL FFV6_0(W(1,36),W(1,20),W(1,1),GC_7,AMP(351))
      CALL FFV11_9_1(W(1,3),W(1,42),GC_725,GC_726,MDL_MT,MDL_WT,W(1,20)
     $ )
C     Amplitude(s) for diagram number 336
      CALL FFV6_0(W(1,33),W(1,20),W(1,1),GC_7,AMP(352))
      CALL FFV6_2(W(1,4),W(1,42),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 337
      CALL FFV6_0(W(1,20),W(1,28),W(1,1),GC_7,AMP(353))
C     Amplitude(s) for diagram number 338
      CALL FFV11_9_0(W(1,20),W(1,28),W(1,1),GC_725,GC_726,AMP(354))
C     Amplitude(s) for diagram number 339
      CALL FFV6_0(W(1,20),W(1,29),W(1,1),GC_7,AMP(355))
C     Amplitude(s) for diagram number 340
      CALL FFV6_0(W(1,20),W(1,30),W(1,1),GC_7,AMP(356))
C     Amplitude(s) for diagram number 341
      CALL FFV6_0(W(1,20),W(1,31),W(1,1),GC_7,AMP(357))
      CALL FFV11_9_2(W(1,4),W(1,42),GC_725,GC_726,MDL_MT,MDL_WT,W(1,20)
     $ )
C     Amplitude(s) for diagram number 342
      CALL FFV6_0(W(1,20),W(1,28),W(1,1),GC_7,AMP(358))
      CALL FFVV2_4_1(W(1,3),W(1,1),W(1,42),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,20))
C     Amplitude(s) for diagram number 343
      CALL FFV2_8_0(W(1,4),W(1,20),W(1,23),GC_651,GC_660,AMP(359))
      CALL FFVV2_4_2(W(1,4),W(1,1),W(1,42),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,20))
C     Amplitude(s) for diagram number 344
      CALL FFV2_8_0(W(1,20),W(1,3),W(1,23),GC_651,GC_660,AMP(360))
      CALL FFV2_8_1(W(1,3),W(1,43),GC_651,GC_660,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 345
      CALL FFV6_0(W(1,33),W(1,20),W(1,1),GC_7,AMP(361))
C     Amplitude(s) for diagram number 346
      CALL FFV11_9_0(W(1,33),W(1,20),W(1,1),GC_725,GC_726,AMP(362))
C     Amplitude(s) for diagram number 347
      CALL FFV6_0(W(1,34),W(1,20),W(1,1),GC_7,AMP(363))
C     Amplitude(s) for diagram number 348
      CALL FFV6_0(W(1,35),W(1,20),W(1,1),GC_7,AMP(364))
C     Amplitude(s) for diagram number 349
      CALL FFV6_0(W(1,36),W(1,20),W(1,1),GC_7,AMP(365))
      CALL FFV11_9_1(W(1,3),W(1,43),GC_721,GC_722,MDL_MT,MDL_WT,W(1,20)
     $ )
C     Amplitude(s) for diagram number 350
      CALL FFV6_0(W(1,33),W(1,20),W(1,1),GC_7,AMP(366))
      CALL FFV4_1(W(1,3),W(1,43),GC_948,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 351
      CALL FFV6_0(W(1,33),W(1,20),W(1,1),GC_7,AMP(367))
      CALL FFV2_1(W(1,3),W(1,43),GC_938,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 352
      CALL FFV6_0(W(1,33),W(1,20),W(1,1),GC_7,AMP(368))
      CALL FFV2_8_2(W(1,4),W(1,43),GC_651,GC_660,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 353
      CALL FFV6_0(W(1,20),W(1,28),W(1,1),GC_7,AMP(369))
C     Amplitude(s) for diagram number 354
      CALL FFV11_9_0(W(1,20),W(1,28),W(1,1),GC_725,GC_726,AMP(370))
C     Amplitude(s) for diagram number 355
      CALL FFV6_0(W(1,20),W(1,29),W(1,1),GC_7,AMP(371))
C     Amplitude(s) for diagram number 356
      CALL FFV6_0(W(1,20),W(1,30),W(1,1),GC_7,AMP(372))
C     Amplitude(s) for diagram number 357
      CALL FFV6_0(W(1,20),W(1,31),W(1,1),GC_7,AMP(373))
      CALL FFV11_9_2(W(1,4),W(1,43),GC_721,GC_722,MDL_MT,MDL_WT,W(1,20)
     $ )
C     Amplitude(s) for diagram number 358
      CALL FFV6_0(W(1,20),W(1,28),W(1,1),GC_7,AMP(374))
      CALL FFV4_2(W(1,4),W(1,43),GC_948,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 359
      CALL FFV6_0(W(1,20),W(1,28),W(1,1),GC_7,AMP(375))
      CALL FFV2_2(W(1,4),W(1,43),GC_938,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 360
      CALL FFV6_0(W(1,20),W(1,28),W(1,1),GC_7,AMP(376))
      CALL FFV6_1(W(1,8),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 361
      CALL FFV6_0(W(1,4),W(1,20),W(1,32),GC_2,AMP(377))
C     Amplitude(s) for diagram number 362
      CALL FFV6_0(W(1,4),W(1,8),W(1,45),GC_7,AMP(378))
C     Amplitude(s) for diagram number 363
      CALL FFV6_0(W(1,4),W(1,20),W(1,42),GC_7,AMP(379))
C     Amplitude(s) for diagram number 364
      CALL FFV2_8_0(W(1,4),W(1,20),W(1,43),GC_651,GC_660,AMP(380))
      CALL FFV6_2(W(1,41),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 365
      CALL FFV6_0(W(1,20),W(1,3),W(1,32),GC_2,AMP(381))
C     Amplitude(s) for diagram number 366
      CALL FFV6_0(W(1,41),W(1,3),W(1,45),GC_7,AMP(382))
C     Amplitude(s) for diagram number 367
      CALL FFV6_0(W(1,20),W(1,3),W(1,42),GC_7,AMP(383))
C     Amplitude(s) for diagram number 368
      CALL FFV2_8_0(W(1,20),W(1,3),W(1,43),GC_651,GC_660,AMP(384))
      CALL FFV1_2(W(1,2),W(1,22),GC_1,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 369
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(385))
      CALL FFV1_1(W(1,7),W(1,22),GC_1,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 370
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(386))
      CALL FFV1_2(W(1,2),W(1,25),GC_1,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 371
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(387))
      CALL FFV1_1(W(1,7),W(1,25),GC_1,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 372
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(388))
      CALL FFV2_5_2(W(1,2),W(1,9),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 373
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(389))
      CALL FFV2_5_1(W(1,7),W(1,9),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 374
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(390))
      CALL FFV2_5_2(W(1,2),W(1,13),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 375
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(391))
      CALL FFV2_5_1(W(1,7),W(1,13),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 376
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(392))
      CALL FFV2_5_2(W(1,2),W(1,16),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 377
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(393))
      CALL FFV2_5_1(W(1,7),W(1,16),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 378
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(394))
      CALL FFV2_5_2(W(1,2),W(1,19),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 379
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(395))
      CALL FFV2_5_1(W(1,7),W(1,19),GC_650,GC_660,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 380
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(396))
      CALL VVV1P0_1(W(1,1),W(1,26),GC_6,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 381
      CALL FFV1_0(W(1,53),W(1,7),W(1,20),GC_7,AMP(397))
C     Amplitude(s) for diagram number 382
      CALL FFV1_0(W(1,2),W(1,56),W(1,20),GC_7,AMP(398))
      CALL FFV1_2(W(1,2),W(1,26),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 383
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(399))
      CALL FFV1_1(W(1,7),W(1,26),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 384
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(400))
      CALL VVV1P0_1(W(1,1),W(1,27),GC_6,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 385
      CALL FFV1_0(W(1,53),W(1,7),W(1,20),GC_7,AMP(401))
C     Amplitude(s) for diagram number 386
      CALL FFV1_0(W(1,2),W(1,56),W(1,20),GC_7,AMP(402))
      CALL FFV1_2(W(1,2),W(1,27),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 387
      CALL FFV1_0(W(1,20),W(1,56),W(1,1),GC_7,AMP(403))
      CALL FFV1_1(W(1,7),W(1,27),GC_7,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 388
      CALL FFV1_0(W(1,53),W(1,20),W(1,1),GC_7,AMP(404))
      CALL FFVV2_4P0_3(W(1,4),W(1,3),W(1,1),GC_728,GC_727,ZERO,ZERO
     $ ,W(1,20))
      CALL FFV1_2(W(1,2),W(1,20),GC_7,ZERO,ZERO,W(1,53))
C     Amplitude(s) for diagram number 389
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,23),GC_650,GC_660,AMP(405))
      CALL FFV1_1(W(1,7),W(1,20),GC_7,ZERO,ZERO,W(1,53))
C     Amplitude(s) for diagram number 390
      CALL FFV2_5_0(W(1,2),W(1,53),W(1,23),GC_650,GC_660,AMP(406))
      CALL FFV1_2(W(1,17),W(1,1),GC_7,ZERO,ZERO,W(1,53))
      CALL FFV1_2(W(1,18),W(1,1),GC_7,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 391
      CALL FFV2_5_0(W(1,53),W(1,7),W(1,23),GC_650,GC_660,AMP(407))
      CALL FFV2_5_0(W(1,17),W(1,7),W(1,23),GC_650,GC_660,AMP(408))
      CALL FFV6_1(W(1,49),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,17))
      CALL FFV6_1(W(1,44),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,49))
C     Amplitude(s) for diagram number 392
      CALL FFV2_8_0(W(1,4),W(1,17),W(1,23),GC_651,GC_660,AMP(409))
      CALL FFV2_8_0(W(1,4),W(1,49),W(1,23),GC_651,GC_660,AMP(410))
      CALL FFV6_2(W(1,55),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,49))
      CALL FFV6_2(W(1,50),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,55))
C     Amplitude(s) for diagram number 393
      CALL FFV2_8_0(W(1,49),W(1,3),W(1,23),GC_651,GC_660,AMP(411))
      CALL FFV2_8_0(W(1,55),W(1,3),W(1,23),GC_651,GC_660,AMP(412))
      CALL FFV1_1(W(1,39),W(1,1),GC_7,ZERO,ZERO,W(1,55))
      CALL FFV1_1(W(1,40),W(1,1),GC_7,ZERO,ZERO,W(1,39))
C     Amplitude(s) for diagram number 394
      CALL FFV2_5_0(W(1,2),W(1,55),W(1,23),GC_650,GC_660,AMP(413))
      CALL FFV2_5_0(W(1,2),W(1,39),W(1,23),GC_650,GC_660,AMP(414))
      JAMP(1)=+1D0/2D0*(+AMP(21)+AMP(22)+AMP(23)+AMP(24)+AMP(30)
     $ +AMP(31)+AMP(32)+AMP(33)+AMP(34)+AMP(47)+AMP(48)+AMP(49)+AMP(50)
     $ +AMP(51)+AMP(60)+AMP(62)+AMP(64)+AMP(68)+AMP(70)+AMP(73)+AMP(76)
     $ +AMP(100)+AMP(101)+AMP(102)+AMP(103)+AMP(104)+AMP(105)+AMP(106)
     $ +AMP(107)+AMP(108)+AMP(109)+AMP(126)+AMP(127)+AMP(131)+AMP(139)
     $ +AMP(140)+AMP(147)+AMP(148)+AMP(150)+AMP(152)+AMP(154)+AMP(157)
     $ +AMP(160)+AMP(162)-IMAG1*AMP(337)-IMAG1*AMP(338)-IMAG1*AMP(339)
     $ -IMAG1*AMP(340)-IMAG1*AMP(341)-IMAG1*AMP(342)-IMAG1*AMP(343)
     $ -IMAG1*AMP(344)-IMAG1*AMP(345)-IMAG1*AMP(346)+AMP(353)+AMP(354)
     $ +AMP(355)+AMP(356)+AMP(357)+AMP(358)-IMAG1*AMP(359)-IMAG1
     $ *AMP(360)-IMAG1*AMP(378)+AMP(379)-IMAG1*AMP(382)+IMAG1*AMP(397)
     $ +IMAG1*AMP(398)+AMP(400)+IMAG1*AMP(401)+IMAG1*AMP(402)+AMP(404)
     $ +IMAG1*AMP(405)+IMAG1*AMP(406)+AMP(412)+AMP(414))
      JAMP(2)=+AMP(75)-1D0/6D0*AMP(76)+AMP(77)+AMP(78)+AMP(79)+AMP(80)
     $ +AMP(81)+AMP(82)+AMP(83)+AMP(84)+AMP(85)+AMP(86)+AMP(87)+AMP(88)
     $ +AMP(89)+AMP(90)+AMP(91)+AMP(92)+AMP(93)+AMP(94)+AMP(95)+AMP(96)
     $ +AMP(97)+AMP(98)+AMP(99)-1D0/6D0*AMP(100)-1D0/6D0*AMP(101)-1D0
     $ /6D0*AMP(102)-1D0/6D0*AMP(103)-1D0/6D0*AMP(104)-1D0/6D0*AMP(105)
     $ -1D0/6D0*AMP(106)-1D0/6D0*AMP(107)-1D0/6D0*AMP(108)-1D0/6D0
     $ *AMP(109)+AMP(110)+AMP(111)+AMP(112)+AMP(113)+AMP(114)+AMP(115)
     $ +AMP(116)+AMP(117)+AMP(118)+AMP(119)+AMP(120)+AMP(121)+AMP(122)
     $ +AMP(123)+AMP(124)+AMP(125)-1D0/6D0*AMP(126)-1D0/6D0*AMP(127)
     $ +AMP(128)+AMP(129)+AMP(130)-1D0/6D0*AMP(131)+AMP(132)+AMP(133)
     $ +AMP(134)+AMP(135)+AMP(136)+AMP(137)+AMP(138)-1D0/6D0*AMP(139)
     $ -1D0/6D0*AMP(140)+AMP(141)+AMP(142)+AMP(143)+AMP(144)+AMP(145)
     $ +AMP(146)-1D0/6D0*AMP(147)-1D0/6D0*AMP(148)+AMP(149)-1D0/6D0
     $ *AMP(150)+AMP(151)-1D0/6D0*AMP(152)+AMP(153)-1D0/6D0*AMP(154)
     $ +AMP(155)+AMP(156)-1D0/6D0*AMP(157)+AMP(158)+AMP(159)-1D0/6D0
     $ *AMP(160)+AMP(161)-1D0/6D0*AMP(162)+AMP(163)-1D0/6D0*AMP(164)
     $ +AMP(165)+AMP(166)+AMP(167)+AMP(168)+AMP(169)+AMP(170)+AMP(171)
     $ +AMP(172)+AMP(173)+AMP(174)+AMP(175)+AMP(176)+AMP(177)+AMP(178)
     $ +AMP(179)+AMP(180)+AMP(181)+AMP(182)+AMP(183)+AMP(184)+AMP(185)
     $ +AMP(186)+AMP(187)-1D0/6D0*AMP(188)-1D0/6D0*AMP(189)-1D0/6D0
     $ *AMP(190)-1D0/6D0*AMP(191)-1D0/6D0*AMP(192)-1D0/6D0*AMP(193)
     $ -1D0/6D0*AMP(194)-1D0/6D0*AMP(195)-1D0/6D0*AMP(196)-1D0/6D0
     $ *AMP(197)+AMP(198)+AMP(199)+AMP(200)+AMP(201)+AMP(202)+AMP(203)
     $ +AMP(204)+AMP(205)+AMP(206)+AMP(207)+AMP(208)+AMP(209)+AMP(210)
     $ +AMP(211)+AMP(212)+AMP(213)-1D0/6D0*AMP(214)-1D0/6D0*AMP(215)
     $ +AMP(216)+AMP(217)+AMP(218)-1D0/6D0*AMP(219)+AMP(220)+AMP(221)
     $ +AMP(222)+AMP(223)+AMP(224)+AMP(225)+AMP(226)-1D0/6D0*AMP(227)
     $ -1D0/6D0*AMP(228)+AMP(229)+AMP(230)+AMP(231)+AMP(232)+AMP(233)
     $ +AMP(234)-1D0/6D0*AMP(235)-1D0/6D0*AMP(236)+AMP(237)-1D0/6D0
     $ *AMP(238)+AMP(239)-1D0/6D0*AMP(240)+AMP(241)-1D0/6D0*AMP(242)
     $ +AMP(243)+AMP(244)-1D0/6D0*AMP(245)+AMP(246)+AMP(247)-1D0/6D0
     $ *AMP(248)+AMP(249)-1D0/6D0*AMP(250)+AMP(325)+AMP(326)+AMP(327)
     $ +AMP(328)+AMP(329)+AMP(330)+AMP(331)+AMP(332)+AMP(333)+AMP(334)
     $ +AMP(335)+AMP(336)-1D0/6D0*AMP(347)-1D0/6D0*AMP(348)-1D0/6D0
     $ *AMP(349)-1D0/6D0*AMP(350)-1D0/6D0*AMP(351)-1D0/6D0*AMP(352)
     $ -1D0/6D0*AMP(353)-1D0/6D0*AMP(354)-1D0/6D0*AMP(355)-1D0/6D0
     $ *AMP(356)-1D0/6D0*AMP(357)-1D0/6D0*AMP(358)+AMP(361)+AMP(362)
     $ +AMP(363)+AMP(364)+AMP(365)+AMP(366)+AMP(367)+AMP(368)+AMP(369)
     $ +AMP(370)+AMP(371)+AMP(372)+AMP(373)+AMP(374)+AMP(375)+AMP(376)
     $ +AMP(377)-1D0/6D0*AMP(379)+AMP(380)+AMP(381)-1D0/6D0*AMP(383)
     $ +AMP(384)+AMP(409)-1D0/6D0*AMP(410)+AMP(411)-1D0/6D0*AMP(412)
      JAMP(3)=+AMP(1)+AMP(2)+AMP(3)+AMP(4)+AMP(5)+AMP(6)+AMP(7)+AMP(8)
     $ +AMP(9)+AMP(10)+AMP(11)+AMP(12)+AMP(13)+AMP(14)+AMP(15)+AMP(16)
     $ +AMP(17)+AMP(18)+AMP(19)+AMP(20)-1D0/6D0*AMP(21)-1D0/6D0*AMP(22)
     $ -1D0/6D0*AMP(23)-1D0/6D0*AMP(24)+AMP(25)+AMP(26)+AMP(27)+AMP(28)
     $ +AMP(29)-1D0/6D0*AMP(30)-1D0/6D0*AMP(31)-1D0/6D0*AMP(32)-1D0
     $ /6D0*AMP(33)-1D0/6D0*AMP(34)+AMP(35)+AMP(36)+AMP(37)+AMP(38)
     $ +AMP(39)+AMP(40)+AMP(41)+AMP(42)+AMP(43)+AMP(44)+AMP(45)+AMP(46)
     $ -1D0/6D0*AMP(47)-1D0/6D0*AMP(48)-1D0/6D0*AMP(49)-1D0/6D0*AMP(50)
     $ -1D0/6D0*AMP(51)+AMP(52)+AMP(53)+AMP(54)+AMP(55)+AMP(56)+AMP(57)
     $ +AMP(58)+AMP(59)-1D0/6D0*AMP(60)+AMP(61)-1D0/6D0*AMP(62)+AMP(63)
     $ -1D0/6D0*AMP(64)+AMP(65)+AMP(66)+AMP(67)-1D0/6D0*AMP(68)+AMP(69)
     $ -1D0/6D0*AMP(70)+AMP(71)+AMP(72)-1D0/6D0*AMP(73)+AMP(74)
     $ +AMP(251)+AMP(252)+AMP(253)+AMP(254)+AMP(255)+AMP(256)+AMP(257)
     $ +AMP(258)+AMP(259)+AMP(260)+AMP(261)+AMP(262)+AMP(263)+AMP(264)
     $ +AMP(265)+AMP(266)+AMP(267)+AMP(268)+AMP(269)+AMP(270)-1D0/6D0
     $ *AMP(271)-1D0/6D0*AMP(272)-1D0/6D0*AMP(273)-1D0/6D0*AMP(274)
     $ +AMP(275)+AMP(276)+AMP(277)+AMP(278)+AMP(279)-1D0/6D0*AMP(280)
     $ -1D0/6D0*AMP(281)-1D0/6D0*AMP(282)-1D0/6D0*AMP(283)-1D0/6D0
     $ *AMP(284)+AMP(285)+AMP(286)+AMP(287)+AMP(288)+AMP(289)+AMP(290)
     $ +AMP(291)+AMP(292)+AMP(293)+AMP(294)+AMP(295)+AMP(296)-1D0/6D0
     $ *AMP(297)-1D0/6D0*AMP(298)-1D0/6D0*AMP(299)-1D0/6D0*AMP(300)
     $ -1D0/6D0*AMP(301)+AMP(302)+AMP(303)+AMP(304)+AMP(305)+AMP(306)
     $ +AMP(307)+AMP(308)+AMP(309)-1D0/6D0*AMP(310)+AMP(311)-1D0/6D0
     $ *AMP(312)+AMP(313)-1D0/6D0*AMP(314)+AMP(315)-1D0/6D0*AMP(316)
     $ +AMP(317)+AMP(318)+AMP(319)-1D0/6D0*AMP(320)+AMP(321)+AMP(322)
     $ -1D0/6D0*AMP(323)+AMP(324)+AMP(385)+AMP(386)+AMP(387)+AMP(388)
     $ +AMP(389)+AMP(390)+AMP(391)+AMP(392)+AMP(393)+AMP(394)+AMP(395)
     $ +AMP(396)-1D0/6D0*AMP(399)-1D0/6D0*AMP(400)-1D0/6D0*AMP(403)
     $ -1D0/6D0*AMP(404)+AMP(407)-1D0/6D0*AMP(408)+AMP(413)-1D0/6D0
     $ *AMP(414)
      JAMP(4)=+1D0/2D0*(+AMP(164)+AMP(188)+AMP(189)+AMP(190)+AMP(191)
     $ +AMP(192)+AMP(193)+AMP(194)+AMP(195)+AMP(196)+AMP(197)+AMP(214)
     $ +AMP(215)+AMP(219)+AMP(227)+AMP(228)+AMP(235)+AMP(236)+AMP(238)
     $ +AMP(240)+AMP(242)+AMP(245)+AMP(248)+AMP(250)+AMP(271)+AMP(272)
     $ +AMP(273)+AMP(274)+AMP(280)+AMP(281)+AMP(282)+AMP(283)+AMP(284)
     $ +AMP(297)+AMP(298)+AMP(299)+AMP(300)+AMP(301)+AMP(310)+AMP(312)
     $ +AMP(314)+AMP(316)+AMP(320)+AMP(323)+IMAG1*AMP(337)+IMAG1
     $ *AMP(338)+IMAG1*AMP(339)+IMAG1*AMP(340)+IMAG1*AMP(341)+IMAG1
     $ *AMP(342)+IMAG1*AMP(343)+IMAG1*AMP(344)+IMAG1*AMP(345)+IMAG1
     $ *AMP(346)+AMP(347)+AMP(348)+AMP(349)+AMP(350)+AMP(351)+AMP(352)
     $ +IMAG1*AMP(359)+IMAG1*AMP(360)+IMAG1*AMP(378)+IMAG1*AMP(382)
     $ +AMP(383)-IMAG1*AMP(397)-IMAG1*AMP(398)+AMP(399)-IMAG1*AMP(401)
     $ -IMAG1*AMP(402)+AMP(403)-IMAG1*AMP(405)-IMAG1*AMP(406)+AMP(408)
     $ +AMP(410))

      M55_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M55_MATRIX = M55_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M55_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M55_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M55_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M55_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M55_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NCOMB
      PARAMETER (NCOMB=128)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M55_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M55_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M55_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M55_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

