      SUBROUTINE M3_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M3_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M3_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M3_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > t t~ h g DIM6<=1 FCNC=0 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=32)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M3_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M3_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M3_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,6) /-1,-1,-1, 1, 0,-1/
      DATA (NHEL(I,   2),I=1,6) /-1,-1,-1, 1, 0, 1/
      DATA (NHEL(I,   3),I=1,6) /-1,-1,-1,-1, 0,-1/
      DATA (NHEL(I,   4),I=1,6) /-1,-1,-1,-1, 0, 1/
      DATA (NHEL(I,   5),I=1,6) /-1,-1, 1, 1, 0,-1/
      DATA (NHEL(I,   6),I=1,6) /-1,-1, 1, 1, 0, 1/
      DATA (NHEL(I,   7),I=1,6) /-1,-1, 1,-1, 0,-1/
      DATA (NHEL(I,   8),I=1,6) /-1,-1, 1,-1, 0, 1/
      DATA (NHEL(I,   9),I=1,6) /-1, 1,-1, 1, 0,-1/
      DATA (NHEL(I,  10),I=1,6) /-1, 1,-1, 1, 0, 1/
      DATA (NHEL(I,  11),I=1,6) /-1, 1,-1,-1, 0,-1/
      DATA (NHEL(I,  12),I=1,6) /-1, 1,-1,-1, 0, 1/
      DATA (NHEL(I,  13),I=1,6) /-1, 1, 1, 1, 0,-1/
      DATA (NHEL(I,  14),I=1,6) /-1, 1, 1, 1, 0, 1/
      DATA (NHEL(I,  15),I=1,6) /-1, 1, 1,-1, 0,-1/
      DATA (NHEL(I,  16),I=1,6) /-1, 1, 1,-1, 0, 1/
      DATA (NHEL(I,  17),I=1,6) / 1,-1,-1, 1, 0,-1/
      DATA (NHEL(I,  18),I=1,6) / 1,-1,-1, 1, 0, 1/
      DATA (NHEL(I,  19),I=1,6) / 1,-1,-1,-1, 0,-1/
      DATA (NHEL(I,  20),I=1,6) / 1,-1,-1,-1, 0, 1/
      DATA (NHEL(I,  21),I=1,6) / 1,-1, 1, 1, 0,-1/
      DATA (NHEL(I,  22),I=1,6) / 1,-1, 1, 1, 0, 1/
      DATA (NHEL(I,  23),I=1,6) / 1,-1, 1,-1, 0,-1/
      DATA (NHEL(I,  24),I=1,6) / 1,-1, 1,-1, 0, 1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1,-1, 1, 0,-1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1,-1, 1, 0, 1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1,-1,-1, 0,-1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1,-1,-1, 0, 1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 1, 1, 0,-1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 1, 1, 0, 1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 1,-1, 0,-1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 1,-1, 0, 1/
      DATA IDEN/256/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M3_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M3_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M3_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M3_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M3_IS_BORN_HEL_SELECTED(IHEL)
     $       ) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M3_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > t t~ h g DIM6<=1 FCNC=0 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=297)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=37, NCOLOR=6)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/9/
      DATA (CF(I,  1),I=  1,  6) /   64,   -8,   -8,    1,    1,   10/
C     1 T(1,2,6,3,4)
      DATA DENOM(2)/9/
      DATA (CF(I,  2),I=  1,  6) /   -8,   64,    1,   10,   -8,    1/
C     1 T(1,6,2,3,4)
      DATA DENOM(3)/9/
      DATA (CF(I,  3),I=  1,  6) /   -8,    1,   64,   -8,   10,    1/
C     1 T(2,1,6,3,4)
      DATA DENOM(4)/9/
      DATA (CF(I,  4),I=  1,  6) /    1,   10,   -8,   64,    1,   -8/
C     1 T(2,6,1,3,4)
      DATA DENOM(5)/9/
      DATA (CF(I,  5),I=  1,  6) /    1,   -8,   10,    1,   64,   -8/
C     1 T(6,1,2,3,4)
      DATA DENOM(6)/9/
      DATA (CF(I,  6),I=  1,  6) /   10,    1,    1,   -8,   -8,   64/
C     1 T(6,2,1,3,4)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL SXXXXX(P(0,5),+1*IC(5),W(1,5))
      CALL VXXXXX(P(0,6),ZERO,NHEL(6),+1*IC(6),W(1,6))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_6,ZERO,ZERO,W(1,7))
      CALL FFS2_4_1(W(1,3),W(1,5),GC_739,GC_738,MDL_MT,MDL_WT,W(1,8))
      CALL FFV6_2(W(1,4),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV6_0(W(1,9),W(1,8),W(1,6),GC_7,AMP(1))
      CALL VVV1P0_1(W(1,7),W(1,6),GC_6,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV6_0(W(1,4),W(1,8),W(1,10),GC_7,AMP(2))
      CALL FFS4_1(W(1,3),W(1,5),GC_954,MDL_MT,MDL_WT,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL FFVV2_4_0(W(1,4),W(1,11),W(1,7),W(1,6),GC_728,GC_727,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV6_0(W(1,9),W(1,11),W(1,6),GC_7,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV11_9_0(W(1,9),W(1,11),W(1,6),GC_725,GC_726,AMP(5))
      CALL FFV11_9_2(W(1,4),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 6
      CALL FFV6_0(W(1,12),W(1,11),W(1,6),GC_7,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL FFV6_0(W(1,4),W(1,11),W(1,10),GC_7,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV11_9_0(W(1,4),W(1,11),W(1,10),GC_725,GC_726,AMP(8))
      CALL FFV6_2(W(1,4),W(1,6),GC_7,MDL_MT,MDL_WT,W(1,13))
C     Amplitude(s) for diagram number 9
      CALL FFV6_0(W(1,13),W(1,8),W(1,7),GC_7,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV6_0(W(1,13),W(1,11),W(1,7),GC_7,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL FFV11_9_0(W(1,13),W(1,11),W(1,7),GC_725,GC_726,AMP(11))
      CALL FFV11_9_2(W(1,4),W(1,6),GC_725,GC_726,MDL_MT,MDL_WT,W(1,14))
C     Amplitude(s) for diagram number 12
      CALL FFV6_0(W(1,14),W(1,11),W(1,7),GC_7,AMP(12))
      CALL FFV6_1(W(1,3),W(1,6),GC_7,MDL_MT,MDL_WT,W(1,15))
C     Amplitude(s) for diagram number 13
      CALL FFVS4_6_0(W(1,4),W(1,15),W(1,7),W(1,5),GC_599,GC_598,AMP(13)
     $ )
C     Amplitude(s) for diagram number 14
      CALL FFS2_4_0(W(1,9),W(1,15),W(1,5),GC_739,GC_738,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL FFS4_0(W(1,9),W(1,15),W(1,5),GC_954,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFS4_0(W(1,12),W(1,15),W(1,5),GC_954,AMP(16))
      CALL FFV11_9_1(W(1,3),W(1,6),GC_725,GC_726,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 17
      CALL FFS4_0(W(1,9),W(1,12),W(1,5),GC_954,AMP(17))
      CALL FFS2_4_2(W(1,4),W(1,5),GC_739,GC_738,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 18
      CALL FFV6_0(W(1,9),W(1,15),W(1,7),GC_7,AMP(18))
      CALL FFS4_2(W(1,4),W(1,5),GC_954,MDL_MT,MDL_WT,W(1,16))
C     Amplitude(s) for diagram number 19
      CALL FFV6_0(W(1,16),W(1,15),W(1,7),GC_7,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV11_9_0(W(1,16),W(1,15),W(1,7),GC_725,GC_726,AMP(20))
C     Amplitude(s) for diagram number 21
      CALL FFV6_0(W(1,16),W(1,12),W(1,7),GC_7,AMP(21))
      CALL FFV6_1(W(1,3),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 22
      CALL FFV6_0(W(1,9),W(1,17),W(1,6),GC_7,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV6_0(W(1,9),W(1,3),W(1,10),GC_7,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFVV2_4_0(W(1,16),W(1,3),W(1,7),W(1,6),GC_728,GC_727,AMP(24)
     $ )
C     Amplitude(s) for diagram number 25
      CALL FFV6_0(W(1,16),W(1,17),W(1,6),GC_7,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV11_9_0(W(1,16),W(1,17),W(1,6),GC_725,GC_726,AMP(26))
      CALL FFV11_9_1(W(1,3),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 27
      CALL FFV6_0(W(1,16),W(1,18),W(1,6),GC_7,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFV6_0(W(1,16),W(1,3),W(1,10),GC_7,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV11_9_0(W(1,16),W(1,3),W(1,10),GC_725,GC_726,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL FFVS4_6_0(W(1,13),W(1,3),W(1,7),W(1,5),GC_599,GC_598,AMP(30)
     $ )
C     Amplitude(s) for diagram number 31
      CALL FFS2_4_0(W(1,13),W(1,17),W(1,5),GC_739,GC_738,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFS4_0(W(1,13),W(1,17),W(1,5),GC_954,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFS4_0(W(1,13),W(1,18),W(1,5),GC_954,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFS4_0(W(1,14),W(1,17),W(1,5),GC_954,AMP(34))
      CALL FFVS4_6P0_3(W(1,4),W(1,3),W(1,5),GC_599,GC_598,ZERO,ZERO
     $ ,W(1,17))
C     Amplitude(s) for diagram number 35
      CALL VVV1_0(W(1,7),W(1,17),W(1,6),GC_6,AMP(35))
      CALL FFVS4_6_1(W(1,3),W(1,6),W(1,5),GC_599,GC_598,MDL_MT,MDL_WT
     $ ,W(1,18))
C     Amplitude(s) for diagram number 36
      CALL FFV6_0(W(1,4),W(1,18),W(1,7),GC_7,AMP(36))
      CALL FFVS4_6_2(W(1,4),W(1,6),W(1,5),GC_599,GC_598,MDL_MT,MDL_WT
     $ ,W(1,10))
C     Amplitude(s) for diagram number 37
      CALL FFV6_0(W(1,10),W(1,3),W(1,7),GC_7,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFVVS2_4_0(W(1,4),W(1,3),W(1,6),W(1,7),W(1,5),GC_601,GC_600
     $ ,AMP(38))
      CALL FFV6_1(W(1,3),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,7))
      CALL FFV6_2(W(1,4),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,19))
C     Amplitude(s) for diagram number 39
      CALL FFVS4_6_0(W(1,19),W(1,7),W(1,6),W(1,5),GC_599,GC_598,AMP(39)
     $ )
      CALL FFS2_4_1(W(1,7),W(1,5),GC_739,GC_738,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 40
      CALL FFV6_0(W(1,19),W(1,20),W(1,6),GC_7,AMP(40))
      CALL FFS4_1(W(1,7),W(1,5),GC_954,MDL_MT,MDL_WT,W(1,21))
C     Amplitude(s) for diagram number 41
      CALL FFV6_0(W(1,19),W(1,21),W(1,6),GC_7,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV11_9_0(W(1,19),W(1,21),W(1,6),GC_725,GC_726,AMP(42))
      CALL FFV6_1(W(1,7),W(1,6),GC_7,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 43
      CALL FFS2_4_0(W(1,19),W(1,22),W(1,5),GC_739,GC_738,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFS4_0(W(1,19),W(1,22),W(1,5),GC_954,AMP(44))
      CALL FFV11_9_1(W(1,7),W(1,6),GC_725,GC_726,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 45
      CALL FFS4_0(W(1,19),W(1,23),W(1,5),GC_954,AMP(45))
      CALL FFV11_9_2(W(1,4),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,24))
C     Amplitude(s) for diagram number 46
      CALL FFV6_0(W(1,24),W(1,21),W(1,6),GC_7,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFS4_0(W(1,24),W(1,22),W(1,5),GC_954,AMP(47))
      CALL FFV11_9_1(W(1,3),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,25))
      CALL FFS4_1(W(1,25),W(1,5),GC_954,MDL_MT,MDL_WT,W(1,26))
C     Amplitude(s) for diagram number 48
      CALL FFV6_0(W(1,19),W(1,26),W(1,6),GC_7,AMP(48))
      CALL FFV6_1(W(1,25),W(1,6),GC_7,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 49
      CALL FFS4_0(W(1,19),W(1,27),W(1,5),GC_954,AMP(49))
      CALL VVV1P0_1(W(1,2),W(1,6),GC_6,ZERO,ZERO,W(1,28))
C     Amplitude(s) for diagram number 50
      CALL FFVS4_6_0(W(1,4),W(1,7),W(1,28),W(1,5),GC_599,GC_598,AMP(50)
     $ )
C     Amplitude(s) for diagram number 51
      CALL FFV6_0(W(1,4),W(1,20),W(1,28),GC_7,AMP(51))
C     Amplitude(s) for diagram number 52
      CALL FFV6_0(W(1,4),W(1,21),W(1,28),GC_7,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFV11_9_0(W(1,4),W(1,21),W(1,28),GC_725,GC_726,AMP(53))
C     Amplitude(s) for diagram number 54
      CALL FFV6_0(W(1,4),W(1,26),W(1,28),GC_7,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV6_0(W(1,9),W(1,7),W(1,28),GC_7,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV6_0(W(1,16),W(1,7),W(1,28),GC_7,AMP(56))
C     Amplitude(s) for diagram number 57
      CALL FFV11_9_0(W(1,16),W(1,7),W(1,28),GC_725,GC_726,AMP(57))
C     Amplitude(s) for diagram number 58
      CALL FFV6_0(W(1,16),W(1,25),W(1,28),GC_7,AMP(58))
      CALL FFV6_1(W(1,7),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 59
      CALL FFV6_0(W(1,9),W(1,29),W(1,6),GC_7,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFV6_0(W(1,9),W(1,22),W(1,2),GC_7,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFVV2_4_0(W(1,16),W(1,7),W(1,2),W(1,6),GC_728,GC_727,AMP(61)
     $ )
C     Amplitude(s) for diagram number 62
      CALL FFV6_0(W(1,16),W(1,29),W(1,6),GC_7,AMP(62))
C     Amplitude(s) for diagram number 63
      CALL FFV11_9_0(W(1,16),W(1,29),W(1,6),GC_725,GC_726,AMP(63))
      CALL FFV11_9_1(W(1,7),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 64
      CALL FFV6_0(W(1,16),W(1,30),W(1,6),GC_7,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL FFV6_0(W(1,16),W(1,22),W(1,2),GC_7,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL FFV11_9_0(W(1,16),W(1,22),W(1,2),GC_725,GC_726,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL FFV6_0(W(1,16),W(1,23),W(1,2),GC_7,AMP(67))
      CALL FFV6_1(W(1,25),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 68
      CALL FFV6_0(W(1,16),W(1,23),W(1,6),GC_7,AMP(68))
C     Amplitude(s) for diagram number 69
      CALL FFV6_0(W(1,16),W(1,27),W(1,2),GC_7,AMP(69))
C     Amplitude(s) for diagram number 70
      CALL FFVS4_6_0(W(1,13),W(1,7),W(1,2),W(1,5),GC_599,GC_598,AMP(70)
     $ )
C     Amplitude(s) for diagram number 71
      CALL FFS2_4_0(W(1,13),W(1,29),W(1,5),GC_739,GC_738,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL FFS4_0(W(1,13),W(1,29),W(1,5),GC_954,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL FFS4_0(W(1,13),W(1,30),W(1,5),GC_954,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL FFV6_0(W(1,13),W(1,20),W(1,2),GC_7,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV6_0(W(1,13),W(1,21),W(1,2),GC_7,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL FFV11_9_0(W(1,13),W(1,21),W(1,2),GC_725,GC_726,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL FFS4_0(W(1,14),W(1,29),W(1,5),GC_954,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL FFV6_0(W(1,14),W(1,21),W(1,2),GC_7,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFS4_0(W(1,13),W(1,23),W(1,5),GC_954,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV6_0(W(1,13),W(1,26),W(1,2),GC_7,AMP(80))
      CALL FFVS4_6_2(W(1,4),W(1,2),W(1,5),GC_599,GC_598,MDL_MT,MDL_WT
     $ ,W(1,26))
C     Amplitude(s) for diagram number 81
      CALL FFV6_0(W(1,26),W(1,7),W(1,6),GC_7,AMP(81))
      CALL FFVV2_4_2(W(1,4),W(1,2),W(1,6),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,23))
C     Amplitude(s) for diagram number 82
      CALL FFS4_0(W(1,23),W(1,7),W(1,5),GC_954,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFV6_0(W(1,10),W(1,7),W(1,2),GC_7,AMP(83))
C     Amplitude(s) for diagram number 84
      CALL FFVVS2_4_0(W(1,4),W(1,7),W(1,2),W(1,6),W(1,5),GC_601,GC_600
     $ ,AMP(84))
      CALL FFV6_2(W(1,4),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,7))
      CALL FFV6_1(W(1,3),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,21))
C     Amplitude(s) for diagram number 85
      CALL FFVS4_6_0(W(1,7),W(1,21),W(1,6),W(1,5),GC_599,GC_598,AMP(85)
     $ )
      CALL FFS2_4_2(W(1,7),W(1,5),GC_739,GC_738,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 86
      CALL FFV6_0(W(1,29),W(1,21),W(1,6),GC_7,AMP(86))
      CALL FFS4_2(W(1,7),W(1,5),GC_954,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 87
      CALL FFV6_0(W(1,20),W(1,21),W(1,6),GC_7,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV11_9_0(W(1,20),W(1,21),W(1,6),GC_725,GC_726,AMP(88))
      CALL FFV6_2(W(1,7),W(1,6),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 89
      CALL FFS2_4_0(W(1,30),W(1,21),W(1,5),GC_739,GC_738,AMP(89))
C     Amplitude(s) for diagram number 90
      CALL FFS4_0(W(1,30),W(1,21),W(1,5),GC_954,AMP(90))
      CALL FFV11_9_2(W(1,7),W(1,6),GC_725,GC_726,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 91
      CALL FFS4_0(W(1,27),W(1,21),W(1,5),GC_954,AMP(91))
      CALL FFV11_9_1(W(1,3),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 92
      CALL FFV6_0(W(1,20),W(1,25),W(1,6),GC_7,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL FFS4_0(W(1,30),W(1,25),W(1,5),GC_954,AMP(93))
      CALL FFV11_9_2(W(1,4),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,22))
      CALL FFS4_2(W(1,22),W(1,5),GC_954,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 94
      CALL FFV6_0(W(1,31),W(1,21),W(1,6),GC_7,AMP(94))
      CALL FFV6_2(W(1,22),W(1,6),GC_7,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 95
      CALL FFS4_0(W(1,32),W(1,21),W(1,5),GC_954,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL FFVS4_6_0(W(1,7),W(1,3),W(1,28),W(1,5),GC_599,GC_598,AMP(96)
     $ )
C     Amplitude(s) for diagram number 97
      CALL FFV6_0(W(1,29),W(1,3),W(1,28),GC_7,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV6_0(W(1,20),W(1,3),W(1,28),GC_7,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL FFV11_9_0(W(1,20),W(1,3),W(1,28),GC_725,GC_726,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL FFV6_0(W(1,31),W(1,3),W(1,28),GC_7,AMP(100))
C     Amplitude(s) for diagram number 101
      CALL FFV6_0(W(1,7),W(1,8),W(1,28),GC_7,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL FFV6_0(W(1,7),W(1,11),W(1,28),GC_7,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL FFV11_9_0(W(1,7),W(1,11),W(1,28),GC_725,GC_726,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFV6_0(W(1,22),W(1,11),W(1,28),GC_7,AMP(104))
      CALL FFV6_2(W(1,7),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,33))
C     Amplitude(s) for diagram number 105
      CALL FFV6_0(W(1,33),W(1,8),W(1,6),GC_7,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV6_0(W(1,30),W(1,8),W(1,2),GC_7,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFVV2_4_0(W(1,7),W(1,11),W(1,2),W(1,6),GC_728,GC_727
     $ ,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV6_0(W(1,33),W(1,11),W(1,6),GC_7,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV11_9_0(W(1,33),W(1,11),W(1,6),GC_725,GC_726,AMP(109))
      CALL FFV11_9_2(W(1,7),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,34))
C     Amplitude(s) for diagram number 110
      CALL FFV6_0(W(1,34),W(1,11),W(1,6),GC_7,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV6_0(W(1,30),W(1,11),W(1,2),GC_7,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV11_9_0(W(1,30),W(1,11),W(1,2),GC_725,GC_726,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV6_0(W(1,27),W(1,11),W(1,2),GC_7,AMP(113))
      CALL FFV6_2(W(1,22),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 114
      CALL FFV6_0(W(1,27),W(1,11),W(1,6),GC_7,AMP(114))
C     Amplitude(s) for diagram number 115
      CALL FFV6_0(W(1,32),W(1,11),W(1,2),GC_7,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFVS4_6_0(W(1,7),W(1,15),W(1,2),W(1,5),GC_599,GC_598
     $ ,AMP(116))
C     Amplitude(s) for diagram number 117
      CALL FFS2_4_0(W(1,33),W(1,15),W(1,5),GC_739,GC_738,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL FFS4_0(W(1,33),W(1,15),W(1,5),GC_954,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFS4_0(W(1,34),W(1,15),W(1,5),GC_954,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL FFV6_0(W(1,29),W(1,15),W(1,2),GC_7,AMP(120))
C     Amplitude(s) for diagram number 121
      CALL FFV6_0(W(1,20),W(1,15),W(1,2),GC_7,AMP(121))
C     Amplitude(s) for diagram number 122
      CALL FFV11_9_0(W(1,20),W(1,15),W(1,2),GC_725,GC_726,AMP(122))
C     Amplitude(s) for diagram number 123
      CALL FFS4_0(W(1,33),W(1,12),W(1,5),GC_954,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL FFV6_0(W(1,20),W(1,12),W(1,2),GC_7,AMP(124))
C     Amplitude(s) for diagram number 125
      CALL FFS4_0(W(1,27),W(1,15),W(1,5),GC_954,AMP(125))
C     Amplitude(s) for diagram number 126
      CALL FFV6_0(W(1,31),W(1,15),W(1,2),GC_7,AMP(126))
      CALL FFVS4_6_1(W(1,3),W(1,2),W(1,5),GC_599,GC_598,MDL_MT,MDL_WT
     $ ,W(1,31))
C     Amplitude(s) for diagram number 127
      CALL FFV6_0(W(1,7),W(1,31),W(1,6),GC_7,AMP(127))
      CALL FFVV2_4_1(W(1,3),W(1,2),W(1,6),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,27))
C     Amplitude(s) for diagram number 128
      CALL FFS4_0(W(1,7),W(1,27),W(1,5),GC_954,AMP(128))
C     Amplitude(s) for diagram number 129
      CALL FFV6_0(W(1,7),W(1,18),W(1,2),GC_7,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFVVS2_4_0(W(1,7),W(1,3),W(1,2),W(1,6),W(1,5),GC_601,GC_600
     $ ,AMP(130))
      CALL VVV1P0_1(W(1,1),W(1,6),GC_6,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 131
      CALL FFVS4_6_0(W(1,4),W(1,21),W(1,7),W(1,5),GC_599,GC_598
     $ ,AMP(131))
      CALL FFV6_2(W(1,4),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 132
      CALL FFS2_4_0(W(1,20),W(1,21),W(1,5),GC_739,GC_738,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL FFS4_0(W(1,20),W(1,21),W(1,5),GC_954,AMP(133))
      CALL FFV11_9_2(W(1,4),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,33))
C     Amplitude(s) for diagram number 134
      CALL FFS4_0(W(1,33),W(1,21),W(1,5),GC_954,AMP(134))
C     Amplitude(s) for diagram number 135
      CALL FFS4_0(W(1,20),W(1,25),W(1,5),GC_954,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL FFV6_0(W(1,9),W(1,21),W(1,7),GC_7,AMP(136))
C     Amplitude(s) for diagram number 137
      CALL FFV6_0(W(1,16),W(1,21),W(1,7),GC_7,AMP(137))
C     Amplitude(s) for diagram number 138
      CALL FFV11_9_0(W(1,16),W(1,21),W(1,7),GC_725,GC_726,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL FFV6_0(W(1,16),W(1,25),W(1,7),GC_7,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL FFVS4_6_0(W(1,19),W(1,3),W(1,7),W(1,5),GC_599,GC_598
     $ ,AMP(140))
      CALL FFV6_1(W(1,3),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 141
      CALL FFS2_4_0(W(1,19),W(1,29),W(1,5),GC_739,GC_738,AMP(141))
C     Amplitude(s) for diagram number 142
      CALL FFS4_0(W(1,19),W(1,29),W(1,5),GC_954,AMP(142))
      CALL FFV11_9_1(W(1,3),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,34))
C     Amplitude(s) for diagram number 143
      CALL FFS4_0(W(1,19),W(1,34),W(1,5),GC_954,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL FFS4_0(W(1,24),W(1,29),W(1,5),GC_954,AMP(144))
C     Amplitude(s) for diagram number 145
      CALL FFV6_0(W(1,19),W(1,8),W(1,7),GC_7,AMP(145))
C     Amplitude(s) for diagram number 146
      CALL FFV6_0(W(1,19),W(1,11),W(1,7),GC_7,AMP(146))
C     Amplitude(s) for diagram number 147
      CALL FFV11_9_0(W(1,19),W(1,11),W(1,7),GC_725,GC_726,AMP(147))
C     Amplitude(s) for diagram number 148
      CALL FFV6_0(W(1,24),W(1,11),W(1,7),GC_7,AMP(148))
      CALL VVV1P0_1(W(1,7),W(1,2),GC_6,ZERO,ZERO,W(1,32))
C     Amplitude(s) for diagram number 149
      CALL FFV6_0(W(1,4),W(1,8),W(1,32),GC_7,AMP(149))
C     Amplitude(s) for diagram number 150
      CALL FFV6_0(W(1,20),W(1,8),W(1,2),GC_7,AMP(150))
C     Amplitude(s) for diagram number 151
      CALL FFVV2_4_0(W(1,4),W(1,11),W(1,7),W(1,2),GC_728,GC_727
     $ ,AMP(151))
C     Amplitude(s) for diagram number 152
      CALL FFV6_0(W(1,4),W(1,11),W(1,32),GC_7,AMP(152))
C     Amplitude(s) for diagram number 153
      CALL FFV11_9_0(W(1,4),W(1,11),W(1,32),GC_725,GC_726,AMP(153))
C     Amplitude(s) for diagram number 154
      CALL FFV6_0(W(1,20),W(1,11),W(1,2),GC_7,AMP(154))
C     Amplitude(s) for diagram number 155
      CALL FFV11_9_0(W(1,20),W(1,11),W(1,2),GC_725,GC_726,AMP(155))
C     Amplitude(s) for diagram number 156
      CALL FFV6_0(W(1,33),W(1,11),W(1,2),GC_7,AMP(156))
C     Amplitude(s) for diagram number 157
      CALL FFV6_0(W(1,9),W(1,3),W(1,32),GC_7,AMP(157))
C     Amplitude(s) for diagram number 158
      CALL FFV6_0(W(1,9),W(1,29),W(1,2),GC_7,AMP(158))
C     Amplitude(s) for diagram number 159
      CALL FFVV2_4_0(W(1,16),W(1,3),W(1,7),W(1,2),GC_728,GC_727
     $ ,AMP(159))
C     Amplitude(s) for diagram number 160
      CALL FFV6_0(W(1,16),W(1,3),W(1,32),GC_7,AMP(160))
C     Amplitude(s) for diagram number 161
      CALL FFV11_9_0(W(1,16),W(1,3),W(1,32),GC_725,GC_726,AMP(161))
C     Amplitude(s) for diagram number 162
      CALL FFV6_0(W(1,16),W(1,29),W(1,2),GC_7,AMP(162))
C     Amplitude(s) for diagram number 163
      CALL FFV11_9_0(W(1,16),W(1,29),W(1,2),GC_725,GC_726,AMP(163))
C     Amplitude(s) for diagram number 164
      CALL FFV6_0(W(1,16),W(1,34),W(1,2),GC_7,AMP(164))
C     Amplitude(s) for diagram number 165
      CALL FFV6_0(W(1,4),W(1,31),W(1,7),GC_7,AMP(165))
C     Amplitude(s) for diagram number 166
      CALL FFV6_0(W(1,26),W(1,3),W(1,7),GC_7,AMP(166))
C     Amplitude(s) for diagram number 167
      CALL VVV1_0(W(1,7),W(1,2),W(1,17),GC_6,AMP(167))
C     Amplitude(s) for diagram number 168
      CALL FFVVS2_4_0(W(1,4),W(1,3),W(1,2),W(1,7),W(1,5),GC_601,GC_600
     $ ,AMP(168))
      CALL FFV6_1(W(1,21),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,7))
C     Amplitude(s) for diagram number 169
      CALL FFV6_0(W(1,9),W(1,7),W(1,6),GC_7,AMP(169))
      CALL FFV6_2(W(1,9),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,34))
C     Amplitude(s) for diagram number 170
      CALL FFV6_0(W(1,34),W(1,21),W(1,6),GC_7,AMP(170))
C     Amplitude(s) for diagram number 171
      CALL FFVV2_4_0(W(1,16),W(1,21),W(1,1),W(1,6),GC_728,GC_727
     $ ,AMP(171))
C     Amplitude(s) for diagram number 172
      CALL FFV6_0(W(1,16),W(1,7),W(1,6),GC_7,AMP(172))
C     Amplitude(s) for diagram number 173
      CALL FFV11_9_0(W(1,16),W(1,7),W(1,6),GC_725,GC_726,AMP(173))
      CALL FFV11_9_1(W(1,21),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,29)
     $ )
C     Amplitude(s) for diagram number 174
      CALL FFV6_0(W(1,16),W(1,29),W(1,6),GC_7,AMP(174))
      CALL FFV6_2(W(1,16),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 175
      CALL FFV6_0(W(1,32),W(1,21),W(1,6),GC_7,AMP(175))
C     Amplitude(s) for diagram number 176
      CALL FFV11_9_0(W(1,32),W(1,21),W(1,6),GC_725,GC_726,AMP(176))
      CALL FFV11_9_2(W(1,16),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,33)
     $ )
C     Amplitude(s) for diagram number 177
      CALL FFV6_0(W(1,33),W(1,21),W(1,6),GC_7,AMP(177))
      CALL FFV6_1(W(1,25),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 178
      CALL FFV6_0(W(1,16),W(1,20),W(1,6),GC_7,AMP(178))
C     Amplitude(s) for diagram number 179
      CALL FFV6_0(W(1,32),W(1,25),W(1,6),GC_7,AMP(179))
C     Amplitude(s) for diagram number 180
      CALL FFVS4_6_0(W(1,13),W(1,21),W(1,1),W(1,5),GC_599,GC_598
     $ ,AMP(180))
C     Amplitude(s) for diagram number 181
      CALL FFS2_4_0(W(1,13),W(1,7),W(1,5),GC_739,GC_738,AMP(181))
C     Amplitude(s) for diagram number 182
      CALL FFS4_0(W(1,13),W(1,7),W(1,5),GC_954,AMP(182))
C     Amplitude(s) for diagram number 183
      CALL FFS4_0(W(1,13),W(1,29),W(1,5),GC_954,AMP(183))
      CALL FFV6_2(W(1,13),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 184
      CALL FFS2_4_0(W(1,29),W(1,21),W(1,5),GC_739,GC_738,AMP(184))
C     Amplitude(s) for diagram number 185
      CALL FFS4_0(W(1,29),W(1,21),W(1,5),GC_954,AMP(185))
      CALL FFV11_9_2(W(1,13),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,22)
     $ )
C     Amplitude(s) for diagram number 186
      CALL FFS4_0(W(1,22),W(1,21),W(1,5),GC_954,AMP(186))
C     Amplitude(s) for diagram number 187
      CALL FFS4_0(W(1,14),W(1,7),W(1,5),GC_954,AMP(187))
      CALL FFV6_2(W(1,14),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,7))
C     Amplitude(s) for diagram number 188
      CALL FFS4_0(W(1,7),W(1,21),W(1,5),GC_954,AMP(188))
C     Amplitude(s) for diagram number 189
      CALL FFS4_0(W(1,13),W(1,20),W(1,5),GC_954,AMP(189))
C     Amplitude(s) for diagram number 190
      CALL FFS4_0(W(1,29),W(1,25),W(1,5),GC_954,AMP(190))
C     Amplitude(s) for diagram number 191
      CALL FFV6_0(W(1,10),W(1,21),W(1,1),GC_7,AMP(191))
      CALL FFV6_2(W(1,19),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 192
      CALL FFV6_0(W(1,10),W(1,8),W(1,6),GC_7,AMP(192))
      CALL FFV6_1(W(1,8),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 193
      CALL FFV6_0(W(1,19),W(1,25),W(1,6),GC_7,AMP(193))
C     Amplitude(s) for diagram number 194
      CALL FFVV2_4_0(W(1,19),W(1,11),W(1,1),W(1,6),GC_728,GC_727
     $ ,AMP(194))
C     Amplitude(s) for diagram number 195
      CALL FFV6_0(W(1,10),W(1,11),W(1,6),GC_7,AMP(195))
C     Amplitude(s) for diagram number 196
      CALL FFV11_9_0(W(1,10),W(1,11),W(1,6),GC_725,GC_726,AMP(196))
      CALL FFV11_9_2(W(1,19),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,20)
     $ )
C     Amplitude(s) for diagram number 197
      CALL FFV6_0(W(1,20),W(1,11),W(1,6),GC_7,AMP(197))
      CALL FFV6_1(W(1,11),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 198
      CALL FFV6_0(W(1,19),W(1,30),W(1,6),GC_7,AMP(198))
C     Amplitude(s) for diagram number 199
      CALL FFV11_9_0(W(1,19),W(1,30),W(1,6),GC_725,GC_726,AMP(199))
      CALL FFV11_9_1(W(1,11),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,35)
     $ )
C     Amplitude(s) for diagram number 200
      CALL FFV6_0(W(1,19),W(1,35),W(1,6),GC_7,AMP(200))
      CALL FFV6_2(W(1,24),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,36))
C     Amplitude(s) for diagram number 201
      CALL FFV6_0(W(1,36),W(1,11),W(1,6),GC_7,AMP(201))
C     Amplitude(s) for diagram number 202
      CALL FFV6_0(W(1,24),W(1,30),W(1,6),GC_7,AMP(202))
C     Amplitude(s) for diagram number 203
      CALL FFVS4_6_0(W(1,19),W(1,15),W(1,1),W(1,5),GC_599,GC_598
     $ ,AMP(203))
C     Amplitude(s) for diagram number 204
      CALL FFS2_4_0(W(1,10),W(1,15),W(1,5),GC_739,GC_738,AMP(204))
C     Amplitude(s) for diagram number 205
      CALL FFS4_0(W(1,10),W(1,15),W(1,5),GC_954,AMP(205))
C     Amplitude(s) for diagram number 206
      CALL FFS4_0(W(1,20),W(1,15),W(1,5),GC_954,AMP(206))
      CALL FFV6_1(W(1,15),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,20))
C     Amplitude(s) for diagram number 207
      CALL FFS2_4_0(W(1,19),W(1,20),W(1,5),GC_739,GC_738,AMP(207))
C     Amplitude(s) for diagram number 208
      CALL FFS4_0(W(1,19),W(1,20),W(1,5),GC_954,AMP(208))
      CALL FFV11_9_1(W(1,15),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,37)
     $ )
C     Amplitude(s) for diagram number 209
      CALL FFS4_0(W(1,19),W(1,37),W(1,5),GC_954,AMP(209))
C     Amplitude(s) for diagram number 210
      CALL FFS4_0(W(1,10),W(1,12),W(1,5),GC_954,AMP(210))
      CALL FFV6_1(W(1,12),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 211
      CALL FFS4_0(W(1,19),W(1,10),W(1,5),GC_954,AMP(211))
C     Amplitude(s) for diagram number 212
      CALL FFS4_0(W(1,36),W(1,15),W(1,5),GC_954,AMP(212))
C     Amplitude(s) for diagram number 213
      CALL FFS4_0(W(1,24),W(1,20),W(1,5),GC_954,AMP(213))
C     Amplitude(s) for diagram number 214
      CALL FFV6_0(W(1,19),W(1,18),W(1,1),GC_7,AMP(214))
      CALL VVV1P0_1(W(1,1),W(1,28),GC_6,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 215
      CALL FFV6_0(W(1,4),W(1,8),W(1,18),GC_7,AMP(215))
C     Amplitude(s) for diagram number 216
      CALL FFV6_0(W(1,4),W(1,25),W(1,28),GC_7,AMP(216))
C     Amplitude(s) for diagram number 217
      CALL FFVV2_4_0(W(1,4),W(1,11),W(1,1),W(1,28),GC_728,GC_727
     $ ,AMP(217))
C     Amplitude(s) for diagram number 218
      CALL FFV6_0(W(1,4),W(1,11),W(1,18),GC_7,AMP(218))
C     Amplitude(s) for diagram number 219
      CALL FFV11_9_0(W(1,4),W(1,11),W(1,18),GC_725,GC_726,AMP(219))
C     Amplitude(s) for diagram number 220
      CALL FFV6_0(W(1,4),W(1,30),W(1,28),GC_7,AMP(220))
C     Amplitude(s) for diagram number 221
      CALL FFV11_9_0(W(1,4),W(1,30),W(1,28),GC_725,GC_726,AMP(221))
C     Amplitude(s) for diagram number 222
      CALL FFV6_0(W(1,4),W(1,35),W(1,28),GC_7,AMP(222))
C     Amplitude(s) for diagram number 223
      CALL FFV6_0(W(1,9),W(1,3),W(1,18),GC_7,AMP(223))
C     Amplitude(s) for diagram number 224
      CALL FFV6_0(W(1,34),W(1,3),W(1,28),GC_7,AMP(224))
C     Amplitude(s) for diagram number 225
      CALL FFVV2_4_0(W(1,16),W(1,3),W(1,1),W(1,28),GC_728,GC_727
     $ ,AMP(225))
C     Amplitude(s) for diagram number 226
      CALL FFV6_0(W(1,16),W(1,3),W(1,18),GC_7,AMP(226))
C     Amplitude(s) for diagram number 227
      CALL FFV11_9_0(W(1,16),W(1,3),W(1,18),GC_725,GC_726,AMP(227))
C     Amplitude(s) for diagram number 228
      CALL FFV6_0(W(1,32),W(1,3),W(1,28),GC_7,AMP(228))
C     Amplitude(s) for diagram number 229
      CALL FFV11_9_0(W(1,32),W(1,3),W(1,28),GC_725,GC_726,AMP(229))
C     Amplitude(s) for diagram number 230
      CALL FFV6_0(W(1,33),W(1,3),W(1,28),GC_7,AMP(230))
C     Amplitude(s) for diagram number 231
      CALL VVV1_0(W(1,1),W(1,28),W(1,17),GC_6,AMP(231))
C     Amplitude(s) for diagram number 232
      CALL FFV6_0(W(1,13),W(1,25),W(1,2),GC_7,AMP(232))
C     Amplitude(s) for diagram number 233
      CALL FFV6_0(W(1,29),W(1,8),W(1,2),GC_7,AMP(233))
C     Amplitude(s) for diagram number 234
      CALL FFVV2_4_0(W(1,13),W(1,11),W(1,1),W(1,2),GC_728,GC_727
     $ ,AMP(234))
C     Amplitude(s) for diagram number 235
      CALL FFV6_0(W(1,13),W(1,30),W(1,2),GC_7,AMP(235))
C     Amplitude(s) for diagram number 236
      CALL FFV11_9_0(W(1,13),W(1,30),W(1,2),GC_725,GC_726,AMP(236))
C     Amplitude(s) for diagram number 237
      CALL FFV6_0(W(1,13),W(1,35),W(1,2),GC_7,AMP(237))
C     Amplitude(s) for diagram number 238
      CALL FFV6_0(W(1,29),W(1,11),W(1,2),GC_7,AMP(238))
C     Amplitude(s) for diagram number 239
      CALL FFV11_9_0(W(1,29),W(1,11),W(1,2),GC_725,GC_726,AMP(239))
C     Amplitude(s) for diagram number 240
      CALL FFV6_0(W(1,22),W(1,11),W(1,2),GC_7,AMP(240))
C     Amplitude(s) for diagram number 241
      CALL FFV6_0(W(1,14),W(1,30),W(1,2),GC_7,AMP(241))
C     Amplitude(s) for diagram number 242
      CALL FFV6_0(W(1,7),W(1,11),W(1,2),GC_7,AMP(242))
C     Amplitude(s) for diagram number 243
      CALL FFV6_0(W(1,9),W(1,20),W(1,2),GC_7,AMP(243))
C     Amplitude(s) for diagram number 244
      CALL FFV6_0(W(1,34),W(1,15),W(1,2),GC_7,AMP(244))
C     Amplitude(s) for diagram number 245
      CALL FFVV2_4_0(W(1,16),W(1,15),W(1,1),W(1,2),GC_728,GC_727
     $ ,AMP(245))
C     Amplitude(s) for diagram number 246
      CALL FFV6_0(W(1,16),W(1,20),W(1,2),GC_7,AMP(246))
C     Amplitude(s) for diagram number 247
      CALL FFV11_9_0(W(1,16),W(1,20),W(1,2),GC_725,GC_726,AMP(247))
C     Amplitude(s) for diagram number 248
      CALL FFV6_0(W(1,16),W(1,37),W(1,2),GC_7,AMP(248))
C     Amplitude(s) for diagram number 249
      CALL FFV6_0(W(1,32),W(1,15),W(1,2),GC_7,AMP(249))
C     Amplitude(s) for diagram number 250
      CALL FFV11_9_0(W(1,32),W(1,15),W(1,2),GC_725,GC_726,AMP(250))
C     Amplitude(s) for diagram number 251
      CALL FFV6_0(W(1,33),W(1,15),W(1,2),GC_7,AMP(251))
C     Amplitude(s) for diagram number 252
      CALL FFV6_0(W(1,16),W(1,10),W(1,2),GC_7,AMP(252))
C     Amplitude(s) for diagram number 253
      CALL FFV6_0(W(1,32),W(1,12),W(1,2),GC_7,AMP(253))
      CALL FFVV2_4_1(W(1,3),W(1,1),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,32))
C     Amplitude(s) for diagram number 254
      CALL FFV6_0(W(1,16),W(1,32),W(1,6),GC_7,AMP(254))
C     Amplitude(s) for diagram number 255
      CALL FFS4_0(W(1,13),W(1,32),W(1,5),GC_954,AMP(255))
      CALL FFVV2_4_2(W(1,4),W(1,1),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,32))
C     Amplitude(s) for diagram number 256
      CALL FFV6_0(W(1,32),W(1,11),W(1,6),GC_7,AMP(256))
C     Amplitude(s) for diagram number 257
      CALL FFS4_0(W(1,32),W(1,15),W(1,5),GC_954,AMP(257))
      CALL VVVV1P0_1(W(1,1),W(1,2),W(1,6),GC_8,ZERO,ZERO,W(1,32))
      CALL VVVV3P0_1(W(1,1),W(1,2),W(1,6),GC_8,ZERO,ZERO,W(1,12))
      CALL VVVV4P0_1(W(1,1),W(1,2),W(1,6),GC_8,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 258
      CALL FFV6_0(W(1,4),W(1,8),W(1,32),GC_7,AMP(258))
      CALL FFV6_0(W(1,4),W(1,8),W(1,12),GC_7,AMP(259))
      CALL FFV6_0(W(1,4),W(1,8),W(1,10),GC_7,AMP(260))
C     Amplitude(s) for diagram number 259
      CALL FFV6_0(W(1,4),W(1,11),W(1,32),GC_7,AMP(261))
      CALL FFV6_0(W(1,4),W(1,11),W(1,12),GC_7,AMP(262))
      CALL FFV6_0(W(1,4),W(1,11),W(1,10),GC_7,AMP(263))
C     Amplitude(s) for diagram number 260
      CALL FFV11_9_0(W(1,4),W(1,11),W(1,32),GC_725,GC_726,AMP(264))
      CALL FFV11_9_0(W(1,4),W(1,11),W(1,12),GC_725,GC_726,AMP(265))
      CALL FFV11_9_0(W(1,4),W(1,11),W(1,10),GC_725,GC_726,AMP(266))
C     Amplitude(s) for diagram number 261
      CALL FFV6_0(W(1,9),W(1,3),W(1,32),GC_7,AMP(267))
      CALL FFV6_0(W(1,9),W(1,3),W(1,12),GC_7,AMP(268))
      CALL FFV6_0(W(1,9),W(1,3),W(1,10),GC_7,AMP(269))
C     Amplitude(s) for diagram number 262
      CALL FFV6_0(W(1,16),W(1,3),W(1,32),GC_7,AMP(270))
      CALL FFV6_0(W(1,16),W(1,3),W(1,12),GC_7,AMP(271))
      CALL FFV6_0(W(1,16),W(1,3),W(1,10),GC_7,AMP(272))
C     Amplitude(s) for diagram number 263
      CALL FFV11_9_0(W(1,16),W(1,3),W(1,32),GC_725,GC_726,AMP(273))
      CALL FFV11_9_0(W(1,16),W(1,3),W(1,12),GC_725,GC_726,AMP(274))
      CALL FFV11_9_0(W(1,16),W(1,3),W(1,10),GC_725,GC_726,AMP(275))
C     Amplitude(s) for diagram number 264
      CALL FFVS4_6_0(W(1,4),W(1,3),W(1,32),W(1,5),GC_599,GC_598
     $ ,AMP(276))
      CALL FFVS4_6_0(W(1,4),W(1,3),W(1,12),W(1,5),GC_599,GC_598
     $ ,AMP(277))
      CALL FFVS4_6_0(W(1,4),W(1,3),W(1,10),W(1,5),GC_599,GC_598
     $ ,AMP(278))
      CALL FFVS4_6_1(W(1,3),W(1,1),W(1,5),GC_599,GC_598,MDL_MT,MDL_WT
     $ ,W(1,10))
C     Amplitude(s) for diagram number 265
      CALL FFV6_0(W(1,19),W(1,10),W(1,6),GC_7,AMP(279))
C     Amplitude(s) for diagram number 266
      CALL FFV6_0(W(1,4),W(1,10),W(1,28),GC_7,AMP(280))
C     Amplitude(s) for diagram number 267
      CALL FFV6_0(W(1,13),W(1,10),W(1,2),GC_7,AMP(281))
      CALL FFVV2_4_1(W(1,3),W(1,1),W(1,6),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,10))
C     Amplitude(s) for diagram number 268
      CALL FFS4_0(W(1,19),W(1,10),W(1,5),GC_954,AMP(282))
C     Amplitude(s) for diagram number 269
      CALL FFV6_0(W(1,16),W(1,10),W(1,2),GC_7,AMP(283))
      CALL FFVS4_6_2(W(1,4),W(1,1),W(1,5),GC_599,GC_598,MDL_MT,MDL_WT
     $ ,W(1,10))
C     Amplitude(s) for diagram number 270
      CALL FFV6_0(W(1,10),W(1,21),W(1,6),GC_7,AMP(284))
C     Amplitude(s) for diagram number 271
      CALL FFV6_0(W(1,10),W(1,3),W(1,28),GC_7,AMP(285))
C     Amplitude(s) for diagram number 272
      CALL FFV6_0(W(1,10),W(1,15),W(1,2),GC_7,AMP(286))
      CALL FFVV2_4_2(W(1,4),W(1,1),W(1,6),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,10))
C     Amplitude(s) for diagram number 273
      CALL FFS4_0(W(1,10),W(1,21),W(1,5),GC_954,AMP(287))
C     Amplitude(s) for diagram number 274
      CALL FFV6_0(W(1,10),W(1,11),W(1,2),GC_7,AMP(288))
C     Amplitude(s) for diagram number 275
      CALL FFV6_0(W(1,13),W(1,31),W(1,1),GC_7,AMP(289))
C     Amplitude(s) for diagram number 276
      CALL FFV6_0(W(1,16),W(1,27),W(1,1),GC_7,AMP(290))
C     Amplitude(s) for diagram number 277
      CALL FFV6_0(W(1,26),W(1,15),W(1,1),GC_7,AMP(291))
C     Amplitude(s) for diagram number 278
      CALL FFV6_0(W(1,23),W(1,11),W(1,1),GC_7,AMP(292))
      CALL FFVVS2_4_1(W(1,3),W(1,1),W(1,2),W(1,5),GC_601,GC_600,MDL_MT
     $ ,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 279
      CALL FFV6_0(W(1,4),W(1,23),W(1,6),GC_7,AMP(293))
      CALL FFVVS2_4_2(W(1,4),W(1,1),W(1,2),W(1,5),GC_601,GC_600,MDL_MT
     $ ,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 280
      CALL FFV6_0(W(1,23),W(1,3),W(1,6),GC_7,AMP(294))
      CALL FFVVS2_4P0_3(W(1,4),W(1,3),W(1,1),W(1,5),GC_601,GC_600,ZERO
     $ ,ZERO,W(1,23))
C     Amplitude(s) for diagram number 281
      CALL VVV1_0(W(1,2),W(1,6),W(1,23),GC_6,AMP(295))
      CALL FFVVS2_4_1(W(1,3),W(1,1),W(1,6),W(1,5),GC_601,GC_600,MDL_MT
     $ ,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 282
      CALL FFV6_0(W(1,4),W(1,23),W(1,2),GC_7,AMP(296))
      CALL FFVVS2_4_2(W(1,4),W(1,1),W(1,6),W(1,5),GC_601,GC_600,MDL_MT
     $ ,MDL_WT,W(1,23))
C     Amplitude(s) for diagram number 283
      CALL FFV6_0(W(1,23),W(1,3),W(1,2),GC_7,AMP(297))
      JAMP(1)=+AMP(2)+AMP(3)+AMP(7)+AMP(8)+IMAG1*AMP(9)+IMAG1*AMP(10)
     $ +IMAG1*AMP(11)+IMAG1*AMP(12)+IMAG1*AMP(22)+AMP(23)+AMP(24)
     $ +IMAG1*AMP(25)+IMAG1*AMP(26)+IMAG1*AMP(27)+AMP(28)+AMP(29)
     $ +IMAG1*AMP(30)+IMAG1*AMP(31)+IMAG1*AMP(32)+IMAG1*AMP(33)+IMAG1
     $ *AMP(34)-AMP(35)+IMAG1*AMP(37)-AMP(38)+IMAG1*AMP(50)+IMAG1
     $ *AMP(51)+IMAG1*AMP(52)+IMAG1*AMP(53)+IMAG1*AMP(54)+IMAG1*AMP(55)
     $ +IMAG1*AMP(56)+IMAG1*AMP(57)+IMAG1*AMP(58)-AMP(59)+IMAG1*AMP(61)
     $ -AMP(62)-AMP(63)-AMP(64)-AMP(68)-AMP(70)-AMP(71)-AMP(72)-AMP(73)
     $ -AMP(74)-AMP(75)-AMP(76)-AMP(77)-AMP(78)-AMP(79)-AMP(80)+IMAG1
     $ *AMP(82)-AMP(83)+IMAG1*AMP(84)+AMP(215)+IMAG1*AMP(216)+AMP(217)
     $ +AMP(218)+AMP(219)+IMAG1*AMP(220)+IMAG1*AMP(221)+IMAG1*AMP(222)
     $ +AMP(223)+AMP(225)+AMP(226)+AMP(227)+AMP(231)-AMP(232)+IMAG1
     $ *AMP(234)-AMP(235)-AMP(236)-AMP(237)-AMP(241)+IMAG1*AMP(254)
     $ +IMAG1*AMP(255)-AMP(260)+AMP(258)-AMP(263)+AMP(261)-AMP(266)
     $ +AMP(264)-AMP(269)+AMP(267)-AMP(272)+AMP(270)-AMP(275)+AMP(273)
     $ -AMP(278)+AMP(276)+IMAG1*AMP(280)-AMP(281)+IMAG1*AMP(292)+IMAG1
     $ *AMP(293)-AMP(295)
      JAMP(2)=-AMP(39)-AMP(40)-AMP(41)-AMP(42)-AMP(43)-AMP(44)-AMP(45)
     $ -AMP(46)-AMP(47)-AMP(48)-AMP(49)-IMAG1*AMP(50)-IMAG1*AMP(51)
     $ -IMAG1*AMP(52)-IMAG1*AMP(53)-IMAG1*AMP(54)-IMAG1*AMP(55)-IMAG1
     $ *AMP(56)-IMAG1*AMP(57)-IMAG1*AMP(58)-AMP(60)-IMAG1*AMP(61)
     $ -AMP(65)-AMP(66)-AMP(67)-AMP(69)-AMP(81)-IMAG1*AMP(82)-IMAG1
     $ *AMP(84)+IMAG1*AMP(140)+IMAG1*AMP(141)+IMAG1*AMP(142)+IMAG1
     $ *AMP(143)+IMAG1*AMP(144)+IMAG1*AMP(145)+IMAG1*AMP(146)+IMAG1
     $ *AMP(147)+IMAG1*AMP(148)+AMP(149)+AMP(151)+AMP(152)+AMP(153)
     $ +AMP(157)+IMAG1*AMP(158)+AMP(159)+AMP(160)+AMP(161)+IMAG1
     $ *AMP(162)+IMAG1*AMP(163)+IMAG1*AMP(164)+IMAG1*AMP(166)+AMP(167)
     $ -AMP(168)-AMP(193)+IMAG1*AMP(194)-AMP(198)-AMP(199)-AMP(200)
     $ -AMP(202)-AMP(215)-IMAG1*AMP(216)-AMP(217)-AMP(218)-AMP(219)
     $ -IMAG1*AMP(220)-IMAG1*AMP(221)-IMAG1*AMP(222)-AMP(223)-AMP(225)
     $ -AMP(226)-AMP(227)-AMP(231)-AMP(259)-AMP(258)-AMP(262)-AMP(261)
     $ -AMP(265)-AMP(264)-AMP(268)-AMP(267)-AMP(271)-AMP(270)-AMP(274)
     $ -AMP(273)-AMP(277)-AMP(276)-AMP(279)-IMAG1*AMP(280)+IMAG1
     $ *AMP(282)+IMAG1*AMP(283)-IMAG1*AMP(292)+AMP(295)+IMAG1*AMP(296)
      JAMP(3)=-AMP(2)-AMP(3)-AMP(7)-AMP(8)-IMAG1*AMP(9)-IMAG1*AMP(10)
     $ -IMAG1*AMP(11)-IMAG1*AMP(12)-IMAG1*AMP(22)-AMP(23)-AMP(24)
     $ -IMAG1*AMP(25)-IMAG1*AMP(26)-IMAG1*AMP(27)-AMP(28)-AMP(29)
     $ -IMAG1*AMP(30)-IMAG1*AMP(31)-IMAG1*AMP(32)-IMAG1*AMP(33)-IMAG1
     $ *AMP(34)+AMP(35)-IMAG1*AMP(37)+AMP(38)+IMAG1*AMP(131)+IMAG1
     $ *AMP(132)+IMAG1*AMP(133)+IMAG1*AMP(134)+IMAG1*AMP(135)+IMAG1
     $ *AMP(136)+IMAG1*AMP(137)+IMAG1*AMP(138)+IMAG1*AMP(139)-AMP(149)
     $ +IMAG1*AMP(150)-AMP(151)-AMP(152)-AMP(153)+IMAG1*AMP(154)+IMAG1
     $ *AMP(155)+IMAG1*AMP(156)-AMP(157)-AMP(159)-AMP(160)-AMP(161)
     $ +IMAG1*AMP(165)-AMP(167)+AMP(168)-AMP(169)+IMAG1*AMP(171)
     $ -AMP(172)-AMP(173)-AMP(174)-AMP(178)-AMP(180)-AMP(181)-AMP(182)
     $ -AMP(183)-AMP(184)-AMP(185)-AMP(186)-AMP(187)-AMP(188)-AMP(189)
     $ -AMP(190)-AMP(191)-AMP(233)-IMAG1*AMP(234)-AMP(238)-AMP(239)
     $ -AMP(240)-AMP(242)-IMAG1*AMP(254)-IMAG1*AMP(255)+AMP(260)
     $ +AMP(259)+AMP(263)+AMP(262)+AMP(266)+AMP(265)+AMP(269)+AMP(268)
     $ +AMP(272)+AMP(271)+AMP(275)+AMP(274)+AMP(278)+AMP(277)+IMAG1
     $ *AMP(287)+IMAG1*AMP(288)-AMP(289)-IMAG1*AMP(293)+IMAG1*AMP(297)
      JAMP(4)=-AMP(85)-AMP(86)-AMP(87)-AMP(88)-AMP(89)-AMP(90)-AMP(91)
     $ -AMP(92)-AMP(93)-AMP(94)-AMP(95)+IMAG1*AMP(96)+IMAG1*AMP(97)
     $ +IMAG1*AMP(98)+IMAG1*AMP(99)+IMAG1*AMP(100)+IMAG1*AMP(101)
     $ +IMAG1*AMP(102)+IMAG1*AMP(103)+IMAG1*AMP(104)-AMP(106)+IMAG1
     $ *AMP(107)-AMP(111)-AMP(112)-AMP(113)-AMP(115)-AMP(127)+IMAG1
     $ *AMP(128)+IMAG1*AMP(130)-IMAG1*AMP(131)-IMAG1*AMP(132)-IMAG1
     $ *AMP(133)-IMAG1*AMP(134)-IMAG1*AMP(135)-IMAG1*AMP(136)-IMAG1
     $ *AMP(137)-IMAG1*AMP(138)-IMAG1*AMP(139)+AMP(149)-IMAG1*AMP(150)
     $ +AMP(151)+AMP(152)+AMP(153)-IMAG1*AMP(154)-IMAG1*AMP(155)-IMAG1
     $ *AMP(156)+AMP(157)+AMP(159)+AMP(160)+AMP(161)-IMAG1*AMP(165)
     $ +AMP(167)-AMP(168)-AMP(170)-IMAG1*AMP(171)-AMP(175)-AMP(176)
     $ -AMP(177)-AMP(179)-AMP(215)-AMP(217)-AMP(218)-AMP(219)-AMP(223)
     $ +IMAG1*AMP(224)-AMP(225)-AMP(226)-AMP(227)+IMAG1*AMP(228)+IMAG1
     $ *AMP(229)+IMAG1*AMP(230)-AMP(231)-AMP(259)-AMP(258)-AMP(262)
     $ -AMP(261)-AMP(265)-AMP(264)-AMP(268)-AMP(267)-AMP(271)-AMP(270)
     $ -AMP(274)-AMP(273)-AMP(277)-AMP(276)-AMP(284)+IMAG1*AMP(285)
     $ -IMAG1*AMP(287)-IMAG1*AMP(288)+IMAG1*AMP(290)+AMP(295)-IMAG1
     $ *AMP(297)
      JAMP(5)=+IMAG1*AMP(1)-AMP(2)-AMP(3)+IMAG1*AMP(4)+IMAG1*AMP(5)
     $ +IMAG1*AMP(6)-AMP(7)-AMP(8)+IMAG1*AMP(13)+IMAG1*AMP(14)+IMAG1
     $ *AMP(15)+IMAG1*AMP(16)+IMAG1*AMP(17)+IMAG1*AMP(18)+IMAG1*AMP(19)
     $ +IMAG1*AMP(20)+IMAG1*AMP(21)-AMP(23)-AMP(24)-AMP(28)-AMP(29)
     $ +AMP(35)+IMAG1*AMP(36)+AMP(38)-IMAG1*AMP(140)-IMAG1*AMP(141)
     $ -IMAG1*AMP(142)-IMAG1*AMP(143)-IMAG1*AMP(144)-IMAG1*AMP(145)
     $ -IMAG1*AMP(146)-IMAG1*AMP(147)-IMAG1*AMP(148)-AMP(149)-AMP(151)
     $ -AMP(152)-AMP(153)-AMP(157)-IMAG1*AMP(158)-AMP(159)-AMP(160)
     $ -AMP(161)-IMAG1*AMP(162)-IMAG1*AMP(163)-IMAG1*AMP(164)-IMAG1
     $ *AMP(166)-AMP(167)+AMP(168)-AMP(192)-IMAG1*AMP(194)-AMP(195)
     $ -AMP(196)-AMP(197)-AMP(201)-AMP(203)-AMP(204)-AMP(205)-AMP(206)
     $ -AMP(207)-AMP(208)-AMP(209)-AMP(210)-AMP(211)-AMP(212)-AMP(213)
     $ -AMP(214)-AMP(243)+IMAG1*AMP(245)-AMP(246)-AMP(247)-AMP(248)
     $ -AMP(252)+IMAG1*AMP(256)+IMAG1*AMP(257)+AMP(260)+AMP(259)
     $ +AMP(263)+AMP(262)+AMP(266)+AMP(265)+AMP(269)+AMP(268)+AMP(272)
     $ +AMP(271)+AMP(275)+AMP(274)+AMP(278)+AMP(277)-IMAG1*AMP(282)
     $ -IMAG1*AMP(283)-AMP(291)+IMAG1*AMP(294)-IMAG1*AMP(296)
      JAMP(6)=-IMAG1*AMP(1)+AMP(2)+AMP(3)-IMAG1*AMP(4)-IMAG1*AMP(5)
     $ -IMAG1*AMP(6)+AMP(7)+AMP(8)-IMAG1*AMP(13)-IMAG1*AMP(14)-IMAG1
     $ *AMP(15)-IMAG1*AMP(16)-IMAG1*AMP(17)-IMAG1*AMP(18)-IMAG1*AMP(19)
     $ -IMAG1*AMP(20)-IMAG1*AMP(21)+AMP(23)+AMP(24)+AMP(28)+AMP(29)
     $ -AMP(35)-IMAG1*AMP(36)-AMP(38)-IMAG1*AMP(96)-IMAG1*AMP(97)
     $ -IMAG1*AMP(98)-IMAG1*AMP(99)-IMAG1*AMP(100)-IMAG1*AMP(101)
     $ -IMAG1*AMP(102)-IMAG1*AMP(103)-IMAG1*AMP(104)-AMP(105)-IMAG1
     $ *AMP(107)-AMP(108)-AMP(109)-AMP(110)-AMP(114)-AMP(116)-AMP(117)
     $ -AMP(118)-AMP(119)-AMP(120)-AMP(121)-AMP(122)-AMP(123)-AMP(124)
     $ -AMP(125)-AMP(126)-IMAG1*AMP(128)-AMP(129)-IMAG1*AMP(130)
     $ +AMP(215)+AMP(217)+AMP(218)+AMP(219)+AMP(223)-IMAG1*AMP(224)
     $ +AMP(225)+AMP(226)+AMP(227)-IMAG1*AMP(228)-IMAG1*AMP(229)-IMAG1
     $ *AMP(230)+AMP(231)-AMP(244)-IMAG1*AMP(245)-AMP(249)-AMP(250)
     $ -AMP(251)-AMP(253)-IMAG1*AMP(256)-IMAG1*AMP(257)-AMP(260)
     $ +AMP(258)-AMP(263)+AMP(261)-AMP(266)+AMP(264)-AMP(269)+AMP(267)
     $ -AMP(272)+AMP(270)-AMP(275)+AMP(273)-AMP(278)+AMP(276)-IMAG1
     $ *AMP(285)-AMP(286)-IMAG1*AMP(290)-IMAG1*AMP(294)-AMP(295)

      M3_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M3_MATRIX = M3_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M3_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M3_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M3_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M3_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M3_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NCOMB
      PARAMETER (NCOMB=32)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M3_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M3_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M3_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M3_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

