      SUBROUTINE M77_SMATRIXHEL(P,HEL,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: HEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M77_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL M77_SMATRIX(P,ANS)
      USERHEL=-1

      END

      SUBROUTINE M77_SMATRIX(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > t t~ vt vt~ g DIM6<=1 FCNC=0 / h @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NINITIAL
      PARAMETER (NINITIAL=2)
      INTEGER NPOLENTRIES
      PARAMETER (NPOLENTRIES=(NEXTERNAL+1)*6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=128)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
C     put in common block to expose this variable to python interface
      COMMON/M77_PROCESS_NHEL/NHEL
      REAL*8 T
      REAL*8 M77_MATRIX
      INTEGER IHEL,IDEN, I, J
C     For a 1>N process, them BEAMTWO_HELAVGFACTOR would be set to 1.
      INTEGER BEAMS_HELAVGFACTOR(2)
      DATA (BEAMS_HELAVGFACTOR(I),I=1,2)/2,2/
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./

C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/M77_HELUSERCHOICE/USERHEL
      DATA USERHEL/-1/

      DATA (NHEL(I,   1),I=1,7) /-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,   2),I=1,7) /-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,   3),I=1,7) /-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,   4),I=1,7) /-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,   5),I=1,7) /-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,   6),I=1,7) /-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,   7),I=1,7) /-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,   8),I=1,7) /-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,   9),I=1,7) /-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  10),I=1,7) /-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  11),I=1,7) /-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  12),I=1,7) /-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  13),I=1,7) /-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  14),I=1,7) /-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  15),I=1,7) /-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  16),I=1,7) /-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  17),I=1,7) /-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  18),I=1,7) /-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  19),I=1,7) /-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  20),I=1,7) /-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  21),I=1,7) /-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  22),I=1,7) /-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  23),I=1,7) /-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  24),I=1,7) /-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  25),I=1,7) /-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  26),I=1,7) /-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  27),I=1,7) /-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  28),I=1,7) /-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  29),I=1,7) /-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  30),I=1,7) /-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  31),I=1,7) /-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  32),I=1,7) /-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  33),I=1,7) /-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  34),I=1,7) /-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  35),I=1,7) /-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  36),I=1,7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  37),I=1,7) /-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  38),I=1,7) /-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  39),I=1,7) /-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  40),I=1,7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  41),I=1,7) /-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  42),I=1,7) /-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  43),I=1,7) /-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  44),I=1,7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  45),I=1,7) /-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  46),I=1,7) /-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  47),I=1,7) /-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  48),I=1,7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  49),I=1,7) /-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  50),I=1,7) /-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  51),I=1,7) /-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  52),I=1,7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  53),I=1,7) /-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  54),I=1,7) /-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  55),I=1,7) /-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  56),I=1,7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  57),I=1,7) /-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  58),I=1,7) /-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  59),I=1,7) /-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  60),I=1,7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  61),I=1,7) /-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  62),I=1,7) /-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  63),I=1,7) /-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  64),I=1,7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  65),I=1,7) / 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  66),I=1,7) / 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  67),I=1,7) / 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  68),I=1,7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  69),I=1,7) / 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  70),I=1,7) / 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  71),I=1,7) / 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  72),I=1,7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  73),I=1,7) / 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  74),I=1,7) / 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  75),I=1,7) / 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  76),I=1,7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  77),I=1,7) / 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  78),I=1,7) / 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  79),I=1,7) / 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  80),I=1,7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  81),I=1,7) / 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  82),I=1,7) / 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  83),I=1,7) / 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  84),I=1,7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  85),I=1,7) / 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  86),I=1,7) / 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  87),I=1,7) / 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  88),I=1,7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  89),I=1,7) / 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  90),I=1,7) / 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  91),I=1,7) / 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  92),I=1,7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  93),I=1,7) / 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  94),I=1,7) / 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  95),I=1,7) / 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  96),I=1,7) / 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  97),I=1,7) / 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  98),I=1,7) / 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  99),I=1,7) / 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 100),I=1,7) / 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 101),I=1,7) / 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 102),I=1,7) / 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 103),I=1,7) / 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 104),I=1,7) / 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 105),I=1,7) / 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 106),I=1,7) / 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 107),I=1,7) / 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 108),I=1,7) / 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 109),I=1,7) / 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 110),I=1,7) / 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 111),I=1,7) / 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 112),I=1,7) / 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 113),I=1,7) / 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 114),I=1,7) / 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 115),I=1,7) / 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 116),I=1,7) / 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 117),I=1,7) / 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 118),I=1,7) / 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 119),I=1,7) / 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 120),I=1,7) / 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 121),I=1,7) / 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 122),I=1,7) / 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 123),I=1,7) / 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 124),I=1,7) / 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 125),I=1,7) / 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 126),I=1,7) / 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 127),I=1,7) / 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 128),I=1,7) / 1, 1, 1,-1, 1,-1, 1/
      DATA IDEN/256/

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M77_BORN_BEAM_POL/POLARIZATIONS
      DATA ((POLARIZATIONS(I,J),I=0,NEXTERNAL),J=0,5)/NPOLENTRIES*-1/

C     
C     FUNCTIONS
C     
      LOGICAL M77_IS_BORN_HEL_SELECTED

C     ----------
C     BEGIN CODE
C     ----------
      IF(USERHEL.EQ.-1) NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
C     When spin-2 particles are involved, the Helicity filtering is
C      dangerous for the 2->1 topology.
C     This is because depending on the MC setup the initial PS points
C      have back-to-back initial states
C     for which some of the spin-2 helicity configurations are zero.
C      But they are no longer zero
C     if the point is boosted on the z-axis. Remember that HELAS
C      helicity amplitudes are no longer
C     lorentz invariant with expternal spin-2 particles (only the
C      helicity sum is).
C     For this reason, we simply remove the filterin when there is
C      only three external particles.
      IF (NEXTERNAL.LE.3) THEN
        DO IHEL=1,NCOMB
          GOODHEL(IHEL)=.TRUE.
        ENDDO
      ENDIF
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL) .OR. NTRY .LT. 20.OR.USERHEL.NE.-1) THEN
            IF(NTRY.GE.2.AND.POLARIZATIONS(0,0).NE.
     $       -1.AND.(.NOT.M77_IS_BORN_HEL_SELECTED(IHEL))) THEN
              CYCLE
            ENDIF
            T=M77_MATRIX(P ,NHEL(1,IHEL),JC(1))
            IF(POLARIZATIONS(0,0).EQ.-1.OR.M77_IS_BORN_HEL_SELECTED(IHE
     $L)) THEN
              ANS=ANS+T
            ENDIF
            IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
              GOODHEL(IHEL)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      IF(USERHEL.NE.-1) THEN
        ANS=ANS*HELAVGFACTOR
      ELSE
        DO J=1,NINITIAL
          IF (POLARIZATIONS(J,0).NE.-1) THEN
            ANS=ANS*BEAMS_HELAVGFACTOR(J)
            ANS=ANS/POLARIZATIONS(J,0)
          ENDIF
        ENDDO
      ENDIF
      END


      REAL*8 FUNCTION M77_MATRIX(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.6.5, 2018-02-03
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > t t~ vt vt~ g DIM6<=1 FCNC=0 / h @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=414)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=40, NCOLOR=6)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(20,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'

C     
C     COLOR DATA
C     
      DATA DENOM(1)/9/
      DATA (CF(I,  1),I=  1,  6) /   64,   -8,   -8,    1,    1,   10/
C     1 T(1,2,7,3,4)
      DATA DENOM(2)/9/
      DATA (CF(I,  2),I=  1,  6) /   -8,   64,    1,   10,   -8,    1/
C     1 T(1,7,2,3,4)
      DATA DENOM(3)/9/
      DATA (CF(I,  3),I=  1,  6) /   -8,    1,   64,   -8,   10,    1/
C     1 T(2,1,7,3,4)
      DATA DENOM(4)/9/
      DATA (CF(I,  4),I=  1,  6) /    1,   10,   -8,   64,    1,   -8/
C     1 T(2,7,1,3,4)
      DATA DENOM(5)/9/
      DATA (CF(I,  5),I=  1,  6) /    1,   -8,   10,    1,   64,   -8/
C     1 T(7,1,2,3,4)
      DATA DENOM(6)/9/
      DATA (CF(I,  6),I=  1,  6) /   10,    1,    1,   -8,   -8,   64/
C     1 T(7,2,1,3,4)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL VXXXXX(P(0,7),ZERO,NHEL(7),+1*IC(7),W(1,7))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_6,ZERO,ZERO,W(1,8))
      CALL FFV6_1(W(1,3),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,9))
      CALL FFV6_2(W(1,4),W(1,8),GC_7,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 1
      CALL FFFF14_6_0(W(1,10),W(1,9),W(1,6),W(1,5),GC_586,GC_124,AMP(1)
     $ )
      CALL FFV2_3(W(1,6),W(1,5),GC_664,MDL_MZ,MDL_WZ,W(1,11))
      CALL FFV6_1(W(1,9),W(1,8),GC_7,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 2
      CALL FFV2_8_0(W(1,4),W(1,12),W(1,11),GC_651,GC_660,AMP(2))
C     Amplitude(s) for diagram number 3
      CALL FFV11_9_0(W(1,4),W(1,12),W(1,11),GC_721,GC_722,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV4_0(W(1,4),W(1,12),W(1,11),GC_948,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV2_0(W(1,4),W(1,12),W(1,11),GC_938,AMP(5))
      CALL FFV11_9_1(W(1,9),W(1,8),GC_725,GC_726,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 6
      CALL FFV2_8_0(W(1,4),W(1,12),W(1,11),GC_651,GC_660,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL FFV2_8_0(W(1,10),W(1,9),W(1,11),GC_651,GC_660,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV11_9_0(W(1,10),W(1,9),W(1,11),GC_721,GC_722,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL FFV4_0(W(1,10),W(1,9),W(1,11),GC_948,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV2_0(W(1,10),W(1,9),W(1,11),GC_938,AMP(10))
      CALL FFV11_9_2(W(1,4),W(1,8),GC_725,GC_726,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 11
      CALL FFV2_8_0(W(1,12),W(1,9),W(1,11),GC_651,GC_660,AMP(11))
      CALL FFV11_9_1(W(1,3),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,13))
      CALL FFV6_1(W(1,13),W(1,8),GC_7,MDL_MT,MDL_WT,W(1,14))
C     Amplitude(s) for diagram number 12
      CALL FFV2_8_0(W(1,4),W(1,14),W(1,11),GC_651,GC_660,AMP(12))
C     Amplitude(s) for diagram number 13
      CALL FFV2_8_0(W(1,10),W(1,13),W(1,11),GC_651,GC_660,AMP(13))
      CALL FFFF14_6_2(W(1,4),W(1,6),W(1,5),GC_586,GC_124,MDL_MT,MDL_WT
     $ ,W(1,14))
C     Amplitude(s) for diagram number 14
      CALL FFV6_0(W(1,14),W(1,9),W(1,8),GC_7,AMP(14))
      CALL FFV6_2(W(1,4),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,15))
      CALL FFV6_1(W(1,3),W(1,8),GC_7,MDL_MT,MDL_WT,W(1,16))
C     Amplitude(s) for diagram number 15
      CALL FFFF14_6_0(W(1,15),W(1,16),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFV2_8_0(W(1,15),W(1,16),W(1,11),GC_651,GC_660,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV11_9_0(W(1,15),W(1,16),W(1,11),GC_721,GC_722,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV4_0(W(1,15),W(1,16),W(1,11),GC_948,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL FFV2_0(W(1,15),W(1,16),W(1,11),GC_938,AMP(19))
      CALL FFV11_9_1(W(1,3),W(1,8),GC_725,GC_726,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 20
      CALL FFV2_8_0(W(1,15),W(1,17),W(1,11),GC_651,GC_660,AMP(20))
      CALL FFV6_2(W(1,15),W(1,8),GC_7,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 21
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,11),GC_651,GC_660,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV11_9_0(W(1,18),W(1,3),W(1,11),GC_721,GC_722,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV4_0(W(1,18),W(1,3),W(1,11),GC_948,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV2_0(W(1,18),W(1,3),W(1,11),GC_938,AMP(24))
      CALL FFV11_9_2(W(1,15),W(1,8),GC_725,GC_726,MDL_MT,MDL_WT,W(1,18)
     $ )
C     Amplitude(s) for diagram number 25
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,11),GC_651,GC_660,AMP(25))
      CALL FFV11_9_2(W(1,4),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 26
      CALL FFV2_8_0(W(1,18),W(1,16),W(1,11),GC_651,GC_660,AMP(26))
      CALL FFV6_2(W(1,18),W(1,8),GC_7,MDL_MT,MDL_WT,W(1,19))
C     Amplitude(s) for diagram number 27
      CALL FFV2_8_0(W(1,19),W(1,3),W(1,11),GC_651,GC_660,AMP(27))
      CALL FFV2_8_2(W(1,4),W(1,11),GC_651,GC_660,MDL_MT,MDL_WT,W(1,19))
C     Amplitude(s) for diagram number 28
      CALL FFV6_0(W(1,19),W(1,16),W(1,7),GC_7,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV11_9_0(W(1,19),W(1,16),W(1,7),GC_725,GC_726,AMP(29))
      CALL FFV11_9_2(W(1,4),W(1,11),GC_721,GC_722,MDL_MT,MDL_WT,W(1,20)
     $ )
C     Amplitude(s) for diagram number 30
      CALL FFV6_0(W(1,20),W(1,16),W(1,7),GC_7,AMP(30))
      CALL FFV4_2(W(1,4),W(1,11),GC_948,MDL_MT,MDL_WT,W(1,21))
C     Amplitude(s) for diagram number 31
      CALL FFV6_0(W(1,21),W(1,16),W(1,7),GC_7,AMP(31))
      CALL FFV2_2(W(1,4),W(1,11),GC_938,MDL_MT,MDL_WT,W(1,22))
C     Amplitude(s) for diagram number 32
      CALL FFV6_0(W(1,22),W(1,16),W(1,7),GC_7,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV6_0(W(1,19),W(1,17),W(1,7),GC_7,AMP(33))
      CALL FFV2_8_1(W(1,3),W(1,11),GC_651,GC_660,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 34
      CALL FFV6_0(W(1,10),W(1,17),W(1,7),GC_7,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV11_9_0(W(1,10),W(1,17),W(1,7),GC_725,GC_726,AMP(35))
      CALL FFV11_9_1(W(1,3),W(1,11),GC_721,GC_722,MDL_MT,MDL_WT,W(1,23)
     $ )
C     Amplitude(s) for diagram number 36
      CALL FFV6_0(W(1,10),W(1,23),W(1,7),GC_7,AMP(36))
      CALL FFV4_1(W(1,3),W(1,11),GC_948,MDL_MT,MDL_WT,W(1,24))
C     Amplitude(s) for diagram number 37
      CALL FFV6_0(W(1,10),W(1,24),W(1,7),GC_7,AMP(37))
      CALL FFV2_1(W(1,3),W(1,11),GC_938,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 38
      CALL FFV6_0(W(1,10),W(1,25),W(1,7),GC_7,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV6_0(W(1,12),W(1,17),W(1,7),GC_7,AMP(39))
      CALL VVV1P0_1(W(1,8),W(1,7),GC_6,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 40
      CALL FFV6_0(W(1,4),W(1,17),W(1,12),GC_7,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV11_9_0(W(1,4),W(1,17),W(1,12),GC_725,GC_726,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV6_0(W(1,4),W(1,23),W(1,12),GC_7,AMP(42))
C     Amplitude(s) for diagram number 43
      CALL FFV6_0(W(1,4),W(1,24),W(1,12),GC_7,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFV6_0(W(1,4),W(1,25),W(1,12),GC_7,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV6_0(W(1,19),W(1,3),W(1,12),GC_7,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFV11_9_0(W(1,19),W(1,3),W(1,12),GC_725,GC_726,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV6_0(W(1,20),W(1,3),W(1,12),GC_7,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL FFV6_0(W(1,21),W(1,3),W(1,12),GC_7,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV6_0(W(1,22),W(1,3),W(1,12),GC_7,AMP(49))
      CALL FFVV2_4_1(W(1,3),W(1,8),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,26))
C     Amplitude(s) for diagram number 50
      CALL FFV2_8_0(W(1,4),W(1,26),W(1,11),GC_651,GC_660,AMP(50))
      CALL FFVV2_4_2(W(1,4),W(1,8),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,26))
C     Amplitude(s) for diagram number 51
      CALL FFV2_8_0(W(1,26),W(1,3),W(1,11),GC_651,GC_660,AMP(51))
      CALL FFFF14_6_1(W(1,3),W(1,6),W(1,5),GC_586,GC_124,MDL_MT,MDL_WT
     $ ,W(1,26))
C     Amplitude(s) for diagram number 52
      CALL FFV6_0(W(1,10),W(1,26),W(1,7),GC_7,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFV6_0(W(1,4),W(1,26),W(1,12),GC_7,AMP(53))
C     Amplitude(s) for diagram number 54
      CALL FFV6_0(W(1,15),W(1,26),W(1,8),GC_7,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV6_0(W(1,14),W(1,16),W(1,7),GC_7,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV6_0(W(1,14),W(1,3),W(1,12),GC_7,AMP(56))
      CALL FFV6_1(W(1,3),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,12))
      CALL FFV6_2(W(1,4),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,16))
      CALL FFV6_1(W(1,12),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,8))
C     Amplitude(s) for diagram number 57
      CALL FFFF14_6_0(W(1,16),W(1,8),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(57))
      CALL FFFF14_6_1(W(1,12),W(1,6),W(1,5),GC_586,GC_124,MDL_MT
     $ ,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 58
      CALL FFV6_0(W(1,16),W(1,10),W(1,7),GC_7,AMP(58))
      CALL FFV2_8_1(W(1,12),W(1,11),GC_651,GC_660,MDL_MT,MDL_WT,W(1,27)
     $ )
C     Amplitude(s) for diagram number 59
      CALL FFV6_0(W(1,16),W(1,27),W(1,7),GC_7,AMP(59))
C     Amplitude(s) for diagram number 60
      CALL FFV11_9_0(W(1,16),W(1,27),W(1,7),GC_725,GC_726,AMP(60))
      CALL FFV11_9_1(W(1,12),W(1,11),GC_721,GC_722,MDL_MT,MDL_WT,W(1
     $ ,28))
C     Amplitude(s) for diagram number 61
      CALL FFV6_0(W(1,16),W(1,28),W(1,7),GC_7,AMP(61))
      CALL FFV4_1(W(1,12),W(1,11),GC_948,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 62
      CALL FFV6_0(W(1,16),W(1,29),W(1,7),GC_7,AMP(62))
      CALL FFV2_1(W(1,12),W(1,11),GC_938,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 63
      CALL FFV6_0(W(1,16),W(1,30),W(1,7),GC_7,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL FFV2_8_0(W(1,16),W(1,8),W(1,11),GC_651,GC_660,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL FFV11_9_0(W(1,16),W(1,8),W(1,11),GC_721,GC_722,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL FFV4_0(W(1,16),W(1,8),W(1,11),GC_948,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL FFV2_0(W(1,16),W(1,8),W(1,11),GC_938,AMP(67))
      CALL FFV11_9_1(W(1,12),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,31)
     $ )
C     Amplitude(s) for diagram number 68
      CALL FFV2_8_0(W(1,16),W(1,31),W(1,11),GC_651,GC_660,AMP(68))
      CALL FFV11_9_2(W(1,4),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 69
      CALL FFV6_0(W(1,32),W(1,27),W(1,7),GC_7,AMP(69))
C     Amplitude(s) for diagram number 70
      CALL FFV2_8_0(W(1,32),W(1,8),W(1,11),GC_651,GC_660,AMP(70))
      CALL FFV11_9_1(W(1,3),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,33))
      CALL FFV2_8_1(W(1,33),W(1,11),GC_651,GC_660,MDL_MT,MDL_WT,W(1,34)
     $ )
C     Amplitude(s) for diagram number 71
      CALL FFV6_0(W(1,16),W(1,34),W(1,7),GC_7,AMP(71))
      CALL FFV6_1(W(1,33),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,35))
C     Amplitude(s) for diagram number 72
      CALL FFV2_8_0(W(1,16),W(1,35),W(1,11),GC_651,GC_660,AMP(72))
      CALL VVV1P0_1(W(1,2),W(1,7),GC_6,ZERO,ZERO,W(1,36))
C     Amplitude(s) for diagram number 73
      CALL FFV6_0(W(1,4),W(1,10),W(1,36),GC_7,AMP(73))
      CALL FFV6_1(W(1,12),W(1,36),GC_7,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 74
      CALL FFV2_8_0(W(1,4),W(1,37),W(1,11),GC_651,GC_660,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV11_9_0(W(1,4),W(1,37),W(1,11),GC_721,GC_722,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL FFV4_0(W(1,4),W(1,37),W(1,11),GC_948,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL FFV2_0(W(1,4),W(1,37),W(1,11),GC_938,AMP(77))
      CALL FFV11_9_1(W(1,12),W(1,36),GC_725,GC_726,MDL_MT,MDL_WT,W(1
     $ ,37))
C     Amplitude(s) for diagram number 78
      CALL FFV2_8_0(W(1,4),W(1,37),W(1,11),GC_651,GC_660,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV6_0(W(1,4),W(1,27),W(1,36),GC_7,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV11_9_0(W(1,4),W(1,27),W(1,36),GC_725,GC_726,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFV6_0(W(1,4),W(1,28),W(1,36),GC_7,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV6_0(W(1,4),W(1,29),W(1,36),GC_7,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFV6_0(W(1,4),W(1,30),W(1,36),GC_7,AMP(83))
      CALL FFV6_1(W(1,33),W(1,36),GC_7,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 84
      CALL FFV2_8_0(W(1,4),W(1,37),W(1,11),GC_651,GC_660,AMP(84))
C     Amplitude(s) for diagram number 85
      CALL FFV6_0(W(1,4),W(1,34),W(1,36),GC_7,AMP(85))
C     Amplitude(s) for diagram number 86
      CALL FFV6_0(W(1,14),W(1,12),W(1,36),GC_7,AMP(86))
      CALL FFV6_1(W(1,12),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 87
      CALL FFFF14_6_0(W(1,15),W(1,37),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV6_0(W(1,15),W(1,10),W(1,2),GC_7,AMP(88))
C     Amplitude(s) for diagram number 89
      CALL FFV2_8_0(W(1,15),W(1,37),W(1,11),GC_651,GC_660,AMP(89))
C     Amplitude(s) for diagram number 90
      CALL FFV11_9_0(W(1,15),W(1,37),W(1,11),GC_721,GC_722,AMP(90))
C     Amplitude(s) for diagram number 91
      CALL FFV4_0(W(1,15),W(1,37),W(1,11),GC_948,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL FFV2_0(W(1,15),W(1,37),W(1,11),GC_938,AMP(92))
      CALL FFV11_9_1(W(1,12),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,10)
     $ )
C     Amplitude(s) for diagram number 93
      CALL FFV2_8_0(W(1,15),W(1,10),W(1,11),GC_651,GC_660,AMP(93))
C     Amplitude(s) for diagram number 94
      CALL FFV6_0(W(1,15),W(1,27),W(1,2),GC_7,AMP(94))
C     Amplitude(s) for diagram number 95
      CALL FFV11_9_0(W(1,15),W(1,27),W(1,2),GC_725,GC_726,AMP(95))
C     Amplitude(s) for diagram number 96
      CALL FFV6_0(W(1,15),W(1,28),W(1,2),GC_7,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV6_0(W(1,15),W(1,29),W(1,2),GC_7,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL FFV6_0(W(1,15),W(1,30),W(1,2),GC_7,AMP(98))
C     Amplitude(s) for diagram number 99
      CALL FFV2_8_0(W(1,18),W(1,37),W(1,11),GC_651,GC_660,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL FFV6_0(W(1,18),W(1,27),W(1,2),GC_7,AMP(100))
      CALL FFV6_1(W(1,33),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 101
      CALL FFV2_8_0(W(1,15),W(1,27),W(1,11),GC_651,GC_660,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL FFV6_0(W(1,15),W(1,34),W(1,2),GC_7,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL FFV6_0(W(1,19),W(1,37),W(1,7),GC_7,AMP(103))
C     Amplitude(s) for diagram number 104
      CALL FFV11_9_0(W(1,19),W(1,37),W(1,7),GC_725,GC_726,AMP(104))
C     Amplitude(s) for diagram number 105
      CALL FFV6_0(W(1,20),W(1,37),W(1,7),GC_7,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL FFV6_0(W(1,21),W(1,37),W(1,7),GC_7,AMP(106))
C     Amplitude(s) for diagram number 107
      CALL FFV6_0(W(1,22),W(1,37),W(1,7),GC_7,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV6_0(W(1,19),W(1,10),W(1,7),GC_7,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV6_0(W(1,19),W(1,8),W(1,2),GC_7,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFV11_9_0(W(1,19),W(1,8),W(1,2),GC_725,GC_726,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV6_0(W(1,20),W(1,8),W(1,2),GC_7,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV6_0(W(1,21),W(1,8),W(1,2),GC_7,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV6_0(W(1,22),W(1,8),W(1,2),GC_7,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV6_0(W(1,19),W(1,31),W(1,2),GC_7,AMP(114))
      CALL FFVV2_4_1(W(1,12),W(1,2),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,31))
C     Amplitude(s) for diagram number 115
      CALL FFV2_8_0(W(1,4),W(1,31),W(1,11),GC_651,GC_660,AMP(115))
C     Amplitude(s) for diagram number 116
      CALL FFV6_0(W(1,19),W(1,27),W(1,7),GC_7,AMP(116))
C     Amplitude(s) for diagram number 117
      CALL FFV6_0(W(1,19),W(1,35),W(1,2),GC_7,AMP(117))
      CALL FFVV2_4_2(W(1,4),W(1,2),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,35))
C     Amplitude(s) for diagram number 118
      CALL FFV2_8_0(W(1,35),W(1,12),W(1,11),GC_651,GC_660,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFV6_0(W(1,14),W(1,37),W(1,7),GC_7,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL FFV6_0(W(1,14),W(1,8),W(1,2),GC_7,AMP(120))
      CALL FFV6_2(W(1,4),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,8))
      CALL FFV6_1(W(1,3),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,37))
      CALL FFV6_2(W(1,8),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 121
      CALL FFFF14_6_0(W(1,12),W(1,37),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(121))
      CALL FFFF14_6_2(W(1,8),W(1,6),W(1,5),GC_586,GC_124,MDL_MT,MDL_WT
     $ ,W(1,27))
C     Amplitude(s) for diagram number 122
      CALL FFV6_0(W(1,27),W(1,37),W(1,7),GC_7,AMP(122))
      CALL FFV2_8_2(W(1,8),W(1,11),GC_651,GC_660,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 123
      CALL FFV6_0(W(1,31),W(1,37),W(1,7),GC_7,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL FFV11_9_0(W(1,31),W(1,37),W(1,7),GC_725,GC_726,AMP(124))
      CALL FFV11_9_2(W(1,8),W(1,11),GC_721,GC_722,MDL_MT,MDL_WT,W(1,10)
     $ )
C     Amplitude(s) for diagram number 125
      CALL FFV6_0(W(1,10),W(1,37),W(1,7),GC_7,AMP(125))
      CALL FFV4_2(W(1,8),W(1,11),GC_948,MDL_MT,MDL_WT,W(1,34))
C     Amplitude(s) for diagram number 126
      CALL FFV6_0(W(1,34),W(1,37),W(1,7),GC_7,AMP(126))
      CALL FFV2_2(W(1,8),W(1,11),GC_938,MDL_MT,MDL_WT,W(1,33))
C     Amplitude(s) for diagram number 127
      CALL FFV6_0(W(1,33),W(1,37),W(1,7),GC_7,AMP(127))
C     Amplitude(s) for diagram number 128
      CALL FFV2_8_0(W(1,12),W(1,37),W(1,11),GC_651,GC_660,AMP(128))
C     Amplitude(s) for diagram number 129
      CALL FFV11_9_0(W(1,12),W(1,37),W(1,11),GC_721,GC_722,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFV4_0(W(1,12),W(1,37),W(1,11),GC_948,AMP(130))
C     Amplitude(s) for diagram number 131
      CALL FFV2_0(W(1,12),W(1,37),W(1,11),GC_938,AMP(131))
      CALL FFV11_9_2(W(1,8),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 132
      CALL FFV2_8_0(W(1,30),W(1,37),W(1,11),GC_651,GC_660,AMP(132))
      CALL FFV11_9_1(W(1,3),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 133
      CALL FFV6_0(W(1,31),W(1,29),W(1,7),GC_7,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL FFV2_8_0(W(1,12),W(1,29),W(1,11),GC_651,GC_660,AMP(134))
      CALL FFV11_9_2(W(1,4),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,28))
      CALL FFV2_8_2(W(1,28),W(1,11),GC_651,GC_660,MDL_MT,MDL_WT,W(1,38)
     $ )
C     Amplitude(s) for diagram number 135
      CALL FFV6_0(W(1,38),W(1,37),W(1,7),GC_7,AMP(135))
      CALL FFV6_2(W(1,28),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,39))
C     Amplitude(s) for diagram number 136
      CALL FFV2_8_0(W(1,39),W(1,37),W(1,11),GC_651,GC_660,AMP(136))
C     Amplitude(s) for diagram number 137
      CALL FFV6_0(W(1,27),W(1,3),W(1,36),GC_7,AMP(137))
      CALL FFV6_2(W(1,8),W(1,36),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 138
      CALL FFV2_8_0(W(1,40),W(1,3),W(1,11),GC_651,GC_660,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL FFV11_9_0(W(1,40),W(1,3),W(1,11),GC_721,GC_722,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL FFV4_0(W(1,40),W(1,3),W(1,11),GC_948,AMP(140))
C     Amplitude(s) for diagram number 141
      CALL FFV2_0(W(1,40),W(1,3),W(1,11),GC_938,AMP(141))
      CALL FFV11_9_2(W(1,8),W(1,36),GC_725,GC_726,MDL_MT,MDL_WT,W(1,40)
     $ )
C     Amplitude(s) for diagram number 142
      CALL FFV2_8_0(W(1,40),W(1,3),W(1,11),GC_651,GC_660,AMP(142))
C     Amplitude(s) for diagram number 143
      CALL FFV6_0(W(1,31),W(1,3),W(1,36),GC_7,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL FFV11_9_0(W(1,31),W(1,3),W(1,36),GC_725,GC_726,AMP(144))
C     Amplitude(s) for diagram number 145
      CALL FFV6_0(W(1,10),W(1,3),W(1,36),GC_7,AMP(145))
C     Amplitude(s) for diagram number 146
      CALL FFV6_0(W(1,34),W(1,3),W(1,36),GC_7,AMP(146))
C     Amplitude(s) for diagram number 147
      CALL FFV6_0(W(1,33),W(1,3),W(1,36),GC_7,AMP(147))
      CALL FFV6_2(W(1,28),W(1,36),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 148
      CALL FFV2_8_0(W(1,40),W(1,3),W(1,11),GC_651,GC_660,AMP(148))
C     Amplitude(s) for diagram number 149
      CALL FFV6_0(W(1,38),W(1,3),W(1,36),GC_7,AMP(149))
C     Amplitude(s) for diagram number 150
      CALL FFV6_0(W(1,8),W(1,26),W(1,36),GC_7,AMP(150))
      CALL FFV6_2(W(1,8),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 151
      CALL FFFF14_6_0(W(1,40),W(1,9),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(151))
C     Amplitude(s) for diagram number 152
      CALL FFV6_0(W(1,27),W(1,9),W(1,2),GC_7,AMP(152))
C     Amplitude(s) for diagram number 153
      CALL FFV2_8_0(W(1,40),W(1,9),W(1,11),GC_651,GC_660,AMP(153))
C     Amplitude(s) for diagram number 154
      CALL FFV11_9_0(W(1,40),W(1,9),W(1,11),GC_721,GC_722,AMP(154))
C     Amplitude(s) for diagram number 155
      CALL FFV4_0(W(1,40),W(1,9),W(1,11),GC_948,AMP(155))
C     Amplitude(s) for diagram number 156
      CALL FFV2_0(W(1,40),W(1,9),W(1,11),GC_938,AMP(156))
      CALL FFV11_9_2(W(1,8),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 157
      CALL FFV2_8_0(W(1,27),W(1,9),W(1,11),GC_651,GC_660,AMP(157))
C     Amplitude(s) for diagram number 158
      CALL FFV6_0(W(1,31),W(1,9),W(1,2),GC_7,AMP(158))
C     Amplitude(s) for diagram number 159
      CALL FFV11_9_0(W(1,31),W(1,9),W(1,2),GC_725,GC_726,AMP(159))
C     Amplitude(s) for diagram number 160
      CALL FFV6_0(W(1,10),W(1,9),W(1,2),GC_7,AMP(160))
C     Amplitude(s) for diagram number 161
      CALL FFV6_0(W(1,34),W(1,9),W(1,2),GC_7,AMP(161))
C     Amplitude(s) for diagram number 162
      CALL FFV6_0(W(1,33),W(1,9),W(1,2),GC_7,AMP(162))
C     Amplitude(s) for diagram number 163
      CALL FFV2_8_0(W(1,40),W(1,13),W(1,11),GC_651,GC_660,AMP(163))
C     Amplitude(s) for diagram number 164
      CALL FFV6_0(W(1,31),W(1,13),W(1,2),GC_7,AMP(164))
      CALL FFV6_2(W(1,28),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 165
      CALL FFV2_8_0(W(1,31),W(1,9),W(1,11),GC_651,GC_660,AMP(165))
C     Amplitude(s) for diagram number 166
      CALL FFV6_0(W(1,38),W(1,9),W(1,2),GC_7,AMP(166))
C     Amplitude(s) for diagram number 167
      CALL FFV6_0(W(1,40),W(1,17),W(1,7),GC_7,AMP(167))
C     Amplitude(s) for diagram number 168
      CALL FFV11_9_0(W(1,40),W(1,17),W(1,7),GC_725,GC_726,AMP(168))
C     Amplitude(s) for diagram number 169
      CALL FFV6_0(W(1,40),W(1,23),W(1,7),GC_7,AMP(169))
C     Amplitude(s) for diagram number 170
      CALL FFV6_0(W(1,40),W(1,24),W(1,7),GC_7,AMP(170))
C     Amplitude(s) for diagram number 171
      CALL FFV6_0(W(1,40),W(1,25),W(1,7),GC_7,AMP(171))
C     Amplitude(s) for diagram number 172
      CALL FFV6_0(W(1,27),W(1,17),W(1,7),GC_7,AMP(172))
C     Amplitude(s) for diagram number 173
      CALL FFV6_0(W(1,12),W(1,17),W(1,2),GC_7,AMP(173))
C     Amplitude(s) for diagram number 174
      CALL FFV11_9_0(W(1,12),W(1,17),W(1,2),GC_725,GC_726,AMP(174))
C     Amplitude(s) for diagram number 175
      CALL FFV6_0(W(1,12),W(1,23),W(1,2),GC_7,AMP(175))
C     Amplitude(s) for diagram number 176
      CALL FFV6_0(W(1,12),W(1,24),W(1,2),GC_7,AMP(176))
C     Amplitude(s) for diagram number 177
      CALL FFV6_0(W(1,12),W(1,25),W(1,2),GC_7,AMP(177))
C     Amplitude(s) for diagram number 178
      CALL FFV6_0(W(1,30),W(1,17),W(1,2),GC_7,AMP(178))
      CALL FFVV2_4_2(W(1,8),W(1,2),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,30))
C     Amplitude(s) for diagram number 179
      CALL FFV2_8_0(W(1,30),W(1,3),W(1,11),GC_651,GC_660,AMP(179))
C     Amplitude(s) for diagram number 180
      CALL FFV6_0(W(1,31),W(1,17),W(1,7),GC_7,AMP(180))
C     Amplitude(s) for diagram number 181
      CALL FFV6_0(W(1,39),W(1,17),W(1,2),GC_7,AMP(181))
      CALL FFVV2_4_1(W(1,3),W(1,2),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,39))
C     Amplitude(s) for diagram number 182
      CALL FFV2_8_0(W(1,8),W(1,39),W(1,11),GC_651,GC_660,AMP(182))
C     Amplitude(s) for diagram number 183
      CALL FFV6_0(W(1,40),W(1,26),W(1,7),GC_7,AMP(183))
C     Amplitude(s) for diagram number 184
      CALL FFV6_0(W(1,12),W(1,26),W(1,2),GC_7,AMP(184))
      CALL VVV1P0_1(W(1,1),W(1,7),GC_6,ZERO,ZERO,W(1,12))
      CALL FFV6_2(W(1,4),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 185
      CALL FFFF14_6_0(W(1,40),W(1,37),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(185))
      CALL FFV6_1(W(1,37),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,8))
C     Amplitude(s) for diagram number 186
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,11),GC_651,GC_660,AMP(186))
C     Amplitude(s) for diagram number 187
      CALL FFV11_9_0(W(1,4),W(1,8),W(1,11),GC_721,GC_722,AMP(187))
C     Amplitude(s) for diagram number 188
      CALL FFV4_0(W(1,4),W(1,8),W(1,11),GC_948,AMP(188))
C     Amplitude(s) for diagram number 189
      CALL FFV2_0(W(1,4),W(1,8),W(1,11),GC_938,AMP(189))
      CALL FFV11_9_1(W(1,37),W(1,12),GC_725,GC_726,MDL_MT,MDL_WT,W(1,8)
     $ )
C     Amplitude(s) for diagram number 190
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,11),GC_651,GC_660,AMP(190))
C     Amplitude(s) for diagram number 191
      CALL FFV2_8_0(W(1,40),W(1,37),W(1,11),GC_651,GC_660,AMP(191))
C     Amplitude(s) for diagram number 192
      CALL FFV11_9_0(W(1,40),W(1,37),W(1,11),GC_721,GC_722,AMP(192))
C     Amplitude(s) for diagram number 193
      CALL FFV4_0(W(1,40),W(1,37),W(1,11),GC_948,AMP(193))
C     Amplitude(s) for diagram number 194
      CALL FFV2_0(W(1,40),W(1,37),W(1,11),GC_938,AMP(194))
      CALL FFV11_9_2(W(1,4),W(1,12),GC_725,GC_726,MDL_MT,MDL_WT,W(1,8))
C     Amplitude(s) for diagram number 195
      CALL FFV2_8_0(W(1,8),W(1,37),W(1,11),GC_651,GC_660,AMP(195))
      CALL FFV6_1(W(1,29),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 196
      CALL FFV2_8_0(W(1,4),W(1,31),W(1,11),GC_651,GC_660,AMP(196))
C     Amplitude(s) for diagram number 197
      CALL FFV2_8_0(W(1,40),W(1,29),W(1,11),GC_651,GC_660,AMP(197))
C     Amplitude(s) for diagram number 198
      CALL FFV6_0(W(1,14),W(1,37),W(1,12),GC_7,AMP(198))
      CALL FFV6_1(W(1,3),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 199
      CALL FFFF14_6_0(W(1,16),W(1,31),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(199))
      CALL FFV6_2(W(1,16),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 200
      CALL FFV2_8_0(W(1,30),W(1,3),W(1,11),GC_651,GC_660,AMP(200))
C     Amplitude(s) for diagram number 201
      CALL FFV11_9_0(W(1,30),W(1,3),W(1,11),GC_721,GC_722,AMP(201))
C     Amplitude(s) for diagram number 202
      CALL FFV4_0(W(1,30),W(1,3),W(1,11),GC_948,AMP(202))
C     Amplitude(s) for diagram number 203
      CALL FFV2_0(W(1,30),W(1,3),W(1,11),GC_938,AMP(203))
      CALL FFV11_9_2(W(1,16),W(1,12),GC_725,GC_726,MDL_MT,MDL_WT,W(1
     $ ,30))
C     Amplitude(s) for diagram number 204
      CALL FFV2_8_0(W(1,30),W(1,3),W(1,11),GC_651,GC_660,AMP(204))
C     Amplitude(s) for diagram number 205
      CALL FFV2_8_0(W(1,16),W(1,31),W(1,11),GC_651,GC_660,AMP(205))
C     Amplitude(s) for diagram number 206
      CALL FFV11_9_0(W(1,16),W(1,31),W(1,11),GC_721,GC_722,AMP(206))
C     Amplitude(s) for diagram number 207
      CALL FFV4_0(W(1,16),W(1,31),W(1,11),GC_948,AMP(207))
C     Amplitude(s) for diagram number 208
      CALL FFV2_0(W(1,16),W(1,31),W(1,11),GC_938,AMP(208))
      CALL FFV11_9_1(W(1,3),W(1,12),GC_725,GC_726,MDL_MT,MDL_WT,W(1,30)
     $ )
C     Amplitude(s) for diagram number 209
      CALL FFV2_8_0(W(1,16),W(1,30),W(1,11),GC_651,GC_660,AMP(209))
      CALL FFV6_2(W(1,32),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 210
      CALL FFV2_8_0(W(1,27),W(1,3),W(1,11),GC_651,GC_660,AMP(210))
C     Amplitude(s) for diagram number 211
      CALL FFV2_8_0(W(1,32),W(1,31),W(1,11),GC_651,GC_660,AMP(211))
C     Amplitude(s) for diagram number 212
      CALL FFV6_0(W(1,16),W(1,26),W(1,12),GC_7,AMP(212))
      CALL VVV1P0_1(W(1,12),W(1,2),GC_6,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 213
      CALL FFV6_0(W(1,4),W(1,17),W(1,27),GC_7,AMP(213))
C     Amplitude(s) for diagram number 214
      CALL FFV11_9_0(W(1,4),W(1,17),W(1,27),GC_725,GC_726,AMP(214))
C     Amplitude(s) for diagram number 215
      CALL FFV6_0(W(1,4),W(1,23),W(1,27),GC_7,AMP(215))
C     Amplitude(s) for diagram number 216
      CALL FFV6_0(W(1,4),W(1,24),W(1,27),GC_7,AMP(216))
C     Amplitude(s) for diagram number 217
      CALL FFV6_0(W(1,4),W(1,25),W(1,27),GC_7,AMP(217))
C     Amplitude(s) for diagram number 218
      CALL FFV6_0(W(1,19),W(1,3),W(1,27),GC_7,AMP(218))
C     Amplitude(s) for diagram number 219
      CALL FFV11_9_0(W(1,19),W(1,3),W(1,27),GC_725,GC_726,AMP(219))
C     Amplitude(s) for diagram number 220
      CALL FFV6_0(W(1,20),W(1,3),W(1,27),GC_7,AMP(220))
C     Amplitude(s) for diagram number 221
      CALL FFV6_0(W(1,21),W(1,3),W(1,27),GC_7,AMP(221))
C     Amplitude(s) for diagram number 222
      CALL FFV6_0(W(1,22),W(1,3),W(1,27),GC_7,AMP(222))
C     Amplitude(s) for diagram number 223
      CALL FFV6_0(W(1,19),W(1,31),W(1,2),GC_7,AMP(223))
C     Amplitude(s) for diagram number 224
      CALL FFV11_9_0(W(1,19),W(1,31),W(1,2),GC_725,GC_726,AMP(224))
C     Amplitude(s) for diagram number 225
      CALL FFV6_0(W(1,20),W(1,31),W(1,2),GC_7,AMP(225))
C     Amplitude(s) for diagram number 226
      CALL FFV6_0(W(1,21),W(1,31),W(1,2),GC_7,AMP(226))
C     Amplitude(s) for diagram number 227
      CALL FFV6_0(W(1,22),W(1,31),W(1,2),GC_7,AMP(227))
C     Amplitude(s) for diagram number 228
      CALL FFV6_0(W(1,19),W(1,30),W(1,2),GC_7,AMP(228))
C     Amplitude(s) for diagram number 229
      CALL FFV6_0(W(1,40),W(1,17),W(1,2),GC_7,AMP(229))
C     Amplitude(s) for diagram number 230
      CALL FFV11_9_0(W(1,40),W(1,17),W(1,2),GC_725,GC_726,AMP(230))
C     Amplitude(s) for diagram number 231
      CALL FFV6_0(W(1,40),W(1,23),W(1,2),GC_7,AMP(231))
C     Amplitude(s) for diagram number 232
      CALL FFV6_0(W(1,40),W(1,24),W(1,2),GC_7,AMP(232))
C     Amplitude(s) for diagram number 233
      CALL FFV6_0(W(1,40),W(1,25),W(1,2),GC_7,AMP(233))
C     Amplitude(s) for diagram number 234
      CALL FFV6_0(W(1,8),W(1,17),W(1,2),GC_7,AMP(234))
      CALL FFVV2_4_1(W(1,3),W(1,12),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,8))
C     Amplitude(s) for diagram number 235
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,11),GC_651,GC_660,AMP(235))
      CALL FFVV2_4_2(W(1,4),W(1,12),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,8))
C     Amplitude(s) for diagram number 236
      CALL FFV2_8_0(W(1,8),W(1,3),W(1,11),GC_651,GC_660,AMP(236))
C     Amplitude(s) for diagram number 237
      CALL FFV6_0(W(1,4),W(1,26),W(1,27),GC_7,AMP(237))
C     Amplitude(s) for diagram number 238
      CALL FFV6_0(W(1,40),W(1,26),W(1,2),GC_7,AMP(238))
C     Amplitude(s) for diagram number 239
      CALL FFV6_0(W(1,14),W(1,3),W(1,27),GC_7,AMP(239))
C     Amplitude(s) for diagram number 240
      CALL FFV6_0(W(1,14),W(1,31),W(1,2),GC_7,AMP(240))
      CALL FFV6_1(W(1,37),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 241
      CALL FFFF14_6_0(W(1,15),W(1,31),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(241))
      CALL FFV6_2(W(1,15),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,27))
C     Amplitude(s) for diagram number 242
      CALL FFFF14_6_0(W(1,27),W(1,37),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(242))
C     Amplitude(s) for diagram number 243
      CALL FFV2_8_0(W(1,15),W(1,31),W(1,11),GC_651,GC_660,AMP(243))
C     Amplitude(s) for diagram number 244
      CALL FFV11_9_0(W(1,15),W(1,31),W(1,11),GC_721,GC_722,AMP(244))
C     Amplitude(s) for diagram number 245
      CALL FFV4_0(W(1,15),W(1,31),W(1,11),GC_948,AMP(245))
C     Amplitude(s) for diagram number 246
      CALL FFV2_0(W(1,15),W(1,31),W(1,11),GC_938,AMP(246))
      CALL FFV11_9_1(W(1,37),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,40)
     $ )
C     Amplitude(s) for diagram number 247
      CALL FFV2_8_0(W(1,15),W(1,40),W(1,11),GC_651,GC_660,AMP(247))
C     Amplitude(s) for diagram number 248
      CALL FFV2_8_0(W(1,27),W(1,37),W(1,11),GC_651,GC_660,AMP(248))
C     Amplitude(s) for diagram number 249
      CALL FFV11_9_0(W(1,27),W(1,37),W(1,11),GC_721,GC_722,AMP(249))
C     Amplitude(s) for diagram number 250
      CALL FFV4_0(W(1,27),W(1,37),W(1,11),GC_948,AMP(250))
C     Amplitude(s) for diagram number 251
      CALL FFV2_0(W(1,27),W(1,37),W(1,11),GC_938,AMP(251))
      CALL FFV11_9_2(W(1,15),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,8))
C     Amplitude(s) for diagram number 252
      CALL FFV2_8_0(W(1,8),W(1,37),W(1,11),GC_651,GC_660,AMP(252))
C     Amplitude(s) for diagram number 253
      CALL FFV2_8_0(W(1,18),W(1,31),W(1,11),GC_651,GC_660,AMP(253))
      CALL FFV6_2(W(1,18),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 254
      CALL FFV2_8_0(W(1,12),W(1,37),W(1,11),GC_651,GC_660,AMP(254))
      CALL FFV6_1(W(1,29),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 255
      CALL FFV2_8_0(W(1,15),W(1,30),W(1,11),GC_651,GC_660,AMP(255))
C     Amplitude(s) for diagram number 256
      CALL FFV2_8_0(W(1,27),W(1,29),W(1,11),GC_651,GC_660,AMP(256))
C     Amplitude(s) for diagram number 257
      CALL FFV6_0(W(1,19),W(1,31),W(1,7),GC_7,AMP(257))
C     Amplitude(s) for diagram number 258
      CALL FFV11_9_0(W(1,19),W(1,31),W(1,7),GC_725,GC_726,AMP(258))
C     Amplitude(s) for diagram number 259
      CALL FFV6_0(W(1,20),W(1,31),W(1,7),GC_7,AMP(259))
C     Amplitude(s) for diagram number 260
      CALL FFV6_0(W(1,21),W(1,31),W(1,7),GC_7,AMP(260))
C     Amplitude(s) for diagram number 261
      CALL FFV6_0(W(1,22),W(1,31),W(1,7),GC_7,AMP(261))
C     Amplitude(s) for diagram number 262
      CALL FFV6_0(W(1,19),W(1,40),W(1,7),GC_7,AMP(262))
      CALL FFV6_1(W(1,37),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 263
      CALL FFV6_0(W(1,19),W(1,40),W(1,1),GC_7,AMP(263))
C     Amplitude(s) for diagram number 264
      CALL FFV11_9_0(W(1,19),W(1,40),W(1,1),GC_725,GC_726,AMP(264))
C     Amplitude(s) for diagram number 265
      CALL FFV6_0(W(1,20),W(1,40),W(1,1),GC_7,AMP(265))
C     Amplitude(s) for diagram number 266
      CALL FFV6_0(W(1,21),W(1,40),W(1,1),GC_7,AMP(266))
C     Amplitude(s) for diagram number 267
      CALL FFV6_0(W(1,22),W(1,40),W(1,1),GC_7,AMP(267))
      CALL FFV11_9_1(W(1,37),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,40)
     $ )
C     Amplitude(s) for diagram number 268
      CALL FFV6_0(W(1,19),W(1,40),W(1,1),GC_7,AMP(268))
      CALL FFVV2_4_1(W(1,37),W(1,1),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,40))
C     Amplitude(s) for diagram number 269
      CALL FFV2_8_0(W(1,4),W(1,40),W(1,11),GC_651,GC_660,AMP(269))
C     Amplitude(s) for diagram number 270
      CALL FFV6_0(W(1,19),W(1,30),W(1,7),GC_7,AMP(270))
      CALL FFV6_1(W(1,29),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 271
      CALL FFV6_0(W(1,19),W(1,30),W(1,1),GC_7,AMP(271))
C     Amplitude(s) for diagram number 272
      CALL FFV6_0(W(1,14),W(1,31),W(1,7),GC_7,AMP(272))
      CALL FFV6_2(W(1,14),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,31))
C     Amplitude(s) for diagram number 273
      CALL FFV6_0(W(1,31),W(1,37),W(1,7),GC_7,AMP(273))
      CALL FFV6_2(W(1,16),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 274
      CALL FFFF14_6_0(W(1,30),W(1,9),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(274))
      CALL FFV6_1(W(1,9),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,29))
C     Amplitude(s) for diagram number 275
      CALL FFFF14_6_0(W(1,16),W(1,29),W(1,6),W(1,5),GC_586,GC_124
     $ ,AMP(275))
C     Amplitude(s) for diagram number 276
      CALL FFV2_8_0(W(1,30),W(1,9),W(1,11),GC_651,GC_660,AMP(276))
C     Amplitude(s) for diagram number 277
      CALL FFV11_9_0(W(1,30),W(1,9),W(1,11),GC_721,GC_722,AMP(277))
C     Amplitude(s) for diagram number 278
      CALL FFV4_0(W(1,30),W(1,9),W(1,11),GC_948,AMP(278))
C     Amplitude(s) for diagram number 279
      CALL FFV2_0(W(1,30),W(1,9),W(1,11),GC_938,AMP(279))
      CALL FFV11_9_2(W(1,16),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 280
      CALL FFV2_8_0(W(1,6),W(1,9),W(1,11),GC_651,GC_660,AMP(280))
C     Amplitude(s) for diagram number 281
      CALL FFV2_8_0(W(1,16),W(1,29),W(1,11),GC_651,GC_660,AMP(281))
C     Amplitude(s) for diagram number 282
      CALL FFV11_9_0(W(1,16),W(1,29),W(1,11),GC_721,GC_722,AMP(282))
C     Amplitude(s) for diagram number 283
      CALL FFV4_0(W(1,16),W(1,29),W(1,11),GC_948,AMP(283))
C     Amplitude(s) for diagram number 284
      CALL FFV2_0(W(1,16),W(1,29),W(1,11),GC_938,AMP(284))
      CALL FFV11_9_1(W(1,9),W(1,1),GC_725,GC_726,MDL_MT,MDL_WT,W(1,5))
C     Amplitude(s) for diagram number 285
      CALL FFV2_8_0(W(1,16),W(1,5),W(1,11),GC_651,GC_660,AMP(285))
C     Amplitude(s) for diagram number 286
      CALL FFV2_8_0(W(1,30),W(1,13),W(1,11),GC_651,GC_660,AMP(286))
      CALL FFV6_1(W(1,13),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 287
      CALL FFV2_8_0(W(1,16),W(1,40),W(1,11),GC_651,GC_660,AMP(287))
      CALL FFV6_2(W(1,32),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,38))
C     Amplitude(s) for diagram number 288
      CALL FFV2_8_0(W(1,38),W(1,9),W(1,11),GC_651,GC_660,AMP(288))
C     Amplitude(s) for diagram number 289
      CALL FFV2_8_0(W(1,32),W(1,29),W(1,11),GC_651,GC_660,AMP(289))
C     Amplitude(s) for diagram number 290
      CALL FFV6_0(W(1,30),W(1,17),W(1,7),GC_7,AMP(290))
C     Amplitude(s) for diagram number 291
      CALL FFV11_9_0(W(1,30),W(1,17),W(1,7),GC_725,GC_726,AMP(291))
C     Amplitude(s) for diagram number 292
      CALL FFV6_0(W(1,30),W(1,23),W(1,7),GC_7,AMP(292))
C     Amplitude(s) for diagram number 293
      CALL FFV6_0(W(1,30),W(1,24),W(1,7),GC_7,AMP(293))
C     Amplitude(s) for diagram number 294
      CALL FFV6_0(W(1,30),W(1,25),W(1,7),GC_7,AMP(294))
C     Amplitude(s) for diagram number 295
      CALL FFV6_0(W(1,6),W(1,17),W(1,7),GC_7,AMP(295))
      CALL FFV6_2(W(1,16),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 296
      CALL FFV6_0(W(1,6),W(1,17),W(1,1),GC_7,AMP(296))
C     Amplitude(s) for diagram number 297
      CALL FFV11_9_0(W(1,6),W(1,17),W(1,1),GC_725,GC_726,AMP(297))
C     Amplitude(s) for diagram number 298
      CALL FFV6_0(W(1,6),W(1,23),W(1,1),GC_7,AMP(298))
C     Amplitude(s) for diagram number 299
      CALL FFV6_0(W(1,6),W(1,24),W(1,1),GC_7,AMP(299))
C     Amplitude(s) for diagram number 300
      CALL FFV6_0(W(1,6),W(1,25),W(1,1),GC_7,AMP(300))
      CALL FFV11_9_2(W(1,16),W(1,7),GC_725,GC_726,MDL_MT,MDL_WT,W(1,6))
C     Amplitude(s) for diagram number 301
      CALL FFV6_0(W(1,6),W(1,17),W(1,1),GC_7,AMP(301))
      CALL FFVV2_4_2(W(1,16),W(1,1),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,6))
C     Amplitude(s) for diagram number 302
      CALL FFV2_8_0(W(1,6),W(1,3),W(1,11),GC_651,GC_660,AMP(302))
C     Amplitude(s) for diagram number 303
      CALL FFV6_0(W(1,38),W(1,17),W(1,7),GC_7,AMP(303))
      CALL FFV6_2(W(1,32),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,38))
C     Amplitude(s) for diagram number 304
      CALL FFV6_0(W(1,38),W(1,17),W(1,1),GC_7,AMP(304))
C     Amplitude(s) for diagram number 305
      CALL FFV6_0(W(1,30),W(1,26),W(1,7),GC_7,AMP(305))
      CALL FFV6_1(W(1,26),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,30))
C     Amplitude(s) for diagram number 306
      CALL FFV6_0(W(1,16),W(1,30),W(1,7),GC_7,AMP(306))
      CALL VVV1P0_1(W(1,1),W(1,36),GC_6,ZERO,ZERO,W(1,38))
C     Amplitude(s) for diagram number 307
      CALL FFV6_0(W(1,4),W(1,17),W(1,38),GC_7,AMP(307))
C     Amplitude(s) for diagram number 308
      CALL FFV11_9_0(W(1,4),W(1,17),W(1,38),GC_725,GC_726,AMP(308))
C     Amplitude(s) for diagram number 309
      CALL FFV6_0(W(1,4),W(1,23),W(1,38),GC_7,AMP(309))
C     Amplitude(s) for diagram number 310
      CALL FFV6_0(W(1,4),W(1,24),W(1,38),GC_7,AMP(310))
C     Amplitude(s) for diagram number 311
      CALL FFV6_0(W(1,4),W(1,25),W(1,38),GC_7,AMP(311))
C     Amplitude(s) for diagram number 312
      CALL FFV6_0(W(1,19),W(1,3),W(1,38),GC_7,AMP(312))
C     Amplitude(s) for diagram number 313
      CALL FFV11_9_0(W(1,19),W(1,3),W(1,38),GC_725,GC_726,AMP(313))
C     Amplitude(s) for diagram number 314
      CALL FFV6_0(W(1,20),W(1,3),W(1,38),GC_7,AMP(314))
C     Amplitude(s) for diagram number 315
      CALL FFV6_0(W(1,21),W(1,3),W(1,38),GC_7,AMP(315))
C     Amplitude(s) for diagram number 316
      CALL FFV6_0(W(1,22),W(1,3),W(1,38),GC_7,AMP(316))
      CALL FFV6_1(W(1,3),W(1,36),GC_7,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 317
      CALL FFV6_0(W(1,19),W(1,32),W(1,1),GC_7,AMP(317))
C     Amplitude(s) for diagram number 318
      CALL FFV11_9_0(W(1,19),W(1,32),W(1,1),GC_725,GC_726,AMP(318))
C     Amplitude(s) for diagram number 319
      CALL FFV6_0(W(1,20),W(1,32),W(1,1),GC_7,AMP(319))
C     Amplitude(s) for diagram number 320
      CALL FFV6_0(W(1,21),W(1,32),W(1,1),GC_7,AMP(320))
C     Amplitude(s) for diagram number 321
      CALL FFV6_0(W(1,22),W(1,32),W(1,1),GC_7,AMP(321))
      CALL FFV11_9_1(W(1,3),W(1,36),GC_725,GC_726,MDL_MT,MDL_WT,W(1,32)
     $ )
C     Amplitude(s) for diagram number 322
      CALL FFV6_0(W(1,19),W(1,32),W(1,1),GC_7,AMP(322))
      CALL FFV6_2(W(1,4),W(1,36),GC_7,MDL_MT,MDL_WT,W(1,32))
C     Amplitude(s) for diagram number 323
      CALL FFV6_0(W(1,32),W(1,17),W(1,1),GC_7,AMP(323))
C     Amplitude(s) for diagram number 324
      CALL FFV11_9_0(W(1,32),W(1,17),W(1,1),GC_725,GC_726,AMP(324))
C     Amplitude(s) for diagram number 325
      CALL FFV6_0(W(1,32),W(1,23),W(1,1),GC_7,AMP(325))
C     Amplitude(s) for diagram number 326
      CALL FFV6_0(W(1,32),W(1,24),W(1,1),GC_7,AMP(326))
C     Amplitude(s) for diagram number 327
      CALL FFV6_0(W(1,32),W(1,25),W(1,1),GC_7,AMP(327))
      CALL FFV11_9_2(W(1,4),W(1,36),GC_725,GC_726,MDL_MT,MDL_WT,W(1,32)
     $ )
C     Amplitude(s) for diagram number 328
      CALL FFV6_0(W(1,32),W(1,17),W(1,1),GC_7,AMP(328))
      CALL FFVV2_4_1(W(1,3),W(1,1),W(1,36),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,32))
C     Amplitude(s) for diagram number 329
      CALL FFV2_8_0(W(1,4),W(1,32),W(1,11),GC_651,GC_660,AMP(329))
      CALL FFVV2_4_2(W(1,4),W(1,1),W(1,36),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,32))
C     Amplitude(s) for diagram number 330
      CALL FFV2_8_0(W(1,32),W(1,3),W(1,11),GC_651,GC_660,AMP(330))
C     Amplitude(s) for diagram number 331
      CALL FFV6_0(W(1,4),W(1,26),W(1,38),GC_7,AMP(331))
C     Amplitude(s) for diagram number 332
      CALL FFV6_0(W(1,4),W(1,30),W(1,36),GC_7,AMP(332))
C     Amplitude(s) for diagram number 333
      CALL FFV6_0(W(1,14),W(1,3),W(1,38),GC_7,AMP(333))
C     Amplitude(s) for diagram number 334
      CALL FFV6_0(W(1,31),W(1,3),W(1,36),GC_7,AMP(334))
C     Amplitude(s) for diagram number 335
      CALL FFV6_0(W(1,19),W(1,29),W(1,2),GC_7,AMP(335))
C     Amplitude(s) for diagram number 336
      CALL FFV11_9_0(W(1,19),W(1,29),W(1,2),GC_725,GC_726,AMP(336))
C     Amplitude(s) for diagram number 337
      CALL FFV6_0(W(1,20),W(1,29),W(1,2),GC_7,AMP(337))
C     Amplitude(s) for diagram number 338
      CALL FFV6_0(W(1,21),W(1,29),W(1,2),GC_7,AMP(338))
C     Amplitude(s) for diagram number 339
      CALL FFV6_0(W(1,22),W(1,29),W(1,2),GC_7,AMP(339))
C     Amplitude(s) for diagram number 340
      CALL FFV6_0(W(1,19),W(1,5),W(1,2),GC_7,AMP(340))
      CALL FFV6_1(W(1,9),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,5))
C     Amplitude(s) for diagram number 341
      CALL FFV6_0(W(1,19),W(1,5),W(1,1),GC_7,AMP(341))
C     Amplitude(s) for diagram number 342
      CALL FFV11_9_0(W(1,19),W(1,5),W(1,1),GC_725,GC_726,AMP(342))
C     Amplitude(s) for diagram number 343
      CALL FFV6_0(W(1,20),W(1,5),W(1,1),GC_7,AMP(343))
C     Amplitude(s) for diagram number 344
      CALL FFV6_0(W(1,21),W(1,5),W(1,1),GC_7,AMP(344))
C     Amplitude(s) for diagram number 345
      CALL FFV6_0(W(1,22),W(1,5),W(1,1),GC_7,AMP(345))
      CALL FFV11_9_1(W(1,9),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,5))
C     Amplitude(s) for diagram number 346
      CALL FFV6_0(W(1,19),W(1,5),W(1,1),GC_7,AMP(346))
      CALL FFVV2_4_1(W(1,9),W(1,1),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,5))
C     Amplitude(s) for diagram number 347
      CALL FFV2_8_0(W(1,4),W(1,5),W(1,11),GC_651,GC_660,AMP(347))
C     Amplitude(s) for diagram number 348
      CALL FFV6_0(W(1,19),W(1,40),W(1,2),GC_7,AMP(348))
      CALL FFV6_1(W(1,13),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,40))
C     Amplitude(s) for diagram number 349
      CALL FFV6_0(W(1,19),W(1,40),W(1,1),GC_7,AMP(349))
C     Amplitude(s) for diagram number 350
      CALL FFV6_0(W(1,14),W(1,29),W(1,2),GC_7,AMP(350))
C     Amplitude(s) for diagram number 351
      CALL FFV6_0(W(1,31),W(1,9),W(1,2),GC_7,AMP(351))
C     Amplitude(s) for diagram number 352
      CALL FFV6_0(W(1,27),W(1,17),W(1,2),GC_7,AMP(352))
C     Amplitude(s) for diagram number 353
      CALL FFV11_9_0(W(1,27),W(1,17),W(1,2),GC_725,GC_726,AMP(353))
C     Amplitude(s) for diagram number 354
      CALL FFV6_0(W(1,27),W(1,23),W(1,2),GC_7,AMP(354))
C     Amplitude(s) for diagram number 355
      CALL FFV6_0(W(1,27),W(1,24),W(1,2),GC_7,AMP(355))
C     Amplitude(s) for diagram number 356
      CALL FFV6_0(W(1,27),W(1,25),W(1,2),GC_7,AMP(356))
C     Amplitude(s) for diagram number 357
      CALL FFV6_0(W(1,8),W(1,17),W(1,2),GC_7,AMP(357))
      CALL FFV6_2(W(1,15),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,8))
C     Amplitude(s) for diagram number 358
      CALL FFV6_0(W(1,8),W(1,17),W(1,1),GC_7,AMP(358))
C     Amplitude(s) for diagram number 359
      CALL FFV11_9_0(W(1,8),W(1,17),W(1,1),GC_725,GC_726,AMP(359))
C     Amplitude(s) for diagram number 360
      CALL FFV6_0(W(1,8),W(1,23),W(1,1),GC_7,AMP(360))
C     Amplitude(s) for diagram number 361
      CALL FFV6_0(W(1,8),W(1,24),W(1,1),GC_7,AMP(361))
C     Amplitude(s) for diagram number 362
      CALL FFV6_0(W(1,8),W(1,25),W(1,1),GC_7,AMP(362))
      CALL FFV11_9_2(W(1,15),W(1,2),GC_725,GC_726,MDL_MT,MDL_WT,W(1,8))
C     Amplitude(s) for diagram number 363
      CALL FFV6_0(W(1,8),W(1,17),W(1,1),GC_7,AMP(363))
      CALL FFVV2_4_2(W(1,15),W(1,1),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,8))
C     Amplitude(s) for diagram number 364
      CALL FFV2_8_0(W(1,8),W(1,3),W(1,11),GC_651,GC_660,AMP(364))
C     Amplitude(s) for diagram number 365
      CALL FFV6_0(W(1,12),W(1,17),W(1,2),GC_7,AMP(365))
      CALL FFV6_2(W(1,18),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,12))
C     Amplitude(s) for diagram number 366
      CALL FFV6_0(W(1,12),W(1,17),W(1,1),GC_7,AMP(366))
      CALL FFVV2_4_1(W(1,3),W(1,1),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,12))
C     Amplitude(s) for diagram number 367
      CALL FFV2_8_0(W(1,15),W(1,12),W(1,11),GC_651,GC_660,AMP(367))
      CALL FFV6_1(W(1,12),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 368
      CALL FFV2_8_0(W(1,4),W(1,17),W(1,11),GC_651,GC_660,AMP(368))
      CALL FFVV2_4_2(W(1,4),W(1,1),W(1,2),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,17))
C     Amplitude(s) for diagram number 369
      CALL FFV2_8_0(W(1,17),W(1,9),W(1,11),GC_651,GC_660,AMP(369))
      CALL FFV6_2(W(1,17),W(1,7),GC_7,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 370
      CALL FFV2_8_0(W(1,9),W(1,3),W(1,11),GC_651,GC_660,AMP(370))
      CALL VVVV1P0_1(W(1,1),W(1,2),W(1,7),GC_8,ZERO,ZERO,W(1,9))
      CALL VVVV3P0_1(W(1,1),W(1,2),W(1,7),GC_8,ZERO,ZERO,W(1,17))
      CALL VVVV4P0_1(W(1,1),W(1,2),W(1,7),GC_8,ZERO,ZERO,W(1,12))
      CALL FFV6_1(W(1,3),W(1,9),GC_7,MDL_MT,MDL_WT,W(1,18))
      CALL FFV6_1(W(1,3),W(1,17),GC_7,MDL_MT,MDL_WT,W(1,8))
      CALL FFV6_1(W(1,3),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 371
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,11),GC_651,GC_660,AMP(371))
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,11),GC_651,GC_660,AMP(372))
      CALL FFV2_8_0(W(1,4),W(1,25),W(1,11),GC_651,GC_660,AMP(373))
C     Amplitude(s) for diagram number 372
      CALL FFV11_9_0(W(1,4),W(1,18),W(1,11),GC_721,GC_722,AMP(374))
      CALL FFV11_9_0(W(1,4),W(1,8),W(1,11),GC_721,GC_722,AMP(375))
      CALL FFV11_9_0(W(1,4),W(1,25),W(1,11),GC_721,GC_722,AMP(376))
C     Amplitude(s) for diagram number 373
      CALL FFV4_0(W(1,4),W(1,18),W(1,11),GC_948,AMP(377))
      CALL FFV4_0(W(1,4),W(1,8),W(1,11),GC_948,AMP(378))
      CALL FFV4_0(W(1,4),W(1,25),W(1,11),GC_948,AMP(379))
C     Amplitude(s) for diagram number 374
      CALL FFV2_0(W(1,4),W(1,18),W(1,11),GC_938,AMP(380))
      CALL FFV2_0(W(1,4),W(1,8),W(1,11),GC_938,AMP(381))
      CALL FFV2_0(W(1,4),W(1,25),W(1,11),GC_938,AMP(382))
      CALL FFV11_9_1(W(1,3),W(1,9),GC_725,GC_726,MDL_MT,MDL_WT,W(1,25))
      CALL FFV11_9_1(W(1,3),W(1,17),GC_725,GC_726,MDL_MT,MDL_WT,W(1,8))
      CALL FFV11_9_1(W(1,3),W(1,12),GC_725,GC_726,MDL_MT,MDL_WT,W(1,18)
     $ )
C     Amplitude(s) for diagram number 375
      CALL FFV2_8_0(W(1,4),W(1,25),W(1,11),GC_651,GC_660,AMP(383))
      CALL FFV2_8_0(W(1,4),W(1,8),W(1,11),GC_651,GC_660,AMP(384))
      CALL FFV2_8_0(W(1,4),W(1,18),W(1,11),GC_651,GC_660,AMP(385))
      CALL FFV6_2(W(1,4),W(1,9),GC_7,MDL_MT,MDL_WT,W(1,18))
      CALL FFV6_2(W(1,4),W(1,17),GC_7,MDL_MT,MDL_WT,W(1,8))
      CALL FFV6_2(W(1,4),W(1,12),GC_7,MDL_MT,MDL_WT,W(1,25))
C     Amplitude(s) for diagram number 376
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,11),GC_651,GC_660,AMP(386))
      CALL FFV2_8_0(W(1,8),W(1,3),W(1,11),GC_651,GC_660,AMP(387))
      CALL FFV2_8_0(W(1,25),W(1,3),W(1,11),GC_651,GC_660,AMP(388))
C     Amplitude(s) for diagram number 377
      CALL FFV11_9_0(W(1,18),W(1,3),W(1,11),GC_721,GC_722,AMP(389))
      CALL FFV11_9_0(W(1,8),W(1,3),W(1,11),GC_721,GC_722,AMP(390))
      CALL FFV11_9_0(W(1,25),W(1,3),W(1,11),GC_721,GC_722,AMP(391))
C     Amplitude(s) for diagram number 378
      CALL FFV4_0(W(1,18),W(1,3),W(1,11),GC_948,AMP(392))
      CALL FFV4_0(W(1,8),W(1,3),W(1,11),GC_948,AMP(393))
      CALL FFV4_0(W(1,25),W(1,3),W(1,11),GC_948,AMP(394))
C     Amplitude(s) for diagram number 379
      CALL FFV2_0(W(1,18),W(1,3),W(1,11),GC_938,AMP(395))
      CALL FFV2_0(W(1,8),W(1,3),W(1,11),GC_938,AMP(396))
      CALL FFV2_0(W(1,25),W(1,3),W(1,11),GC_938,AMP(397))
      CALL FFV11_9_2(W(1,4),W(1,9),GC_725,GC_726,MDL_MT,MDL_WT,W(1,25))
      CALL FFV11_9_2(W(1,4),W(1,17),GC_725,GC_726,MDL_MT,MDL_WT,W(1,8))
      CALL FFV11_9_2(W(1,4),W(1,12),GC_725,GC_726,MDL_MT,MDL_WT,W(1,18)
     $ )
C     Amplitude(s) for diagram number 380
      CALL FFV2_8_0(W(1,25),W(1,3),W(1,11),GC_651,GC_660,AMP(398))
      CALL FFV2_8_0(W(1,8),W(1,3),W(1,11),GC_651,GC_660,AMP(399))
      CALL FFV2_8_0(W(1,18),W(1,3),W(1,11),GC_651,GC_660,AMP(400))
C     Amplitude(s) for diagram number 381
      CALL FFV6_0(W(1,4),W(1,26),W(1,9),GC_7,AMP(401))
      CALL FFV6_0(W(1,4),W(1,26),W(1,17),GC_7,AMP(402))
      CALL FFV6_0(W(1,4),W(1,26),W(1,12),GC_7,AMP(403))
C     Amplitude(s) for diagram number 382
      CALL FFV6_0(W(1,14),W(1,3),W(1,9),GC_7,AMP(404))
      CALL FFV6_0(W(1,14),W(1,3),W(1,17),GC_7,AMP(405))
      CALL FFV6_0(W(1,14),W(1,3),W(1,12),GC_7,AMP(406))
      CALL FFVV2_4_1(W(1,3),W(1,1),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,12))
C     Amplitude(s) for diagram number 383
      CALL FFV2_8_0(W(1,16),W(1,12),W(1,11),GC_651,GC_660,AMP(407))
      CALL FFV6_1(W(1,12),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,16))
C     Amplitude(s) for diagram number 384
      CALL FFV2_8_0(W(1,4),W(1,16),W(1,11),GC_651,GC_660,AMP(408))
      CALL FFVV2_4_2(W(1,4),W(1,1),W(1,7),GC_728,GC_727,MDL_MT,MDL_WT
     $ ,W(1,16))
C     Amplitude(s) for diagram number 385
      CALL FFV2_8_0(W(1,16),W(1,37),W(1,11),GC_651,GC_660,AMP(409))
      CALL FFV6_2(W(1,16),W(1,2),GC_7,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 386
      CALL FFV2_8_0(W(1,37),W(1,3),W(1,11),GC_651,GC_660,AMP(410))
      CALL FFV6_1(W(1,39),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 387
      CALL FFV2_8_0(W(1,4),W(1,37),W(1,11),GC_651,GC_660,AMP(411))
      CALL FFV6_2(W(1,35),W(1,1),GC_7,MDL_MT,MDL_WT,W(1,37))
C     Amplitude(s) for diagram number 388
      CALL FFV2_8_0(W(1,37),W(1,3),W(1,11),GC_651,GC_660,AMP(412))
C     Amplitude(s) for diagram number 389
      CALL FFV6_0(W(1,15),W(1,30),W(1,2),GC_7,AMP(413))
C     Amplitude(s) for diagram number 390
      CALL FFV6_0(W(1,27),W(1,26),W(1,2),GC_7,AMP(414))
      JAMP(1)=-IMAG1*AMP(15)-IMAG1*AMP(16)-IMAG1*AMP(17)-IMAG1*AMP(18)
     $ -IMAG1*AMP(19)-IMAG1*AMP(20)-IMAG1*AMP(21)-IMAG1*AMP(22)-IMAG1
     $ *AMP(23)-IMAG1*AMP(24)-IMAG1*AMP(25)-IMAG1*AMP(26)-IMAG1*AMP(27)
     $ -IMAG1*AMP(28)-IMAG1*AMP(29)-IMAG1*AMP(30)-IMAG1*AMP(31)-IMAG1
     $ *AMP(32)-IMAG1*AMP(33)-AMP(40)-AMP(41)-AMP(42)-AMP(43)-AMP(44)
     $ -AMP(45)-AMP(46)-AMP(47)-AMP(48)-AMP(49)-AMP(50)-AMP(51)-AMP(53)
     $ -IMAG1*AMP(54)-IMAG1*AMP(55)-AMP(56)-IMAG1*AMP(73)-IMAG1*AMP(74)
     $ -IMAG1*AMP(75)-IMAG1*AMP(76)-IMAG1*AMP(77)-IMAG1*AMP(78)-IMAG1
     $ *AMP(79)-IMAG1*AMP(80)-IMAG1*AMP(81)-IMAG1*AMP(82)-IMAG1*AMP(83)
     $ -IMAG1*AMP(84)-IMAG1*AMP(85)-IMAG1*AMP(86)+AMP(87)+AMP(88)
     $ +AMP(89)+AMP(90)+AMP(91)+AMP(92)+AMP(93)+AMP(94)+AMP(95)+AMP(96)
     $ +AMP(97)+AMP(98)+AMP(99)+AMP(100)+AMP(101)+AMP(102)+AMP(103)
     $ +AMP(104)+AMP(105)+AMP(106)+AMP(107)+AMP(108)-IMAG1*AMP(115)
     $ +AMP(116)-IMAG1*AMP(118)+AMP(119)-AMP(307)-AMP(308)-AMP(309)
     $ -AMP(310)-AMP(311)-AMP(312)-AMP(313)-AMP(314)-AMP(315)-AMP(316)
     $ -IMAG1*AMP(323)-IMAG1*AMP(324)-IMAG1*AMP(325)-IMAG1*AMP(326)
     $ -IMAG1*AMP(327)-IMAG1*AMP(328)-AMP(329)-AMP(330)-AMP(331)-IMAG1
     $ *AMP(332)-AMP(333)+AMP(358)+AMP(359)+AMP(360)+AMP(361)+AMP(362)
     $ +AMP(363)-IMAG1*AMP(364)+AMP(366)-IMAG1*AMP(367)-IMAG1*AMP(368)
     $ -AMP(371)+AMP(373)-AMP(374)+AMP(376)-AMP(377)+AMP(379)-AMP(380)
     $ +AMP(382)-AMP(383)+AMP(385)-AMP(386)+AMP(388)-AMP(389)+AMP(391)
     $ -AMP(392)+AMP(394)-AMP(395)+AMP(397)-AMP(398)+AMP(400)+AMP(403)
     $ -AMP(401)+AMP(406)-AMP(404)-IMAG1*AMP(412)+AMP(413)
      JAMP(2)=+AMP(57)+AMP(58)+AMP(59)+AMP(60)+AMP(61)+AMP(62)+AMP(63)
     $ +AMP(64)+AMP(65)+AMP(66)+AMP(67)+AMP(68)+AMP(69)+AMP(70)+AMP(71)
     $ +AMP(72)+IMAG1*AMP(73)+IMAG1*AMP(74)+IMAG1*AMP(75)+IMAG1*AMP(76)
     $ +IMAG1*AMP(77)+IMAG1*AMP(78)+IMAG1*AMP(79)+IMAG1*AMP(80)+IMAG1
     $ *AMP(81)+IMAG1*AMP(82)+IMAG1*AMP(83)+IMAG1*AMP(84)+IMAG1*AMP(85)
     $ +IMAG1*AMP(86)+AMP(109)+AMP(110)+AMP(111)+AMP(112)+AMP(113)
     $ +AMP(114)+IMAG1*AMP(115)+AMP(117)+IMAG1*AMP(118)+AMP(120)-IMAG1
     $ *AMP(199)-IMAG1*AMP(200)-IMAG1*AMP(201)-IMAG1*AMP(202)-IMAG1
     $ *AMP(203)-IMAG1*AMP(204)-IMAG1*AMP(205)-IMAG1*AMP(206)-IMAG1
     $ *AMP(207)-IMAG1*AMP(208)-IMAG1*AMP(209)-IMAG1*AMP(210)-IMAG1
     $ *AMP(211)-IMAG1*AMP(212)-AMP(213)-AMP(214)-AMP(215)-AMP(216)
     $ -AMP(217)-AMP(218)-AMP(219)-AMP(220)-AMP(221)-AMP(222)-IMAG1
     $ *AMP(223)-IMAG1*AMP(224)-IMAG1*AMP(225)-IMAG1*AMP(226)-IMAG1
     $ *AMP(227)-IMAG1*AMP(228)-AMP(235)-AMP(236)-AMP(237)-AMP(239)
     $ -IMAG1*AMP(240)+AMP(296)+AMP(297)+AMP(298)+AMP(299)+AMP(300)
     $ +AMP(301)-IMAG1*AMP(302)+AMP(304)+AMP(306)+AMP(307)+AMP(308)
     $ +AMP(309)+AMP(310)+AMP(311)+AMP(312)+AMP(313)+AMP(314)+AMP(315)
     $ +AMP(316)+IMAG1*AMP(323)+IMAG1*AMP(324)+IMAG1*AMP(325)+IMAG1
     $ *AMP(326)+IMAG1*AMP(327)+IMAG1*AMP(328)+AMP(329)+AMP(330)
     $ +AMP(331)+IMAG1*AMP(332)+AMP(333)+AMP(371)+AMP(372)+AMP(374)
     $ +AMP(375)+AMP(377)+AMP(378)+AMP(380)+AMP(381)+AMP(383)+AMP(384)
     $ +AMP(386)+AMP(387)+AMP(389)+AMP(390)+AMP(392)+AMP(393)+AMP(395)
     $ +AMP(396)+AMP(398)+AMP(399)+AMP(402)+AMP(401)+AMP(405)+AMP(404)
     $ -IMAG1*AMP(407)-IMAG1*AMP(408)+IMAG1*AMP(412)
      JAMP(3)=+IMAG1*AMP(15)+IMAG1*AMP(16)+IMAG1*AMP(17)+IMAG1*AMP(18)
     $ +IMAG1*AMP(19)+IMAG1*AMP(20)+IMAG1*AMP(21)+IMAG1*AMP(22)+IMAG1
     $ *AMP(23)+IMAG1*AMP(24)+IMAG1*AMP(25)+IMAG1*AMP(26)+IMAG1*AMP(27)
     $ +IMAG1*AMP(28)+IMAG1*AMP(29)+IMAG1*AMP(30)+IMAG1*AMP(31)+IMAG1
     $ *AMP(32)+IMAG1*AMP(33)+AMP(40)+AMP(41)+AMP(42)+AMP(43)+AMP(44)
     $ +AMP(45)+AMP(46)+AMP(47)+AMP(48)+AMP(49)+AMP(50)+AMP(51)+AMP(53)
     $ +IMAG1*AMP(54)+IMAG1*AMP(55)+AMP(56)-IMAG1*AMP(185)-IMAG1
     $ *AMP(186)-IMAG1*AMP(187)-IMAG1*AMP(188)-IMAG1*AMP(189)-IMAG1
     $ *AMP(190)-IMAG1*AMP(191)-IMAG1*AMP(192)-IMAG1*AMP(193)-IMAG1
     $ *AMP(194)-IMAG1*AMP(195)-IMAG1*AMP(196)-IMAG1*AMP(197)-IMAG1
     $ *AMP(198)+AMP(213)+AMP(214)+AMP(215)+AMP(216)+AMP(217)+AMP(218)
     $ +AMP(219)+AMP(220)+AMP(221)+AMP(222)-IMAG1*AMP(229)-IMAG1
     $ *AMP(230)-IMAG1*AMP(231)-IMAG1*AMP(232)-IMAG1*AMP(233)-IMAG1
     $ *AMP(234)+AMP(235)+AMP(236)+AMP(237)-IMAG1*AMP(238)+AMP(239)
     $ +AMP(241)+AMP(242)+AMP(243)+AMP(244)+AMP(245)+AMP(246)+AMP(247)
     $ +AMP(248)+AMP(249)+AMP(250)+AMP(251)+AMP(252)+AMP(253)+AMP(254)
     $ +AMP(255)+AMP(256)+AMP(257)+AMP(258)+AMP(259)+AMP(260)+AMP(261)
     $ +AMP(262)-IMAG1*AMP(269)+AMP(270)+AMP(272)+AMP(352)+AMP(353)
     $ +AMP(354)+AMP(355)+AMP(356)+AMP(357)+IMAG1*AMP(364)+AMP(365)
     $ +IMAG1*AMP(367)+IMAG1*AMP(368)-AMP(372)-AMP(373)-AMP(375)
     $ -AMP(376)-AMP(378)-AMP(379)-AMP(381)-AMP(382)-AMP(384)-AMP(385)
     $ -AMP(387)-AMP(388)-AMP(390)-AMP(391)-AMP(393)-AMP(394)-AMP(396)
     $ -AMP(397)-AMP(399)-AMP(400)-AMP(403)-AMP(402)-AMP(406)-AMP(405)
     $ -IMAG1*AMP(409)-IMAG1*AMP(410)+AMP(414)
      JAMP(4)=+AMP(121)+AMP(122)+AMP(123)+AMP(124)+AMP(125)+AMP(126)
     $ +AMP(127)+AMP(128)+AMP(129)+AMP(130)+AMP(131)+AMP(132)+AMP(133)
     $ +AMP(134)+AMP(135)+AMP(136)-IMAG1*AMP(137)-IMAG1*AMP(138)-IMAG1
     $ *AMP(139)-IMAG1*AMP(140)-IMAG1*AMP(141)-IMAG1*AMP(142)-IMAG1
     $ *AMP(143)-IMAG1*AMP(144)-IMAG1*AMP(145)-IMAG1*AMP(146)-IMAG1
     $ *AMP(147)-IMAG1*AMP(148)-IMAG1*AMP(149)-IMAG1*AMP(150)+AMP(173)
     $ +AMP(174)+AMP(175)+AMP(176)+AMP(177)+AMP(178)-IMAG1*AMP(179)
     $ +AMP(181)-IMAG1*AMP(182)+AMP(184)+IMAG1*AMP(185)+IMAG1*AMP(186)
     $ +IMAG1*AMP(187)+IMAG1*AMP(188)+IMAG1*AMP(189)+IMAG1*AMP(190)
     $ +IMAG1*AMP(191)+IMAG1*AMP(192)+IMAG1*AMP(193)+IMAG1*AMP(194)
     $ +IMAG1*AMP(195)+IMAG1*AMP(196)+IMAG1*AMP(197)+IMAG1*AMP(198)
     $ -AMP(213)-AMP(214)-AMP(215)-AMP(216)-AMP(217)-AMP(218)-AMP(219)
     $ -AMP(220)-AMP(221)-AMP(222)+IMAG1*AMP(229)+IMAG1*AMP(230)+IMAG1
     $ *AMP(231)+IMAG1*AMP(232)+IMAG1*AMP(233)+IMAG1*AMP(234)-AMP(235)
     $ -AMP(236)-AMP(237)+IMAG1*AMP(238)-AMP(239)+AMP(263)+AMP(264)
     $ +AMP(265)+AMP(266)+AMP(267)+AMP(268)+IMAG1*AMP(269)+AMP(271)
     $ +AMP(273)+AMP(307)+AMP(308)+AMP(309)+AMP(310)+AMP(311)+AMP(312)
     $ +AMP(313)+AMP(314)+AMP(315)+AMP(316)-IMAG1*AMP(317)-IMAG1
     $ *AMP(318)-IMAG1*AMP(319)-IMAG1*AMP(320)-IMAG1*AMP(321)-IMAG1
     $ *AMP(322)+AMP(329)+AMP(330)+AMP(331)+AMP(333)-IMAG1*AMP(334)
     $ +AMP(371)+AMP(372)+AMP(374)+AMP(375)+AMP(377)+AMP(378)+AMP(380)
     $ +AMP(381)+AMP(383)+AMP(384)+AMP(386)+AMP(387)+AMP(389)+AMP(390)
     $ +AMP(392)+AMP(393)+AMP(395)+AMP(396)+AMP(398)+AMP(399)+AMP(402)
     $ +AMP(401)+AMP(405)+AMP(404)+IMAG1*AMP(409)+IMAG1*AMP(410)-IMAG1
     $ *AMP(411)
      JAMP(5)=-IMAG1*AMP(1)-IMAG1*AMP(2)-IMAG1*AMP(3)-IMAG1*AMP(4)
     $ -IMAG1*AMP(5)-IMAG1*AMP(6)-IMAG1*AMP(7)-IMAG1*AMP(8)-IMAG1
     $ *AMP(9)-IMAG1*AMP(10)-IMAG1*AMP(11)-IMAG1*AMP(12)-IMAG1*AMP(13)
     $ -IMAG1*AMP(14)-IMAG1*AMP(34)-IMAG1*AMP(35)-IMAG1*AMP(36)-IMAG1
     $ *AMP(37)-IMAG1*AMP(38)-IMAG1*AMP(39)+AMP(40)+AMP(41)+AMP(42)
     $ +AMP(43)+AMP(44)+AMP(45)+AMP(46)+AMP(47)+AMP(48)+AMP(49)+AMP(50)
     $ +AMP(51)-IMAG1*AMP(52)+AMP(53)+AMP(56)+IMAG1*AMP(199)+IMAG1
     $ *AMP(200)+IMAG1*AMP(201)+IMAG1*AMP(202)+IMAG1*AMP(203)+IMAG1
     $ *AMP(204)+IMAG1*AMP(205)+IMAG1*AMP(206)+IMAG1*AMP(207)+IMAG1
     $ *AMP(208)+IMAG1*AMP(209)+IMAG1*AMP(210)+IMAG1*AMP(211)+IMAG1
     $ *AMP(212)+AMP(213)+AMP(214)+AMP(215)+AMP(216)+AMP(217)+AMP(218)
     $ +AMP(219)+AMP(220)+AMP(221)+AMP(222)+IMAG1*AMP(223)+IMAG1
     $ *AMP(224)+IMAG1*AMP(225)+IMAG1*AMP(226)+IMAG1*AMP(227)+IMAG1
     $ *AMP(228)+AMP(235)+AMP(236)+AMP(237)+AMP(239)+IMAG1*AMP(240)
     $ +AMP(274)+AMP(275)+AMP(276)+AMP(277)+AMP(278)+AMP(279)+AMP(280)
     $ +AMP(281)+AMP(282)+AMP(283)+AMP(284)+AMP(285)+AMP(286)+AMP(287)
     $ +AMP(288)+AMP(289)+AMP(290)+AMP(291)+AMP(292)+AMP(293)+AMP(294)
     $ +AMP(295)+IMAG1*AMP(302)+AMP(303)+AMP(305)+AMP(335)+AMP(336)
     $ +AMP(337)+AMP(338)+AMP(339)+AMP(340)-IMAG1*AMP(347)+AMP(348)
     $ +AMP(350)-IMAG1*AMP(369)-IMAG1*AMP(370)-AMP(372)-AMP(373)
     $ -AMP(375)-AMP(376)-AMP(378)-AMP(379)-AMP(381)-AMP(382)-AMP(384)
     $ -AMP(385)-AMP(387)-AMP(388)-AMP(390)-AMP(391)-AMP(393)-AMP(394)
     $ -AMP(396)-AMP(397)-AMP(399)-AMP(400)-AMP(403)-AMP(402)-AMP(406)
     $ -AMP(405)+IMAG1*AMP(407)+IMAG1*AMP(408)
      JAMP(6)=+IMAG1*AMP(1)+IMAG1*AMP(2)+IMAG1*AMP(3)+IMAG1*AMP(4)
     $ +IMAG1*AMP(5)+IMAG1*AMP(6)+IMAG1*AMP(7)+IMAG1*AMP(8)+IMAG1
     $ *AMP(9)+IMAG1*AMP(10)+IMAG1*AMP(11)+IMAG1*AMP(12)+IMAG1*AMP(13)
     $ +IMAG1*AMP(14)+IMAG1*AMP(34)+IMAG1*AMP(35)+IMAG1*AMP(36)+IMAG1
     $ *AMP(37)+IMAG1*AMP(38)+IMAG1*AMP(39)-AMP(40)-AMP(41)-AMP(42)
     $ -AMP(43)-AMP(44)-AMP(45)-AMP(46)-AMP(47)-AMP(48)-AMP(49)-AMP(50)
     $ -AMP(51)+IMAG1*AMP(52)-AMP(53)-AMP(56)+IMAG1*AMP(137)+IMAG1
     $ *AMP(138)+IMAG1*AMP(139)+IMAG1*AMP(140)+IMAG1*AMP(141)+IMAG1
     $ *AMP(142)+IMAG1*AMP(143)+IMAG1*AMP(144)+IMAG1*AMP(145)+IMAG1
     $ *AMP(146)+IMAG1*AMP(147)+IMAG1*AMP(148)+IMAG1*AMP(149)+IMAG1
     $ *AMP(150)+AMP(151)+AMP(152)+AMP(153)+AMP(154)+AMP(155)+AMP(156)
     $ +AMP(157)+AMP(158)+AMP(159)+AMP(160)+AMP(161)+AMP(162)+AMP(163)
     $ +AMP(164)+AMP(165)+AMP(166)+AMP(167)+AMP(168)+AMP(169)+AMP(170)
     $ +AMP(171)+AMP(172)+IMAG1*AMP(179)+AMP(180)+IMAG1*AMP(182)
     $ +AMP(183)-AMP(307)-AMP(308)-AMP(309)-AMP(310)-AMP(311)-AMP(312)
     $ -AMP(313)-AMP(314)-AMP(315)-AMP(316)+IMAG1*AMP(317)+IMAG1
     $ *AMP(318)+IMAG1*AMP(319)+IMAG1*AMP(320)+IMAG1*AMP(321)+IMAG1
     $ *AMP(322)-AMP(329)-AMP(330)-AMP(331)-AMP(333)+IMAG1*AMP(334)
     $ +AMP(341)+AMP(342)+AMP(343)+AMP(344)+AMP(345)+AMP(346)+IMAG1
     $ *AMP(347)+AMP(349)+AMP(351)+IMAG1*AMP(369)+IMAG1*AMP(370)
     $ -AMP(371)+AMP(373)-AMP(374)+AMP(376)-AMP(377)+AMP(379)-AMP(380)
     $ +AMP(382)-AMP(383)+AMP(385)-AMP(386)+AMP(388)-AMP(389)+AMP(391)
     $ -AMP(392)+AMP(394)-AMP(395)+AMP(397)-AMP(398)+AMP(400)+AMP(403)
     $ -AMP(401)+AMP(406)-AMP(404)+IMAG1*AMP(411)

      M77_MATRIX = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        M77_MATRIX = M77_MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO

      END

      SUBROUTINE M77_GET_VALUE(P, ALPHAS, NHEL ,ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER NHEL
      DOUBLE PRECISION ALPHAS
      REAL*8 PI
CF2PY INTENT(OUT) :: ANS
CF2PY INTENT(IN) :: NHEL
CF2PY INTENT(IN) :: P(0:3,NEXTERNAL)
CF2PY INTENT(IN) :: ALPHAS
C     ROUTINE FOR F2PY to read the benchmark point.    
C     the include file with the values of the parameters and masses 
      INCLUDE 'coupl.inc'

      PI = 3.141592653589793D0
      G = 2* DSQRT(ALPHAS*PI)
      CALL UPDATE_AS_PARAM()
      IF (NHEL.NE.0) THEN
        CALL M77_SMATRIXHEL(P, NHEL, ANS)
      ELSE
        CALL M77_SMATRIX(P, ANS)
      ENDIF
      RETURN
      END

      SUBROUTINE M77_INITIALISEMODEL(PATH)
C     ROUTINE FOR F2PY to read the benchmark point.    
      IMPLICIT NONE
      CHARACTER*512 PATH
CF2PY INTENT(IN) :: PATH
      CALL SETPARA(PATH)  !first call to setup the paramaters    
      RETURN
      END

      LOGICAL FUNCTION M77_IS_BORN_HEL_SELECTED(HELID)
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=7)
      INTEGER    NCOMB
      PARAMETER (NCOMB=128)
C     
C     ARGUMENTS
C     
      INTEGER HELID
C     
C     LOCALS
C     
      INTEGER I,J
      LOGICAL FOUNDIT
C     
C     GLOBALS
C     
      INTEGER HELC(NEXTERNAL,NCOMB)
      COMMON/M77_PROCESS_NHEL/HELC

      INTEGER POLARIZATIONS(0:NEXTERNAL,0:5)
      COMMON/M77_BORN_BEAM_POL/POLARIZATIONS
C     ----------
C     BEGIN CODE
C     ----------

      M77_IS_BORN_HEL_SELECTED = .TRUE.
      IF (POLARIZATIONS(0,0).EQ.-1) THEN
        RETURN
      ENDIF

      DO I=1,NEXTERNAL
        IF (POLARIZATIONS(I,0).EQ.-1) THEN
          CYCLE
        ENDIF
        FOUNDIT = .FALSE.
        DO J=1,POLARIZATIONS(I,0)
          IF (HELC(I,HELID).EQ.POLARIZATIONS(I,J)) THEN
            FOUNDIT = .TRUE.
            EXIT
          ENDIF
        ENDDO
        IF(.NOT.FOUNDIT) THEN
          M77_IS_BORN_HEL_SELECTED = .FALSE.
          RETURN
        ENDIF
      ENDDO

      RETURN
      END

